### PR TITLE
fix(vcarousel delimiter aria-label): a11y carousel delimiters

### LINKED ISSUE #7996: [Feature Request] Vuetify 1.5/2 carousel's delimiters don't have right support for a11y
### Problem to solve
ay11 issues solved for buttons used in carousel's delimiter.
as you can see there is no `aria-label` in button of the delimiter so the screen readers would read it as 'button' only leaving the users without the real information what is it really about.

https://codepen.io/just-vr/pen/GVqEoV?editors=1000

### Proposed solution
a prop that will deliver an: `id`, `aria-label`, `aria-labelledby`, `title` or maybe not even a prop, maybe just an id that would write out the carousel's item name and number such as 'carousel-item-${number}'. not completely sure what the solution could be, but this might help https://dequeuniversity.com/rules/axe/3.1/button-name?application=lighthouse

```javascript
// example with aria-label
<button type="button" value="0" aria-label="some-title-from-props" class="v-carousel__controls__item v-btn v-item--active v-btn--active v-btn--fab v-btn--flat v-btn--icon v-btn--round theme--dark v-size--small"><span class="v-btn__content"><i aria-hidden="true" class="v-icon notranslate material-icons theme--dark" style="font-size: 18px;">stop</i></span></button>
```

### PR DESCRIPTION
**Pull request by redahas**
It is an a11y violation to have no aria-labels on clickable UI elements such as the carousel
navigation buttons. Adding aria-labels will support a screen reader

fix #7996

## Description
Added an aria-label attribute for VCarousel delimiter buttons so that screen readers have something to dictate. Ideally there should be a locale string added and translated to support languages other than English.

## Motivation and Context
Fixes issue: https://github.com/vuetifyjs/vuetify/issues/7996

## How Has This Been Tested?
Added expect to delimiter unit test in VCarousel.spec.ts
Manually/visually (manually inspecting the DOM)

## Markup:
<details>

```vue
<template>
  <v-container>
    <v-carousel>
    <v-carousel-item
      v-for="(color, i) in colors"
      :key="color"
    >
      <v-sheet
        :color="color"
        height="100%"
        tile
      >
        <v-row
          class="fill-height"
          align="center"
          justify="center"
        >
          <div class="display-3">Slide {{ i + 1 }}</div>
        </v-row>
      </v-sheet>
    </v-carousel-item>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    colors: [
      'primary',
      'secondary',
      'yellow darken-2',
      'red',
      'orange',
    ],
  })
}
</script>

```
</details>

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by redahas** [comment]
@johnleider I added the English string to the locale files for each language. I was advised on discord that this was what to do as translations were done via crowdin. Is this correct? Cheers

**Comment by MajesticPotatoe** [comment]
@redahas the translation done in Crowdin just pertains to docs. As for adding to each locale, I believe that's right, though not entirely sure on that structure.

**Comment by redahas** [comment]
@MajesticPotatoe ok no worries! The structure of the string itself, or the object structure? I was following dataTable.ariaLabel.{x} structure which already exists. Happy to change it to whatever is a better fit 👍

**Comment by MajesticPotatoe** [comment]
Should be fine, outwardly thinking is all.

**Comment by redahas** [comment]
@MajesticPotatoe absolutely. Happy to change it if you decide that would be better :)

**Pull request merged**
