### PR TITLE
feat(VProgress): only play animations when visible

### LINKED ISSUE #12731: [Feature Request] Add lazy functionality to Progress components
### Problem to solve
There have been various reports of the Progress components spiking CPU in different scenarios.

#### Various reports:
#2324, #785, #720, #553

#### Progress components:
https://vuetifyjs.com/en/components/progress-circular
https://vuetifyjs.com/en/components/progress-linear/

### Proposed solution
A member of my team discovered that if you wrap these components with `VLazy` you can greatly reduce the performance impact - especially if multiple instances of Progress components exist on the page.

The proposed solution is to add a `lazy` prop to the Progress components that gives them lazy functionality (i.e. not rendering if not visible on the page).

This would be either by wrapping in `VLazy` or using the `v-intersect` directive - likely requiring a minimal change to the `render` function and an added `prop` of `lazy`.

https://vuetifyjs.com/en/components/lazy
https://vuetifyjs.com/en/directives/intersect/

P.S. some kind of `lazy` directive would be cool but not sure if it's feasible/wanted and would for sure have a namespace clash with `v-lazy`

### PR DESCRIPTION
**Pull request by Bamblehorse**
## Description

This PR resolves #12731 and deals with reducing CPU load for `VProgressCircular` and `VProgressLinear` while they aren't visible.

## Motivation and Context

The solution seeks to reduce reported CPU spikes(#2324, #785, #720, #553) by pausing the components animations when not visible on the page (through the `Intersect` directive)
## How Has This Been Tested?

Unit tests  have been updated
## Markup:

<details>

```vue
<template>
  <v-container style="height: 300vh; padding-top: 200vh;">
    <v-progress-circular
      indeterminate
    />
    <v-progress-linear
      indeterminate
      style="margin-top: 10vh;"
    />
    <v-progress-linear
      striped
      indeterminate
      reverse
      style="margin-top: 10vh;"
    />
    <v-progress-linear
      stream
      :value="25"
      buffer-value="50"
      style="margin-top: 10vh;"
    />
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      //
    }),
  }
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
My idea was more to just apply a class that disables the CSS animation, rather than hiding elements.

**Comment by Bamblehorse** [comment]
> My idea was more to just apply a class that disables the CSS animation, rather than hiding elements.

@KaelWD that would be much more simple 🙂 I'll adjust the PR and get back to you

**Comment by Bamblehorse** [comment]
> My idea was more to just apply a class that disables the CSS animation, rather than hiding elements.

@KaelWD thank you for your feedback 🙂 it was helpful and made sense.

I have refactored to use the `Intersect` directive to toggle a class which pauses the animation when the element is not visible. I was going to use the `Intersectable` mixin but realized it doesn't pass the `isIntersecting` Boolean to the callback so it seemed appropriate to use the directive instead.

Let me know what you think when you have some time 🙂

**Comment by nekosaur** [comment]
Don't call the directive methods directly. Use `directives` option in vnode data when using `h()`. See for example `v-lazy` component.

**Comment by Bamblehorse** [comment]
> Don't call the directive methods directly. Use `directives` option in vnode data when using `h()`. See for example `v-lazy` component.

Of course 😅 thanks for the sanity check and pointer to `v-lazy` - have added it in properly

I'm wondering if this should use similar logic to `v-img` to check for intersect availability:
https://github.com/vuetifyjs/vuetify/blob/21331625b9707f19cc2004f2e0957b288a2ccad3/packages/vuetify/src/components/VImg/VImg.ts#L25
https://github.com/vuetifyjs/vuetify/blob/21331625b9707f19cc2004f2e0957b288a2ccad3/packages/vuetify/src/components/VImg/VImg.ts#L258-L269

Alternatively could set `isVisible` to be `true` by default which should catch those edge cases as well

**Comment by KaelWD** [comment]
> I'm wondering if this should use similar logic to v-img to check for intersect availability

The directive itself should probably handle that?

**Comment by Bamblehorse** [comment]
> > I'm wondering if this should use similar logic to v-img to check for intersect availability
> 
> The directive itself should probably handle that?

I was under the impression if this was used on an unsupported browser - say IE - the animation would never play - so I was thinking to set `isVisible` to `true` which would hopefully solve that

**Comment by Bamblehorse** [comment]
@KaelWD / @nekosaur Thanks for your continued feedback 🙂 I appreciate it

I have updated in line with my comment above to set `isVisible` to `true` by default

It immediately switches to `false` on browsers that support `IntersectionObserver` so is a simple fail safe

I have added a regression test to keep it in place

**Comment by KaelWD** [comment]
Looks great, thanks. Are you planning to do the same for VProgressLinear?

**Comment by Bamblehorse** [comment]
> Looks great, thanks. Are you planning to do the same for VProgressLinear?

Awesome 🙂 yeah just wanted to check the changes fitted in with the codebase - I've added the equivalent changes for `VProgressLinear` in https://github.com/vuetifyjs/vuetify/pull/13136/commits/900d452beb78cd50a6ab65c3a9b2b863f0b0b87a

Let me know if you want me to separate the PRs or if the changes are similar enough that it's okay.

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
