### PR TITLE
Localized numbers in pagination

### PR DESCRIPTION
**Pull request by alireza4050**
## Description
Uses the `.toLocaleString` method and the locale from  `$vuetify.lang.current` in data-iterable pagination.

## Motivation and Context
To localize numbers in v-data-table and v-data-iterator pagination. 

## How Has This Been Tested?
visually

## Markup:

<details>

```vue
/<template>
  <v-app dark>
    <v-content>
      <v-container fill-height>
        <v-layout column
                  justify-space-between>
          <v-data-table :headers="headers"
                        :items="desserts"
                        class="elevation-1">
            <template slot="items"
                      slot-scope="props">
              <td>{{ props.item.name }}</td>
              <td class="text-xs-right">{{ props.item.calories }}</td>
              <td class="text-xs-right">{{ props.item.fat }}</td>
              <td class="text-xs-right">{{ props.item.carbs }}</td>
              <td class="text-xs-right">{{ props.item.protein }}</td>
              <td class="text-xs-right">{{ props.item.iron }}</td>
            </template>
          </v-data-table>
          <v-spacer></v-spacer>
          <v-data-iterator :items="desserts"
                           content-tag="v-layout"
                           row
                           wrap>
            <v-flex slot="item"
                    slot-scope="props"
                    xs12
                    sm6
                    md4
                    lg3>
              <v-card>
                <v-card-title>
                  <h4>{{ props.item.name }}</h4>
                </v-card-title>
                <v-divider></v-divider>
                <v-list dense>
                  <v-list-tile>
                    <v-list-tile-content>Calories:</v-list-tile-content>
                    <v-list-tile-content class="align-end">{{ props.item.calories }}</v-list-tile-content>
                  </v-list-tile>
                  <v-list-tile>
                    <v-list-tile-content>Protein:</v-list-tile-content>
                    <v-list-tile-content class="align-end">{{ props.item.protein }}</v-list-tile-content>
                  </v-list-tile>
                </v-list>
              </v-card>
            </v-flex>
          </v-data-iterator>
          <v-switch :label="`Language: ${this.$vuetify.lang.current}`"
                    v-model="langSwitch"></v-switch>
        </v-layout>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
export default {
  mounted() {
    this.langSwitch = true;
  },
  computed: {
    langSwitch: {
      get() {
        return this.$vuetify.lang.current === 'fa-IR';
      },
      set(val) {
        this.$vuetify.lang.current = val ? 'fa-IR' : 'en';
      }
    }
  },
  data() {
    return {
      _radioBtn: 0,
      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'left',
          sortable: false,
          value: 'name'
        },
        { text: 'Calories', value: 'calories' },
        { text: 'Protein (g)', value: 'protein' },
      ],
      desserts: [
        {
          value: false,
          name: 'Frozen Yogurt',
          calories: 159,
          protein: 4.0,
        },
        {
          value: false,
          name: 'Ice cream sandwich',
          calories: 237,
          protein: 4.3,
        }
      ]
    }
  }
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by nekosaur** [comment]
I have admittedly not looked at this too closely, but why not keep the default value of rowsPerPageItems in the prop def?

**Comment by KaelWD** [comment]
They won't update if the current language is changed.

**Comment by alireza4050** [comment]
Any suggestions on what should be default for `useGrouping`?

**Comment by jacekkarczmarczyk** [comment]
Imho `true`

**Comment by nekosaur** [comment]
Well I was thinking something like this.

```
rowsPerPageItems: {
  type: Array,
  default: () => ([
    { value: 5, text: 5 },
    { value: 10, text: 10 },
    { value: 25, text: 25 },
    { value: -1, text: '$vuetify.dataIterator.rowsPerPageAll' }
  ])
},
```

```
computedRowsPerPageItems () {
  return this.rowsPerPageItems.map(item => {
    return isObject(item)
      ? {
        ...item,
        text: !isNaN(item.text) ? localizeNumber(item.text, this.currentLocale) : this.$vuetify.t(item.text)
      }
      : item
  })
},
```

I also think that localizeNumber could be moved to `lang` object.

**Comment by alireza4050** [comment]
@jacekkarczmarczyk > Imho true
Problem is that would differ from the current behavior.
```js
(1000000).toString(); // "1000000"
(1000000).toLocaleString('en-US'); // "1,000,000"
```

**Comment by jacekkarczmarczyk** [comment]
I forgot we're talking about items per page, which is very unlikely to be more than 999, so it doesn't really matter

**Comment by alireza4050** [comment]
> I also think that localizeNumber could be moved to lang object.

@nekosaur We could also just do it in the `t` method by checking if the key passed is a number:
```ts
    t (key, ...params) {
      if (typeof key === 'number') {
        const locale = params.length > 0 ? (params[0] as string) : this.current;
        const options = (params.length === 2 ? params[1] : { useGrouping: false }) as Intl.NumberFormatOptions;
        return (key as number).toLocaleString(locale, options);
      }
      if (!key.startsWith(LANG_PREFIX)) return key

      if (config.t) return config.t(key, ...params)

      const translation = getTranslation(this.locales[this.current], key)

      return translation.replace(/\{(\d+)\}/g, (match: string, index: string) => {
        return String(params[+index])
      })
    },
  }
```

**Pull request closed without merging**
