### PR TITLE
feat(VTextField, VSelect): add clearable mixin (#4144, #5722, #6751)

### PR DESCRIPTION
**Pull request by bludnic**
## Description
Add clearable mixin to customize reset value by using `reset-value` prop.

Tested with these components: VTextField, VTextarea, VSelect, VAutocomplete, VCombobox, VOverflowBtn.

## Motivation and Context

Solves these issues: #4144, #5722, #6751. And maybe #2752.

## How Has This Been Tested?

unit, visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <!-- VTextField -->
    <v-layout
      wrap
      class="w300"
    >
      <h3 class="headline">TextField</h3>
      <v-text-field
        v-model="text"
        clearable
        reset-value="reset"
      ></v-text-field>
    </v-layout>

    <v-divider></v-divider>

    <!-- VTextarea -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VTextarea</h3>
      <v-textarea
        v-model="text"
        clearable
        reset-value="reset"
      ></v-textarea>
    </v-layout>

    <v-divider></v-divider>

    <!-- VSelect -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VSelect</h3>
      <v-flex xs12>
        <v-select
          v-model="select"
          :items="items"
          clearable
          reset-value="Vue"
        ></v-select>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VSelect (multiple) -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VSelect (multiple)</h3>
      <v-flex xs12>
        <v-select
          v-model="selectMultiple"
          :items="items"
          :reset-value="['Vue']"
          clearable
          multiple
        ></v-select>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VAutocomplete -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VAutocomplete</h3>
      <v-flex xs12>
        <v-autocomplete
          v-model="select"
          :items="items"
          :search-input.sync="search"
          placeholder="Search"
          hide-details
          clearable
          :reset-value="'Vue'"
        ></v-autocomplete>
      </v-flex>

      <v-flex xs12>
        <v-alert
          type="info"
          value="true"
        >
          {{ select }}
        </v-alert>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VCombobox -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VCombobox</h3>
      <v-flex xs12>
        <v-combobox
          v-model="select"
          :items="items"
          clearable
          reset-value="Vue"
          chips
          label="Select"
        ></v-combobox>
      </v-flex>

      <v-flex xs12>
        <v-alert
          type="info"
          value="true"
        >
          {{ select }}
        </v-alert>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VCombobox (multiple) -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VCombobox (multiple)</h3>
      <v-flex xs12>
        <v-combobox
          v-model="selectMultiple"
          :items="items"
          label="Select"
          multiple
          clearable
          :reset-value="['Vue']"
          chips
          deletable-chips
        ></v-combobox>
      </v-flex>

      <v-flex xs12>
        <v-alert
          type="info"
          value="true"
        >
          {{ selectMultiple }}
        </v-alert>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VOverflowBtn -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VOverflowBtn</h3>
      <v-flex xs12>
        <v-overflow-btn
          v-model="select"
          :items="items"
          clearable
          reset-value="Vue"
        ></v-overflow-btn>
      </v-flex>

      <v-flex xs12>
        <v-alert
          type="info"
          value="true"
        >
          {{ select }}
        </v-alert>
      </v-flex>
    </v-layout>

    <v-divider></v-divider>

    <!-- VOverflowBtn (multiple) -->
    <v-layout
      wrap
      class="w300"
      mt-5
    >
      <h3 class="headline">VOverflowBtn (multiple)</h3>
      <v-flex xs12>
        <v-overflow-btn
          v-model="selectMultiple"
          :items="items"
          multiple
          clearable
          :reset-value="['Vue']"
        ></v-overflow-btn>
      </v-flex>

      <v-flex xs12>
        <v-alert
          type="info"
          value="true"
        >
          {{ selectMultiple }}
        </v-alert>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
  import VTextField from '../src/components/VTextField/VTextField'
  import VTextarea from '../src/components/VTextarea/VTextarea'
  import VSelect from '../src/components/VSelect/VSelect'
  import VCombobox from '../src/components/VCombobox/VCombobox'
  import VAutocomplete from '../src/components/VAutocomplete/VAutocomplete'
  import VOverflowBtn from '../src/components/VOverflowBtn/VOverflowBtn'
  export default {
    components: { VTextField, VTextarea, VSelect, VCombobox, VAutocomplete, VOverflowBtn },
    data: () => ({
      text: '',
      search: '',
      select: '',
      selectMultiple: [],
      items: [
        'Programming',
        'Design',
        'Vue',
        'Vuetify',
      ],
    }),
  }
</script>

<style>
.w300 {
  width: 300px
}
</style>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
I'm going to have to put this on hold until https://github.com/vuetifyjs/vuetify/pull/7385 makes it in, thank you for your patience!

**Comment by johnleider** [comment]
Reviewing this it feels weird that it's possible to clear the field and still have the clear icon visible. Possibly do a check to see if the **reset-value** === **this.internalValue**?

**Comment by johnleider** [comment]
I've changed base-branch to `dev`. Please resolve the merge conflicts (these existed on `next` as well).

**Comment by bludnic** [comment]
Did I understand correctly, the VChip inside the VCombobox has no longer a `v-chip__close`, so this test is useless?
https://github.com/vuetifyjs/vuetify/pull/7441/commits/a7415fc0cb6047efbb73651433910e8f10c2ce0a#diff-f4de2ac835b084bb1e85b600680a6f26R145-R169

**Comment by bludnic** [comment]
> Reviewing this it feels weird that it's possible to clear the field and still have the clear icon visible. Possibly do a check to see if the **reset-value** === **this.internalValue**?

What if resetValue is an array or an object? Should we do deep comparison?

**Comment by johnleider** [comment]
Yea, that may be required considering that they could technically provide anything.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
