### PR TITLE
fix(bind-attrs): fix transition-group animation

### LINKED ISSUE #9171: [Bug Report] VSpeedDial strane animation if buttons have event listener
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90, Mozilla Firefox, Google Chrome
**OS:** Windows 10, Windows, Linux, Android

### Steps to reproduce
Create `VSpeedDial`, add `VBtn` with event listener (`@click, @hover`, etc.)

if there are no event listeners animations work as expected

### Expected Behavior
smooth animations on opening and closing

### Actual Behavior
choppy animation on opening

### Reproduction Link
<a href="https://codesandbox.io/embed/vuetify-playground-h1mk9" target="_blank">https://codesandbox.io/embed/vuetify-playground-h1mk9</a>

### PR DESCRIPTION
**Pull request by BjornLuG**
fix #9171

## Description

The watchers with `immediate: true` is removed as using $set in it causes issue in transition groups. Instead, the immediate watchers' initialization are moved to created.

## Motivation and Context

The current bind-attrs uses $set inside immediate watchers to set attrs$ and listeners$, this causes issues with transition groups where the enter animation directly "snaps". It seems to be a bug in Vue and I have opened [an issue there](https://github.com/vuejs/vue/issues/10596).

It fixes #9171.

## How Has This Been Tested?

The changes are tested in [codesandbox](https://codesandbox.io/s/vue-transition-group-bug-wnvwv) and on my personal project.

## Markup:

<details>

```vue
<template>
  <div id="app">
    <input v-model="open" id="toggle" type="checkbox">
    <label for="toggle">Toggle transition</label>
    <transition-group name="scale">
      <test v-if="open" key="1"></test>
      <test v-if="open" key="2"></test>
    </transition-group>
  </div>
</template>

<script>
function makeWatcher (property) {
  return function (val, oldVal) {
    for (const attr in oldVal) {
      if (!Object.prototype.hasOwnProperty.call(val, attr)) {
        this.$delete(this.$data[property], attr)
      }
    }
    for (const attr in val) {
      this.$set(this.$data[property], attr, val[attr])
    }
  }
}

export default {
  name: "App",
  components: {
    Test: {
      template: '<div>attrs$: {{ attrs$ }}</div>',
      data: () => ({
        attrs$: {},
        listeners$: {},
      }),

     created () {
       // Work around unwanted re-renders: https://github.com/vuejs/vue/issues/10115
       // Make sure to use `attrs$` instead of `$attrs` (confusing right?)
       this.$watch('$attrs', makeWatcher('attrs$'), { immediate: true })
       this.$watch('$listeners', makeWatcher('listeners$'), { immediate: true })
      },
    }
  },
  data: () => ({
    open: false
  })
};
</script>


<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  border: 1px solid black;
  padding: 1rem;
}

.scale-enter,
.scale-leave-to {
  opacity: 0;
  transform: scale(0);
}
.scale-enter-active,
.scale-leave-active {
  transition: all 0.5s ease;
}

.scale-move {
  transition: transform 0.6s;
}
</style>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Well that's a fun one. Does `this.$watch($attrs, makeWatcher('attrs$'), { immediate: true })` in `created` (to avoid duplication) break it too?

**Comment by KaelWD** [comment]
Or `attrs$: this.$attrs` in `data`

**Comment by BjornLuG** [comment]
Gosh, the lint errors are embarrasing.

>  Does this.$watch($attrs, makeWatcher('attrs$'), { immediate: true }) in created (to avoid duplication) break it too?

Didn't thought of this. Will try it out.

> Or attrs$: this.$attrs in data

I think this would directly reference the original $attrs, which would make this code redundant. Maybe a shallow clone like `attrs$: { ...this.$attrs }` could work too?

**Comment by BjornLuG** [comment]
Just tried both and it actually worked! I guess it now comes down to preference.

`this.$watch($attrs, makeWatcher('attrs$'), { immediate: true })` looks cleaner whereas `attrs$: { ...this.$attrs }` is more simpler, but then the data option needs to be changed to a scoped function to access `this`.

**Comment by BjornLuG** [comment]
I changed the watch strategy to use `$watch` and double-check everything. Hope there's no more errors.

**Pull request merged**
