### PR TITLE
fix(VSelect): show input placeholder

### PR DESCRIPTION
**Pull request by KaelWD**
## Description

reverts 37c9e539 and part of 641426c2

v-select now can't be tabbed to, it needs tabindex and styles on the root element like in 1.0

## Markup
```vue
<template>
  <v-app>
    <v-container>
      <v-autocomplete placeholder="placeholder (already works on dev)"></v-autocomplete>
      <v-select placeholder="can't tab to this any more"></v-select>
    </v-container>
  </v-app>
</template>
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by KaelWD** [comment]
Yeah, it does cause new problems with tabbing though. You're welcome to finish it if you want.

**Comment by johnleider** [comment]
I would if I knew what it was fixing, playground?

**Comment by KaelWD** [comment]
Thought I'd put one already. Updated.

**Comment by johnleider** [comment]
So testing on current dev, the placeholder does not show (as expected by the style that needs changing), but I am able to tab to it because it is readonly. With this PR I am unable to tab to it and by default is disabling the select input which is not correct.

**Comment by KaelWD** [comment]
:man_facepalming: Fuck I'm retarded, no idea why I changed that.

**Comment by KaelWD** [comment]
Oh right, I think it was that IE11 cursor thing. I'm on my shitbox linux laptop rn so I can't check.

**Comment by KaelWD** [comment]
I think it should be ok still - #4062

**Pull request merged**
