### PR TITLE
feat(VAutocomplete): add autoSelectFirst prop

### PR DESCRIPTION
**Pull request by throskam**
## Description

Add a new boolean prop in **v-autocomplete** to optionally auto-select the first option of the result set.

## Motivation and Context

fixes https://github.com/vuetifyjs/vuetify/issues/4207

## How Has This Been Tested?

visually and unit test.

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-autocomplete
      label="state"
      v-model="state"
      :items="states"
      autoSelectFirst
    />
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      state: null,
      states: [
        'Alabama', 'Alaska', 'American Samoa', 'Arizona',
        'Arkansas', 'California', 'Colorado', 'Connecticut',
        'Delaware', 'District of Columbia', 'Federated States of Micronesia',
        'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho',
        'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
        'Louisiana', 'Maine', 'Marshall Islands', 'Maryland',
        'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
        'Missouri', 'Montana', 'Nebraska', 'Nevada',
        'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
        'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio',
        'Oklahoma', 'Oregon', 'Palau', 'Pennsylvania', 'Puerto Rico',
        'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
        'Texas', 'Utah', 'Vermont', 'Virgin Island', 'Virginia',
        'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
      ]
    })
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
Resolve conflicts and we'll get this in for v1.3

**Comment by throskam** [comment]
Conflicts resolved.

However, there were still debates about the property name in #4207.

**Comment by bedeoan** [comment]
<v-autocomplete solo-inverted dark  clearable :items="products" item-value="id" hide-details v-model="selectedProductId" v-auto-select />
just add : v-auto-select directive

=======main.js=====
Vue.directive('auto-select', {
  bind(el, binding, vnode) {
    vnode.autoSelectHandler = event => {
      Vue.nextTick(() => {
        Vue.nextTick(() => {
          vnode.componentInstance.setMenuIndex(0)
        })
      })
    }
    const input = vnode.componentInstance.$refs.input
    input.addEventListener('input', vnode.autoSelectHandler)
  },
  unbind(el, binding, vnode) {
    const input = vnode.componentInstance.$refs.ixnput
    input.removeEventListener('input', vnode.autoSelectHandler)
  }
})

**Comment by johnleider** [comment]
Going to throw out a few ideas for the name:

- `auto-suggest`
- `auto-select-search`
- `select-suggestion`
- `auto-select`
- `select-first-suggestion` <-- I know right

Just trying to think semantically. Open to suggestions.

**Comment by johnleider** [comment]
Sticking with current naming convention.

**Pull request merged**
