### PR TITLE
(wip) Add CSS variables

### PR DESCRIPTION
**Pull request by yordis**
## Description
Use CSS variables for the theme. My intention is to keep maintain the branch using CSS variables so when we are ready to switch it will some work done.

Also, worth to point out, I am just trying to remove the needs of the creating different themes, no necessarily embrace CSS variables good practices all over the place (baby steps).

Right now, keeping this branch open helps me to fix merge conflicts.

## Motivation and Context

- Small bundle size
- Faster rendering/painting
- Easier theme

## How Has This Been Tested?

I definitely will need your support on this, regression is done by human eyes catching all the issues; unless you have some advance tooling setup.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Adding vars first to the theming mechanism would be a useful enhancement instead of breaking change

**Comment by yordis** [comment]
@jacekkarczmarczyk that is my target, just theming and then go crazy with all the good features of CSS variables, but I want to minimize the breaking changes.

**Comment by jacekkarczmarczyk** [comment]
I mean this https://github.com/vuetifyjs/vuetify/blob/dev/src/util/theme.js

**Comment by yordis** [comment]
@jacekkarczmarczyk **at some point the usage of CSS variables is beyond the theming**, also I am confused with that file I don't see that much theming going on (I am new into Vuetify so I don't know the full source code)

The only one left is IE11 and at this point I would kill any support, specially that big piece of Vuetify users are using for admin tools primarily (but I don't care about it right now, I just want to keep this branch update it until everyone decide to move on with IE since all green browsers support CSS variables)

**Comment by KaelWD** [comment]
I've considered doing that but never got around to it. 

Use case:
```vue
<template>
  ...
</template>

<style>
.my-class {
  color: var(--vuetify-primary); /* dynamic, will update if I change this.$vuetify.theme */
}
</style>
```

If you decide to this, it also has to work with SSR without flashing a default color or bloating the stylesheet too much.

**Comment by KaelWD** [comment]
Another option would be to still use stylus variables to store everything, then render all variable usage from a mixin. This would allow a fallback to stylus if someone has to support IE.

**Comment by yordis** [comment]
Folks, my intention is not use CSS variables for theming only by embrace all good the good practices which no preprocessor can do.

This is just the first step and to be honest I wouldn’t put any effort to support IE. I don’t expect you to take this PR in the next couple of months but it is out of my scope to care about IE and all the issues related.

CSS variables are not just for theming, and even just for that, you couldn’t do it in some use cases because you need the DOM structure

**Comment by johnleider** [comment]
Due to the amount of changes coming before 2.0, I'd say this is an effort that should happen later on. Due to the amount of conflicts and current status, closing for now.

**Pull request closed without merging**
