### PR TITLE
Uzbek translation

### PR DESCRIPTION
**Pull request by tensor2flow**

### CODE REVIEW

**Comment by sh7dm** [comment]
aren't we using crowdin?

**Comment by MajesticPotatoe** [comment]
> aren't we using crowdin?

For docs yes, this is locale (part of source)

**Comment by MajesticPotatoe** [comment]
pulse check

**Comment by MajesticPotatoe** [comment]
This issue is being closed due to inactivity. Please resubmit your PR to the correct branch with the requested changes and we will get this added in. 

Thank you for your interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
