### PR TITLE
Fix snackbar animation and refactor

### PR DESCRIPTION
**Pull request by manico**
To solve #2759 I ended up with quite a refactoring.
Now, I have a few questions to see if I'm going in the right direction.

- Snackbar is rather strict with allowing only message and action button. I have created new props for this to replace default slot as button added to snackbar does not conform to material design (no ripple, no padding, no hover). Would these new props make sense?

- I have added transitions to `snackbar.styl` as it is very custom containing transitions to container and content. Is there a reason that transitions are separated from component style file or is it ok that they are inside like in this example?

- As for #2759 and stacking of snackbars. This requires more refactoring as snackbars should be aware of one another (some global "storage" for this). Any suggestions?

### CODE REVIEW

**Comment by manico** [comment]
Added small vuetify store to handle snackbar queue.
Would this approach be ok for the library?
If it is ok, I can create more tests to cover refactored snackbar.

**Comment by KaelWD** [comment]
The queue is a separate issue to the animation: #2384. I don't think I'd handle it the way you have here.

**Comment by manico** [comment]
In #2759 it is mentioned to create sequential snackbars and since animation fix requires refactoring I figured it would be good to implement that too. Any suggestions on how you would handle queue?

**Comment by jacekkarczmarczyk** [comment]
I think that the queue implementation should be done in another PR. I'm also not sure if it should be done in the `VSnackbar.js`, the component itself should be responsible just for displaying the snackbar and queing should be handled by a separate mixin/component/helper/whatever

**Comment by johnleider** [comment]
Chiming in, queue implementation should not be built in to the component.

**Comment by KaelWD** [comment]
@manico can you merge in the changes from 3392d13b9726509f86cbeba9071a97007878b29e?

**Comment by manico** [comment]
@KaelWD Sorry, I totally missed this. :(
Do you still need me to merge 3392d13?

**Comment by KaelWD** [comment]
I already did it. I'll finish reviewing this today, it's blocking another task that I need to do.

**Comment by johnleider** [comment]
After reviewing this, I've come to the conclusion that we should revert this PR back to the original scope of #2759 and modify the animation only.

**Pull request merged**
