### PR TITLE
docs(contributing): specify guideline for before resolving an issue

### PR DESCRIPTION
**Pull request by yuwu9145**
## Description

Contributing guideline update to clarify some respectful rules of before deciding resolving an issue

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
I'm assuming this is regarding your grievance with #13262 and #13264. While I understand why you'd have a problem with this, it is extra work for everyone to do it your way instead of just opening a new PR with the alternate implementation.

**Comment by yuwu9145** [comment]
Thanks @KaelWD for your comment.

A different better solution definitely needs to be contributed as a separate pull request and will be merged eventually. 

I think the main point is lodging multiple pull requests towards the same issue from different contributors without communication & collaboration would be harmful. This could result in some contributors who spent a lot of time are completely ignored.

So probably it is better to commucate with the initial pull request author first, when there is a new solution, the person who proposed it in the thread should lodge the seperate pull request.

**Comment by yuwu9145** [comment]
To be honest, I am hesitating to push this forward because I am not sure if it actually makes sense to make a generic rule based on a rare case. Perhaps we could review this later when any similar situation happens in the future? @KaelWD @johnleider if you thought in the same way, feel free to close this pull request for now.

**Comment by johnleider** [comment]
I definitely understand your frustration and I greatly appreciate your contribution. With that being said, this is the first time I can remember this type of event happening since I started the framework; in other words, this is ridiculously rare.

Because of this, I'm going to close this issue. Thank you.

**Pull request closed without merging**
