### PR TITLE
refactor(VAutocomplete): rename variable name

### PR DESCRIPTION
**Pull request by starfish719**
## Description

- rename variable name
    - VSelect default menu props

## Motivation and Context

- The variable name after change is easier to understand purpose 🤔 

## How Has This Been Tested?

- none

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by starfish719** [comment]
As the first pullrequest, please tell me if there is any incompleteness ☺️

**Comment by starfish719** [comment]
How can I check my local?

**Comment by KaelWD** [comment]
I appreciate wanting to help, this change does not seem necessary at all to me though. Perhaps consider tackling [an existing issue](https://github.com/vuetifyjs/vuetify/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22T%3A+bug%22) instead. 

> How can I check my local?

Contributing guide is on its way, but the gist of it is:
 - create `packages/vuetify/dev/Playground.vue`
 - run `yarn`
 - run `yarn dev`

**Comment by starfish719** [comment]
I understand `packages/vuetify/dev/Playground.vue` is required.
I'll try `good first issue`.

thanks @KaelWD 👍

**Pull request closed without merging**
