### PR TITLE
feat(VDataTable): index prop in item* slots

### LINKED ISSUE #10646: [Feature Request] VDataTable: add missing index variable in "item.<name>" scoped slot
### Problem to solve
It would be very useful for adding a column with row index, and using index for custom stuff in a cell.

### Proposed solution
Inside the scoped slot "item.\<name>", the props should also contain the "index" property, like in the "item" scoped slot (cf #8199 and #8283).

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Description
Adds `index` to `item`, `item.<name>`, `expanded-item` slots

## Motivation and Context
fixes #10646

## How Has This Been Tested?
playground

## Markup:

<details>

```vue
<template>
  <v-container>
    <h2>#item.&lt;name&gt;</h2>

    <v-data-table
      :headers="tableHeaders"
      :items="tableData"
    >
      <template #item.index="{ index }">
        {{ index }}
      </template>
      <template #item.name="{ item }">
        {{ item.name }}
      </template>
    </v-data-table>

    <h2>#item</h2>

    <v-data-table
      :headers="tableHeaders"
      :items="tableData"
    >
      <template #item="{ index, item }">
        <tr><td>{{ index }}</td><td>{{ item.name }}</td></tr>
      </template>
    </v-data-table>

    <v-data-iterator :items="tableData">
      <template #item="{ index, item }">
        <div>{{ index }}: {{ item.name }}</div>
      </template>
    </v-data-iterator>
  </v-container>
</template>

<script>
  export default {
    data () {
      return {
        tableHeaders: [
          {
            text: 'No',
            sortable: false,
            value: 'index',
          },
          {
            text: 'Name',
            sortable: true,
            value: 'name',
          },
        ],
        tableData: Array(50).fill(null).map((_, index) => ({ name: `Data ${index}` })),
      }
    },
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Is this the index in the table, or the index in `items`? Index in items would be more useful but conflicts with #8283.

**Comment by jacekkarczmarczyk** [comment]
in `items` (look at playground, first page has indices 0-9, next one 10-19)
does it make sense to leave `index` as index in table and add other prop for index in `items`?

**Comment by KaelWD** [comment]
That's a breaking change then, although the current behaviour seems pretty useless so I don't know if it would even affect anyone.

**Comment by jacekkarczmarczyk** [comment]
> Does it account for sorting?

No, I'm not sure if it's even possible (especially with server side data). I think if someone wants to take sorting/filtering into account he should just put `index` as a property of `item`

> That's a breaking change then

So is "Reset/clear on inputs" already in 2.4, which imho may have bigger impact than this. As I mentioned before it would be safe to add another property (`globalIndex`?), but I feel like it's not worth it
@vuetifyjs/core-team thoughts?

**Comment by KaelWD** [comment]
> especially with server side data

More so that you can do something like `items.splice(index, 1)`, you do get `item` in the slot though so I guess an `indexOf` isn't that hard. 

Looking at #10646 and #8199 it seems like they would want what you've done here, but maybe without the pagination?

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
