### PR TITLE
Fix RTL VTabs onTouchEnd event (v2.0)

### LINKED ISSUE #8116: [Bug Report] Chip group slider in touch mode in RTL has the wrong direction
### Environment
**Vuetify Version:** 2.0.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Fix the direction of the slider in RTL mode

### Expected Behavior
When swiping to the right, the slider does not back to the left. 

### Actual Behavior
When swiping to the right, the slider will back to the left. 

### Reproduction Link
<a href="https://codepen.io/seyed_me/pen/XvNONv?&editable=true&editors=101" target="_blank">https://codepen.io/seyed_me/pen/XvNONv?&editable=true&editors=101</a>

### PR DESCRIPTION
**Pull request by melbahja**
Playground:
https://codepen.io/dev0x0/full/dxoxqq
Fixes #8116 

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
@melbahja Does your PR fixes https://github.com/vuetifyjs/vuetify/issues/8116 as well?
Also please rebase to `master` branch and fix the linting errors (just run lint autofixer)

**Comment by melbahja** [comment]
@jacekkarczmarczyk Yes this pull request will fix #8027 issue
I will fix the lint and rebase today sorry about that

**Comment by jacekkarczmarczyk** [comment]
Thanks for the info (btw - you mean 8116 not 8027?)

**Comment by melbahja** [comment]
Yes i mean #8116 (github autocomplete) confused me

**Comment by melbahja** [comment]
@jacekkarczmarczyk I think it's ready now ?

**Comment by jacekkarczmarczyk** [comment]
Looks ready, i'll take a look before tuesday release, please only resolve conflicts in the v-list PR

**Comment by melbahja** [comment]
@jacekkarczmarczyk thank you
I will fix conflicts today or tomorrow morning

**Pull request merged**
