### PR TITLE
docs: kind guide for using missing material icons

### PR DESCRIPTION
**Pull request by jjangga0214**
## Description
I added a kind description of how to use missing material icons.

## Motivation and Context

Some material icons are missing by default. For example, `person` and `person_outline` are available, but `visibility_outline` isn't while `visibility` is. This has been a known issue for a while, but I personally had a bit embarrassing experience finding how to solve this inconsistency as there wasn't a clear and explicit description. Therefore I thought it would be helpful or at least convenient for other people if I can add some guide that can be easily copied and pasted.

Fixes https://github.com/vuetifyjs/vuetify/issues/4164

## How Has This Been Tested?

Of course I run docs server on my local machine and found no problem.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jjangga0214** [comment]
The content would be located just after <https://vuetifyjs.com/en/framework/icons#component-icons>, and it's like below.

# Using missing Material Icons

Some material icons are missing by default. For example, `person` and `person_outline` are available, but `visibility_outline` isn't, while `visibility` is. To use missing material icons, include the font below (remove another material font if already registered).

```html
<link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
/>
```

You can add your custom component. Let me assume it is __@/components/MaterialIcon.vue.__

```vue
<template>
  <i :class="standardClass">{{ parsed.id }}</i>
</template>

<script>
export default {
  props: {
    name: {
      type: String
    }
  },
  computed: {
    parsed() {
      const check = (customPrefixes, standardPrefix) => {
        for (let prefix of customPrefixes) {
          prefix = `_${prefix}`
          if (this.name.endsWith(prefix)) {
            return {
              prefix: standardPrefix,
              id: this.name.substring(0, this.name.indexOf(prefix))
            }
          }
        }
        return false
      }

      return (
        check(['fill', 'filled'], '') ||
        check(['outline', 'outlined'], 'outlined') ||
        check(['two-tone', 'two-toned'], 'two-tone') ||
        check(['round', 'rounded'], 'round') ||
        check(['sharp', 'shapened'], 'sharp') || {
          prefix: '',
          id: this.name
        }
      )
    },
    standardClass() {
      if (this.parsed.prefix) {
        return `material-icons-${this.parsed.prefix}`
      }
      return 'material-icons'
    }
  }
}
</script>
```

Then you need to register the exact material icons you want.

```js
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import 'vuetify/src/stylus/app.styl'
import MaterialIcon from '@/components/MaterialIcon'

function missingMaterialIcons(ids) {
  const icons = {}
  for (const id of ids) {
    for (const prefix of ['fill', 'outline', 'two-tone', 'round', 'sharp']) {
      const name = `${id}_${prefix}`
      icons[name] = {
        component: MaterialIcon,
        props: {
          name
        }
      }
    }
  }
  return icons
}

Vue.use(Vuetify, {
  // iconfont: 'md',
  icons: {
    ...missingMaterialIcons(['visibility', 'visibility_off', '<ICON YOU WANT>']) 
    // This will enable 'visibility_outline', 'visibility_off_round' and so on.
  }
})
```
Finally you can use the material icons like this.
```vue
<!-- using as a prop. Be careful of double and single quotation. -->
<v-text-field
    label="password"
    :append-icon="
      pwShow
        ? '$vuetify.icons.visibility_outline'
        : '$vuetify.icons.visibility_off_outline'
    "
    @click:append="pwShow = !pwShow"
    :type="pwShow ? 'text' : 'password'"
  />

<!-- using directly as an icon component -->
<v-icon>$vuetify.icons.visibility_outline</v-icon>
```

**Comment by jjangga0214** [comment]
@MajesticPotatoe I've just checked out to and looked around `next`, but couldn't know how to run docs server. Would you let me know or cherry-pick the commits to `next` by yourself?

P.S. By the way, I personally still feels this PR is good to be added on master as well.

**Comment by sh7dm** [comment]
@jjangga0214 just run `yarn dev docs` from root or `yarn dev` from `/packages/docs`

**Comment by jjangga0214** [comment]
@sh7dm Thank you. 
Unfortunately, however, errors occur. 
Do you know how to deal with it?
Screenshot from 2019-07-04 21-15-09

Screenshot from 2019-07-04 21-13-55

**Comment by sh7dm** [comment]
@jjangga0214 run `yarn` and `yarn build` in root dir

**Comment by MajesticPotatoe** [comment]
@jjangga0214 Its not that it wont be put into master eventually, its that master is frozen right now in prep for 2.0 and the vast amount of changes between the 2 branches. Everything done in next will be merged into master by the end of the month.

**Pull request closed without merging**
