### PR TITLE
feat(VDataTable): add `foot` and `footer.prepend` slots

### LINKED ISSUE #8767: [Feature Request] tfoot in VDataTable
### Problem to solve
Able to create a `<tfoot>` element in the table which can be used for summarising the values of the table, such as summing up. Furthermore, this enables developers to use better CSS selectors rather than a class such as `.tfoot` whereas it's actually inside `<tbody>` by using `body.append` slot. This may possibly provide a better SEO and screen reader experience.

This has been proposed in #1172 and was implemented in version [0.14.8](https://github.com/vuetifyjs/vuetify/releases/tag/v0.14.8) (#1190). Since 2.0.x, the `footer` slot is repurposed for `VDataFooter` which is a pagination component stays outside of `<table>` element.

### Proposed solution
1. Repurpose `footer` slot back to creating `<tfoot>`, reasons (https://github.com/vuetifyjs/vuetify/issues/8651#issuecomment-523337233):
   > There is a `top` slot which has similar behaviour to `footer` slot but adds content before the `<table>` element instead. Should they have consistent naming, such as `top` and `bottom` or `header` (which is now occupied and appends inside `<table>` element as `<thead>`) and `footer` instead?

   However, this introduces breaking changes. A check whether all immediate descendants of the content of the `footer` slot are not `<tr>` elements may be needed. If not, wrap them inside a `<tr>` with `colspan` equals the length of `headers` to remedy the issue and reduce the effect of breaking changes.

2. Or, simply create a new slot for `<tfoot>` element.

### LINKED ISSUE #9695: [Feature Request] Add a slot in the v-data-footer before the pagination controls
### Problem to solve
This would help keep buttons and other controls associated with the table data close to it and not require more real estate. There is typically a good deal of empty space to the left of the controls in the footer. One could put an Add button or a switch to toggle the data for example.

### Proposed solution
Add a slot in the v-data-footer right before the v-data-footer__select element to utilize the space.

### PR DESCRIPTION
**Pull request by KaelWD**
resolves #8767
resolves #9695

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="desserts"
      :items-per-page="-1"
      class="elevation-1"
    >
      <template #foot>
        <tfoot>
          <tr class="text-bold grey lighten-4">
            <td class="font-weight-black">Total:</td>
            <template v-for="header in headers">
              <td
                v-if="header.value in totals"
                :key="header.value"
                class="font-weight-medium"
              >{{ totals[header.value] }}</td>
            </template>
          </tr>
        </tfoot>
      </template>
      <template #footer.prepend>
        <div>Footer prepend</div>
      </template>
    </v-data-table>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'start',
          sortable: false,
          value: 'name',
        },
        { text: 'Calories', value: 'calories' },
        { text: 'Fat (g)', value: 'fat' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Protein (g)', value: 'protein' },
        { text: 'Iron (%)', value: 'iron' },
      ],
      desserts: [
        {
          name: 'Frozen Yogurt',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          iron: '1%',
        },
        {
          name: 'Ice cream sandwich',
          calories: 237,
          fat: 9.0,
          carbs: 37,
          protein: 4.3,
          iron: '1%',
        },
        {
          name: 'Eclair',
          calories: 262,
          fat: 16.0,
          carbs: 23,
          protein: 6.0,
          iron: '7%',
        },
        {
          name: 'Cupcake',
          calories: 305,
          fat: 3.7,
          carbs: 67,
          protein: 4.3,
          iron: '8%',
        },
        {
          name: 'Gingerbread',
          calories: 356,
          fat: 16.0,
          carbs: 49,
          protein: 3.9,
          iron: '16%',
        },
        {
          name: 'Jelly bean',
          calories: 375,
          fat: 0.0,
          carbs: 94,
          protein: 0.0,
          iron: '0%',
        },
        {
          name: 'Lollipop',
          calories: 392,
          fat: 0.2,
          carbs: 98,
          protein: 0,
          iron: '2%',
        },
        {
          name: 'Honeycomb',
          calories: 408,
          fat: 3.2,
          carbs: 87,
          protein: 6.5,
          iron: '45%',
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
          iron: '22%',
        },
        {
          name: 'KitKat',
          calories: 518,
          fat: 26.0,
          carbs: 65,
          protein: 7,
          iron: '6%',
        },
      ],
    }),

    computed: {
      totals () {
        const totals = this.desserts.reduce((acc, item) => {
          Object.entries(item).forEach(([key, val]) => {
            if (key in acc) acc[key] += parseFloat(val, 10)
          })
          return acc
        }, {
          calories: 0,
          fat: 0,
          carbs: 0,
          protein: 0,
          iron: 0,
        })
        Object.keys(totals).forEach(k => {
          if (typeof totals[k] === 'number') {
            totals[k] = Number(totals[k].toFixed(2))
          }
        })
        totals.iron = totals.iron + '%'
        return totals
      },
    },
  }
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

### CODE REVIEW

**Comment by nekosaur** [comment]
Should rows in tfoot have top border by default?

image

**Comment by KaelWD** [comment]
Probably. SimpleTable is currently using `:not(:last-child)` for tbody rows, that would have to change to use `:not(:first-child)` instead.

**Review by nekosaur — APPROVED** [review]

**Comment by nekosaur** [comment]
approved, but what's up with the commits?

**Comment by KaelWD** [comment]
Some idiot merged master instead of dev

**Comment by taltukh** [comment]
When will it be merged to master?

**Comment by mdjabeer4u** [comment]
When it is going live? Need asap!

**Pull request merged**
