### PR TITLE
feat(VIcon): add font awesome support

### PR DESCRIPTION
**Pull request by Tronix117**
## Description
Font Awesome icons does not returns directly an SVG path like MDI, but an object containing more informations. One very useful information is the viewbox size, which was defaulting to 24 within VIcon.

This commit brings a new interface `VuetifyIconSVG` which can be given directly as the slot of VIcon, to handle those cases.

It also add the support for a Font Awesome SVG icon definition object to be passed directly within the VIcon slot (it will internaly be converted to a VuetifyIconSVG).

This changes is fully retro-compatible and does not change the API of VIcon.

## Motivation and Context
It solves the issue #9995, which was not resolved fully by #9996.

## How Has This Been Tested?
Unit test have been added to test the case with :
* a custom path given within a `VuetifyIconSVG` payload
* an icon definition from Font Awesome Pro 5
It has also been tested successfuly within a project with ~50 components.

unit | visually

## Markup:

<details>

```vue
<template>
  <v-row
    align="center"
    justify="center"
  >
    <v-icon>{{ icons.faDogLeashed }}</v-icon>
    <div class="mx-2"></div>
    <v-icon>{{ icons.faTachometer }}</v-icon>
    <div class="mx-2"></div>
    <v-icon>{{ icons.faInbox }}</v-icon>
    <div class="mx-2"></div>
    <v-btn
      color="primary"
      depressed
    >
      <v-icon left>{{ icons.faComments }}</v-icon>
      Comment
    </v-btn>
  </v-row>
</template>

<script>
  import {
    faDogLeashed,
    faTachometer,
    faInbox,
    faComments,
  } from "@fortawesome/pro-light-svg-icons";

  export default {
    data: () => ({
      icons: {
        faDogLeashed,
        faTachometer,
        faInbox,
        faComments,
      },
    }),
  }
</script>
```

</details>

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by Tronix117** [comment]
I'm not sure if this should be merged into the `dev` branch or into the `master` branch, please tell me so I can update the PR accordingly.

**Comment by MajesticPotatoe** [comment]
Features to dev

**Comment by johnleider** [comment]
There is quite a bit going on here and the v-icon file is started to feel bloated. We need to come up with a better way for adding support for other iconfonts, svg included, without having to hard code for each one. I'm open to ideas, but otherwise I'd like to move this request to v3.

**Comment by Tronix117** [comment]
@johnleider I agree, there should be a rewrite + this PR needs to be improved, because it's not fully compatible with base icon from within vuetify components. Indeed in some components, there is no slot to specify some icons (like $next, $prev, ...), to low in the hierarchy. On my project, I added the support for specifying SVG in the Vuetify config, but it's not yet in this PR.

**Comment by johnleider** [comment]
Unfortunately this will not be making it into the v2.3 release. With that, the structure is drastically changing for the docs here soon and v3 is a completely rewrite.

Thank you for your contribution and interest in improving Vuetify. Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
