### PR TITLE
VTreeSelect new component

### LINKED ISSUE #6089: [Feature Request] Nested v-autocomplete
### Problem to solve
Happens all the time, that if you have a nested data structure and you would want to display it in the same way as an other v-autocomplete layout. (so mounted in a v-menu + v-lists)

### Proposed solution
Allow 2 props on v-autocomplete -> "nested" & "nested-key"
if nested = true && nested-key (default ="children")
show it in a nested layout.

### PR DESCRIPTION
**Pull request by kolesnikovav**
## Description

VAutocomplete extention that allows to select from tree like data
Combines VAutocomplete and VTreeview in one
## Motivation and Context
The idea is here https://vue.ant.design/components/tree-select/
Fix #6089 
I hope, that component may be useful
Thanks for vuetify creators!
Sorry, if I make something wrong 

## How Has This Been Tested?
visually 

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-tree-select :items="itemsSimple" :chips = true  :itemValue = "id" clearable>
    <v-list-tile
      slot="prepend-item"
      ripple
    >Test prepend-item slot
    </v-list-tile>
    <v-divider
      slot="prepend-item"
      class="mt-2"
    ></v-divider>
    <v-divider
      slot="append-item"
      class="mb-2"
    ></v-divider>
    <v-list-tile
      slot="append-item"
      disabled
    >Test append-item slot</v-list-tile>
    </v-tree-select>
    <v-tree-select :items="itemsSimple" small-chips  :itemValue = "id" clearable></v-tree-select>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      itemsSimple: [
        {
          id: 1,
          name: 'Applications :',
          children: [
            { id: 2, name: 'Calendar : app' },
            { id: 3, name: 'Chrome : app' },
            { id: 4, name: 'Webstorm : app' }
          ]
        },
        {
          id: 5,
          name: 'Documents :',
          children: [
            {
              id: 6,
              name: 'vuetify :',
              children: [
                {
                  id: 7,
                  name: 'src :',
                  children: [
                    { id: 8, name: 'index : ts' },
                    { id: 9, name: 'bootstrap : ts' }
                  ]
                }
              ]
            },
            {
              id: 10,
              name: 'material2 :',
              children: [
                {
                  id: 11,
                  name: 'src :',
                  children: [
                    { id: 12, name: 'v-btn : ts' },
                    { id: 13, name: 'v-card : ts' },
                    { id: 14, name: 'v-window : ts' }
                  ]
                }
              ]
            }
          ]
        },
        {
          id: 15,
          name: 'Downloads :',
          children: [
            { id: 16, name: 'October : pdf' },
            { id: 17, name: 'November : pdf' },
            { id: 18, name: 'Tutorial : html' }
          ]
        },
        {
          id: 19,
          name: 'Videos :',
          children: [
            {
              id: 20,
              name: 'Tutorials :',
              children: [
                { id: 21, name: 'Basic layouts : mp4' },
                { id: 22, name: 'Advanced techniques : mp4' },
                { id: 23, name: 'All about app : dir' }
              ]
            },
            { id: 24, name: 'Intro : mov' },
            { id: 25, name: 'Conference introduction : avi' }
          ]
        }
      ]
    }),
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x ] The PR title is no longer than 64 characters.
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sh7dm** [comment]
This should go to `next`, not `dev`, `dev` is feature-frozen now. Features/breaking to `next`, fixes to `master`

**Comment by kolesnikovav** [comment]
I will write unit tests and merge changes with next branch as it possible. Thank you.

**Comment by sh7dm** [comment]
@kolesnikovav have you tested it on your local machine? CI failed. Please fix tests.

**Comment by kolesnikovav** [comment]
Hi. I can't complete any commit because of tslint error.
Environment:

- win10x64

- vscode

Thank you for help.

git log below

> > git commit --quiet --allow-empty-message --file -
husky > pre-commit (node v11.5.0)
yarn run v1.13.0
$ lerna run lint --parallel
lerna notice cli v3.13.0
lerna info Executing command in 3 packages: "yarn run lint"
vuetifyjs.com: $ eslint --ext .js,.vue,.json src
@vuetify/kitchen: $ eslint --ext .js,.vue src
vuetify: $ concurrently -n "tsc,tslint,eslint,types" --kill-others-on-fail "tsc --noEmit --pretty" "tslint -p . src/**/*.ts -t stylish" "eslint --ext .js,.ts src" "yarn test:types"
vuetify: [types] $ tsc -p ./types/test/tsconfig.json
vuetify: [types] yarn test:types exited with code 0
vuetify: [tsc] tsc --noEmit --pretty exited with code 0
vuetifyjs.com: c:\vuetify\treeselect\vuetify\packages\docs\src\pages\documentation\Page.vue
vuetifyjs.com:   56:5  warning  The "watch" property should be above the "asyncData" property on line 54  vue/order-in-components
vuetifyjs.com: ✖ 1 problem (0 errors, 1 warning)
vuetifyjs.com:   0 errors and 1 warning potentially fixable with the `--fix` option.
vuetify: [eslint] eslint --ext .js,.ts src exited with code 0
vuetify: [tslint] c:/vuetify/treeselect/vuetify/packages/vuetify/src/components/VDataTable/VDataTable.ts:115:29
vuetify: [tslint] ERROR: 115:29  no-inferred-empty-object-type  Explicit type parameter needs to be provided to the function call
vuetify: [tslint] 
vuetify: [tslint] tslint -p . src/**/*.ts -t stylish exited with code 2
vuetify: error Command failed with exit code 1.
vuetify: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run lint exited 1 in 'vuetify'
lerna ERR! yarn run lint stdout:
$ concurrently -n "tsc,tslint,eslint,types" --kill-others-on-fail "tsc --noEmit --pretty" "tslint -p . src/**/*.ts -t stylish" "eslint --ext .js,.ts src" "yarn test:types"
[types] $ tsc -p ./types/test/tsconfig.json
[types] yarn test:types exited with code 0
[tsc] tsc --noEmit --pretty exited with code 0
[eslint] eslint --ext .js,.ts src exited with code 0
[tslint] c:/vuetify/treeselect/vuetify/packages/vuetify/src/components/VDataTable/VDataTable.ts:115:29
[tslint] ERROR: 115:29  no-inferred-empty-object-type  Explicit type parameter needs to be provided to the function call
[tslint] 
[tslint] tslint -p . src/**/*.ts -t stylish exited with code 2
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

>

**Comment by sh7dm** [comment]
@kolesnikovav use `--no-verify` option when commiting

**Comment by kolesnikovav** [comment]
> @kolesnikovav use `--no-verify` option when commiting

@sh7dm . Thanks. You are super.

**Comment by nekosaur** [comment]
Or rebase/merge next

**Comment by MajesticPotatoe** [comment]
@kolesnikovav @sh7dm though `--no-verify` will get your commit to push, travis will still throw an error because your linting is failing. This issue happens to be something in next. shouldn't have an issue now.

**Comment by nekosaur** [comment]
@vuetifyjs/core-team What are your thoughts on including this? I am leaning towards voting to keep this in user land.

**Comment by jacekkarczmarczyk** [comment]
I'd leave it in userland if we had an option to replace the default VSelectList with user's component, but i think it's not possible now (at least not without some heavy hacking)

**Comment by sh7dm** [comment]
I think it will be nice addition

**Comment by MajesticPotatoe** [comment]
vote userland, or at the very least revisit it after refactor of select/combobox/autocomplete

**Comment by johnleider** [comment]
This is something that I would consider a userland implementation. We provide all the necessary tools to do this and it seems to be very niche.

Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by pynner** [comment]
RIP VTreeSelect, I think it's a solid component, VSelect is pretty useless for nested data. Thanks @kolesnikovav for the work, I'll be using it

**Comment by kolesnikovav** [comment]
Nice. I am so happy. @pynner 
Currently, I still working on some over improvements and customizations. 
Enjoy

**Pull request closed without merging**
