### PR TITLE
feat(VAutocomplete): make items copy-pasteable

### LINKED ISSUE #6226: [Feature Request] Chips in a multiple combobox field are not copy-pasteable, but could be
### Problem to solve
Allowing copy-paste would make for a more natural interaction from the user, as chips are not responsive to copy-paste. The user is expecting that behaviour anyway since chips are fundamentally text strings.

### Proposed solution
Add a property to the v-combobox element to allow for copy-pastable chips.

### PR DESCRIPTION
**Pull request by dima74**
## Description

1. Add listener for `copy` events in `v-autocomplete` when it is focused. Process such event by replacing copy data with text of selected item (if such exists).

2. Add listener for `paste` events on `v-combobox` input. If:

    * source of pasted text is item in another v-combobox/v-autocomplete
    * current combobox is multiple
    * search is empty
    * there are no items with same text

    then prevent default event behaviour (paste as text) and instead create new item with pasted text.

## Motivation and Context

Fix #6226

## How Has This Been Tested?

visually & unit

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-layout align-center justify-center>
      <v-flex xs4 text-xs-center>

        <v-autocomplete
          :items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
          :value="select1"
          label="1. Default"
        />
        <v-autocomplete
          chips
          :items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
          :value="select2"
          label="2. Chips"
        />
        <v-autocomplete
          multiple
          :items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
          :value="select3"
          label="3. Multiple"
        />
        <v-autocomplete
          multiple
          chips
          :items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
          :value="select4"
          label="4. Multiple Chips"
        />
        <v-autocomplete
          solo
          multiple
          chips
          label="Empty autocomplete to paste into"
        />
        <v-combobox
          solo
          multiple
          chips
          :items="['Bbb', 'Ccc']"
          label="Empty combobox to paste into"
        />
        <v-text-field
          solo
          label="Empty text field to paste into"
        />

      </v-flex>
    </v-layout>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      select1: 'Aaa',
      select2: 'Bbb',
      select3: ['Ccc', 'Ddd'],
      select4: ['Ccc', 'Ddd'],
    }),
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by dima74** [comment]
@MajesticPotatoe thank you, I moved handling for `copy` events from VCombobox to VAutocomplete, and added some tests for `paste` event. But unfortunately I don't know how to add test for `copy` events (I think it is not supported in avoriaz/jsdom: https://stackoverflow.com/a/52975164)

**Comment by jacekkarczmarczyk** [comment]
@dima74 maybe you can mock execCommand? `document.execCommand = someSpyMethod`

**Comment by dima74** [comment]
@jacekkarczmarczyk actually I don't use `execCommand` anywhere in the code, but I use

    document.addEventListener('copy', this.onCopy)

And I want to do something like `document.trigger('copy')` to simulate copy request (`document.execCommand` is roughly equivalent to usually used `wrapper.trigger`, but `document.execCommand` is not supported). Probably `this.onCopy` can be just directly called in tests.

**Comment by johnleider** [comment]
`dev` is currently on lock down and will not be accepting any PRs. As well, I would want to wait until we have the inputs upgrade to md2 before adding any new features on `next` branch.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
