### PR TITLE
fix(VCombobox): close first chip correctly

### LINKED ISSUE #15824: [Bug Report][3.0.0-beta.11] All chips vanish from Combobox if first chip from the left is "x" closed.
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.40
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Click on first chip in a combox with chips. The input field will be emptied.

### Expected Behavior
First chip is removed.

### Actual Behavior
All chips are removed.

### Reproduction Link
<a href="https://codepen.io/jjaskulowski/pen/PoeQVQp" target="_blank">https://codepen.io/jjaskulowski/pen/PoeQVQp</a>

### PR DESCRIPTION
**Pull request by 7nohe**
## Description
fixes #15824 

## Motivation and Context
`VChip` uses `useProxiedModel`and manages `modelValue` internally, so when the first chip is closed, the remaining chips do not become Active properly and all disappear.
To solve this, specify `onUpdate:modelValue` for `VChip` in `VCombobox` to manage `modelValue` on `VCombobox` side.

## How Has This Been Tested?
visually (on Playground.vue)

## Markup:
<details>

```vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-combobox
            v-model="select"
            :items="items"
            label="I use chips"
            multiple
            chips
            closable-chips
          ></v-combobox>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      select: ['Vuetify', 'Programming'],
      items: [
        'Programming',
        'Design',
        'Vue',
        'Vuetify',
      ],
    }),
  }
</script>

```
</details>

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
Looks good, but could you possibly add a test for this as well?

**Comment by KaelWD** [comment]
Thanks for your contribution @7nohe, but both this and #15871 were needed so I merged them in 380044ca8

**Comment by 7nohe** [comment]
Oh..I was writing a test for this just now.

**Comment by KaelWD** [comment]
You can open another PR for that if you like, wanted to get the fix in for release. Note that it applies to the other two components as well.

**Comment by 7nohe** [comment]
OK. I'll create a new PR for that!

**Pull request closed without merging**
