### PR TITLE
[WIP] Auto generate web-types.json to provide autocomplete for JetBrains IDEs

### LINKED ISSUE #7674: [Feature Request] Support jetbrains web-types standard
### Problem to solve
Code completion and hints in jetbrains IDEs

### Proposed solution
Publish a web-types.json file to npm and link it in package.json

https://github.com/JetBrains/web-types
https://youtrack.jetbrains.com/issue/WEB-31682#comment=27-3538850

### PR DESCRIPTION
**Pull request by vaibhavhrt**
- [ ] closes #7674 
- [ ] tests added/passed

### CODE REVIEW

**Comment by vaibhavhrt** [comment]
@KaelWD so the method `writeJsonFile` converts a given js object to json file. I will just have to create an object in js which matches the schema of web-types.json and use `writeJsonFile` on it. Correct me if I am wrong.

**Comment by vaibhavhrt** [comment]
Also I make a lot of commits, hope you guyz squash and merge to keep your repo's git history clean.

**Comment by jacekkarczmarczyk** [comment]
Thanks for your effort, it should go to the `next` branch though, we'll squash it
I see you're passing `components` object to your method, but maybe (I'm not sure, it's just a thought) it would be easier to process our api.json file instead?

**Comment by vaibhavhrt** [comment]
@jacekkarczmarczyk so I need to open PR for the branch `next`?

**Comment by vaibhavhrt** [comment]
It's getting messed up, I will close this, create a new branch on my fork from upstream/next and open a new PR.

**Comment by vaibhavhrt** [comment]
I can't find `api.json`, it's `api.js` and it's created from `components` and `directives`. So why not create my own web-types object from `components` and `directives` instead of using `api.js`.

**Pull request closed without merging**
