### PR TITLE
fix(types): add declaration for vuetify/lib/components

### PR DESCRIPTION
**Pull request by Djaler**
## Description
Vuetify has separated `declare module` for `vuetify/lib/directives`. This add `vuetify/lib/components` too.

## Motivation and Context
Now we can do something like `import * as VuetifyComponents from 'vuetify/lib/components';` without typescript errors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
I think it looks but not sure what is the best way to test it, after adding this to node_modules/vuetify/types/lib.d.ts i still have ts error (both in IDE and during compilation)
Also the components list was updated so should be updated in this PR as well

**Comment by Djaler** [comment]
Yeah, I'm able to reexport them (but still need to list them all.
We can make it vice versa - declare types in `vuetify/lib/components` and `vuetify/lib/directives` and then just do 
```
export * from 'vuetify/lib/components'
export * from 'vuetify/lib/directives'
```
in `vuetify/lib` module.
What do you think about it? @johnleider

**Comment by jacekkarczmarczyk** [comment]
Sounds good for me

**Comment by Djaler** [comment]
So here it is

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
