### PR TITLE
Fix(docs): import directives with lowercase

### PR DESCRIPTION
**Pull request by DRoet**
## Description

Directive exports became lowercase in `2.0`, this should be reflected in the docs

## Motivation and Context

small fix

## How Has This Been Tested?

none

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
This exists in quite a few more places: 
image

**Comment by johnleider** [comment]
Should we also normalize this in our components?

image

**Comment by DRoet** [comment]
We could, but those components are currently using the default export so it shouldn't matter

**Comment by MajesticPotatoe** [comment]
I would say we should, for consistency. Can already see one in there that's lowercase among the rest of uppercase ones

**Pull request merged**
