### PR TITLE
fix(v-window-item) render with transition="false"

### PR DESCRIPTION
**Pull request by buzzzzer**
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by buzzzzer** [comment]
v1.3.0-alpha.2

when i use
<v-tab-item  :transition="false" :reverse-transition="false"/>
Transition starts and does not end and sometimes i got strange artifacts.

image


here is example: https://codepen.io/Buzzzzer/pen/mzWYde

**Comment by johnleider** [comment]
Please update the snapshots and add a unit test.

**Comment by johnleider** [comment]
This is the final PR I would like to get in for v1.3. Close-off will be tomorrow. After that we'll push to next patch.

**Comment by buzzzzer** [comment]
@johnleider 
Snapshot updated.
Add unit test quickly  still hard for me. :(
need mode experience

**Comment by johnleider** [comment]
This has been resolved in 4af99de2e979ade669d3f479346101e530f5cddc

**Comment by buzzzzer** [comment]
@johnleider, on 1.3.3 the same.

image

Transitions resolved only on mouse focus
After mouse focus on tab content:
image

**Pull request closed without merging**
