### PR TITLE
feat(VColorPicker): add hideSliders property

### LINKED ISSUE #11138: [Feature Request] v-color-picker new prop to hide sliders / show swatches only ?
### Problem to solve
In my use case, I'd like to enable the user to only pick a color among a predefined set of colors (aka. `swatches`) But there is no prop to remove these sliders :
image

Would it be possible to add this feature ?

From now on I did this :

```
<v-color-picker
  flat
  hide-canvas
  hide-inputs
  show-swatches/>
```

which result in this :

image

### Proposed solution
Add a prop `hide-sliders` (or whatever the name) so that it can be hidden.

Then it would be possible to have a colorpicker that looks like this (if `:swatches` is defined of course or it displays the full list) :

image

### PR DESCRIPTION
**Pull request by ryo-gk**
## Description

Hide sliders if `hide-sliders` prop is true.

## Motivation and Context

closes #11138
## How Has This Been Tested?

visually, unit test
## Markup:

<details>

```vue
<template>
  <v-app class="ma-3">
    <v-color-picker
      flat
      :hide-inputs="hideInputs"
      :hide-sliders="hideSliders"
      show-swatches
    >
    </v-color-picker>
  </v-app>
</template>

<script>
export default {
  data () {
    return {
      hideInputs: false,
      hideSliders: true,
    }
  },
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by pechpaul** [comment]
I'd like to have that spec for a project too, would be nice if someone could approve the merge

**Review by KaelWD — CHANGES_REQUESTED** [review]
Looks alright, please resolve merge conflicts and it can go in.

**Comment by Mikilll94** [comment]
@KaelWD 
It seems that this PR is abandoned. That's why I have created a new PR where the conflicts are resolved -> https://github.com/vuetifyjs/vuetify/pull/12618

**Comment by ryo-gk** [comment]
@Mikilll94
I was just about to do this,
but fortunately you took over this.
Thank you.

**Pull request closed without merging**
