### PR TITLE
docs: fix focusing search input by pressing '/'

### LINKED ISSUE #9911: [Documentation] Hitting "/" won't focus the search input
### Environment

**Browsers:** Firefox 70.0, Google Chrome, Mozilla Firefox
**OS:** Linux, Ubuntu undefined

### Steps to reproduce
I'm using a Portugues keyboard, and can't focus on the search input with shift+7 or the keypad / . I have tested this in multiple computers with different linux distros and on firefox and chrome, all using a PT keyboard.

### Expected Behavior
When hitting the "/" to focus the search input.

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://vuetifyjs.com/en/" target="_blank">https://vuetifyjs.com/en/</a>

### PR DESCRIPTION
**Pull request by ToasteR1032**
## Description

Before this fix, pressing the slash key did not (always) focus the search input.

Fixes #9911

## Motivation and Context

Fixes #9911

## How Has This Been Tested?

Visually by pressing the "slash" key and confirming that the search input field is focused.

## Markup:

<details>
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by annymosse** [comment]
@ToasteR1032 i use `shift+/` to focus; the placeholder must be update or must merge your PR.

**Comment by ToasteR1032** [comment]
> @ToasteR1032 i use `shift+/` to focus; the placeholder must be update or must merge your PR.

Ah okay. The problem with Shift+/ is that many Keyboard Layouts (e.g. the German one) don't have a separate '/' key. Instead you have to press Shift+7 (on a German Keyboard). Thus, Shift is already used to get the slash character and cannot be used as a part of the shortcut anymore. Of course you could use the '/' (or ÷) key on the numpad instead, but many keyboards, like laptop keyboard layouts, are missing a numpad.

**Comment by ToasteR1032** [comment]
@MajesticPotatoe what do you think of this small change?

**Comment by MajesticPotatoe** [comment]
@ToasteR1032 It functions the same at least on a US keyboard. Cant say for other keyboard denominations. I would like some input from the other team members before I commit it though as this has been a topic of discussion in the past.

**Pull request merged**
