### PR TITLE
fix(types): declare vuetify/lib/services/goto module

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Motivation and Context
#13812 was not enough

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Why would you need to import this separately? It's already on the vuetify instance.

**Comment by jacekkarczmarczyk** [comment]
So that I don't need to import vuetify instance, mainly for composition api
Anyway feel free to close if using $vuetify.goTo is obligatory

**Comment by zoton2** [comment]
Another point to make is that the documentation example for using "use with router" also won't resolve types with the current setup either: https://vuetifyjs.com/en/features/scrolling/#use-with-router

**Comment by KaelWD** [comment]
OK I wasn't aware we were documenting it that way, if that's the case then this should probably go in. 

`/es5` is legacy, we do have some type definitions for it but it was mostly kept to ease the 2.0 upgrade slightly.

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
