### PR TITLE
Feat/v3 stepper

### PR DESCRIPTION
**Pull request by MFJamil**
## Markup:

```vue

```

### CODE REVIEW

**Comment by MFJamil** [comment]
Migrating the Stepper Component

**Comment by nekosaur** [comment]
You will need to clean up this PR.

- It should point to `dev`
- It should only contain the relevant commits for the feature
- Please add description and markup

**Comment by MFJamil** [comment]
I will create another PR based on the latest DEV Version according to the discussions on discord. Planning to inform you guys on Discord about the url for the new PR

**Comment by MajesticPotatoe** [comment]
Currently Obsolete. Steppers already released to labs.

**Pull request closed without merging**
