### PR TITLE
fix [Bug Report] Search not paginate #3322

### PR DESCRIPTION
**Pull request by IgorDePaula**
## Description
Correct the paginate react with search results.

## Motivation and Context
The paginate not react with search results. On search, the paginate not react with results of search.

## How Has This Been Tested?
No with tester tools, but only change the source and build to browser.

## Markup:
```
itemsLength () {
      if (this.search) return this.searchLength
      if (this.search) return this.totalItems
       return this.totalItems || this.items.length
       return this.totalItems || this.items.length
     },
     },
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
Can you please give some additional information in regards to what this fixes. An existing issue perhaps, or a minimal reproduction of the bug.

**Comment by IgorDePaula** [comment]
https://github.com/vuetifyjs/vuetify/issues/3322

I used the search from datatables in database, but,  the datatables show only the quantity configureted, without paginate, the paginate not works.

**Comment by johnleider** [comment]
Can you please fill out the required fields in this PR

**Comment by IgorDePaula** [comment]
I not fill all fields because not everything is true: I put my PR on wrong branch,  my change NOT requires a change to the documentation etc.

**Comment by johnleider** [comment]
I'm talking about this:

image

**Comment by IgorDePaula** [comment]
Finish?

**Comment by nekosaur** [comment]
Markup should be the HTML markup that shows the problem/that you tested with

**Comment by IgorDePaula** [comment]
But the problem not occur with html markup, but on intern calc of results of the paginate.

**Comment by nekosaur** [comment]
I meant, what does the HTML markup look like that shows this problem.

**Comment by johnleider** [comment]
I have to double check but I think this https://github.com/vuetifyjs/vuetify/commit/e57229d09e33a920575f0fdaa3c4b2edff513d4f might resolve this

**Comment by johnleider** [comment]
This appears to be resolved by https://github.com/vuetifyjs/vuetify/commit/e57229d09e33a920575f0fdaa3c4b2edff513d4f

**Pull request closed without merging**
