### PR TITLE
Enh/foreach optimizations

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
Replaced `forEach` with `for(;;)` or `for ... of` loops (everywhere, just for consistency)

### CODE REVIEW

**Comment by smares** [comment]
Just a side-note: According to https://jsperf.com/foreach-vs-for-of only Chrome performs better with for...of vs. forEach, while IE 11, Edge 16 and Firefox 57 are all much worse.

**Comment by KaelWD** [comment]
Vuetify uses babel, yo you should compare https://jsbench.me/7ejagsewtr instead.

**Comment by jacekkarczmarczyk** [comment]
With babel it's even worse :/

Firefox:
for(;;) - 15.000.000 op/s
forEach - 4.000.000 op/s
for of - 450.000 op/s
babel - 170.000 op/s

Chrome:
for(;;) - 9.000.000 op/s
forEach - 710.000 op/s
for of - 3.000.000 op/s
babel - 3.100.000 op/s

**Comment by smares** [comment]
Yup, I can confirm, Firefox for of babel 243,757 ops/s, forEach 6,573,502 ops/s. Edge won't run so I opened https://jsperf.com/foreach-vs-for-loop-vs-for-in-vs-for-of-vs-babel-for-of in Edge and got 6,520 for of babel and 331,662 forEach.

**Comment by KaelWD** [comment]
The jsperf test is broken, that why I moved it to jsbench in the first place.

**Comment by smares** [comment]
I see. Anyways, the test with Firefox was ran on jsbench and there forEach is faster than for of babel. :/

**Comment by smares** [comment]
Just updated from Chrome 62 to 63 and now I am getting better results with forEach even in Chrome.

for(;;) - 11,181,912 ops/s
forEach - 4,298,081 ops/s
for of - 3,903,166 ops/s
babel - 3,919,877 ops/s

**Comment by jacekkarczmarczyk** [comment]
Just in time @smares , I was about to go for `for(;;)`...
I guess with Chrome 63 it's ok to stay with `forEach`, isn't it?

**Comment by smares** [comment]
for(;;) is fastest with every browser, but forEach has decent performance now in Chrome, too.

**Pull request merged**
