### PR TITLE
fix(inputs): reset value to null instead of undefined

### LINKED ISSUE #7429: [Bug Report] Form reset should set value to null
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 75.0.3770.80
**OS:** Linux x86_64

### Steps to reproduce
Press "Reset" button

### Expected Behavior
Resetting form should set input value to null (according to docs) 

### Actual Behavior
Resetting form set input value to undefined

### Reproduction Link
<a href="https://codepen.io/anon/pen/zQVmob?editors=1010#0" target="_blank">https://codepen.io/anon/pen/zQVmob?editors=1010#0</a>

### PR DESCRIPTION
**Pull request by KaelWD**
## Description

This fixes some inconsistencies when resetting input fields. 

- **v-text-field** would reset to `null` when clear was clicked, but `undefined` in a form.  
- **v-select** and variants, and **v-file-input** would reset to `undefined` or `[]` if multiple.  
- **v-autocomplete** and **v-combobox** would reset `search-input` to `null`, unless clear was clicked then it would be `undefined` instead

With this change these will all be `null` or `[]`, allowing values to be sent as JSON without having to check for `undefined` first. 

This is technically a breaking change if someone was relying on `form.reset()` to reset inputs to `undefined` but this is unlikely and can easily be worked around by setting the values manually afterwards.  
**v-select** also now re-selects an item with `value: null` if the clear button is clicked (#4431, unit test). Again, unlikely to actually be a problem (either intended behaviour or not using both clearable and a null item) and easily worked around by implementing the clear button yourself with `append-icon` and `@click:clear`. 

The consistency is worth these low-impact changes in my opinion. 

Some sort of clear-value prop (#4144, #7441) would be even better, but the PR was abandoned and apparently had problems with non-falsy values. 

fixes #7429

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

---

Untested outside of existing unit tests btw, might be scuffed

### CODE REVIEW

**Review by johnleider — DISMISSED** [review]

**Review by sindilevich — CHANGES_REQUESTED** [review]
Hello, this is a great PR that tremendously streamlines handling inputs' data!
I thought to highlight, however, that some traces of `undefined` are still left unaltered. I can't tell whether they'd matter at all, but thought it'd better to point them out:
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L54
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L99
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L180
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts#L288
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VFileInput/VFileInput.ts#L69-L70
- https://github.com/vuetifyjs/vuetify/blob/4a1bf59bfe83a395fac8bc07480b2beee5eb37be/packages/vuetify/src/components/VSelect/VSelect.ts#L122-L124

Hope it helps, and thank you.

**Comment by KaelWD** [comment]
Good catch, thanks.

**Review by johnleider — APPROVED** [review]
It's outside of this issue's scope but I think we should explore exposing the reset process so the user could set it to whatever they want.

**Comment by sindilevich** [comment]
> It's outside of this issue's scope but I think we should explore exposing the reset process so the user could set it to whatever they want.

Letting user a way to control the reset value - is a great idea! Hope someone could come up with an appropriate PR.

**Pull request merged**
