### PR TITLE
style(VNavigationDrawer): The internal avatar is displayed in the center of the menu collapse

### PR DESCRIPTION
**Pull request by Nisekoi5**
Related to https://github.com/vuetifyjs/vuetify/issues/18561
But I later discovered that the reduction of the internal avatar might be intentional.
Because you can keep a similar size to the icon below
https://vuetifyjs.com/zh-Hans/components/navigation-drawers/#section-7a84578b53d853166548679c 
The avatar in the menu here in the document will be scaled but not centered when folded
This modification worked for my use case and no other errors occurred after applying it.
Maybe css selectors should be more rigorous. Can you provide some comments?

before 

v1

after

v2

### CODE REVIEW

**Comment by johnleider** [comment]
We need a less flimsy way of dealing with this over different densities.

**Comment by Nisekoi5** [comment]
> We need a less flimsy way of dealing with this over different densities.

I checked why it happened and found out that the reason was because the style `v-list-item--nav` set `padding-inline: $list-nav-padding` which broke the padding setting of `v-list-item`
This submitted change makes `v-list-item--nav` will only take effect on the sub-elements of `v-list`

**Comment by johnleider** [comment]
This is the playground I'm talking about. https://play.vuetifyjs.com/#eNq1VU1v1DAQ/Ssml4JEktKlElptEb0hBEdOLIchmd0Y/CV7Erqq+t8ZO7ttks3uAbW5JJ73PH7jsV9+3GfBV+Wtc0XXYrbMVoTaKSD8uDZCrLocnEufaVBZQyAN+n2oD4KvH8cpomBnWxrEUtRAJ7dA0pq89vAX/RAXosu1rVHdrLM9mo3xpQcZ0fiaYg69BoOGxuFPlZLVn/0ccSM2oAKO545E9uJlIFGjCZJ2PLWy2kFF60yw/gn7kZ9L3rYpxrI8OjR1Dh0QeE7WELmwLEsPpra6DegLjSU4WTrriVVSKDWa8sN18dttp1XGhyQp5ExfbGPEV5T18UbFh7VOg0faWf2h2bz5QVlacrNZ7wwzVfqLzBzCrQMvwRDLIrzjrZpnST49TNG1zKsGO8/nQOHmJL1vXhHIuqcOvprr/r6+VZkkztVZjk71GBp08D/bOyissRrzik/Oud59ZtIc3oFqIx6THOOpvmeUClVlW74xZ4R+24nb06yD3JOJXkhxvvW2dTk7jGIrOqf/O1+wcE56vIEzhLPCD9jY3jh45G9TA9RsnSLQLmlrUG4bWoqr60t3t87SkpEwdNK40thKY2jgt2k48uQY6S17dOh5GCovHYmA1PaOLnU0HXEvPG7Eg9h4q8UF/wUuIshZow2mOvjeMeU1+RbfPGH7GzlAVmW/BmfPHt5mi+J9cZmDcg0U77I4XhRXi+znPwbVw2o=

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
