### PR TITLE
fix(VCheckbox) label slot rendering

### PR DESCRIPTION
**Pull request by Yiin**
## Description
Pass `default` and `label` slots to `VSelectionControl` component.

## Motivation and Context
Currently, `label` slot is not being rendered on `VCheckbox` component.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
Please provide a test playground.

**Comment by Yiin** [comment]
Reproduction can be seen on examples page:
https://next.vuetifyjs.com/en/components/checkboxes/

**Comment by Yiin** [comment]
The same issue is also present in VSwitch component. I can include it in this PR as well, but maybe you have a better idea on how to solve it.

**Comment by johnleider** [comment]
The fix for this was not that complex. I've resolved this on next with ba892ae98.

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
