### PR TITLE
Fix: Prevent stylus variable vs. animation name collision ("query")

### PR DESCRIPTION
**Pull request by detroitenglish**
## Description

This bugfix prevents the final value of the stylus iteration variable "query" from being injected as the v-linear-progress component's animation title of the same name.

## Motivation and Context

"query" is used as both a non-prefixed variable in _display.styl and an animation name used in v-linear-progress:

stylus-collision

This results in the final iteration value being injected in place of the animation name "query":

stylus-keyframe-fuckups

## How Has This Been Tested?

Proposed change allows building app.css with intended animation name:

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
Should we be using a different naming convention for these iterables?

**Comment by KaelWD** [comment]
image

Links: [first](http://stylus-lang.com/try.html#?code=%24breakpoints%20%3A%3D%20%7B%0A%20%20one%3A%20%27one%27%0A%20%20two%3A%20%27two%27%0A%7D%0A%0A%0Afor%20size%2C%20query%20in%20%24breakpoints%0A%20%20.hidden%0A%20%20%20%20%26-%7Bsize%7D%0A%20%20%20%20%20%20%40media%20query%0A%20%20%20%20%20%20%20%20display%3A%20none%0A%20%20%0A%40keyframes%20query%0A%20%200%25%0A%20%20%20%20width%2010px), [second](http://stylus-lang.com/try.html#?code=%24breakpoints%20%3A%3D%20%7B%0A%20%20one%3A%20'one'%0A%20%20two%3A%20'two'%0A%7D%0A%0A%0Ahidden()%0A%20%20for%20size%2C%20query%20in%20%24breakpoints%0A%20%20%20%20.hidden%0A%20%20%20%20%20%20%26-%7Bsize%7D%0A%20%20%20%20%20%20%20%20%40media%20query%0A%20%20%20%20%20%20%20%20%20%20display%3A%20none%0A%20%20%0Ahidden()%0A%20%20%0A%40keyframes%20query%0A%20%200%25%0A%20%20%20%20width%2010px)

**Comment by KaelWD** [comment]
- add `$` to all variables
 - put the loop in a function so it doesn't leak

**Comment by detroitenglish** [comment]
> add `$` to all variables

But it isn't future-proof... `$query` becomes a booby-trap for future component authors 🙈 Declaring  `$<name> = <value>` is the stylus equivalent of `const <name> = <value>` imo

> put the loop in a function so it doesn't leak

This would work - not sure how to standardize it, though. Playing around with some concepts... [A kind of utility function](http://stylus-lang.com/try.html#?code=_invoke(args...)%0A%20%20fn%20%3D%20pop(args)%0A%20%20fn(args)%0A%0A_breakpoints(obj)%0A%20%20for%20size%2C%20query%20in%20%24breakpoints%0A%20%20%20%20.hidden%0A%20%20%20%20%20%20%26-%7Bsize%7D%0A%20%20%20%20%20%20%20%20%40media%20query%0A%20%20%20%20%20%20%20%20%20%20display%3A%20none%0A%0A%24breakpoints%20%3A%3D%20%7B%0A%20%20pancakes%3A%20'mobile'%0A%20%20waffles%3A%20'desktop'%0A%7D%0A%0A_invoke(%24breakpoints%2C%20_breakpoints)%0A%20%20%0A%40keyframes%20query%0A%20%200%25%0A%20%20%20%20width%2010px), maybe?

I personally think using a dedicated prefix like `for _size, _query in $breakpoints` for iterables is the simplest solution... also easiest to lint if there's ever an official Vuetify styleguide ;)

**Comment by johnleider** [comment]
I agree with the future proofing, but the styles files in general need love, and that could be part of a larger effort, maybe 1.3 era. For now, this is great.

**Pull request merged**
