### PR TITLE
fix(VDataTable): make expand button focusable

### LINKED ISSUE #9939: [Bug Report] Expand Row Button Not Tab Accessible
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 7

### Steps to reproduce
Start with the focus outside of a table that has an expand row.
Press tab.
Focus never lands on the expand row button.

### Expected Behavior
Focus lands on the expand row button. 
Expand Row aria-label and aria-expanded values are read to the screen reader.
Pressing enter, expands and collapses the expansion area.

### Actual Behavior
Expand Button cannot be tabbed to.

### Reproduction Link
<a href="https://codepen.io/rkrasnan/pen/oNgxBOz?&editable=true&editors=101" target="_blank">https://codepen.io/rkrasnan/pen/oNgxBOz?&editable=true&editors=101</a>

### PR DESCRIPTION
**Pull request by phiter**
## Description
This PR makes the expand buttons in VDataTables focusable and adds the `aria-expanded` attribute.

## Motivation and Context
The current expand buttons in VDataTables are not focusable and have no expanded state information, which breaks accessibility
fixes #9939 

## How Has This Been Tested?
I updated the snapshots for VDataTables because of the changes. I did test it visually and with NVDA.

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="desserts"
      :expanded.sync="expanded"
      item-key="name"
      show-expand
      class="elevation-1"
    >
      <template v-slot:top>
        <v-toolbar flat>
          <v-toolbar-title>Expandable Table</v-toolbar-title>
        </v-toolbar>
      </template>
      <template v-slot:expanded-item="{ headers }">
        <td :colspan="headers.length">Peek-a-boo!</td>
      </template>
    </v-data-table>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      expanded: [],
      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'left',
          sortable: false,
          value: 'name',
        },
        { text: 'Calories', value: 'calories' },
        { text: 'Fat (g)', value: 'fat' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Protein (g)', value: 'protein' },
        { text: 'Iron (%)', value: 'iron' },
        { text: '', value: 'data-table-expand' },
      ],
      desserts: [
        {
          name: 'Frozen Yogurt',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
          iron: '1%',
        },
        {
          name: 'Ice cream sandwich',
          calories: 237,
          fat: 9.0,
          carbs: 37,
          protein: 4.3,
          iron: '1%',
        },
        {
          name: 'Eclair',
          calories: 262,
          fat: 16.0,
          carbs: 23,
          protein: 6.0,
          iron: '7%',
        },
      ],
    }),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by phiter** [comment]
This was fixed by 86133ea but this PR also changes the expand icon with an actual button which probably gives it a better look.

**Comment by phiter** [comment]
Oh dammit it's a conflict because of a snapshot because of 86133eabf01f3748056b6eae0a54d073e606f013

**Comment by phiter** [comment]
I agree. They're definitely useful for custom elements.

**Comment by nekosaur** [comment]
Agreed

**Comment by johnleider** [comment]
I've fixed the conflicts, what's left to do with this PR?

**Comment by phiter** [comment]
As I mentioned before, this was fixed in https://github.com/vuetifyjs/vuetify/commit/86133eabf01f3748056b6eae0a54d073e606f013 and subsequently the clickable icons got replaced with buttons, so this PR has no point any longer.

As discussed with @johnleider on discord, we'll be closing it.

**Pull request closed without merging**
