### PR TITLE
feat(VCard): add hover effect when focusing

### PR DESCRIPTION
**Pull request by cawa-93**
## Description
When navigating using the keyboard, the v-card:focus has no visual confirmation. It is necessary to add a similar visual elevation as when hovering the cursor

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-card hover to="/">
      <v-img :aspect-ratio="225/314" src="https://fakeimg.pl/225x314/"></v-img>
    </v-card>
  </v-container>
</template>
```
</details>

Demo with problem: https://codepen.io/cawa-93/pen/gVBEmP?editors=1000
Demo with suggested changes: https://codepen.io/cawa-93/pen/xvyBdm?editors=1100

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
Missing playground markup @cawa-93

**Comment by cawa-93** [comment]
@nekosaur I don't really understand what you mean.  I do not change the standard of behavior in any way and do not add new behavior.  I just suggest complementing your existing behavior.  To take the example, the focus and focus are identical.  I think cards should be done the same way.

**Comment by jacekkarczmarczyk** [comment]
He just asked you to provide a sample code where we could compare the behaviour before and after PR, see the `Markup` section in other PRs, for example <https://github.com/vuetifyjs/vuetify/pull/8409>

**Comment by cawa-93** [comment]
Oh. Ok. I will make this later

**Comment by cawa-93** [comment]
@nekosaur I added playground markup and codepen demos

**Comment by johnleider** [comment]
Why only apply when using the hover prop? The same issue would apply for regular cards as well.

**Comment by cawa-93** [comment]
I think the focus and the hover are the same. And they should behave the same way (with some very rare exceptions). If there is no hover effect on the card, then this effect is not required when focusing.

**Comment by johnleider** [comment]
Remove the **hover** prop and try to focus those cards. The first 2 aren't noticed at all.

**Pull request merged**
