### PR TITLE
fix(VNavigationDrawer): use right by default on RTL

### PR DESCRIPTION
**Pull request by melbahja**
## Description
Add right by default to VNavigationDrawer in rtl 

## Motivation and Context
This PR fix: #8461 

## Markup:
<details>

```vue
<template>
  <div>
      <v-app-bar>
        <v-app-bar-nav-icon class="mx-1" @click="drawer = !drawer" /></v-app-bar-nav-icon>
        <v-toolbar-title>Title</v-toolbar-title>
  
        <v-toolbar-items>
          <v-btn text>Link 1</v-btn>
          <v-btn text>Link 2</v-btn>
          <v-btn text>Link 3</v-btn>
        </v-toolbar-items>
  
        <v-spacer></v-spacer>
  
        <template v-if="$vuetify.breakpoint.smAndUp">
          <v-btn icon>
            <v-icon>mdi-export-variant</v-icon>
          </v-btn>
          <v-btn icon>
            <v-icon>mdi-delete-circle</v-icon>
          </v-btn>
          <v-btn icon>
            <v-icon>mdi-plus-circle</v-icon>
          </v-btn>
        </template>
      </v-app-bar>

      <v-col cols="12" class="text-center">
        <v-btn class="primary mt-5" @click="$vuetify.rtl = !$vuetify.rtl"> 
          Toggle RTL 
        </v-btn>
      </v-col>

      <v-col v-if="$vuetify.rtl === false" cols="12" class="text-center">
        <v-btn class="primary mt-5" @click="right = true"> 
          Force Right
        </v-btn>
      </v-col>
      
      <v-navigation-drawer
      v-model="drawer"
      absolute
      :right="right"
      temporary
    >
      <v-list-item>
        <v-list-item-avatar>
          <v-img src="https://randomuser.me/api/portraits/men/78.jpg"></v-img>
        </v-list-item-avatar>

        <v-list-item-content>
          <v-list-item-title>John Leider</v-list-item-title>
        </v-list-item-content>
      </v-list-item>

      <v-divider></v-divider>

      <v-list dense>

        <v-list-item
          v-for="item in items"
          :key="item.title"
          link
        >
          <v-list-item-icon>
            <v-icon>{{ item.icon }}</v-icon>
          </v-list-item-icon>

          <v-list-item-content>
            <v-list-item-title>{{ item.title }}</v-list-item-title>
          </v-list-item-content>
        </v-list-item>
      </v-list>
    </v-navigation-drawer>
  </div>
</template>


<script>
export default
{
	data () 
	{
      return {
        drawer: true,
        right: false,
        items: [
          { title: 'Home', icon: 'dashboard' },
          { title: 'About', icon: 'question_answer' },
        ],
      }
    },
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
This seems like it could be solved easier with updating the default value of the `right` prop.

```
right: {
  type: Boolean,
  default () {
    return this.$vuetify.rtl
  }
}
```

**Comment by melbahja** [comment]
@johnleider I tested that but what if the app switches from rtl to ltr and ```right``` prop not passed the drawer should go back to left by default. 
i think if devs pass a ```:right="$vuetify.rtl"``` prop will solve this problem

**Comment by jacekkarczmarczyk** [comment]
How do we display the drawer on the left side in RTL mode with this PR?

**Comment by melbahja** [comment]
@jacekkarczmarczyk i got your point
but did you mean on rtl ```right``` prop becomes left?
for example mr-1 on rtl mode we changed to margin left.

**Comment by jacekkarczmarczyk** [comment]
`mr-1` in RTL is still margin-right
I think we need to live with `:right="$vuetify.rtl"` solution for now, maybe in 3.0 we could replace `right` prop with `opposite`

**Comment by melbahja** [comment]
Yes i think this PR should be closed ;)

**Pull request closed without merging**
