### PR TITLE
feat: v-autocomplete custom highlighting

### PR DESCRIPTION
**Pull request by coyotte508**
## Description

Provides a way to specify the highlighted portion in the matches for `VAutocomplete`.

This is done by allowing the `filter` prop to return a range (`[number, number]`) instead of `true` when there is a match. The range is then used to only highlight the corresponding portion of the item's text.

## Motivation and Context

As discussed in https://github.com/vuetifyjs/vuetify/issues/4417, it provides a way to easily implement a diacritic-insensitive `VAutocomplete` with proper highlighting.

## How Has This Been Tested?

In progress

## Markup:

In progress
<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by coyotte508** [comment]
Note: Currently the filter function is called twice for every item, once to test if it should be present, and another to get the highlight range.

Calling it once should be possible but it involves quite a bit more refactoring instead of the few changes.

**Comment by johnleider** [comment]
Pulse check on this PR.

**Comment by coyotte508** [comment]
Sorry, I don't know when I'll get time to look into the doc and tests

**Comment by johnleider** [comment]
At this time the team is not considering any feature requests for the v2.x Major. If you are interested in working with the team on the v3 implementation, please reach out to us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
