### PR TITLE
feat(v-data-table): no-data/no-results slots can take tr/tds

### LINKED ISSUE #2504: [Feature Request] Let user determine full content of table no-data slot
### New Functionality
Currently content in `no-data` is put inside a single `<td>` that spans the entire table.
I want to provide my own `<tr>` and `<td>`s just like I can with the default table slot.

This demonstrates what I want to do: https://codepen.io/beedesignllc/pen/xPrepX

### Improvements
No current workaround

### Bugs or Edge Cases it Helps Avoid
This gives the user more flexibility and control.

It's probably a breaking change, so you may want to get it in before v1

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
using the same logic as in the items slot, no-data and no-results slots can now define their own tr and/or td tags.

people currently using the slots will have to wrap their slot content in `<td colspan="100%"></td>` if they want the original functionality

## Motivation and Context
fixes #2504

## How Has This Been Tested?
created new tests

## Markup:
```
<v-data-table>
  <template slot="no-data">
    <td colspan="2">
      <v-alert :value="true" color="error" icon="warning">
        Sorry, nothing to display here :(
      </v-alert>
    </td>
  </template>
</v-data-table>
```

```
<v-data-table>
  <template slot="no-data">
    <tr>
      <td>
        <v-alert :value="true" color="error" icon="warning">
          Sorry, nothing to display here :(
        </v-alert>
      </td>
    </tr>
  </template>
</v-data-table>
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Any reason why dev can't just do 
```vue
<v-data-table>
  <template slot="no-data">
      <v-alert :value="true" color="error" icon="warning">
        Sorry, nothing to display here :(
      </v-alert>
  </template>
</v-data-table>
```?

**Comment by nekosaur** [comment]
No reason they can't. I mean if it's just text you can just as well use the `no-data-text` prop. It's just that since we don't automatically do colspan 100% anymore people will need to make the change to keep original functionality

**Comment by mahmoudrady248** [comment]
please how can replace loading in Data table ?

**Comment by nekosaur** [comment]
If you have questions please go to our [chat](https://chat.vuetifyjs.com).

**Pull request merged**
