### PR TITLE
vslider: prop decreasing allows max on left and min on right

### PR DESCRIPTION
**Pull request by sureshvv**
Implementation is very similar to global Vue rtl setting but specific setting is local to the particular v-slider.

## Motivation and Context

1. Needed just one particular slider to have a decreasing mode - max on the left and min on the right

## How Has This Been Tested?

Manual testing only.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [ x] The PR title is no longer than 64 characters.
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sureshvv** [comment]
Fixes https://github.com/vuetifyjs/vuetify/issues/6763

**Comment by sureshvv** [comment]
Screenshot from 2019-03-23 11-35-09

**Comment by sh7dm** [comment]
@sureshvv please use `master` branch for bug fixes, `next` for features. `dev` is frozen now, v1.6 isn't planned.

**Comment by sureshvv** [comment]
@MajesticPotatoe Have created #6814

**Comment by MajesticPotatoe** [comment]
closed in favor of #6814

**Pull request closed without merging**
