### PR TITLE
fix: change curser:default selector to [aria-disabled="true"]

### LINKED ISSUE #11003: [Bug Report] Wrong cursor on [aria-disabled] selector
### Environment
**Vuetify Version:** 2.2.20
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Add [aria-disabled="false"] on any element

### Expected Behavior
Cursor shouldn't change

### Actual Behavior
Cursor changes to "default"

### Reproduction Link
<a href="https://codepen.io/letmecode/pen/gOpybMG" target="_blank">https://codepen.io/letmecode/pen/gOpybMG</a>

### Other comments
The selector in _reset.scss for "cursor: default" should be `[aria-disabled="true"]` instead of `[aria-disabled]`. Currently it also applies to `[aria-disabled="false"]`

Also, according to the specification https://www.w3.org/WAI/PF/aria/states_and_properties#aria-disabled the default value for "aria-disabled" is "false"

### PR DESCRIPTION
**Pull request by clandau**
## Description
Changed the selector for "cursor: default" to `[aria-disabled="true"]` so that the behavior does not apply to `[aria-disabled="false"]`

Resolves #11003 

## How Has This Been Tested?
Tested in the playground.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <!--  -->
    <v-btn>
      button1 (cursor default)
    </v-btn>
    <v-btn aria-disabled="true">
      button2 (cursor pointer)
    </v-btn>
    <v-btn aria-disabled="false">
      button3 (cursor default)
    </v-btn>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
    //
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by lmcsu** [comment]
Sorry to bother, but it's still not in master. Is that ok?

**Comment by jacekkarczmarczyk** [comment]
No, it's not, good catch

**Comment by KaelWD** [comment]
Conflict from 2c723c0c6be9fe6317d01432e19663eeb9842551 was resolved incorrectly in 906c8858925190d1645944158dd35cc453785202

**Comment by lmcsu** [comment]
So what to do? Can you reopen the issue or something please.
I really need that thing in my project.

**Comment by jacekkarczmarczyk** [comment]
@lmcsu c64431b08100921b4d31241caa5a4aa5345fdbc7

**Pull request merged**
