### PR TITLE
feat: add autofocus for v-radio and v-checkbox

### LINKED ISSUE #4951: [Bug Report] autofocus does not work for Checkboxes, Radios
### Problem to solve
Currently (1.1.14) some of the Vuetify inputs support the 'autofocus' attribute, yet Checkboxes and Radios do not.  It would be ideal if all input controls supported this feature (I'm not sure if there are any others as well lacking this).

### Proposed solution
Implement the 'autofocus' attribute for all input controls.

### PR DESCRIPTION
**Pull request by sh7dm**
## Description

Add autofocus prop for v-radio and v-checkbox.

## Motivation and Context

Fixes #4951

## How Has This Been Tested?

Visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-app>
    <v-content>
      <v-container class="ma-5 pa-5">
        <v-btn @click="r = !r">Switch</v-btn>
        <v-radio-group v-if='r'>
          <v-radio
            autofocus
            label="Radio 1"
            :value="1"
          ></v-radio>
        </v-radio-group>
        <v-checkbox
          v-else
          autofocus
          label="Checkbox 1"
        ></v-checkbox>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>
export default {
  data: () => ({
    r: true
  })
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by sh7dm** [comment]
I haven't yet created PR  in the documentation, but I can create it later.

**Comment by johnleider** [comment]
This should probably be done at the `v-input` level and extend to everything.

**Comment by sh7dm** [comment]
@johnleider OK

**Comment by johnleider** [comment]
This Pull Request is being closed due to unresolved merge conflicts. Once corrected we will re-open.

Thank you for your contribution and interest in improving Vuetify!

**Pull request closed without merging**
