### PR TITLE
Fix icon styles

### PR DESCRIPTION
**Pull request by PavelCSS**
**Before:**
button - http://prntscr.com/hkcukm ,
lists - http://prntscr.com/hkcusz
**After:**
button - http://prntscr.com/hkcusz
lists - http://prntscr.com/hkcv5x

### CODE REVIEW

**Comment by nekosaur** [comment]
Please provide some more information about what issue this fixes. Is it an existing issue? If so please link to it in the description.

**Comment by PavelCSS** [comment]
https://next.vuetifyjs.com/components/buttons#example-floating

Before: http://prntscr.com/hkcukm
After: http://prntscr.com/hkcusz

**Comment by johnleider** [comment]
You've posted screenshots and thank you, but it doesn't reproduce the issue in front of my computer in order to understand why it is doing that. Currently the next docs are displaying correctly for me.

**Comment by johnleider** [comment]
Closing due to inactivity.

**Comment by PavelCSS** [comment]
https://next.vuetifyjs.com/components/lists#example-icon-two-lines-and-action

**Comment by johnleider** [comment]
This is what it looks like for me:
image

**Pull request closed without merging**
