### PR TITLE
fix(VColorPicker): center swatch grid

### PR DESCRIPTION
**Pull request by nigeltiany**
## Description
Swatch grid is off center. This is obvious when the swatch is small enough that it does not have a scrollbar. See swatch in current documentation

## Motivation and Context
discovered while browsing lib
## Markup:

<details>

```vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-color-picker class="ma-2" show-swatches></v-color-picker>
      </v-col>
      <v-col>
        <v-color-picker class="ma-2" :swatches="swatches" show-swatches></v-color-picker>
      </v-col>
      <v-col>
        <v-color-picker class="ma-2" show-swatches swatches-max-height="300px"></v-color-picker>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      swatches: [
        ['#FF0000', '#AA0000', '#550000'],
        ['#FFFF00', '#AAAA00', '#555500'],
        ['#00FF00', '#00AA00', '#005500'],
        ['#00FFFF', '#00AAAA', '#005555'],
        ['#0000FF', '#0000AA', '#000055'],
      ],
    }),
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nigeltiany** [comment]
I have updated the form

**Comment by johnleider** [comment]
Can you please provide a Playground, thank you.

**Comment by nigeltiany** [comment]
Thanks for the review @sh7dm . @johnleider I may not get the time to set that up. However, [the swatch documentation](https://vuetifyjs.com/en/components/color-pickers) highlights why this fix is needed. Inspecting the element causing the issue and adding the line of code in the PR fixes the issue without causing more layout problems.  

## before
Screenshot from 2020-02-26 19-44-47

## after
Screenshot from 2020-02-26 19-45-45

**Comment by jacekkarczmarczyk** [comment]
I've added the playground

**Pull request merged**
