### PR TITLE
feat(bootable): keep-content-alive prop

### LINKED ISSUE #1687: Dialog scroll position does not reset on subsequent shows
### Steps to reproduce
You can take Dialog Example 7 (Overflow), scroll it, close it and then show it again.

### Versions
0.15.3 using latest Chrome/Opera/Edge

### What is expected ?
The scroll position for the dialog should reset to zero.

### What is actually happening ?
It could be that the dialog state is being cached, which i totally understand. But i was expecting the scroll position to be reset.

### Reproduction Link

https://vuetifyjs.com/components/dialogs - Just try the codepen on example 7 and you'll see.

### LINKED ISSUE #4502: [Bug Report] Time picker in dialog defaults to selecting minutes after first time opened
### Versions and Environment
**Vuetify:** 1.1.1
**Vue:** 2.5.2
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Click on time field to open dialog.
2. Select hours and minutes.
3. Close dialog.
4. Click on time field again.

### Expected Behavior
The time picker should always default to selecting hours when opened in a dialog or menu. Perhaps, when the dialog is closed, the picker should reset `selectingHour` to `true`.

### Actual Behavior
Opening a time picker in a dialog or menu for the first time shows hours. When I re-open the dialog, it always shows minutes until I specifically click on hours.

### Reproduction Link
[https://codepen.io/anon/pen/aKgzzm?editors=1010#0](https://codepen.io/anon/pen/aKgzzm?editors=1010#0)

### Other comments
Likely related to the issue from [PR 4198](https://github.com/vuetifyjs/vuetify/pull/4198).

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Description
Adds `keep-content-alive` prop to bootables that destroys the content when bootable is deactivated

## Motivation and Context
fixes #4502
fixes #1687

Both issues can be solved by adding `v-if="dialogModel"` to the content, but that requires a model

## How Has This Been Tested?
visually, unit

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-container>
      <v-btn @click="dialog = !dialog">Open time picker</v-btn>
      <v-dialog ref="dialog" v-model="dialog" :return-value.sync="time" width="290px" :keep-content-alive="false">
        <v-time-picker v-model="time">
          <v-btn flat color="primary" @click="dialog = false">Cancel</v-btn>
          <v-btn flat color="primary" @click="$refs.dialog.save(time)">OK</v-btn>
        </v-time-picker>
      </v-dialog>

    <v-dialog scrollable max-width="300px" :keep-content-alive="false">
      <v-btn slot="activator">Open scrollable dialog</v-btn>
      <v-card>
        <v-card-text>
          <v-subheader v-for="i in 100" :key="i">Hello world</v-subheader>
        </v-card-text>
      </v-card>
    </v-dialog>

    </v-container>
  </v-app>
</template>

<script>
export default {
  data: () => ({
    dialog: false,
    time: null
  })
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

## Other comments
Personally i think that `:keep-content-alive="true"` should be the deafult behaviour, this could be considered as a breaking change though

### CODE REVIEW

**Comment by backbone87** [comment]
i got the dialog closing transition working by removing the show directive, if `keepContentAlive === false` here
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VDialog/VDialog.js#L172

and changing the dialog creation here
https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VDialog/VDialog.js#L201
to
```ts
var dialog = this.hasContent ? h('div', data, this.$slots.default) : undefined;
```

**Comment by jacekkarczmarczyk** [comment]
@backbone87 it didn't help. The problem is not with the dialog transition but with dialog content which dissapears right after dialog's model changes to false. Content should be destroyed after transition has finished

**Comment by jacekkarczmarczyk** [comment]
That indeed helped for `v-dialog`, but there's more components using `showLazyContent`, I tried similar thing with `v-menu` but with no success. Will try to look at it again soon, feel free to experiment with it if you have time (and share results)

**Comment by backbone87** [comment]
Does the following work for VMenu?

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VMenu/mixins/menu-generators.js#L55
```ts
if (this.keepContentAlive) {
  directives.push({
    name: 'show',
    value: this.isContentActive
  })
}
```

https://github.com/vuetifyjs/vuetify/blob/dev/src/components/VMenu/mixins/menu-generators.js#L88
```ts
return this.hasContent ? this.$createElement('div', options, this.$slots.default) : undefined
```

**Comment by jacekkarczmarczyk** [comment]
That's what I did, actually transition worked, but there'a another problem with position of the menu

**Comment by johnleider** [comment]
This has issues with `v-dialog`'s closing animation. Spoke with @jacekkarczmarczyk , closing for now.

**Comment by jacekkarczmarczyk** [comment]
Correction - problem with `v-dialog` is solved by @backbone87 , but still there are problems with `v-menu` and other detachables

**Comment by clickBi** [comment]
Any news regarding the KeepContentAlive, at the moment the lazy flag adds a lot of helps when handling with lots of slots because of vue performance bug, but at the same time the animations on certain things break down (expansion-panels for example)

**Pull request closed without merging**
