### PR TITLE
fix(VBottomNavigation): use active prop for visibility

### LINKED ISSUE #16041: [Bug Report][3.0.0] Bottom navigation is using the same prop for selection and visibility
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.41
**Browsers:** Chrome 107.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
Click "one"

### Expected Behavior
The selected item changes

### Actual Behavior
The bar hides itself

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqFUEtOwzAQvcrIm4JEfoVVlSJxAjbsMAu3nYCleGw5kwCqenfGTstXol75fW29x726C6GcRlQr1Q7baAPDgDyGW03WBR8Z9hCxgwN00TtYiHWhSdPW08Dg/A57WCfHRXOpqa3mDkkLYHShN4yCANqpMCHVghwBUsDGEsYjpVlIxjcuOov9Dvg94ForGt0Go1YwFfmxciZEyVCE6liQWzee2buCzGSfDVtPp9xX4NM+B5hgNZl+TI/Vot4TtlXm/zE2Ynx49eeNy2R8ifinM+Pfnz2tI9rPeRIzr9dW31ZVhyt1XS7Lm0alS13W6ukDlQyVRA==)

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #16041

## Description

fixes #16041

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<script setup>
import { ref } from 'vue'

const model = ref(null)
</script>

<template>
  <v-app>
    <v-container>
    	<v-text-field type="number" v-model.number="model" />
      <v-bottom-navigation v-model="model">
        <v-btn :value="0">One</v-btn>
        <v-btn :value="1">Two</v-btn>
        <v-btn :value="2">Three</v-btn>
      </v-bottom-navigation>
    </v-container>
  </v-app>
</template>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
This doesn't fix the underlying problem, selection and visibility need to be completely separate.

**Comment by yuwu9145** [comment]
Thanks, I focused too much on that hiding issue, will take a further look

**Comment by yuwu9145** [comment]
now use `inputValue` to for visibility. Same as vuetify 2

**Comment by johnleider** [comment]
I believe the terminology we are using in v3 is to always use **modelValue** for display state unless an internal item value is needed as well, in which case it's **active**. Can you confirm @KaelWD

**Comment by yuwu9145** [comment]
@KaelWD could you please advice?

**Comment by KaelWD** [comment]
The only other component I can think of which has both selection and visibility is VProgressLinear, which does use `modelValue` for selection and `active` for visibility. VList also kinda has both but for children rather than itself, and uses `selected` and `opened`.

**Comment by yuwu9145** [comment]
now use `active` for visibility while `modelValue` for selection

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
