### PR TITLE
Bugfix - ReferenceError: isMaskDelimiter is not defined

### LINKED ISSUE #2998: [Bug Report] Filter X
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
Write then click somewhere else

### Expected Behavior
text should stay when click somewhere

### Actual Behavior
the text disappear

### Reproduction Link
[https://codepen.io/anon/pen/LemKra](https://codepen.io/anon/pen/LemKra)

### PR DESCRIPTION
**Pull request by sorinsarca**
## Description
Fixes a js error ReferenceError: isMaskDelimiter is not defined.
I also moved `defaultDelimiters` export to top for better readability.

## Motivation and Context
An error is thrown in es6 version on load, in es5 there error can be seen if you use char `X` for `mask` property on a `v-text-field`.

Fixes #2998

## How Has This Been Tested?
You can reproduce the bug using the following snippet:
```js
const x = {test: isMaskDelimiter};
const isMaskDelimiter = "something";
```
In "es5 version" of the bug the property will be `undefined`:
```js
var x = {test: isMaskDelimiter};
var isMaskDelimiter = "something";
console.log(x.test); // undefined
```

No test files created.

## Markup:

Not needed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Please read https://github.com/vuetifyjs/vuetify/blob/dev/.github/CONTRIBUTING.md#pull-requests before creating PRs and  use the template that you were given when you created this PR (https://github.com/vuetifyjs/vuetify/blob/dev/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by sorinsarca** [comment]
The description was updated using the template @jacekkarczmarczyk

**Comment by jacekkarczmarczyk** [comment]
Thank you, however maybe i'm blind, but 

> I also moved defaultDelimiters export to top for better readability.

is the only change I see in this PR

**Comment by sorinsarca** [comment]
`export const isMaskDelimiter = ...` is also moved (this causes the error, being used without being defined).
https://github.com/vuetifyjs/vuetify/pull/3006/commits/0395be24eefd453dfbc85c2a938498ae22c9cdd2#diff-1362e26f423269ee89883f93cdf28857R14

**Comment by jacekkarczmarczyk** [comment]
Oh, now I see, thanks for explanation

**Pull request merged**
