### PR TITLE
Added Indonesia Locale

### PR DESCRIPTION
**Pull request by jefrydco**
Add Indonesia translation.

## Description

Added Indonesian locale translation.

## Motivation and Context

Increase vuetify user in Indonesia

## How Has This Been Tested?

none

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sh7dm** [comment]
@jefrydco please resolve merge conflicts.

**Comment by sh7dm** [comment]
@jefrydco It seems that your `patch-1` branch is created from `master` branch, not from `dev`. I think merge conflicts are caused by this. Try to change base branch to `master`

**Comment by MajesticPotatoe** [comment]
Locales are to dev. PR was originally to master. They just need to resolve conflicts.

**Comment by jefrydco** [comment]
@sh7dm @MajesticPotatoe Thanks for reminding me about that, perhaps I'll close this pr and create new one based from dev branch instead.

**Pull request closed without merging**
