### PR TITLE
fix(VSlider): set value to min if it's less than min (#6604)

### LINKED ISSUE #6604: [Bug Report] VSlider value can be set to be less than the min value and renders incorrectly
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.7
**Browsers:** Chrome 73.0.3683.46
**OS:** Mac OS 10.14.2

### Steps to reproduce
Create a VSlider with min and max values and set the value of the slider to be less than the min value.

### Expected Behavior
The value should be set to the min value.

### Actual Behavior
The value is not set to the min value, and the thumb is positioned outside of the slider.

### Reproduction Link
<a href="https://codepen.io/hrayr/pen/MxWvYR" target="_blank">https://codepen.io/hrayr/pen/MxWvYR</a>

### PR DESCRIPTION
**Pull request by hrayr-artunyan**
## Description
Forces the slider value to be within the boundaries set by min and max props.

## Motivation and Context
fixes #6604 

## How Has This Been Tested?
Tested visually with the provided playground code.

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-layout justify-center wrap>
      <v-flex xs7>
        <v-slider
          v-model="val"
          min="55"
          max="80" />
      </v-flex>
    </v-layout>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      val: 50
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
Thank you for your contribution. Could you possibly create a test for this as well?

**Comment by sh7dm** [comment]
@hrayr-artunyan please add unit tests!

**Comment by hrayr-artunyan** [comment]
@sh7dm I will do so shortly. Thank you.

**Comment by hrayr-artunyan** [comment]
@nekosaur and @sh7dm I finally got around to adding a unit test. 

Please test, thanks!

**Pull request merged**
