### PR TITLE
feat(VSlideGroup) add steps

### PR DESCRIPTION
**Pull request by melbahja**
## Description
Steps is a prop that add some dynamic touch scroll

**Without steps prop (default):**
before
**With steps prop**
Screencastfrom09-09-2019072154PM

## How Has This Been Tested?
visually 

## Markup:
on touch screens add ```steps``` prop on VSlideGroup

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by melbahja** [comment]
> Needs unit tests and docs

If this PR acceptable I will add tests and docs

**Comment by sh7dm** [comment]
We'll need to discuss that with our team.

**Comment by johnleider** [comment]
I think that this has considerably more usability throughout the framework. For example, being able to cycle items like this in a slide group. That would move v-carousel cycle functionality to the base component and give us many more options for the user.

One thing that would be particularly great would be the ability to continuously scroll in any direction endlessly.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
