### PR TITLE
fix(VRangeSlider): Displaying trackFillColor passed via prop

### LINKED ISSUE #12733: [Bug Report] v-range-slider doesn't obey prop track-fill-color
### Environment
**Vuetify Version:** 2.3.19
**Vue Version:** 2.6.12
**Browsers:** Chrome 84.0.4147.89, Mozilla Firefox, Google Chrome
**OS:** Windows, Linux x86_64

### Steps to reproduce
1. Instanciate component v-range-slider with a custom color for prop `track-fill-color`

```
      <v-range-slider v-model="hue" min=0 max=360 track-fill-color="green" />
```

### Expected Behavior
The value of property `track-fill-color` should update the color of element `v-slider__track-fill`

### Actual Behavior
Always rendered with color `primary`

### Reproduction Link
<a href="https://codepen.io/barrabinfc/pen/qBabzeP" target="_blank">https://codepen.io/barrabinfc/pen/qBabzeP</a>

### Other comments
It's working as expected on brother component `v-slider`

### PR DESCRIPTION
**Pull request by dchinu97**
## Description
Display the Track color mentioned in the v-range-silder prop track-fill-color
fixes #12733 

## Motivation and Context
Done to fix #12733
Previously wrong method was used to access the fill color

## How Has This Been Tested?
UT have been added and Visually 

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-range-slider
      v-model="range"
      min="0"
      max="360"
      track-fill-color="red"
      track-color="grey"
    />
    <v-range-slider
      v-model="range"
      min="0"
      max="360"
      track-fill-color="rgba(255, 255, 0, 0.5)"
      track-color="grey"
    />
    <v-slider
      v-model="single"
      min="0"
      max="100"
      track-fill-color="green"
      track-color="grey"
    />
  </v-container>
</template>

<script>
  export default {
    data: () => {
      //
      return {
        range: [10, 20],
        single: [10],
      }
    },
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by bigbadfatman — COMMENTED** [review]
Would be good to have a test case for when the fill color is an rgba string as well.

That said, it does fix the issue.

**Comment by dchinu97** [comment]
> Would be good to have a test case for when the fill color is an rgba string as well.
> 
> That said, it does fix the issue.

@bigbadfatman Thanks for the input, I have added Test for rgba string.

**Review by MajesticPotatoe — APPROVED** [review]
👍 
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by dchinu97** [comment]
> 👍
> Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

@MajesticPotatoe Thank you for the Review, Can we merge these changes?

**Pull request merged**
