### PR TITLE
fix(v-checkbox, v-radio): fix adding 'checked' attribute to input element

### PR DESCRIPTION
**Pull request by ochikoji**
## Description

I fixed v-checkbox and v-radio components to apply for non-javascript form page by adding 'checked' attribute on them when they are actived.

## Motivation and Context

I'm using this framework with Laravel to make website to be rich appearance.
When I'm creating form page on laravel-blade-template, I realized v-checkbox and v-radio are not applied for non-javascript html form page.
So I fixed them working.

Sorry for my poor english. and I'm a biginner.
## How Has This Been Tested?

Sorry, I can't understand how to test yet..
But, I checked them on my own web site.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
Please rebase your branch off of master

**Comment by ochikoji** [comment]
Oh.. I don't understand anything. Sorry, I will learn how to use git.

**Comment by johnleider** [comment]
Closing due to inactivity.

**Comment by ivanwitzke** [comment]
Have this functionality been implemented later to the project? I'm having trouble with checkboxes, switches and selects for a non-spa app that i'm working on and can't figure out how to send the values to the server.

**Pull request closed without merging**
