### PR TITLE
fix(theme): only apply theme to head element when not using vue-meta

### LINKED ISSUE #3405: [Bug Report] cannot set theme dynamically
### Versions and Environment
**Vuetify:** 1.0.3
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
$nuxt.$vuetify.theme = Store.config.campaign.theme

### Expected Behavior
Colors change  to defined schema

### Actual Behavior
Cannot set property 'innerHTML' of null
    at VueComponent.applyTheme

### Reproduction Link
[https://codepen.io/anon/pen/xYQaVm](https://codepen.io/anon/pen/xYQaVm)

### Other comments
I just upgraded from 0.17 to 1.0.3 and now I cannot set the theme dynamically anymore

I do not have a reproduction link. The provided one is empty so I could submit the form.

### PR DESCRIPTION
**Pull request by KaelWD**
## Motivation and Context

fixes #3405

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by SeregPie** [comment]
Sorry. Why is this change needed? I use vue-meta and I use dynamic theme in vuetify. I updated vuetify and it broke my project.

**Comment by johnleider** [comment]
It was needed for the linked issue that it resolves. If you are having a problem with the new release, please create a new issue using https://issues.vuetifyjs.com or come to the community so we can troubleshoot, https://community.vuetifyjs.com

**Comment by SeregPie** [comment]
This merge causes this bug #3482.

**Comment by KaelWD** [comment]
I know. It was an oversight because I only ever tested it with nuxt SSR.

**Pull request merged**
