### PR TITLE
fix(VListGroup): missing hover overlay

### LINKED ISSUE #16830: [Bug Report][3.1.7] List-Group missing hover background when opened
### Environment
**Vuetify Version:** 3.1.7
**Vue Version:** 3.3.0-alpha.4
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When you hover over the closed item-group a background is used (as expected). Once you open the group and hover over the parent again, there's no background-color.

### Expected Behavior
Opened group-parents should also indicate the interactivity by the background-color.

### Actual Behavior
hover background color missing.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqdVE2P2jAQ/SuWL9mVcEJFpUqUXe3eeump6olw8DoGXPwl28l2hfjvHTvJbkiAquUSPDNv5r03cdZH/Gxt3tQcL/EqcGUlDfyx1AitGsKoq+JfhJik3j+UWP0mtA6mxG34VVRhD+HFfN6GEjJhpfABNUSZisulsVzzCgrjnxJ3Ve91RMBkZB2HbEUEMzqOqgTZG8VLjIIIkkPoWzo+rooBDHqNu+2cqS1qqKwj6Kfnzg9mQl2vE/h5acKSsiAaGoyD8iPwMNaj0xnknOowjqDJi9BRXAL21vS/C6ooY6bWgTDhmARB54BebMd7mJwofydXDFY3CF805LlSYriE/7bklil/s+VDZ0fnPH1V6VWttze0TULu1mnoDMVlbOBxj4RGNBKYEFwe+BtAxCTe807PSXa07viY1PSLuNDhxoaHu/y4QJfCfbC9xnCI9xgOI+dWnjlhA/I8tNAyCGWNC+iIHN+iE9o6o1AGH4fsKwACaIE7Ha8weogVd+ssvaTZ5h7yAG8LWj+hZN3SWWffqaY7rrgO2QxlwyugahmElZyYOkihebaZ9aAfPAShd76HMLMbVW3iVBDY6gAFeIZbBURRm//yRsNX7RiLYBMpAWteohSJMVAWzyXeh2D9sihqbQ+7nBlVPEGucEBRKE4qo54W+SKfEyrtnuafiwrsHaZz7hV5ceYV/IDBJe5kpBlBbN+uzenS0P5T/qVt24Viy0mrAvo33BEH7xh33N2kP6q9JGFUMpERR59KfQJnwfiDH5nKfDK0W/Q/6oO3JE8N0i7jkNMMn3GEqQmHN38ASzERGg==)

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

not at all sure this is the way to fix it

closes #16830

## Markup:

```vue
<template>
  <v-card
    class="mx-auto"
    width="300"
  >
    <v-list v-model:opened="open">
      <v-list-item prepend-icon="mdi-home" title="Home"></v-list-item>

      <v-list-group value="Users">
        <template v-slot:activator="{ props }">
          <v-list-item
            v-bind="props"
            prepend-icon="mdi-account-circle"
            title="Users"
          ></v-list-item>
        </template>

        <v-list-group value="Admin">
          <template v-slot:activator="{ props }">
            <v-list-item
              v-bind="props"
              title="Admin"
            ></v-list-item>
          </template>

          <v-list-item
            v-for="([title, icon], i) in admins"
            :key="i"
            :title="title"
            :prepend-icon="icon"
            :value="title"
          ></v-list-item>
        </v-list-group>
      </v-list-group>
    </v-list>
  </v-card>
</template>

<script setup>
 	import { ref } from 'vue';
	const open = ref(['Users']);
 	const admins = [
    ['Management', 'mdi-account-multiple-outline'],
    ['Settings', 'mdi-cog-outline'],
  ];
  </script>

```

### CODE REVIEW

**Comment by KaelWD** [comment]
Another option would be to just add `:not(:hover)` if we're ok with it being darker

**Comment by KaelWD** [comment]
I think active-variant might fix this too

**Comment by nekosaur** [comment]
When hovering over group item

Before
image

After
image

Not sure what you mean by active-variant @KaelWD

**Comment by johnleider** [comment]
active-variant is a concept I proposed where you can have a variant applied at default and when the item is active.

**Comment by johnleider** [comment]
> Another option would be to just add :not(:hover) if we're ok with it being darker

Following up on the status of this.

**Review by johnleider — APPROVED** [review]
I tested a few alternate implementations and none felt better than this implementation. I say it's good to go.

**Pull request merged**
