### PR TITLE
fix(types): add declarations for composables (display, icons, theme)

### LINKED ISSUE #13901: [Bug Report][3.0.0-alpha.8] Missing type declarations for composables and iconsets
### Environment
**Vuetify Version:** 3.0.0-alpha.8
**Vue Version:** 3.1.4
**Browsers:** Chrome 91.0.4472.124
**OS:** Windows 10

### Steps to reproduce
Try to use types like:

- `IconSet`, `IconAliases`, `IconProps` ([ref](https://next.vuetifyjs.com/en/features/icon-fonts/#creating-a-custom-icon-set))
- `ThemeDefinition` ([ref](https://next.vuetifyjs.com/en/features/theme/#setup))
- `aliases`, `mdi` from `"vuetify/lib/iconsets/mdi-svg"` ([ref](https://next.vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg))
- `useDisplay` ([ref](https://next.vuetifyjs.com/en/features/display-and-platform/#usage))
  - (as mentioned on Discord)

### Expected Behavior
Types to exist.

### Actual Behavior
They don't.

### Reproduction Link
n/a

### Other comments
It's really quite difficult working with all these missing types. 🙂

### PR DESCRIPTION
**Pull request by glen-84**
## Description

Add type declarations for some of the types referenced in the alpha documentation.

Things _may_ change a bit if/when api-extractor is integrated, but this is alpha, so those changes don't need to be backwards-compatible, and this unblocks users who need to use these types.

If this is accepted, I'll split the icon set declarations into a separate issue, as a decision still needs to be made regarding whether or not to rename the symbols (`aliases` -> `mdiAliases`, etc.) to make them unique.

Fixes #13901.

## Motivation and Context

#13901.

## How Has This Been Tested?

Manually (test project referencing types from locally-installed vuetify package).

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
(... it's 68 – is this a problem?)
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by glen-84** [comment]
@KaelWD,

Should I add `composables/layout` to this PR as well, or do that in a follow-up PR?

Could you please let me know if this PR is likely to be merged any time soon, as it's really quite awkward working without types. If something isn't right then I can make the necessary changes.

**Review by johnleider — APPROVED** [review]
I think we will be sticking with **'vuetify/lib'** instead of **'vuetify'** for CDN purposes. Is this accurate @KaelWD?

**Comment by KaelWD** [comment]
No, `vuetify/lib` is now the default export for esm environments. I'm going to do some more work on the build config this week so paths might change, putting this on hold for now.

**Comment by glen-84** [comment]
Closing in favour of #14099.

**Pull request closed without merging**
