### PR TITLE
docs: validation function must return true or a string

### PR DESCRIPTION
**Pull request by xrnoz**
## Description
If the validation rule function returns false, you get this error in the console: false is not a valid value. Rule functions must return boolean true or a string.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Shouldn't then https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/composables/validation.ts#L15 be changed to `string | true`?

**Comment by KaelWD** [comment]
@jacekkarczmarczyk #15443

**Comment by jacekkarczmarczyk** [comment]
@xrnoz https://github.com/vuetifyjs/vuetify/pull/16113#issuecomment-1321668301

**Comment by johnleider** [comment]
So what is actionable here? Do the types need to be changed here or reverted?

**Comment by jacekkarczmarczyk** [comment]
As far as I understand @KaelWD 's comment `true` in types is intentional and should stay

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
