### PR TITLE
feat(dist): Components and directive names type

### PR DESCRIPTION
**Pull request by a3mitskevich**
## Description
Added a dts file with component and directive names for more comfortable development plugins/tools what based from vuetify.

Where it will be placed:
image
How it would be looks:
image

### CODE REVIEW

**Comment by KaelWD** [comment]
Why?

**Comment by a3mitskevich** [comment]
> Why?

I think it will be very helpful for the vue-loader ignore property ( for example ). Instead of creating every time additional scripts to generate types or write types manually, we can create an auto-generated file with name types that to placed to dist in every release.

**Comment by a3mitskevich** [comment]
If you think is a overfeature - I will close the pull request 
But I hope additional typescript types can be very helpful for other developers

**Comment by KaelWD** [comment]
Yeah doesn't really clarify what you'd actually use this for or why you can't do `import type * as components from 'vuetify/components'`

**Comment by a3mitskevich** [comment]
> Yeah doesn't really clarify what you'd actually use this for or why you can't do `import type * as components from 'vuetify/components'`

Your example provides a component type that is not a literal representation. To get a default Vuetify component name needs to access to name field which is not easy in typescript. 
image
For directives is not possible. Need to declare it manually in every project there it needed 😢

**Comment by KaelWD** [comment]
Again, what are you actually trying to use this for?

**Comment by a3mitskevich** [comment]
> Again, what are you actually trying to use this for?
example:
image

**Comment by KaelWD** [comment]
```
import type * as components from 'vuetify/components'
(keyof components)[]
```

**Pull request closed without merging**
