### PR TITLE
Made RTL the v-stepper-step icon

### PR DESCRIPTION
**Pull request by mehranrasulian**
## Description

Override the `.v-stepper__step__step` margin-right to margin-left for the *RTL* apps

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-stepper v-model="e6" vertical>
    <v-stepper-step :complete="e6 > 1" step="1">
      انتخاب یک اپ
      <small>چکیده اگه نیاز باشه</small>
    </v-stepper-step>
    <v-stepper-content step="1">
      <v-card color="grey lighten-1" class="mb-5" height="200px"></v-card>
      <v-btn color="primary" @click.native="e6 = 2">ادامه</v-btn>
      <v-btn flat>انصراف</v-btn>
    </v-stepper-content>
  </v-stepper>
</template>

<script>
  export default {
    data () {
      return {
        e6: 1
      }
    }
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by mehranrasulian** [comment]
@KaelWD where is the conflict? maybe?

**Comment by KaelWD** [comment]
There's an extra commit that shouldn't be there. This probably needs rebasing.

**Comment by mehranrasulian** [comment]
@KaelWD Just call me if there was any way I can help.

**Comment by KaelWD** [comment]
you need to `git rebase --onto upstream/dev HEAD~ && git push -f`

**Comment by mehranrasulian** [comment]
@KaelWD the given command failed with:
```bash
fatal: Needed a single revision
Does not point to a valid commit: upstream/dev
```

**Comment by KaelWD** [comment]
oh, you've done this straight on your dev branch

```
git remote add upstream https://github.com/vuetifyjs/vuetify.git
git fetch upstream
git rebase --onto upstream/dev HEAD~ && git push -f
```

remember to always make a new branch for future PRs

**Comment by mehranrasulian** [comment]
@KaelWD OOPPS! I even didn't remember to create a new branch. would do the next time ;)

**Comment by mehranrasulian** [comment]
@KaelWD It's been done, in the case you want to do the review.

**Comment by mehranrasulian** [comment]
@KaelWD I've added some other RTL things as well,
Should I add them here or open another PR?

**Pull request merged**
