### PR TITLE
docs(examples): Mini in desktop and default variant in mobile

### PR DESCRIPTION
**Pull request by chiragshahklc**
In this example toggle of navigation drawer happens with some other button. Navigation drawer should toggle between mini(hidden) and full(show) in desktop and should have default behavior toggle between hide and show in mobile devices.

## Description
Different Variant of navigation drawer in mobile and desktop

## Motivation and Context
Having different variant of navigation drawer based on device is sometime important.
There is no example which shows this and it's little bit complex to get at first as well.

## How Has This Been Tested?
I have tested it using codepen.
[Link to Codepen](https://codepen.io/anon/pen/Gawyox?editors=1010)

## Markup:
Link to Codepen

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by chiragshahklc** [comment]
@jacekkarczmarczyk 
Should I update the code with your suggestions?

>  using v-list-tile instead of v-list-item, using v-app and so on. You need to run the actual dev environment to see them all

**Comment by MajesticPotatoe** [comment]
> Should I update the code with your suggestions?

Yes. Should be free of lint errors, deprecation messages, and the likes.
Though i would have to agree with jacek that it would be better suited for pre-defined layouts section

**Comment by nekosaur** [comment]
Agreed on putting this in pre-defined layout. ping @chiragshahklc

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Pull request closed without merging**
