### PR TITLE
fix(grid): don't halve gutters between v-rows

### LINKED ISSUE #12915: [Bug Report] Halved gutter width between v-rows
### Environment
**Vuetify Version:** 2.4.0
**Vue Version:** 2.6.12
**Browsers:** Chrome 87.0.4280.88
**OS:** Linux x86_64

### Steps to reproduce
After the breaking change in 2.4.0 all layouts with nested `dense` `v-row`s are kinda broken.

Current workaround is to remove the `pt-0` and `pb-0` in the nested `v-col` and then add a `pt-1` in each `v-row`

This is just one breaking example and I would have around 80 more files to check with maybe some more complex layout issues.

### Expected Behavior
Working as in 2.3.23

### Actual Behavior
Has a workaround, but I want to ask if this is going to be re-worked and should I wait for more bug fixes or if I am now revising ~80 files in my project

### Reproduction Link
<a href="https://codepen.io/shinigami92/pen/RwGJxvG" target="_blank">https://codepen.io/shinigami92/pen/RwGJxvG</a>

### Other comments
https://github.com/vuetifyjs/vuetify/issues/11408#issuecomment-750868206

### PR DESCRIPTION
**Pull request by KaelWD**
fixes #12915

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-row dense>
      <v-col cols="8">
        <v-card height="100%"></v-card>
      </v-col>
      <v-col cols="4">
        <v-row dense>
          <v-col cols="12">
            <v-card>
              <v-skeleton-loader type="article" />
            </v-card>
          </v-col>
          <v-col cols="12">
            <v-card>
              <v-skeleton-loader type="article" />
            </v-card>
          </v-col>
        </v-row>
      </v-col>
    </v-row>
    <v-row dense>
      <v-col
        v-for="i in 6"
        :key="i"
        cols="6"
      >
        <v-card>
          <v-skeleton-loader type="article" />
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Shinigami92** [comment]
Any news about this PR?
Is there anything I can do to help get this fix released?

**Comment by KaelWD** [comment]
@vuetifyjs/core-team Nobody reviewed this, if it's broken it's your fault.

**Comment by Shinigami92** [comment]
> @vuetifyjs/core-team Nobody reviewed this, if it's broken it's your fault.

lol...

Today (18:26 GMT+2) I'm to tired and wont test it
But I will let you know tomorrow after updating and use with a production environment
So you may hear from me in about the next 24 hours :slightly_smiling_face: 
Good night o/

**Comment by Shinigami92** [comment]
... or if it's possible for you, I could also try a beta release :thinking:  
Like `2.4.3-beta.1`

**Comment by vmihailenco** [comment]
I can confirm that this is broken.

**Comment by Shinigami92** [comment]
I just arrived at my working station, will test it now

**Comment by Shinigami92** [comment]
## 2.3.23
adSoul-Dashboard 2 3 23

## 2.4.3
adSoul-Dashboard 2 4 3

LGTM

I just removed the `pt-0` and `pb-0` from my `v-col`s and don't need any `p`s or `m`s in my grid anymore

Just noticed that it moved `4px` up, but I think that is intended!

---

@vmihailenco Could you provide a little bit more information about what is broken for you?  
Maybe open a new issue and/or link it here

**Comment by vmihailenco** [comment]
@Shinigami92 does this everyting for you "This is just one breaking example and I would have around 80 more files to check with maybe some more complex layout issues."?

This does not fixes the regressions I have in v2.4.x and additionally breaks `margin-top`, e.g. `v-row dense class="mt-4"`.

**Comment by Shinigami92** [comment]
This was just the same example as I showed in https://github.com/vuetifyjs/vuetify/issues/12915
That's why I send it here

But many more sites worked the same for me

Yeah it's a breaking change from 2.3 to 2.4, but this 2.4.3 is the fixed version 2.4 where I think I can finally migrate to 2.4
But I encountered another issue with `v-text-field` and `label`+`placeholder`, but I will search if anyone else has already reported it or open a new one, but this is not related to this issue/pr/fix

I have encountered a part where I have a custom created component where I need to add `my-0`, but that's totally fine for me because it is a self made component and the "workaround" just worked

image
image
image

Checking more files now
I currently was half way trough my tool :D

**Comment by Shinigami92** [comment]
Ok, so I think I have visited almost all pages in our tool and it looks a bit more slimmer to me
That's the `4px` less at the top (and so I also think at the bottom?)

## 2.3.23

Screenshot_20210122_091609

## 2.4.3
Screenshot_20210122_091604

---

So I can even think about that this change was indeed intended
And so I'm fine with this
Or in other words, this fix fixed more that it broke for me :slightly_smiling_face: 

@vmihailenco If you encountered other problems, please open a new issue and we can try to work on that
Screenshots of your problems could also help

**Pull request merged**
