### PR TITLE
Updated wrong link in the documentation's Colors page

### PR DESCRIPTION
**Pull request by salvadornico**
## Description
Replaced broken link in Colors documentation with the correct, updated one.

## Motivation and Context
It seems like the link to the settings file in the Colors page of the documentation was from before everything was moved into one repo. I just updated it to the working one.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Thanks. There's probably a whole bunch more if you want to have a go at finding them.

**Comment by salvadornico** [comment]
> 
> 
> Thanks. There's probably a whole bunch more if you want to have a go at finding them.

Sure, I'll give it a search now

**Comment by jacekkarczmarczyk** [comment]
They could actually point to the files in correct versions, for example

https://github.com/vuetifyjs/vuetify/tree/v1.3.6/packages/vuetify/src/....

**Comment by salvadornico** [comment]
> They could actually point to the files in correct version, for example
> 
> https://github.com/vuetifyjs/vuetify/tree/v1.3.6/packages/vuetify/src/....

So this would be for the links in the built files?

I've updated the translation files with all the current links, except for the Example.vue files, which I haven't quite figured out yet.

**Pull request merged**
