### PR TITLE
feat(vdatafooter): add itemsPerPageMenuProps to VDataFooter

### LINKED ISSUE #10535: [Feature Request] No way to customize "Items per page" list in v-data-table footer
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Windows 10

### Steps to reproduce
I want to customize "Items per page" list in the data table footer to look, i.e. like this:

image

But this is NOT POSSIBLE. This list is attached to `v-app` element so I cannot target it via CSS selector from 'v-data-table' component. I can only create a global style but this will style all lists in my app which is very bad.

### Expected Behavior
Add "content-class" prop to `v-data-footer` to specify CSS class which will be added to "Items per page" list.

### Actual Behavior
There is no way to customize "Items per page" list in the data table footer.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/zYGGwGv?editable=true&editors=101" target="_blank">https://codepen.io/mikilll94/pen/zYGGwGv?editable=true&editors=101</a>

### PR DESCRIPTION
**Pull request by Mikilll94**
Added possibility to specify `menuProps` on "items per page" select in VDataFooter component.

fix #10535

## Description
When using VDataTable with default footer, there is no possibility to customize the "items per page" list. It is described in detail in #10535.

This PR adds the possibility to specify custom **menuProps** on VDataFooter. So, i.e. now on VDataTable I can specify:
```
:footer-props="{
    itemsPerPageMenuProps: { contentClass: 'my-fancy-class' }
}"
```

## Motivation and Context
The inability to just simply target the "Items per page" list in `v-data-table` default footer was a little bit annoying for me. That's why I made this PR.

## How Has This Been Tested?
visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="desserts"
      :items-per-page="5"
      class="elevation-1"
      :footer-props="{
        itemsPerPageMenuProps: { contentClass: 'my-fancy-class' }
      }"
    ></v-data-table>
  </v-container>
</template>

<script>
  export default {
    data() {
      return {
        headers: [
          {
            text: 'Dessert (100g serving)',
            align: 'left',
            sortable: false,
            value: 'name',
          },
          { text: 'Calories', value: 'calories' },
          { text: 'Fat (g)', value: 'fat' },
          { text: 'Carbs (g)', value: 'carbs' },
          { text: 'Protein (g)', value: 'protein' },
          { text: 'Iron (%)', value: 'iron' },
        ],
        desserts: [
          {
            name: 'Frozen Yogurt',
            calories: 159,
            fat: 6.0,
            carbs: 24,
            protein: 4.0,
            iron: '1%',
          },
          {
            name: 'Ice cream sandwich',
            calories: 237,
            fat: 9.0,
            carbs: 37,
            protein: 4.3,
            iron: '1%',
          },
          {
            name: 'Eclair',
            calories: 262,
            fat: 16.0,
            carbs: 23,
            protein: 6.0,
            iron: '7%',
          },
          {
            name: 'Cupcake',
            calories: 305,
            fat: 3.7,
            carbs: 67,
            protein: 4.3,
            iron: '8%',
          },
          {
            name: 'Gingerbread',
            calories: 356,
            fat: 16.0,
            carbs: 49,
            protein: 3.9,
            iron: '16%',
          },
          {
            name: 'Jelly bean',
            calories: 375,
            fat: 0.0,
            carbs: 94,
            protein: 0.0,
            iron: '0%',
          },
          {
            name: 'Lollipop',
            calories: 392,
            fat: 0.2,
            carbs: 98,
            protein: 0,
            iron: '2%',
          },
          {
            name: 'Honeycomb',
            calories: 408,
            fat: 3.2,
            carbs: 87,
            protein: 6.5,
            iron: '45%',
          },
          {
            name: 'Donut',
            calories: 452,
            fat: 25.0,
            carbs: 51,
            protein: 4.9,
            iron: '22%',
          },
          {
            name: 'KitKat',
            calories: 518,
            fat: 26.0,
            carbs: 65,
            protein: 7,
            iron: '6%',
          },
        ],
      }
    },
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
We are feature locked for future minor releases on the 2.x branch. Closing this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Mikilll94** [comment]
@johnleider 
Hey, but this is just a small feature which is also a bugfix.

Please take a look at #10535. It was classified as a feature but it is rather a bug than a feature.

**Comment by MajesticPotatoe** [comment]
Couldn't re-open if we wanted to as the original repository has been deleted (github doesn't allow for it)

**Comment by Mikilll94** [comment]
@MajesticPotatoe 
That's right. I have accidentally deleted the fork. If you want I can create a new PR with the same changes as in this PR.

**Comment by alexkleinwaechter** [comment]
It would be great. The Attach property would help a lot too. In my embedded app, the items per page menu opens somewhere....

**Comment by jklmnopr** [comment]
hey @Mikilll94 any news on this?

**Comment by alphabt** [comment]
We're running into this issue on my team and we are looking forward to have this fixed as well. @Mikilll94 I don't want to take away the credit from you by creating a new PR with your changes, but is there's anything I can do to help?

**Comment by Mikilll94** [comment]
Hello, guys!

@alphabt 
Yes, you can help me.

Please create a new PR with the same changes as mine (with some adjustments if needed). Right now i don't have time to work on this. But I remember that on my team we had also a problem with this data table footer.

**Pull request closed without merging**
