### PR TITLE
fix(VSelect): emit click event

### LINKED ISSUE #10839: [Bug Report] v-select click event does not fire
### Environment
**Vuetify Version:** 2.2.17
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.132
**OS:** Windows 10

### Steps to reproduce
use a v-select in your component - in the browser click on the resulting select input - no click event is fired

### Expected Behavior
Clicking on the select element in browser fires click event

### Actual Behavior
click event does not fire 

### Reproduction Link
<a href="https://codepen.io/pmagix/pen/yLNKZrX?editors=1111" target="_blank">https://codepen.io/pmagix/pen/yLNKZrX?editors=1111</a>

### PR DESCRIPTION
**Pull request by basselAhmed**
## Description
Emit click event in v-select and add a test for it.
fixes #10839

## Motivation and Context
Bugfix.
fixes #10839

## How Has This Been Tested?
unit

## Markup:
<details>

```vue
<template>
  <v-container>
    <!--  -->
    <v-select @change="doSomething('change')" @click="doSomething('click')" :items=items></v-select>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    items: ['one', 'two']
  }),
  methods: {
    doSomething(eventType) {
      console.log(eventType)
    }
  }
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by YipingRuan** [comment]
Just to check my understanding based on this design,
If you click the input, the click.native will be fired.
If you actually change the item, the click will be fired.

**Comment by basselAhmed** [comment]
@YipingRuan No, it will be like this:
- If you click the input, the `click` event will be fired.
- If you actually change the item, the change will be fired.

There will be no need to use `.native` modifier at all

**Comment by YipingRuan** [comment]
Would you like to update the documentation part as well?

**Comment by basselAhmed** [comment]
@YipingRuan I don't think there should be any changes to documentation, the reason for this PR was that the documentation described that the click event should be fired when the select is clicked, and for some reason, the click event was not firing, so I fixed that.

I am not sure what @johnleider meant by his comment but perhaps he can say more 😄

> The .native behavior is a Vue idiosyncrasy: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

> @vuetifyjs/documentation Could possibly reword the default language for change and input events. Thoughts?

**Comment by MajesticPotatoe** [comment]
@basselAhmed What john was referring to there was that we use a boilerplate description for almost all `change` an `input` events, and was suggesting to update the verbiage for it.

As for the `.native` multiplier bit, he was simply saying those modifiers are derived from the Vue ecosystem.

I think for the sake of this PR the default `Emitted when input is clicked` should suffice, unless you can think of something more descriptive for the `change` event

**Comment by basselAhmed** [comment]
@MajesticPotatoe Thank you, I think the current description should suffice as you said.

**Pull request merged**
