### PR TITLE
paramaterize sort icon

### PR DESCRIPTION
**Pull request by thelonecabbage**
Adds the ability to set as a prop the v-icon for data table sort. 
`
<v-data-table  sort-icon="arrow_drop_down" .../>
`
## Description
- Added property "sortIcon"
- use this.sortIcon in genHeaderSortingData

## Motivation and Context
There is currently no way to override the default icon for sort in Data Tables

## How Has This Been Tested?
Ran locally, testing in company storybook

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
I like this change, but I think we should ultimately move some of this logic into a sort of "config" for vuetify components. You can currently use a custom icon, but you have to use slots. @nekosaur What are your thoughts on how we should proceed forward with this?

**Comment by nekosaur** [comment]
We've had some prior talks about how to decouple material icons from the framework, and I think the general consensus was some sort of config object on $vuetify where you can specify the default internal icons to be used. While still supporting per-component changes through either prop and/or slots.

**Comment by jacekkarczmarczyk** [comment]
see also https://github.com/vuetifyjs/vuetify/issues/3080#issuecomment-359706142 (and issue #3080 itself)

**Comment by jacekkarczmarczyk** [comment]
Some icons are not displayed properly (but that's not a problem with this PR)
image

**Pull request merged**
