### PR TITLE
fix(VDialog) checking before if the click is not on the overlay

### LINKED ISSUE #6969: [Bug Report] Releasing mouse button outside a dialog should not close the dialog
### Versions and Environment
**Vuetify:** 1.5.11
**Vue:** 2.6.10
**Browsers:** Chrome 73.0.3683.86
**OS:** Windows 10

### Steps to reproduce
1. Open the dialog
1. Left-click on the dialog
1. Without releasing the button, move the cursor outside the dialog
1. Release the button

### Expected Behavior
The dialog should remain open. The dialog should only be closed if the mouse button is both pressed and released outside the dialog.

### Actual Behavior
The dialog is closed.

### Reproduction Link
<a href="https://codepen.io/gjen_123/pen/ZZKMLb" target="_blank">https://codepen.io/gjen_123/pen/ZZKMLb</a>

### LINKED ISSUE #7121: [Bug Report] dialog is disabled when you select a text and release on overlay
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.6
**Browsers:** Chrome 73.0.3683.103
**OS:** Linux x86_64

### Steps to reproduce
Open dialog
Click and hold with left button mouse the text from dialog
Drop the selection on overlay

### Expected Behavior
Dialog keeps active after you select the text

### Actual Behavior
Dialog is disabled when you select the text

### Reproduction Link
<a href="https://codepen.io/anon/pen/KYjRYp" target="_blank">https://codepen.io/anon/pen/KYjRYp</a>

### PR DESCRIPTION
**Pull request by danielpfs**
## Description 
I changed when is checked if the click is on the overlay to resolve the problem with selection

## Motivation and Context
Fixes #6969 

## How Has This Been Tested?
visually

## Markup:

<details>

```
<template>
  <v-app>
    <v-dialog
      max-width="700px"
    >
      <v-btn slot="activator">Button</v-btn>
      <v-card>
        <v-card-text>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. In sed enim neque temporibus. Alias animi, quasi iste modi dolor ea perferendis nihil, corporis fugiat dolore qui. Iste autem aliquid vel?
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. In sed enim neque temporibus. Alias animi, quasi iste modi dolor ea perferendis nihil, corporis fugiat dolore qui. Iste autem aliquid vel?
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. In sed enim neque temporibus. Alias animi, quasi iste modi dolor ea perferendis nihil, corporis fugiat dolore qui. Iste autem aliquid vel?
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. In sed enim neque temporibus. Alias animi, quasi iste modi dolor ea perferendis nihil, corporis fugiat dolore qui. Iste autem aliquid vel?
        </v-card-text>
      </v-card>
    </v-dialog>
  </v-app>
</template>
```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [X] The PR title is no longer than 64 characters.
- [X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by Xambey** [comment]
Will it be fixed? Very necessary changes ...

**Comment by johnleider** [comment]
We have removed the on hold label. Please resolve the merge conflicts. Thank you

**Comment by johnleider** [comment]
Just a reminder that this will be closed in 3 days due to inactivity unless merge conflicts are resolved.

**Comment by danielpfs** [comment]
I changed what was needed. Sorry for the delay

**Comment by johnleider** [comment]
I'm sorry that I broke this from another fix, can you update again? :)

**Comment by danielpfs** [comment]
No problem. Only with the part that I had changed the click animation of the persistent dialog was working again, but I decided to keep another overlay check to avoid any other bugs =)

**Pull request merged**
