### PR TITLE
feat(VDataTable) : add sass variables for text color 

### LINKED ISSUE #10952: [Feature Request] Add Sass varaiable for color definition of datatables headers
### Problem to solve
This feature add the ability to change color of text of all data-table header

### Proposed solution
Add Sass variables in the theme file to override it [here](https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file) if necessary

### PR DESCRIPTION
**Pull request by deka**
## Description
SASS Theme variables for datatable header text color

fix #10952 

.../styles/settings/_light.scss  : 
```
...
'table': (
      'header': (
        'text-color': rgba(map-get($shades, 'black'), 0.6),
        'text-color-active': rgba(map-get($shades, 'black'), 0.87),
        'text-color-disabled': rgba(map-get($shades, 'black'), 0.38)
      ),
...
```

## Motivation and Context

fix #10952 

## How Has This Been Tested?
Visual check

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by deka** [comment]
@johnleider,
 can you add this pr to 2.3 ?

**Comment by johnleider** [comment]
If you want this in v2.3, need to have feedback and conflicts resolved.

**Comment by deka** [comment]
Hi @johnleider.
No time. 
I try this week-end

**Comment by johnleider** [comment]
Unfortunately this did not make it for v2.3. Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
