### PR TITLE
feat: emit event on mobile breakpoint

### LINKED ISSUE #1929: [feature-request] emit mobile-breakpoint event on v-navigation-drawer when isMobile state changes
## What will it allow you to do that you can't do today?
Let parent know when the state of the navigation drawer has changed to be able to react in other ways, like modifying props on other components to suit the change, without having to watch v-resize for the same breakpoint.

## How will it make current work-arounds straightforward?
Simplify watching for a breakpoint

## What potential bugs and edge cases does it help to avoid?
Having parent's mobile breakpoint be different from navigation drawer

### PR DESCRIPTION
**Pull request by NothingWeAre**
fixes #1929

### CODE REVIEW

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/issues/1929#issuecomment-340667854

**Comment by jacekkarczmarczyk** [comment]
BTW - this PR emits event on every resize, but it should emit only when mobile state has changed

**Comment by NothingWeAre** [comment]
@jacekkarczmarczyk I agree, fixed

**Comment by KaelWD** [comment]
Why don't you do it in the `isMobile` watcher instead? That is only called when the value actually changes.

**Comment by NothingWeAre** [comment]
@KaelWD 
Sorry, you are right. I was editing commit on the go, from tablet, and didn't notice watcher.
Will fix when i will be able to sit in front of normal monitor and read source more attentively.

**Comment by NothingWeAre** [comment]
moved `$emit` to watcher

**Comment by johnleider** [comment]
As I try to avoid $emit calls when at all possible, I'm leaning towards this should be handled by the developer.

**Pull request closed without merging**
