### PR TITLE
Fix list items tag prop

### LINKED ISSUE #8942: [Bug Report] [VList] tag prop does not work. Lists should be able to render as ul and li.
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
1. Open the codepen
2. Inspect the list

### Expected Behavior
The list should render as an `ul`.

### Actual Behavior
It is rendering as a `div`. Also, the `list-items` are rendering as anchors instead of `li`.

### Reproduction Link
<a href="https://codepen.io/phiter/pen/MWgXbQW?editors=1010" target="_blank">https://codepen.io/phiter/pen/MWgXbQW?editors=1010</a>

### Other comments
I understand that a `v-list-item` that has a `:to=""` prop transforms itself into a `router-link`, but `router-link` has a [`tag` property](https://router.vuejs.org/api/#tag) which can be used to change it into something else. Vuetify does not pass that prop to the router-link.

The prop tag is being ignored in the `VList` component, as seen in the following lines:

https://github.com/vuetifyjs/vuetify/blob/a01a1508219ae2a23049e3fcf070b032cb2ba853/packages/vuetify/src/components/VList/VList.ts#L94-L105

My suggestion is to allow changing the tag of a `v-list` to something else, and if a list item has both `to` and `tag` props, maybe wrap the anchor inside the chosen tag.

That would allow for semantic HTML, instead of always using divs.
This is important for accessibility, since screen readers rely on lists in order to provide better information to the user.

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
## Description

fixes #8942

## Motivation and Context

if a list item has both to and tag props, wrap the anchor inside the chosen tag.

## How Has This Been Tested?
unit | visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-app>
      <v-card
        class="mx-auto mt-10"
        min-width="400"
        max-width="400"
      >
        <v-list tag="ul">
          <v-list-item tag="li">
            <v-list-item-content>
              <v-list-item-title>Item0</v-list-item-title>
            </v-list-item-content>
          </v-list-item>

          <v-list-item
            tag="li"
            link
          >
            <v-list-item-content>
              <v-list-item-title>Item1</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            tag="li"
            inactive
            @click="() => {}"
          >
            <v-list-item-content>
              <v-list-item-title>Item2</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            tag="li"
            @click="() => {}"
          >
            <v-list-item-content>
              <v-list-item-title>Item3</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            tag="li"
            @click="() => {}"
          >
            <v-list-item-content>
              <v-list-item-title>Item4</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            to="b"
            inactive
          >
            <v-list-item-content>
              <v-list-item-title>Item5</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item to="b">
            <v-list-item-content>
              <v-list-item-title>Item6</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            to="b"
            tag="li"
            inactive
            @click="() => {}"
          >
            <v-list-item-content>
              <v-list-item-title>Item7</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            to="b"
            tag="li"
            @click="() => {}"
            disabled
          >
            <v-list-item-content>
              <v-list-item-title>Item8</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            to="c"
            tag="li"
            @click="() => {}"
          >
            <v-list-item-content>
              <v-list-item-title>Item9</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item href="/home">
            <v-list-item-content>
              <v-list-item-title>Item10</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            tag="li"
            href="/home"
          >
            <v-list-item-content>
              <v-list-item-title>Item11</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            href="/home"
            inactive
          >
            <v-list-item-content>
              <v-list-item-title>Item12</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
        </v-list>
      </v-card>
    </v-app>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      //
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Related: 
https://github.com/vuetifyjs/vuetify/issues/10529
https://github.com/vuetifyjs/vuetify/commit/fb062bfa9e27d93cad6c10d095ae70c830deb6b9

**Comment by tanmoyopenroot** [comment]
Hi @MajesticPotatoe @jacekkarczmarczyk ,
Can you please review this PR?

**Comment by jacekkarczmarczyk** [comment]
Be patient, it will be reviewed eventually ;)

**Comment by johnleider** [comment]
The original issue was resolved by what @jacekkarczmarczyk posted. This aims to change the default expected behavior when working with a `<router-link>`.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
