### PR TITLE
fix(VCard): remove opacity transition from underlay

### PR DESCRIPTION
**Pull request by alokVishu**
## Description
I have removed the `background` property from the `$card-transition-property:` variable to the background transition issue. SEE GIF
chrome-capture-2022-7-6

## How Has This Been Tested?
IDK much about tests but I had to generate new snapshot to commit my changes and possibly all test ran successfully.

## Markup:

<details>

```vue
$card-transition-property: box-shadow, opacity, background !default; => $card-transition-property: box-shadow, opacity !default;
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
This issue exists for all components that implement **variant**. Here is a playground:

```html
<template>
  <div class="ma-4 pa-4">
    <v-btn @click="variant = !variant">Click me</v-btn>

    <br>
    <br>

    <v-card :variant="variant ? 'tonal' : 'elevated'">
      <v-card-title>Card</v-card-title>

      <v-card-text>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde voluptatem!
      </v-card-text>
    </v-card>

    <br>

    <v-btn :variant="variant ? 'tonal' : 'elevated'">Tonal variant</v-btn>

    <br>
    <br>

    <v-alert title="Alert" :variant="variant ? 'tonal' : 'elevated'">Tonal variant</v-alert>
  </div>
</template>

<script>
  export default {
    data: () => ({
      variant: false,
    }),
  }
</script>
```

**Comment by alokVishu** [comment]
What should be do next then?

**Review by johnleider — APPROVED** [review]

**Comment by johnleider** [comment]
@KaelWD and I went over this and determined that it's not necessary for us to define a transition on the **underlay** element for all variants. I reverted your change for the update so that you still get credit for the PR.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Review by KaelWD — APPROVED** [review]

**Comment by alokVishu** [comment]
Hello @johnleider,

Thank you for merging this PR.

But the main issue still exists. Changes in this PR don't remove the default card's background transition.  See the GIF.
chrome-capture-2022-8-2

Is it required to transition the background in the card component?

**Pull request merged**
