### PR TITLE
fix(VRadio): do not use cursor pointer if disabled

### LINKED ISSUE #12023: [Bug Report] Disabled radio in radio group has pointer cursor instead of default
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.10
**Browsers:** Firefox 79.0
**OS:** Windows 10

### Steps to reproduce
Open reproduction link. Put mouse over the radio.

### Expected Behavior
Disabled radio should have default cursor

### Actual Behavior
It has pointer cursor

### Reproduction Link
<a href="https://codepen.io/ilyalyu/pen/oNxgMXV" target="_blank">https://codepen.io/ilyalyu/pen/oNxgMXV</a>

### Other comments
Similar issue was fixed here:
https://github.com/vuetifyjs/vuetify/issues/2670
for checkbox

### PR DESCRIPTION
**Pull request by YipingRuan**
fix #12023

## Markup:

<details>

```vue
<template>
  <div id="app">
    <v-app>
      <div style="width: 200px;">
        <v-radio-group>
          <v-radio
            label="Label A"
            value="a"
            disabled
          />
          <v-radio
            label="Label B"
            value="b"
          />
        </v-radio-group>
        <v-checkbox label="Checkbox"></v-checkbox>
        <v-checkbox
          label="Checkbox"
          disabled
        ></v-checkbox>
        <v-switch
          v-model="switchValue"
          label="John"
          value="John"
          @click="onClick"
        ></v-switch>
        <v-switch
          v-model="switchValue"
          label="Jacob"
          value="Jacob"
          disabled
          @click="onClick"
        ></v-switch>
      </div>
    </v-app>
  </div>
</template>

<script>
  export default {
    data: () => ({
      checkbox: ['John'],
      switchValue: null,
      radio: null,
    }),
    methods: {
      onClick () {
        console.log('click')
      },
    },
  }
</script>

<style>
  .v-input__slot {
    padding: 15px;
    border: 1px green solid;
  }

  .v-input--selection-controls__input {
    padding: 10px;
    margin: 10px;
    border: 1px red solid;
  }

  .v-label {
    padding: 10px;
    margin-left: 40px;
    border: 1px red solid;
  }
</style>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by YipingRuan** [comment]
Correctly change pointer to cursor at the v-radio div
pointer

**Review by KaelWD — DISMISSED** [review]
See my selection controls playground in #5968, switches and checkboxes need it on `.v-input__slot`

**Review by anilkumarggk — APPROVED** [review]

**Comment by KaelWD** [comment]
No. The green area is clickable but only the red area has a changed cursor:
image

**Comment by YipingRuan** [comment]
Will this work?
cursor

**Review by johnleider — APPROVED** [review]
I made a small tweak to the styles, moving the radio-group declaration into its actual style file. Everything else lgtm.

**Pull request merged**
