### PR TITLE
feat(api-generator): extract component data from types

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

rewrite api-generator to extract component data directly from types

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by MajesticPotatoe — CHANGES_REQUESTED** [review]
- [ ] directive api pages (arguments/modifiers) are not displaying properly (likely just needs table update for the json structure
- [ ] global sass vars are excluded (not sure the best way to handle this, maybe apply them to an applicable composable, or export them separately to a 'global' api (think we used $vuetify in v2)

**Comment by nekosaur** [comment]
> * [ ]  directive api pages (arguments/modifiers) are not displaying properly (likely just needs table update for the json structure
> * [ ]  global sass vars are excluded (not sure the best way to handle this, maybe apply them to an applicable composable, or export them separately to a 'global' api (think we used $vuetify in v2)

- directive pages look okay for me
- yeah global variables are disabled for now, not a showstopper for merging this

**Comment by MajesticPotatoe** [comment]
Actually, this looks like its because the URL links on the api page for those directives are correct, but also arent throwing a 404

**Review by MajesticPotatoe — APPROVED** [review]
👍

**Pull request merged**
