### PR TITLE
feat(VBtn): add download attribute

### PR DESCRIPTION
**Pull request by MehdiKhoshnevisz**
## Description
In this PR, `download` attribute is added to v-btn component. If v-btn component has `href` and `download` props, the link in the `href` will be downloaded by the browser.

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-btn color="primary" :href="href" download>
      Download Button
    </v-btn>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    href: '' // Put your link (in your domain) to dowlaod
  })
};
</script>

```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
This is already passed through, it doesn't need to be explicitly defined.

**Comment by MehdiKhoshnevisz** [comment]
> This is already passed through, it doesn't need to be explicitly defined.

Hey. Could you please mention in which version?

**Comment by KaelWD** [comment]
All of them

**Comment by MehdiKhoshnevisz** [comment]
> Every version

Please mention its documentation if it exists!

**Pull request closed without merging**
