### PR TITLE
Sorting issue for non-english locales

### LINKED ISSUE #3672: [Bug Report] Sorting issue for non-english locales
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.162
**OS:** Linux x86_64

### Steps to reproduce
Create a sortable table, where sorted values contain any non-standard (non-english) characters, and try to sort them by the name, or just run a codepen link.

### Expected Behavior
String values should be sorted correctly in alphabetical order.

### Actual Behavior
String values are not sorted correctly. Character "Ł" based on a standard latin "L" is pushed to the end of sorted array.

### Reproduction Link
[https://codepen.io/dmitrij-schmidt/pen/geGvza](https://codepen.io/dmitrij-schmidt/pen/geGvza)

### Other comments
Possible solution http://www.jstips.co/en/javascript/sorting-strings-with-accented-characters/

### PR DESCRIPTION
**Pull request by ebisbe**
## Description

Sorting using localeCompare in order to get good ordenation

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Check_browser_support_for_extended_arguments

## Motivation and Context

Fixes #3672 

## How Has This Been Tested?

visually

Ordering is still happening the same way it happened but now some special chars are sorted correctly.
I have added  a new prop called `Locale` with a default value to `en`. Anyone can set its own locale without the need for a custom function to match your current locale . The same markup from the test is ordered different with these locales:
- es
- en
- de
- de-DE-u-co-phonebk

## Markup:

<details>
<template>
  <v-app id="inspire">
    <v-data-table
      :headers="headers"
      :items="items"
      hide-actions
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
      </template>
    </v-data-table>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      headers: [
        {
          text: 'Name',
          value: 'name'
        },
      ],
      items: [
        {
          value: false,
          name: 'Anna',
        },
        {
          value: false,
          name: 'Ämna',
        },
        {
          value: false,
          name: 'Lidia',
        },
        {
          value: false,
          name: 'Łucja',
        },
        {
          value: false,
          name: 'Robert',
        },
        {
          value: false,
          name: 'Walter',
        },
        {
          value: false,
          name: 'álter',
        },
        {
          value: false,
          name: 'Úrbano'
        },
        {
          value: false,
          name: 'Würst'
        },
        {
          value: false,
          name: 'Wäb'
        }
      ]
    })
  }
</script>

</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

If you are fine with this I will make the current update to the documentation. 
Do you want a test to check the default value of `locale` prop is always `en`?

### CODE REVIEW

**Comment by johnleider** [comment]
Please add a test for this.

**Comment by ebisbe** [comment]
@johnleider Any thing else? When you think is ready I'll make a Pr with the docs update

**Comment by jacekkarczmarczyk** [comment]
There's possible similar issue with filtering

https://github.com/vuetifyjs/vuetify/blob/94d31c653d384fc69cf13f0bb83b674a8701635b/src/mixins/data-iterable.js#L71

**Comment by ebisbe** [comment]
Perfect I'll look into that issue as well.

**Comment by johnleider** [comment]
Closing due to inactivity.

**Comment by ebisbe** [comment]
@niutech I've been busy with other things and the last things that need to be done are the comments from jacekkarczmarc . But I won't be able to do it in a long time...

**Comment by jacekkarczmarczyk** [comment]
This will be covered by neko's table refactor https://github.com/vuetifyjs/vuetify/pull/5232/files#diff-6d72529ad1b516918669f430ffe9704cR36

**Comment by niutech** [comment]
@jacekkarczmarczyk Thanks!

**Pull request closed without merging**
