### PR TITLE
fix(VBreadcrumbs): set overflow-x to auto

### LINKED ISSUE #18464: [Bug Report][3.3.21] VBreadcrumbs content overflow
### Environment
**Vuetify Version:** 3.3.21
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Resize the window.

### Expected Behavior
`VBreadcrumbs` items should be visible and accessible.

### Actual Behavior
`VBreadcrumbs` content overflows, therefore some items can't be seen / accesed.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqF0UFLwzAUB/Cv8ieXKowWnafSCYp48DrcZd0hZq8SXJqQvEyk9LubtgriDjn9ycsvL+FlP4jgVfXgXHmOJGrRMBl3kkz3bQ80u0dP8qh8NG8BtU6bYdOKOVuBKqGm+nMiLYPy2jECcXRzD22c9YwBnjqM6Lw1KNJlxcQBZfvAmDtiM5mr/VQGhiUA1nyiGsUu0su2WC3l8Scv1LOXhj6t/whZmhqy7r6y7smqaKhnydr2ea09KdZnyj9gaw3h+Ouz/DXI93/qcD39wDLzNG0xrsS6XJd3YsnbG3H4Bjy7kWU=)

### PR DESCRIPTION
**Pull request by bogdanciuca**
## Description

Add `overflow-x: auto` so that the component becomes scrollable when it doesn't fit the screen. Fixes #18464 

## Markup:

```vue
<template>
  <VBreadcrumbs :items="items" />
</template>

<script setup>
  import { ref } from 'vue'

  const items = ref([
    {
      title: 'VueJS',
    },
    {
      title: 'Frameworks',
    },
    {
      title: 'Vuetify',
    },
    {
      title: 'Documentation',
    },
    {
      title: 'Directives',
    },
    {
      title: 'Some directive',
    },
    {
      title: 'Usage',
    },
  ])
</script>
```

### CODE REVIEW

**Comment by johnleider** [comment]
I think it's worth exploring something the user can opt into as opposed to just setting the overflow.

**Comment by bogdanciuca** [comment]
@johnleider Assuming that you are referring to a new prop, can you advise on a name for it?

**Comment by johnleider** [comment]
Maybe "scrollable" or something similar.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
