### PR TITLE
feat(VSparkline): add support for multiple paths

### PR DESCRIPTION
**Pull request by sh7dm**
## Description
Add support of multiple paths for sparkline

## Motivation and Context
#6029

## How Has This Been Tested?
visually
- [ ] `jest`

## Markup:

<details>

```vue
<template>
  <v-sparkline
    :value="value"
    :gradient="gradient"
    :smooth="radius || false"
    :padding="padding"
    :line-width="width"
    :stroke-linecap="lineCap"
    :gradient-direction="gradientDirection"
    :fill="fill"
    :type="type"
    :auto-line-width="autoLineWidth"
    auto-draw
  ></v-sparkline>
</template>

<script>
  const gradients = [
    ['#222'],
    ['#42b3f4'],
    ['red', 'orange', 'yellow'],
    ['purple', 'violet'],
    ['#00c6ff', '#F0F', '#FF0'],
    ['#f72047', '#ffd200', '#1feaea'],
  ]

  export default {
    data: () => ({
      width: 2,
      radius: 10,
      padding: 8,
      lineCap: 'round',
      gradient: gradients[5],
      value: [
        [0, 2, 5, 9, 5, 10, 3, 5, 0, 0, 1, 8, 2, 9, 0],
        [4, 1, 8, 2, 7, 1, 3, 3, 7],
      ],
      gradientDirection: 'top',
      gradients,
      fill: false,
      type: 'trend',
      autoLineWidth: false,
    }),
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sh7dm** [comment]
# TODO:
- [x] support `trend` variant
- [x] comparing ability
- [ ] support `labels` as a 2D array
- [ ] support `gradient` as a 2D array
- [ ] support `color` as an array
- [ ] support `bar` variant

**Comment by hifall** [comment]
What's the status of this PR? Looks like a really useful feature!

**Comment by nekosaur** [comment]
This needs to be rebased before consideration

**Comment by johnleider** [comment]
Pulse check.

**Comment by johnleider** [comment]
At this time the team is not considering any feature requests for the v2.x

**Pull request closed without merging**
