### PR TITLE
fix(helpers): update with correct path to `vuetify/types`

### PR DESCRIPTION
**Pull request by husayt**
correct path to `vuetify/types`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
We use `from 'types'` everywhere else without a problem, what does this actually fix?

**Comment by husayt** [comment]
@KaelWD it works fine if you use that from within vuetify. But any code using it externally stumbles. Also it will then be consistent with the line above, which refers to `"vuetify/types/services/icons"` not just `"types/services/icons"`.

**Comment by jacekkarczmarczyk** [comment]
For consistency it should be updated in other places too

**Comment by johnleider** [comment]
@jacekkarczmarczyk Can you add that as a review and request changes please.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by bramceulemans** [comment]
Is there a list of places this needs to happen? I can refactor them if needed.

**Comment by jacekkarczmarczyk** [comment]
Would be great! Just search for `from 'types'`

**Comment by bramceulemans** [comment]
Yep, thought of that myself as well. Working on it now!

**Comment by bramceulemans** [comment]
Pull request can be found here: #11314

**Pull request closed without merging**
