### PR TITLE
fix(VCombobox): don't trigger keydown listener during composition session

### LINKED ISSUE #18421: [Bug Report][3.3.20] Unintended Japanese input with v-combobox behavior
### Environment
**Vuetify Version:** 3.3.20
**Vue Version:** 3.3.4
**Browsers:** Chrome 117.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. enter text in v-combobox (e.g., "うれしい)
2. convert input into Kanji characters with space key (e.g. "嬉しい")
3. confirm with the Enter key, the same string is entered at the same time as it is registered (e.g. "嬉しい 嬉しい")

### Expected Behavior
```
嬉しい
```
Also, this is not confirmed, but is confirmed when you press Enter again

### Actual Behavior
```
嬉しい 嬉しい
```

### Reproduction Link
[<a href="https://play.vuetifyjs.com/#..." target="_blank">https://play.vuetifyjs.com/#...</a><br/>](<a href="https://play.vuetifyjs.com/#eNpNjs0OgjAMx1+l7oImCkY8mUnizTfwoB4Ah1mysWYrxITw7m4MI6e2v/w/eh+Ys3V2QUz7TrAT4yQ0qpJE8WgBeL8rEad1OmrTUilbYWc0Q12ZynxAd4okKlHw7E9/5gkt3YHEcJ4tSv3paiuRwAnqYrfUaCzBAFY0MEJjjYbE/5sEOYDPdQTaveEcFOvkKpQycDNWvVbJJhTESB/Gxi3L0zw9sjgPe/b8Aq0gVWU=)" target="_blank">https://play.vuetifyjs.com/#eNpNjs0OgjAMx1+l7oImCkY8mUnizTfwoB4Ah1mysWYrxITw7m4MI6e2v/w/eh+Ys3V2QUz7TrAT4yQ0qpJE8WgBeL8rEad1OmrTUilbYWc0Q12ZynxAd4okKlHw7E9/5gkt3YHEcJ4tSv3paiuRwAnqYrfUaCzBAFY0MEJjjYbE/5sEOYDPdQTaveEcFOvkKpQycDNWvVbJJhTESB/Gxi3L0zw9sjgPe/b8Aq0gVWU=)</a><br/>

### Other comments
I have observed the intended behavior on Windows and v2, but abnormal behavior only on mac in v3.
|vuetify|windows|mac|
|:-:|:-:|:-:|
|v2|ok|ok|
|v3|ok|ng|

### PR DESCRIPTION
**Pull request by yuwu9145**
fixes #18421

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-combobox
        chips
        multiple
      />
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const msg = ref('Hello World!')
</script>
```

### CODE REVIEW

**Review by KaelWD — APPROVED** [review]
I can't check iOS but it still works on android and doesn't break english so :+1:

**Comment by johnleider** [comment]
The last time we did something with isComposing in the framework we ended up reverting it:

https://github.com/vuetifyjs/vuetify/commit/5f82fe23fe2fafe2fdb24f715346f98f17bb4639

Just pasting to make sure we're not repeating the mistake.

**Comment by KaelWD** [comment]
Yeah I checked that, it still updates as you type. We actually had the same problem in v3 at one point: #11243

**Comment by yuwu9145** [comment]
I think the proper fix is having an universal helper that checks whether a press key is a composition operation, so we can prevent composition operations conflicting with Vuetify logic

V2 uses `keyCode` which always returns 229 during composition sessions, so #18421 doesn't exist in v2. But it has been deprecated not being used in v3

**Review by johnleider — APPROVED** [review]

**Pull request merged**
