### PR TITLE
fix(VSelect):fixed prefix shifted vertically

### LINKED ISSUE #9600: [Bug Report] Outlined autocomplete's prefix is shifted vertically
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Create an autocomplete that looks like this.
```vue
<v-autocomplete
  label="test"
  prefix="test"
  outlined
></v-autocomplete>
```

### Expected Behavior
I expect the prefix to be inline with the label.

### Actual Behavior
The prefix is shifted up.

### Reproduction Link
<a href="https://codepen.io/Punknium/pen/rNNdEqN" target="_blank">https://codepen.io/Punknium/pen/rNNdEqN</a>

### PR DESCRIPTION
**Pull request by ryo-my-favorite**
## Description
VAutocomplete's prefix is shifted vertically when outline property used.
Fixed that not to shifted vertically.

## Motivation and Context

fixes #9600
## How Has This Been Tested?

visually
## Markup:

<details>

```vue
<template>
  <v-container>
    <v-autocomplete
      label="test"
      prefix="pre"
      :items="items"
      outlined
    ></v-autocomplete>
    <v-autocomplete
      label="test"
      prefix="test"
    ></v-autocomplete>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    items: ["normal"]
  })
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
This causes breaking changes and doesn't cover all the input variations.

s test_8080_ (1)

**Comment by ryo-my-favorite** [comment]
Thank you for reviewing, I check it.

**Comment by johnleider** [comment]
@ryo-my-favorite Pulse check on this PR.

**Comment by johnleider** [comment]
This appears to be resolved in the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
