### PR TITLE
style(all): fix comma dangling error on .ts component files

### PR DESCRIPTION
**Pull request by adrienbaron**
## Description

I ran `yarn lint:fix` and comited the changes.

## Motivation and Context

Running `yarn lint` on master currently results in a lot of linting error related to the rule `'comma-dangle': ['error', 'always-multiline']`.

## How Has This Been Tested?

No tests needed as it's only stylistic changes.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Did you accidentally update eslint? This will conflict with #9594

**Comment by adrienbaron** [comment]
I don’t think so, I tried deleting my node_modules and running `yarn install` again from the root of the project and the issue was still there. Happy to close if nobody else reproduces though.

**Comment by KaelWD** [comment]
I mean CI is passing and it doesn't happen for me. comma-dangle for functions was added in eslint 6.6.0 and master is only on 6.1.0

**Comment by adrienbaron** [comment]
Ok will close then, I have to figure out what's happening on my machine 👍

**Pull request closed without merging**
