### PR TITLE
fix(Theme): fix theme issue when using Vue Meta without SSR 

### PR DESCRIPTION
**Pull request by kevinmarrec**
## Description
Fix theme issues for applications using Vue Meta without SSR like not being able to dynamically change theme colors cause of duplicate css overriding the one which is correctly updated in the DOM.

Implementation :
- Rename `initNuxt` to `initVueMeta` as it's not only Nuxt specific.
- Call it only if `$meta` exists on Vue instance and that `$isServer` is truthy (https://fr.vuejs.org/v2/api/#vm-isServer)

Should fix https://github.com/nuxt-community/vuetify-module/issues/69

## Motivation and Context
**`initNuxt`** was called without checking if we were server side.
Which meant that any application that had **Vue Meta without SSR** (_i.e._ Nuxt **SPA** mode or any Vue application using [vue-meta](https://github.com/nuxt/vue-meta) without SSR) would have 2 stylesheets in DOM, the second one being the Vue Meta one and always overriding the first that is updated client-side by Vuetify when trying to change `$vuetify.theme`.

## How Has This Been Tested?
I've been performing the following tests with a Nuxt project using the Vuetify module :
SSR (development + production environments) ✔
SPA (development + production environments) ✔

On these 4 tests I succeed to dynamically change theme and move between 2 pages without theme issues. Before this fix, it was not possible to dynamically change theme in SPA mode.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by kevinmarrec** [comment]
No idea how to fix the nuxt test cause of this TS issue :
Screenshot from 2019-07-26 23-48-27

Should we TS ignore the line ?

**Comment by pauldaiko** [comment]
this change has caused the vuetify theme  stylesheet to be nuked on route change. will see if i can make a repo.

**Comment by kevinmarrec** [comment]
@pauldaiko AFAIK there's still issues around theming after route change, you can check https://github.com/nuxt-community/vuetify-module/issues/63

**Comment by pauldaiko** [comment]
is this issue connected  https://github.com/nuxt-community/vuetify-module/issues/91 ?

**Comment by kevinmarrec** [comment]
@pauldaiko If you're using `head` in your components, it may be connected yes

**Comment by pauldaiko** [comment]
im not using the vuetify module. i have it set up through a plugin. And yes I am using head for page components. Is this a vue meta issue? if so this PR shouldnt have been pushed till that is fixed.

**Comment by kevinmarrec** [comment]
Yes it's a `vue-meta` issue but only with Vue Meta 1.x, it should ha been fixed along 2.x of Vue Meta.
You can try manually upgrade it in your project.

This PR is fixing a bug for people using VueMeta without SSR where people couldn't dynamically change theme.

**Comment by kevinmarrec** [comment]
@pauldaiko https://github.com/nuxt-community/vuetify-module/issues/91#issuecomment-516910455

My mistake, seems to be buggy as you described only since last release if Vuetify (so this PR is related to the issue)

**Pull request merged**
