### PR TITLE
Remove ripple and change cursor on disabled selection controls

### LINKED ISSUE #1665: disabled radio button has ripple and hover
### Steps to reproduce
Create disabled radio button

### Versions
0.15.3

### What is expected ?
Disabled radio button show use default mouse cursor and should not have ripple effect

### What is actually happening ?
Disabled radio button has pointer mouse cursor on hover and has ripple effect

### Reproduction Link
https://codepen.io/anon/pen/ZXzzKM

EDIT: same for chekbox/switch

### PR DESCRIPTION
**Pull request by KaelWD**
Unsure whether the cursor should be `default`, or `not-allowed`

Fixes #1665

### CODE REVIEW

**Comment by johnleider** [comment]
Looks good, but 3 duplications of the same code **should** be triggering codebeat. Is there a way we could DRY this up?

**Comment by KaelWD** [comment]
It's not triggering codebeat because I basically just moved some existing stuff behind an `if`. I don't have time now, but I'll have a look again tomorrow and see what I can do.

**Comment by johnleider** [comment]
Something like that, will have to look into it further.

**Comment by johnleider** [comment]
I've already corrected this, thank you.

**Pull request closed without merging**
