### PR TITLE
fix(VDataTable): use item.raw and columns in sorting transform

### LINKED ISSUE #20045: [Bug Report][3.6.10] VDataTable group is not sorted when key is not in header
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
In the example `groupBy` is set to the key `group` with a sort order of `desc`, but the `group` is _not_ included in the headers

### Expected Behavior
The grouped values are correctly sorted descending

### Actual Behavior
Sorting is not applied. It does work however, if the column `group` is also included in the headers.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq9lt9P2zAQx/+VUyQESP2Rpk2gUTeJwcYYe9jrRHlwk6NEuHHkON06xP8+u02CXWx1eWB9aC7fO8f38Z2d3D17JU+GF0UxWFfoxd5M4KqgRODHeQ4wW/dTIkhfkAVFiJecVUV/sfkw97bmp83cg/gRSYq8lGJtKTGTz1FSimWJXChNSf01oRVKPScrnHu7SYb6LFKaDbUk5G2Z8KwQ0h4O4SJNYe49g8gExRiOr1Uexz14wo2822Z1DC89OZ1gUOejzJJxAQnjHBNBN/McfxdKSfGBVFTAs0pEJXFyurMBOIqK580dQE0cw12jwKtT/fQUerqDcZmFdMm1SHSPTLO271urTtmcpaW92q0mnIx8fwnSXGf58rTFV4u6pbcMvSSU8QzLNjhpBMeAL0TOoz38gQj3s/miNIITpbjCf3AmMMuNAcVOcw254UzGH73GZ1LQg19XsOk4d6HUMilAzv5gDj/ZsuLCrFizNjGMwqnhkasQQzTw98IlbQzBxFBrpBgme+Eqdzn/6MicdEkrgdLxQGiJpkf1lMzF2jt2uJsEIeFIVlCSPP2VJY8uwmB89pZwaifcC9UIx/+d8HNCScadVFHwlmrkKpyZfYu1H15jnTmwBK+sVHomh6guqyIhT+jCGvvhW6zxwCxLTRV1K9b5O1Jdy2MK+UL2Y+okC6N/L9jE3JQt2nhgOpo+jN6R7RtSuoEFktyJdmYpmm8nmzrOkP3wmszvusO6kH1nlGYF23ubaVxTyx7zB6bYcJ07uGxUQVcqvaEPUX1lOW4Stlq4sCa+mWu9x6xY5449Fg3Mktdgk7BjI3YBu2J55XyPTUJLrYLQ3oShfg4bJ4d1ewWuermo9B4/RHWbiVv55eHACkeWWgWOUyMya9JimTWsoboeGXam5rPkRV2ULI3ZsP2g9V56eUXp9u/+L75E840=)

### PR DESCRIPTION
**Pull request by tongxuanbao**
## Description

fixes #20045 

## Markup:

```vue
<template>
  <v-data-table
    :group-by="groupBy"
    :headers="headers"
    :items="desserts"
    item-value="name"
  >
  </v-data-table>
</template>

<script>
  export default {
    data() {
      return {
        groupBy: [
          {
            key: 'group.deep', // work with deep key now
            order: 'desc',
          },
        ],
        headers: [
          { title: 'Dessert (100g serving)', key: 'name' },
          { title: 'Calories', key: 'calories' },
          { title: 'Fat (g)', key: 'fat' },
          { title: 'Carbs (g)', key: 'carbs' },
          { title: 'Protein (g)', key: 'protein' },
          { title: 'Iron (%)', key: 'iron' },
        ],
        desserts: [
          {
            name: 'Frozen Yogurt',
            calories: 159,
            fat: 6.0,
            carbs: 24,
            protein: 4.0,
            iron: '1%',
            gluten: false,
            group: {
             deep: 1,
            }
          },
          {
            name: 'Ice cream sandwich',
            calories: 237,
            fat: 9.0,
            carbs: 37,
            protein: 4.3,
            iron: '1%',
            gluten: false,
            group: {
             deep: 1,
            }
          },
          {
            name: 'Eclair',
            calories: 262,
            fat: 16.0,
            carbs: 23,
            protein: 6.0,
            iron: '7%',
            gluten: true,
            group: {
             deep: 2,
            }
          },
          {
            name: 'Cupcake',
            calories: 305,
            fat: 3.7,
            carbs: 67,
            protein: 4.3,
            iron: '8%',
            gluten: true,
            group: {
             deep: 2,
            }
          },
          {
            name: 'Gingerbread',
            calories: 356,
            fat: 16.0,
            carbs: 49,
            protein: 3.9,
            iron: '16%',
            gluten: true,
            group: {
             deep: 2,
            }
          },
          {
            name: 'Jelly bean',
            calories: 375,
            fat: 0.0,
            carbs: 94,
            protein: 0.0,
            iron: '0%',
            gluten: false,
            group: {
             deep: 2,
            }
          },
          {
            name: 'Lollipop',
            calories: 392,
            fat: 0.2,
            carbs: 98,
            protein: 0,
            iron: '2%',
            gluten: false,
            group: {
             deep: 3,
            }
          },
          {
            name: 'Honeycomb',
            calories: 408,
            fat: 3.2,
            carbs: 87,
            protein: 6.5,
            iron: '45%',
            gluten: true,
            group: {
             deep: 3,
            }
          },
          {
            name: 'Donut',
            calories: 452,
            fat: 25.0,
            carbs: 51,
            protein: 4.9,
            iron: '22%',
            gluten: true,
            group: {
             deep: 4,
            }
          },
          {
            name: 'KitKat',
            calories: 518,
            fat: 26.0,
            carbs: 65,
            protein: 7,
            iron: '6%',
            gluten: true,
            group: {
             deep: 4,
            }
          },
        ],
      }
    },
  }
</script>
```

### CODE REVIEW

**Comment by cjhudson101** [comment]
I was hoping that this would fix the issue with https://github.com/vuetifyjs/vuetify/issues/20045 but it does not appear to fix the group by sort issue.

**Comment by cjhudson101** [comment]
This looks good.  Was hoping this fixed an issue with group by sort getting overriden by sort-by prop, but it does not.

**Comment by tongxuanbao** [comment]
> This looks good. Was hoping this fixed an issue with group by sort getting overriden by sort-by prop, but it does not.

Do you have a reproduce of the issue ? It might be related

**Comment by chudson-incomm** [comment]
@tongxuanbao Another PR appears to be fixing the issue I am describing.  You can take a look at it if you like.

https://github.com/vuetifyjs/vuetify/pull/20047

**Review by johnleider — APPROVED** [review]

**Pull request merged**
