### PR TITLE
fix(VImg): clear polling timer on component unmount

### LINKED ISSUE #18072: [Bug Report][3.3.13] VImg "window is not defined" with Vitest (flaky tests)
### Environment
**Vuetify Version:** 3.3.13
**Vue Version:** 3.3.4
**Browsers:** Chrome 115.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
This issue is hard to reproduce, but is resulting in flaky tests when using Vitest.

Our tests randomly fail from time to time with the following error:

```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 10 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: window is not defined
 ❯ Timeout.poll node_modules/vuetify/src/components/VImg/VImg.tsx:204:7
 ❯ listOnTimeout node:internal/timers:569:17
 ❯ processTimers node:internal/timers:512:7
This error originated in "tests/components/Header.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword
```

The errors are always pointing to: `node_modules/vuetify/src/components/VImg/VImg.tsx:204:7`

I am going to assume it has something to do with this, since it's the only `window` usage in that file:

```ts
timer = window.setTimeout(poll, timeout)
```

Hopefully someone knows what the issue is here, because having flaky test pipelines is getting quite frustrating. 😂

### Expected Behavior
Expect non-flaky tests when using VImg component.

### Actual Behavior
Flaky tests when using VImg component.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqlkEGOwjAMRa9Sed0kGnVWXXEPwgKIRxNo3MoORQj17iShSFXZILH0t/2fv7d38GHoOaqwH/RJeoIW7paqys4NsdBWRcnaeMFcW/iPcZDWmKOjtOaw8yNrwmhoCGaTxgxfKPqAyvVh0+hG/xrnJS5ljRLUgfurICcTC/UCE/3f7QPUPFkIP80TMWuq2x8kM968TQKOyIqRHDLyp5FWa8tYq9ZbtEyfLE1QQ+fpLKtfH6X8efs68rvMxS1b7TJxqqEcmtDPDdg9ANsIqg4=)

### LINKED ISSUE #18651: [Bug Report][3.4.0] VImg thorws error in VDataTableVirtual on fast scroll
### Environment
**Vuetify Version:** 3.4.0
**Vue Version:** 3.3.8
**Browsers:** Google Chrome
**OS:** Linux x86_64

### Steps to reproduce
1. Scroll fast over the list, you will see an error as follows:
```
Cannot destructure property 'naturalHeight' of 'img' as it is null.
```

Might be due to this commit:
https://github.com/vuetifyjs/vuetify/commit/f88588187736c1e538d65b03b8823d77f6f0e6fe

### Expected Behavior
No Error

### Actual Behavior
Following error is emitted to console:
```
Cannot destructure property 'naturalHeight' of 'img' as it is null.
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNq1Vm1r2zAQ/iuH2xEHGtt560tIC+2HboONjbW0jCRQxVYTEb8hK4HM5L/vZFuOE9mMtTQfYuvuHuu5R6eTJqmRcNe+jWNrs6bGyBgLGsQ+EfRmGgKMNx0Sx9lrNnCjUBAWUl6YMqNHBOkIMvdpZ8O4WBNfOQFGS0o8ypPrqVG8TY2Kl+Fs0lfg7iIiDgKWlC2WAgMGjlO1S1xnQ/w1RV9IArp3lsyQm8oFTiTA2rBggfFpBofd1KjEZpmgH0aoBwaVAIwa25mr+mX7QKbcVKeEkg6dh9pJSy7twbdwmLicxQISKta58iyIIy4gBTcK4rWgHuzglUcBtHDJWhID6AoTgXJlEsM1TPJ5UxBM+HQEraevwaJ1BsRnixCHiSBc4HhFtziSebZgd3YMkusBj9uYNiKl9nXIh5giT3MVRiJpV9A09EpsImPqwN9ouBBLMIMmpJ8F1EF/cuZSME+bkLH01wF/U8IbMFvpKiCzqtxzWa4VsVUpSDkRtxQiTka27UecBq8+c1fcwiW0zweO3T93bC/CFVEYKaTSLREUuShPJtMI+sPSkqc/gl6vNGV5YZAjf6VVMscwp9ctTGXe/0nVJbjkR1R/uJSE30kt2Z5OtsK/IDtsIKtMbya7JKxCqaD7FG3Joo7qnoGiOtCoXtRT7V69l2q+o3W2z2RDf61D7BYa4YFOuORREu5l4uraqop5K+FILrpetZTccUr/YJ84VvdSLwRVjCXZQT3ZrsK+leyS8Hmka/slM39eE457/IhvOeee73DPrOB72VANF+/eZTrZBxl2zyqaq37Q1/vBQOsHDWXw3n6QxATbqMZVRDzAQiCrun22b1ZlJezFLvief1BL8KPQi/S6fWah90CYr5eB3r+GWlO4+qCmMGcrXdt7bLSPzNN3WF9VXaUOtIrtZSX7r3ZwcLhVr2R4xqm7h2m24fpG5cTxksJDmFiWdcs52ZpdOU/bwoMzMdszKyCxySrx1ZMTP5oCArNTdMLgE3SdGd7KikBptmTyGPdympbDHZycpmz3ouIKCtJf5NKWT/k/tvO7FN6ijN2Z0bf61qUhnwPLMWZ/ASoIJGs=)

### PR DESCRIPTION
**Pull request by ax-jstern**
## Description
Fixes an issue where a component can be destroyed before the timer completes, causing the callback to be called on an invalid object. Also moves from window.setTimeout to global setTimeout, which seems to be the standard in other files. Calling the callback of a destroyed component, combined with the use of window.setTimeout, caused tests run with vitest
to throw random unhandled exceptions because window was no longer defined. Without having the timer cleared in unmount, there's no good way to ensure it will not trigger after tests clean up.

fixes #18072
fixes #18651

### CODE REVIEW

**Comment by KaelWD** [comment]
> moves from window.setTimeout to global setTimeout, which seems to be the standard in other files

window.setTimeout is the standard in frontend code due to `@types/node` infecting the global setTimeout

**Comment by ax-jstern** [comment]
> window.setTimeout is the standard in frontend code due to `@types/node` infecting the global setTimeout
I'm happy to return it to window.setTimeout. Would clearTimeout and the setTimeout further up in the file also want to go to window.setTimeout / window.clearTimeout in that case? I've flip-flopped a few times in our own frontend code between doing window.setTimeout vs just letting typescript figure out which source it's coming from, so I'd be perfectly happy with either approach.

**Comment by KaelWD** [comment]
Generally best to just stick with whatever the existing code style of the project is.

**Comment by ax-jstern** [comment]
@KaelWD Just a heads up, I don't think this code as it is right now will fix #18651. It looks like for that bug the template ref for 'image' isn't set by the time the initial setTimeout in init is called, so pollForSize is passed a null. I could update this to address that bug if that'd be helpful.

**Pull request closed without merging**
