### PR TITLE
WIP: Add disabled prop to v-form

### LINKED ISSUE #1707: [Feature Request] disable prop for v-form that disables all child input elements
What will it allow you to do that you can't do today?
Disable all fields in a form with one prop

How will it make current work-arounds straightforward?
Remove need to add a disabled prop to every item on a form.

What potential bugs and edge cases does it help to avoid?
Forgetting to add a disabled prop to a given form element

### PR DESCRIPTION
**Pull request by KaelWD**
This would probably be better off as an injection once vuejs/vue#6322 is released, but I'm not sure how to make them reactive. 

Closes #1707

### CODE REVIEW

**Comment by mitar** [comment]
#6097 was merged into Vue.

**Comment by johnleider** [comment]
Is this still a WIP or completed?

**Comment by KaelWD** [comment]
This is still WIP, I think I'll redo it with registrable.

**Comment by mitar** [comment]
Was this implemented somewhere or it is being just closed?

**Comment by KaelWD** [comment]
#1707 is still open, but this PR is no good any more.

**Comment by mitar** [comment]
Thanks.

**Pull request closed without merging**
