### PR TITLE
Set active class if isActive

### PR DESCRIPTION
**Pull request by smiller171**
By allowing `isActive` to set the `activeClass` The initial active tab can be set with `v-model`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by smiller171** [comment]
Should also change how you determine the active link to move the slider appropriately when using the back button https://github.com/vuetifyjs/vuetify/blob/f85456684bd7ef4e91ea34d297d6d1f3be7a98ad/src/components/VTabs/VTabs.js#L139

**Comment by KaelWD** [comment]
That behaviour is intentional. If you are using the `to` prop you probably want to be syncing the tabs with vue-router, so you should be using the router to change the initial path instead. If you have some reasonable rationale for this change, please update the PR filling out all the required details.

**Comment by smiller171** [comment]
@KaelWD I'm using Nuxt generate and want `/` to default to `/about/`. I tried redirecting from `/` to `/about/`, but when I do that my theme doesn't load. Seems to be something wrong with the Nuxt Layout not parsing correctly when doing a redirect. Instead I've set my index file to export about so it renders the same content, but that means if the user is on `/` I want the `about` tab to be active.

I've hacked around this right now to achieve the same result, but first-party support for being able to manually set the active tab instead of being completely dependent on the URL path would be helpful.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please direct them to the official [Discord](https://chat.vuetifyjs.com) server.

**Pull request closed without merging**
