### PR TITLE
docs(locale): Updates and adds German translations

### PR DESCRIPTION
**Pull request by JonasSchubert**
## Description

The docs have only few German  translations and some of them were incorrect, either grammar or wrong words. So I started fixing some and adding new ones.

## Motivation and Context

German translation for docs is in the beginning, so I started my part.

## How Has This Been Tested?

Not unit tested or similar as translations only were added or updated.

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by MajesticPotatoe** [comment]
Docs translations are to be done via our crowdin project.
To start, click the "help translate" in the language selection of the docs.

Thank you for your contribution and interest in improving Vuetify! If you have any questions please make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Comment by JonasSchubert** [comment]
Alright. Working on it ;)
But I cannot find  packages/docs/src/data/i18n/languages.json there. I really want to change the translation for german as it contains a typo. Can you lead me here or change it yourself, @MajesticPotatoe ? Thanks!

**Comment by MajesticPotatoe** [comment]
You wont find that in Crowdin as that is not part of the lang folder, its a part of the docs structure. In the future you can submit those things via PR.
I've edited it manually for you. 63ff6f4 Enjoy.

**Comment by JonasSchubert** [comment]
Thanks!

**Pull request closed without merging**
