### PR TITLE
feat(VTreeview): watch openAll prop

### LINKED ISSUE #9192: [Feature Request] TreeView open-all prop should be watched
### Problem to solve
Allows user to dynamically open all or close all nodes.

### Proposed solution
Instead of just on Mount (https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTreeview/VTreeview.ts#L170), move handling of openAll prop into watcher with immediate property set to true.

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Motivation and Context
fixes #9192

## How Has This Been Tested?
jest, plaground

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-switch v-model="openAll" label="openAll" />
    <v-treeview :items="items" />
    <v-treeview :items="items" open-all />
    <v-treeview :items="items" :open-all="openAll" />
  </v-container>
</template>

<script>
export default {
  data: () => ({
    openAll: false,
    items: [{ id: 1, name: 'FizzBuzz', children: [
      { id: 2, name: 'Foo', children: [] },
      { id: 3, name: 'Bar', children: [
        { id: 4, name: 'Baz', children: [] }
      ]}
    ]}],
  }),
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
If we're watching it, should it not also close all if given false?

**Comment by johnleider** [comment]
Pulse check.

**Comment by jacekkarczmarczyk** [comment]
As i've commented on discord, IMHO whe watch behaviour would be inconsistent with the initial prop value:
- if it's initially true all nodes will be opened, if it changes to true all nodes will open <- that's ok
- if it's initially false some nodes may be opened, some may be closed, if it changes to false all nodes will close <- that I think is inconsistent

One more team's thumb up to Neko's comment and I'll change it ;) @vuetifyjs/core-team

**Comment by johnleider** [comment]
At this time the team is not considering any feature requests for the v2.x Major.

**Pull request closed without merging**
