### PR TITLE
Add option to keep VSnackbar open indefinitely.

### PR DESCRIPTION
**Pull request by Flamenco**
## Description
Add option to use -1 for timeout to keep VSnackbar open indefinitely.

## Motivation and Context
-1 instead of setting to a giant integer value. No need for a setTimeout call in this case.

## How Has This Been Tested?
Not tested at all.

## Markup:

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by nekosaur** [comment]
This is already supported by setting `timeout` to `null`

**Comment by KaelWD** [comment]
Or 0

**Comment by Flamenco** [comment]
That makes sense.  It was not documented, though.  I will update my doc PR...

**Comment by Flamenco** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/pull/469/files

**Pull request closed without merging**
