### PR TITLE
Fixed bug when mask prop is not a string.

### PR DESCRIPTION
**Pull request by azaars**

### CODE REVIEW

**Comment by KaelWD** [comment]
Can you give some information about the bug this is supposed to fix?

**Comment by azaars** [comment]
The mask prop is defined to be of type [Object, String]. The Object type is in preparation for upcoming mask enhanced features. But for now, when an Object is passed, the checking on String.length will fail.

**Comment by KaelWD** [comment]
Have you actually tried passing an object? It fails in maskable.js line 46.  
`this.masked` will always be an array, so this check is pointless.

**Comment by azaars** [comment]
`this.masked` will fail when `mask` is passed as object. Therefore a fix is needed there.

Never mind, I'll pass this pull for now.

**Pull request closed without merging**
