### PR TITLE
adds `disable-hover` prop to disable mouseenter/mouseleave events for tooltip

### LINKED ISSUE #2002: [Feature request] Add possibility to disable showing/hiding tooltip on mouse out
### What will it allow you to do that you can't do today?

It will allow to hide the tooltip only on specific action, like clicking the button for example, otherwise it can be accidentally closed on mouseenter/leave

### How will it make current work-arounds straightforward?

I'm not aware of any workaround for this (could possibly disable pointer events on the activator, but the activator can have its own hover behaviour which would be disabled as well)

### Example usage

This functionality could be used for example when introducing the application to the new user and showing features explicitely instead of making user to discover it by himself
Example codepen: https://codepen.io/anon/pen/dVZOGM - toggling tooltip on hover is not a desired behaviour

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
fixes #2002
Not sure if good prop name

### CODE REVIEW

**Comment by KaelWD** [comment]
I think this would probably be better if it was based on `value` instead of a separate prop. ie. current behaviour if `value == null`, and disable hover otherwise.

**Comment by KaelWD** [comment]
PR: jacekkarczmarczyk/vuetify#1

**Comment by Webifi** [comment]
Since tooltip is toggleable, its "value" is already used for its current toggle state, and it emits "input" on state change.  (v-model compatible.)  I think you'd want to use a different prop, like this PR does.

**Comment by jacekkarczmarczyk** [comment]
Closing in favour of https://github.com/vuetifyjs/vuetify/pull/2164

**Pull request closed without merging**
