### PR TITLE
Enhancement: <v-text-field> to include input masking and formatting

### PR DESCRIPTION
**Pull request by azaars**
An attempt to enhance `v-text-field` to include input masking and formatting. Supported formats are numeral, date, credit card and block. The base source is from [Cleave.js](https://github.com/nosir/cleave.js) & the [Demo here](http://nosir.github.io/cleave.js/). Other formats such as phone number can be injected into the component's `format` props. The following is a sample that can be injected. The sample is using Google's libphonenumber:

`import { asYouType as AsYouType } from 'libphonenumber-js'`

`const LibphonenumberFormatter = {`
`  countryCode: 'US',`

`  formatValue: function (phoneNumber) {`
`    return this.countryCode == null`
`      ? new AsYouType().input(phoneNumber) : new` `AsYouType(this.countryCode).input(phoneNumber)`
`  }`
`}`

`export default LibphonenumberFormatter`

_*libphonenumber-js is available from `npm i libphonenumber-js`_

# Usage
`<template>`
  `<v-text-field :mask="numeric"></v-text-field>`
  `<v-text-field :format="formatter"></v-text-field>`
`</template>`

`<script>`
`import LibphonenumberFormatter from 'libphonenumber-formatter'`

`export default {`
`  props: {`
`    numeric: {`
`       numeral: true,`
`       numeralThousandsGroupStyle: 'thousand'`
`    },`
`    formatter: LibphonenumberFormatter`
`  }`
`}`
`</script>`

### CODE REVIEW

**Comment by johnleider** [comment]
Would it be possible to make a few tweaks to v-text-field and allow it to be supported natively?

**Comment by azaars** [comment]
Thank you for reviewing, John.

By native support, you didn't mean to include `libphonenumber` natively did you? Because that would mean Vuetify will start to have dependencies to external libs in it's build.

**Comment by johnleider** [comment]
No. I mean just being able to hook it up, similar to vuelidate can hook in
for forms.

**Comment by azaars** [comment]
I thought so. So the hook is via the 'format' props.

**Comment by johnleider** [comment]
This going to have to be put on hold until I finish the integrated masking feature that I'm working on for v-text-field, as to not cause any issues.

**Comment by azaars** [comment]
Ok, put on hold it is.

I'm working on a mobile cellular project that requires strong client-side validation of phone numbers. Just so that you'll keep that in mind about allowing a hook to external validators and access to some keystroke events.

**Pull request closed without merging**
