### PR TITLE
Add props.mask watch to reposition the caret

### PR DESCRIPTION
**Pull request by azaars**

### CODE REVIEW

**Comment by johnleider** [comment]
Can you please update this to only include the 1 changed file please.

**Comment by KaelWD** [comment]
This doesn't fix anything as far as I can tell. 

Type a number:
image

Backspace the `3`:
image

Enter `4` instead:
image

Cursor should be behind the `4` I just typed, not the `1`.

**Comment by azaars** [comment]
@johnleider Ok John, I will close this and make a new PR. My apologies.

@KaelWD I comment out those additional lines and I got it working. Watch the GIF. I'll remove them in the next PR. Perhaps we've got it mixed up.

sep-26-2017 23-31-20

**Comment by KaelWD** [comment]
I've merged this in manually, thanks azaars.

**Pull request closed without merging**
