### PR TITLE
fix(VChip): icon size based on chip size prop

### PR DESCRIPTION
**Pull request by daikiojm**
## Description

fixes https://github.com/vuetifyjs/vuetify/issues/13248

## How Has This Been Tested?

visually(use Playground)

before
スクリーンショット 2021-04-12 10 33 25

after
スクリーンショット 2021-04-12 10 32 02

## Markup:

<details>

```vue
<template>
 <v-app id="inspire">
    <div class="text-center">
      <v-chip
        class="ma-2"
        color="indigo"
        text-color="white"
              x-small
      >
        <v-avatar left>
          <v-icon>mdi-account-circle</v-icon>
        </v-avatar>
        Mike
      </v-chip>

      <v-chip
        class="ma-2"
        color="orange"
        text-color="white"
              large
      >
        Premium
        <v-icon right>
          mdi-star
        </v-icon>
      </v-chip>

      <v-chip
        class="ma-2"
        color="primary"
        text-color="white"
        small
      >
        1 Year
        <v-icon right>
          mdi-cake-variant
        </v-icon>
      </v-chip>


    </div>
  </v-app>
</template>

<script>
  export default {
    data: () => ({
      hasMessage: false,
      hideDetails: false,
    }),
    computed: {
      d () {
        return this.hideDetails ? this.hideDetails : 'auto'
      },
    },
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by KaelWD — APPROVED** [review]

**Comment by johannes-huther** [comment]
I recently used a medium sized `v-icon` in a `small` `v-chip`, which (more or less coincidentally) fit perfectly (rounded icon matched curve of chip). After this change, the icon is `small` as well. 

I'd like to reset the icon size, but adding `medium` doesn't do the trick (`large` works, but is to large of cause). Is there a property that does that? Should `medium` work?

```vue
           <v-chip
              small
              :href="GIT_ROOT"
              id="gh-link"
              color="#24292e"
              text-color="white"
            >
              <v-icon class="pr-1" medium>mdi-github</v-icon>
              GitHub
            </v-chip>
```

Before:
image

After: 
image



*To be clear, I don't want to critizise this PR. It does totally make sense in most cases, just not in mine. I'm not sure if this is the right place to ask either, but I figured you might know since you made the change.*

**Comment by gustavosbarreto** [comment]
@johannes-huther same here.

@KaelWD I think this PR should be reverted because that changes modifies the behavior of already existing apps and behaves differently than a `VIcon`  inside a `VBtn`.

Let's take this code snippet as an example:

```
    <v-chip small>
      <v-icon medium>mdi-account</v-icon>
      v-chip
    </v-chip>

    <v-btn primary small>
      <v-icon medium>mdi-account</v-icon>
      v-btn
    </v-btn>
```

before this PR:

download - 2021-06-10T100903 319

after this PR:
download - 2021-06-10T100815 856

It seems to me that the code added by this PR should be on the @daikiojm application's side not in the Vuetify library.

**Comment by tlebel** [comment]
We've also run into the same issues after update; icons got really small. 

Just quick additional note that the current state is not inline anymore with Material Design Chip specs, where the icon size is closer to the previous `24px` for the default/medium size. Cf.: https://material.io/components/chips#types

**Comment by jojomatik** [comment]
Interesting points @gustavosbarreto, @tlebel.

I don't know to much about Material Design, therefore I can't judge what is right or wrong. 

From my point of view this change does make sense, but adding `medium` to the `v-icon` should definitely make it possible to make it look like it looked before this change, which is currently not the case.

**Comment by johannes-huther** [comment]
Interesting points @gustavosbarreto, @tlebel.

I don't know to much about Material Design, therefore I can't judge what is right or wrong.

From my point of view this change does make sense, but adding `medium` to the `v-icon` should definitely make it possible to make it look like it looked before this change, which is currently not the case.

**Comment by KaelWD** [comment]
@daikiojm I'm going to revert this, it breaks more common use cases and I don't have time to look into a proper fix.

**Comment by WIStudent** [comment]
If you liked what this PR did and still want it after it was reverted you can add the following to your own css
```scss
@use "~vuetify/src/components/VChip/variables";
@each $name, $size in variables.$icon-sizes {
  .v-chip.v-size--#{$name} .v-icon {
    font-size: #{map-get($size, 'font-size')}px;
    height: #{map-get($size, 'font-size')}px;
    width: #{map-get($size, 'font-size')}px;
  }
}
```

If you only want it in selected components, add it as scoped style to those:
````html
<style scoped lang="scss">
@use "~vuetify/src/components/VChip/variables";
@each $name, $size in variables.$icon-sizes {
  .v-chip.v-size--#{$name} .v-icon {
    font-size: #{map-get($size, 'font-size')}px;
    height: #{map-get($size, 'font-size')}px;
    width: #{map-get($size, 'font-size')}px;
  }
}
</style>
````

Personally I prefer the icons a bit bigger so I added 4px to each size:
```scss
@use "~vuetify/src/components/VChip/variables";
@each $name, $size in variables.$icon-sizes {
  .v-chip.v-size--#{$name} .v-icon {
    font-size: #{map-get($size, 'font-size') + 4}px;
    height: #{map-get($size, 'font-size') + 4}px;
    width: #{map-get($size, 'font-size') + 4}px;
  }
}
```

If you prefer sass, look  how the PR did it in sass and adapt it accordingly.

**Pull request merged**
