### PR TITLE
feat(VInput): Show error messages with hide-details

### PR DESCRIPTION
**Pull request by zorn-v**
## Description

изображение

## Motivation and Context

If you have input with hide-details you can not see why it is in error state.

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<v-text-field hide-details :rules="[true]" :error-messages="['ERROR 1', 'ERROR 2']"/>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
You can already do this through the append slot, or in a separate element with v-form's slot.

**Comment by zorn-v** [comment]
Yes, but I though that will be good to have such behavior as default.

**Comment by zorn-v** [comment]
More context - if you use `rules` or `error-messages` you expect that messages will be visible in such way.
`hide-details` is broke this expectations. By the way I have hide-details by default because huge margins.

**Comment by KaelWD** [comment]
You can use `hide-details="auto"`. 
hide-details might also be used if you're showing the validation errors externally like in an alert.

**Comment by zorn-v** [comment]
> You can use hide-details="auto"
"Dancing" markup is no good.

**Comment by zorn-v** [comment]
I found a solution :smile:
```vue
<script setup>
const props = defineProps({
  errorText: { type: String },
})
</script>

<template>
  <v-text-field v-bind="$attrs">
    <template #append v-if="errorText">
      <v-tooltip :text="errorText" location="bottom">
        <template v-slot:activator="{ props }">
          <v-icon v-bind="props" role="button">mdi-alert-circle-outline</v-icon>
        </template>
      </v-tooltip>
    </template>
  </v-text-field>
</template>
```

And use function in `error-text` prop which do all magic to return client/server messages or false.
Moreover it is possible to use `append-inner` slot (which is looks more better in this case in my opinion), as no slot props is not required now.

**Pull request closed without merging**
