### PR TITLE
fix(VTreeviewNode): allow empty children item to behave as leaf

### PR DESCRIPTION
**Pull request by GaetanWi**
## Description

Allow a node with empty children array to behave as a leaf

## Motivation and Context

It makes impossible to use activatable and open-on-click property with empty array leaf. 
Fixing https://github.com/vuetifyjs/vuetify/issues/9043

## How Has This Been Tested?

unit test

## Markup:

<details>

```
            if (this.openOnClick && this.children && this.children.length > 0) {
              this.open()
            } else if (this.activatable) {
              this.isActive = !this.isActive
              this.treeview.updateActive(this.key, this.isActive)
              this.treeview.emitActive()
            }
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by GaetanWi** [comment]
Jest is kinda obscure to me. Don't really know how unit test frameworks are working. If someone wanna help on this, I'd gladly appreciate. 

```
  const singleRootWithEmptySubChildrens = { id: 0, name: 'Root', children: [{ id: 1, name: 'Child', children: []}, { id: 2, name: 'Child 2', children: null}] }
  it('should be able to have active children with empty array', () => {
    const wrapper = mountFunction({
      propsData: {
        items: singleRootWithEmptySubChildrens,
        activatable: true,
        openOnClick: true,
        open: [0]
      },
    })
    // I don't even know of to start with here. I need to click on a specific div and see if after the click, it has a special css class. It's all obscure to me (front unit testing always have been)
    expect(wrapper.html()).toMatchSnapshot()
  })
```

**Comment by GaetanWi** [comment]
I commited my work in progress on test. would appreciate a hand on that :)

**Comment by GaetanWi** [comment]
Hello @johnleider . Unit tests have been added to the project ! 😄

**Comment by nekosaur** [comment]
I haven't had the time to review this, but have you explicitly checked if this does not break anything to do with `load-children` functionality?

**Comment by GaetanWi** [comment]
Didn't test the `load-children` part.

Maybe I should use the `hasChildren()` method instead then?

**Comment by GaetanWi** [comment]
Changed code. 
Used `hasChildren` method to prevent any issue if the user specify a `load-children` function.

**Comment by GaetanWi** [comment]
Hello @nekosaur and @johnleider.

Do you need something more for this PR?

**Pull request merged**
