### PR TITLE
fix(VDialog): when long dialog scroll, the background should not scroll

### LINKED ISSUE #3875: [Bug Report] IOS: when long dialog scroll, background should not scroll issue
### Versions and Environment
**Vuetify:** 1.0.15
**Vue:** 2.5.13
**Browsers:** Safari 11.1
**OS:** iOS

### Steps to reproduce
show a dialog with very long height. (NOT a full screen dialog)

### Expected Behavior
the background should not scroll on IOS

### Actual Behavior
the background scrolls sometimes

### Reproduction Link
[https://github.com/](https://github.com/)

### Other comments
To fix this issue:

    beforeCreate Dialog
        document.getElementsByTagName("body")[0].className="noscroll";

    beforeDestroy Dialog
        document.body.removeAttribute("class","noscroll");

STYLUS:
.noscroll
    position: fixed
    overflow-x: hidden
    overflow-y: hidden

### PR DESCRIPTION
**Pull request by hivokas**
## Description
When long dialog scroll, the background should not scroll, but it scrolls (Safari).

## Motivation and Context
This pull request fixes this problem.
fixes #3875

## How Has This Been Tested?
This fix has been tested on iPhone (Safari).

## Markup:
"Overflowed" example of dialog from documentation (https://vuetifyjs.com/en/components/dialogs) reproduces this bug.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by davidp-ctg** [comment]
I tried this on my iPhone, this didn't fix the problem for me.

**Comment by sh7dm** [comment]
@davidp-ctg how did you do that? Did you run a webserver on your computer and connect to it from your iPhone?

**Comment by sh7dm** [comment]
@davidp-ctg strange. Sorry, I can't check this myself.

**Comment by hivokas** [comment]
So what we are going to do?

**Comment by KaelWD** [comment]
@davidp-ctg make sure it was actually applied, scoped css might not work  
@hivokas how did you test the fix on the device?

@hivokas @davidp-ctg what devices/iOS versions/safari versions?

**Comment by davidp-ctg** [comment]
I was not using scoped, css was applied.
iPhone7, latest iOS version: 12.1.2 (which includes latest Safari)

**Comment by johnleider** [comment]
Has there been a final consensus on this being an effective fix?

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

Thank you for your contribution and interest in improving Vuetify!

**Pull request closed without merging**
