### PR TITLE
fix(VSlider): make slider drag respond to mousedown

### LINKED ISSUE #12639: [Bug Report] Sliders do not drag on mousedown
### Environment
**Vuetify Version:** 2.3.18
**Vue Version:** 2.6.11
**Browsers:** Chrome 86.0.4240.193
**OS:** Linux x86_64

### Steps to reproduce
1. create slider
2. Try dragging the slider from a place other than the indicator

### Expected Behavior
Slider drags from anywhere on it

### Actual Behavior
Slider does not drag until you let go

### Reproduction Link
<a href="https://codesandbox.io/s/prod-snow-u3lbr?file=/src/components/Playground.vue" target="_blank">https://codesandbox.io/s/prod-snow-u3lbr?file=/src/components/Playground.vue</a>

### Other comments
[Default browser range sliders support this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)
[Material UI also supports this](https://material-ui.com/components/slider/)

### PR DESCRIPTION
**Pull request by Bluskript**
## Description

Makes the Vuetify slider draggable outside the thumb. Resolves #12639

## Motivation and Context

The default HTML range input allows you to drag the thumb from any part of the body. It is also very unsatisfying to have no feedback on mousedown.
This fixes https://github.com/vuetifyjs/vuetify/issues/12639

## How Has This Been Tested?

Visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-slider></v-slider>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    //
  })
};
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by MajesticPotatoe** [comment]
Looks good, Only thing I see that seems iffy is on v-range-slider if you perform the drag, it will drag the last focused thumb as appose to the closest thumb like it does now.

**Comment by Bluskript** [comment]
Ranged sliders have been fixed. I also updated one of the tests because the active thumb gets updated on drag now:
```diff
+ expect(wrapper.vm.activeThumb).toBe(1)
- expect(wrapper.vm.activeThumb).toBe(0)
```

**Review by BboyAkers — APPROVED** [review]
LGTM

**Review by MajesticPotatoe — APPROVED** [review]
👍

**Pull request merged**
