### PR TITLE
Update globals.ts

### PR DESCRIPTION
**Pull request by nopeless**
globals.ts:3 Uncaught TypeError: Cannot read properties of undefined (reading 'DEBUG')

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nopeless** [comment]
Can I have a response

**Comment by nopeless** [comment]
Well this error pops up in a browser
do you need a reproduction @KaelWD

**Comment by nopeless** [comment]
I looked into the issue again and I found out this issue is reproducable. Please correct me if I'm doing something wrong.

https://stackblitz.com/edit/nuxt-starter-z12gzz?file=package.json,app.vue,nuxt.config.ts

**Comment by nopeless** [comment]
@KaelWD

**Comment by KaelWD** [comment]
Yeah nice, nuxt are defining `process` in the browser without any of the actual properties: https://nuxtjs.org/pt/docs/concepts/context-helpers#process-helpers
Turns out those two are unused anyway, I've just removed them instead.

**Comment by nopeless** [comment]
so the issue is resolved in the next release candidate? @KaelWD

**Pull request closed without merging**
