### PR TITLE
fix(VChipGroup): supports color props

### LINKED ISSUE #19678: [Bug Report][3.5.17] Can't change color of chips in v-chip-group
### Environment
**Vuetify Version:** 3.5.17
**Vue Version:** 3.4.21
**Browsers:** Firefox 126.0
**OS:** Windows 10

### Steps to reproduce
Set color prop on v-chip in v-chip-group. 

### Expected Behavior
The chip color should change with the props color even when the chip is a child of a v-chip-group.

### Actual Behavior
Color props have no impact on chips in a v-chip-group

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNVE1P20AQ/SvTvQASa5eGtlIUEKhV1Z6LygFzMPYQL+yXdtcGFOW/d3bthNhBgkOU2fl4b97Mrm9W7NLarGuRzdkioLKyDHheaIBFx515gofWB3H/clawCnVAV7AUTfHKSKCfp+DJl4KBV2R9J0PVZHwjQy7J+LqtSVW+QQyAErsyCKNj8WdKdabVNcbCZ7lTQCW16KCSpY88tuSnoyjFP3F+1aBHqBphPfjGtLKGOwSHNXA+TqauKYsvic6Cpy6qgDXfwAd8Dtw6oUr3Qj2RuFbp+GccRQlvwr0FHOdAx+/TKZRLEBpm5Jo/YpwiefYwIHUOqxXE/PV6wpD3FGMdg7MXQqHpRK6Ne/TwJAJNIyT8QfPbA5lohAalNMa8Rb7IaSGvC6WEtNHNtYgFRvZXiGy6Q2Qv8p27RUdfOWH7Eny2xgWo8b5sZYBVD1OXoZzD4RGcncPh4IM4Hj+Hm9deDqLMg+Mdx2+jEP4o60yHim7sKPivrNKdGzl/GVOPHD9d+YTOj3x/G2Ot0MuR89KN4a+wakaOHw6Jr0O4diKMqm8Ha32UDFr5It8OhR0zKfSjzx680fQwk356gN4XbCu/YE0I1s/zvKo1ZdYoRecyjSHXVuX0pOO7vZhls+xkRivzYePjsrzzWUKLULeFXhOjUHEPXJV2QtsHEvWwiIIRUjy/08MFpeWu1UEo5LVRqZnTvpcdd4Ze8Tu6KB4dgRRsmE2iiQ1/gOpducSxh50TYYeOO6Qvj4vfto9JmpTtypqE9qQNy16z9TFLZTT5vmd2+x8MW7I7)

### Other comments
The bug had been reported here in August 2023 without follow-up.

https://github.com/vuetifyjs/vuetify/issues/18088

### PR DESCRIPTION
**Pull request by lzl0304**
## Description
fixes #19678 

## Markup:

```vue
<template>
  <v-row justify="center">
    <v-col cols="12" sm="7" md="6" lg="5">
      <v-sheet elevation="10" rounded="xl">
        <div class="pa-4">
          <!--These chips should be red -->
          <v-chip-group color="red" selected-class="text-primary" column>
            <v-chip v-for="tag in 3" :key="tag">
              chip {{ tag }}
            </v-chip>
          </v-chip-group>

          <!--Works without chip-group -->
          <v-chip color="red"> hellooo </v-chip>
        </div>
      </v-sheet>
    </v-col>
  </v-row>
</template>
```

### CODE REVIEW

**Comment by Co-7** [comment]
Thanks for the PR on my problem, just one question, does the change above also fix the application of a color to the VChip with the theme as with the code below ? 

```js
import { createVuetify } from 'vuetify'
import { VChip } from 'vuetify/components/VChip'
import { VChipGroup } from 'vuetify/components/VChipGroup'

export default createVuetify({
  defaults: {
    VChip: {
      class: "chip", // Works
      color: "primary" // Works
    },
    VChipGroup: {
      class: "chip_group", // Works
      VChip: {
        class: "chip_child", // Works
        color: "primary" // Not Working
      },
    }
  },
})
```

**Comment by lzl0304** [comment]
> Thanks for the PR on my problem, just one question, does the change above also fix the application of a color to the VChip with the theme as with the code below ?
> 
> ```js
> import { createVuetify } from 'vuetify'
> import { VChip } from 'vuetify/components/VChip'
> import { VChipGroup } from 'vuetify/components/VChipGroup'
> 
> export default createVuetify({
>   defaults: {
>     VChip: {
>       class: "chip", // Works
>       color: "primary" // Works
>     },
>     VChipGroup: {
>       class: "chip_group", // Works
>       VChip: {
>         class: "chip_child", // Works
>         color: "primary" // Not Working
>       },
>     }
>   },
> })
> ```
> 
> In the example above, the VChip has the primary color applied, but only if it's not a child of a VChipGroup. It's more or less the same problem as my issue, but I don't know if there's another place to modify it or not.

It's effective, I'm not sure if it's the effect you want.
image

**Comment by Co-7** [comment]
I'm not sure either, but at this point, if VChipsGroup's props color is going to change the color of the children's VChips then I should do more like this for the theme :

```js
import { createVuetify } from 'vuetify'
import { VChip } from 'vuetify/components/VChip'
import { VChipGroup } from 'vuetify/components/VChipGroup'

export default createVuetify({
  defaults: {
    VChip: {
      class: "chip",
      color: "primary"
    },
    VChipGroup: {
      class: "chip_group",
      color: "primary"
    }
  },
})
```

If you apply this in the code, the VChips remain red as usual and if you remove the `color="red"` property from the VChipsGroup the VChips take on the primary color ?

**Comment by johnleider** [comment]
Color is applied to the active item in groups. I don't think that this is a bug.

**Pull request closed without merging**
