### PR TITLE
Better spacing (support grid-breakpoints)

### PR DESCRIPTION
**Pull request by Fl0pZz**
[Here](https://repl.it/J0HM/1) i try to show, how it works:
The big spaces between blocks will be only screen size more then 1024px as example

Sorry, my English is too bad to write documentation

### CODE REVIEW

**Comment by johnleider** [comment]
I like this, I only worry about the size it adds to the package, will check out later tonight.

**Comment by johnleider** [comment]
Looking for some input from other dev members.

**Comment by hrayr-artunyan** [comment]
This is very useful, I'm curious why it hasn't been reviewed and merged yet.

**Comment by johnleider** [comment]
It has been reviewed, I forgot to remove the tag. It hasn't been implemented yet as there is still consideration for the increase to the output css size.

**Comment by johnleider** [comment]
One of my current issues is that you remove the existing spacing declarations, making a pretty large breaking change. Is there a specific reason for this?

**Comment by jacekkarczmarczyk** [comment]
You can always leave the old classes (.ma-4 etc) and just add new ones. But of course it will make the CSS size even bigger...

**Comment by HendrikGrobler** [comment]
Any update on this? Would really like to use it ASAP.

**Comment by johnleider** [comment]
I'm considering suggesting a different way of handling this but I'm not sure. Recently a global variable was added for determining the viewport size which would allow something like:

```
:class="{ 'pa-3': $vuetify.breakpoint.sm, 'pa-5': $vuetify.breakpoint.md-and-up }"
```

While this is a bit more to type, I'm considering this to be the solution, willing to hear feedback.

**Comment by dohomi** [comment]
@johnleider I think you are right on this. With the variables dev has full flexibility and the bit of typing does not harm 👍

**Comment by hrayr-artunyan** [comment]
@johnleider this is an excellent solution. The global variables allows for a lot more flexibility in other areas as well.

**Comment by johnleider** [comment]
Closing this in favor of using global variable.

**Pull request closed without merging**
