### PR TITLE
fix(babelrc): transform harmony exports

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
There is no export syntax in ES5, thus `export default` makes the artifact non-importable. CommonJS has become the defacto and this is the correct way to get imports working.

## Motivation and Context

Parsing of the imported es5 module, for example `import colors from 'vuetify/es5/util/colors'` fails. This is mentioned in [doc](https://next.vuetifyjs.com/style/theme#customizing).

This issue at least occurs as a Nuxt.js plugin and probably affect more cases. In some cases this can silently work because babel+webpack is used very widely around the Vue.js community.

## How Has This Been Tested?

Nothing was performed because there is currently no integration tests / doctests.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- The PR title is no longer than 64 characters.
- The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- My code follows the code style of this project.
- (Not applicable) My change requires a change to the documentation.
- (Not applicable) I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Slight coverage regression: just looks like an early return to me though.

**Comment by nekosaur** [comment]
Thank you for your contribution. This is actually something we brought up just the other day.

**Comment by ishitatsuyuki** [comment]
Is this ready to be merged? Actually this issue is a blocker for my migration to new Vuetify versions.

**Comment by ishitatsuyuki** [comment]
@KaelWD can you merge or delegate it to someone with permissions?

**Comment by KaelWD** [comment]
I can, but john wants to check it himself.

**Pull request merged**
