### PR TITLE
Fix/vue version validation

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
Sorry, accidentally changed filemode from 644 to 755

### CODE REVIEW

**Comment by johnleider** [comment]
You committed a revert, is that intentional?

**Comment by jacekkarczmarczyk** [comment]
In the first commit 48cd74b there's a change in the source (intended) and change of file mode 100644 → 100755 (not intended), in the second commit 3222da9 I've reverted only file mode change, so both commits together result only in the changes in the source code, file mode remains 100644

**Comment by johnleider** [comment]
image
This is what I see, I also confirmed by pulling down your branch.

**Comment by jacekkarczmarczyk** [comment]
And this is what you should see when looking at BOTH commits merged together, if you look at only one you'll see the file mode change

**Comment by johnleider** [comment]
Yea, I realized that last night. Sorry for the confusion.

**Pull request merged**
