### PR TITLE
fix(VAutocomplete): call updateMenuDimensions on item prop change

### LINKED ISSUE #10375: [Bug Report] [v-autocomplete] Wrong menu position on items change if it is already open
### Environment
**Vuetify Version:** 2.2.8
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.117
**OS:** Mac OS 10.15.2

### Steps to reproduce
While the autocomplete menu is open and items of the autocomplete change (in the example from empty array to a 5 elements array), the menu doesn't change position until I close and re-open it.

### Expected Behavior
I expect that after the item list of the autocomplete change, it will adjust the dropdown menu position, also if it already open

### Actual Behavior
Position of dropdown position doesn't change until the dropdown menu is not reopened

### Reproduction Link
<a href="https://codepen.io/alessandro-mesti-sinerbit/pen/ZEYNyjW?editors=1010" target="_blank">https://codepen.io/alessandro-mesti-sinerbit/pen/ZEYNyjW?editors=1010</a>

### PR DESCRIPTION
**Pull request by ricardovanlaarhoven**
fixes #10375

## Description
fixes #10375 

## Motivation and Context
#10375 

## How Has This Been Tested?
visually with the codepen code from the issue

## Markup:

<details>

```vue
<template><v-app id="inspire">
  <v-container fluid style="height:100%; padding: 0 10px;">
    <v-row
        align="center"
        style="height: 100%;"
    >
      <v-col cols="12" style="margin-top: auto;">
        <v-autocomplete
            v-model="value"
            :items="items"
            dense
            filled
            label="Filled"
            :loading="loading"
            :menu-props="{ auto: true, overflowY: false }"
        ></v-autocomplete>
        <v-select
            v-model="value"
            :items="items"
            dense
            filled
            label="Filled"
            :loading="loading"
            :menu-props="{ auto: true, overflowY: false }"
        ></v-select>
      </v-col>
    </v-row>
  </v-container>
</v-app>
</template>

<script>
  export default {
    data: () => ({
      items: [],
      values: ['foo', 'bar'],
      value: null,
      loading: true,
    }),
    mounted() {
      setTimeout(() => {
        this.items = ['foo', 'bar', 'fizz', 'buzz', 'color',];
        this.loading = false;
      }, 5000);
    }
  }
</script>


```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by ricardovanlaarhoven** [comment]
I'm not sure if it's ok to just call the updateMenuDimensions when items change. But this does fix it.
I don't know why it would be bad if it's called every time the items change.

**Review by MajesticPotatoe — CHANGES_REQUESTED** [review]
Works v-autocomplete,
Doesn't work for [v-select](https://github.com/vuetifyjs/vuetify/issues/10375#issuecomment-592893663)

**Comment by ricardovanlaarhoven** [comment]
It's a fix just for the autocomplete. The PR and the issue has `autocomplete` in it's title
Does the select use this part of code as well, and is it now broken?
Or what do you mean?

**Comment by ricardovanlaarhoven** [comment]
> Works v-autocomplete, Doesn't work for [v-select](https://github.com/vuetifyjs/vuetify/issues/10375#issuecomment-592893663)
It's a fix just for the autocomplete. The PR and the issue has `autocomplete` in it's title
Does the select use this part of code as well, and is it now broken?
Or what do you mean?

**Comment by MajesticPotatoe** [comment]
> > Works v-autocomplete, Doesn't work for [v-select](https://github.com/vuetifyjs/vuetify/issues/10375#issuecomment-592893663)
> 
> It's a fix just for the autocomplete. The PR and the issue has `autocomplete` in it's title Does the select use this part of code as well, and is it now broken? Or what do you mean?

v-autocomplete extends v-select, You are applying the fix to v-autocomplete, but the same issue in same scenario effects v-select (pretty much take the same codepen and swap out v-autocomplete for v-select and you get the same issue). This is why the original issue was tagged as v-select.

**Comment by KaelWD** [comment]
You could even go down to v-menu for this and use ResizeObserver.

**Comment by ricardovanlaarhoven** [comment]
Thnx!
will check in to that tomorrow morning!

**Comment by ricardovanlaarhoven** [comment]
Couldn't get it to work with the resize observer in VMenu.

I've added the updateMenuDimensions to VSelect and removed it from VAutocomplete. I've updated the playground i used to test it, and both components work

**Pull request closed without merging**
