### PR TITLE
fix(VTextField): remain placeholder after values selected

### LINKED ISSUE #16493: [Bug Report][3.1.2] Combobox placeholder remains displayed when values selected
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just add a placeholder attr to a combobox and then select a value

### Expected Behavior
no placeholder displayed

### Actual Behavior
placeholder displayed

### Reproduction Link
[https://codepen.io/pasco82/pen/qByxZov](https://codepen.io/pasco82/pen/qByxZov)

### LINKED ISSUE #16519: [Bug Report][3.1.2] VAutoComplete doesn't hide placeholder when "multiple" property is defined
### Environment
**Vuetify Version:** 3.1.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 109.0.0.0
**OS:** Windows 10

### Steps to reproduce
Create a v-auto-complete component and define `multiple` and `placeholder` props to it like the below example:

``` html
<v-autocomplete
   :items="items"
   placeholder="Select Item"
   multiple
></v-autocomplete>
```

### Expected Behavior
To hide placeholder when v-model exists or user manually selects items

### Actual Behavior
The placeholder is still visible even after selecting items

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNp9UctugzAQ/BXLlzQSDzVtL4hE6bHnHkMODiyNG8CWH7RNxL93baAlRC0cbO+MZ2fHuwt9ljJqLdCEpgZqWTEDm6whJG1DJqXf+kPNeDOc/Odwa0Qu8A4YmCD4IV0UUK0z2rLKgs7oNZ5w7KUR9uscRRM5HEVVgELKK1SQG/KCTEfMzO9f28pwbD+9vknja2fjCFj+mcFz/HRpPJk61bni0ngKfEqhDCmgZNiFXHqVghmWkLslWW/I3VAjxE+RkN2iFGIRkMWBKbeU/Hz2R4vrPhjZfSQz+gh3S7/pnLPBDQ0or50Z9C+jdy0afCzfG/PzACaYjA4xcgvunNGjMVIncWwbeXqLMI94i1isbGN4DWEh6u1DtIoen+KCazOtR6Dr8KDEhwaFHTM6uPPihpdffzUYYNS9j1a97FBykjdSMeq3oEIFDT42qH99z7hX3mfYjf8h0w6zrHhz0rMYc+0j3O0dpQtoL41kPwfdfwOzrgCz)

### PR DESCRIPTION
**Pull request by gitemad**
## Description

Fix placeholder remains displayed when selecting items in components like VCombobox and VAutoComplete.
I solve this issue using isDirty value in VTextField component.

fixes #16519
fixes #16493

## Markup:

VAutoComplete
```vue
<template>
  <v-app>
    <v-main>
         <v-autocomplete
            v-model="values"
            :items="items"
            placeholder="Select Item"
            multiple
          ></v-autocomplete>
    </v-main>
  </v-app>
</template>
<script>
  export default {
    data: () => ({
      items: ['foo', 'bar', 'fizz', 'buzz'],
      values: ['foo', 'bar'],
    }),
  }
</script>
```

VCombobox
```vue
<template>
  <v-app>
    <v-container>
      <v-combobox
        v-model="select"
        :items="items"
        label="I use chips"
        multiple
        placeholder="asdfasdfasdf"
        chips
      ></v-combobox>
    </v-container>
  </v-app>
</template>

<script>
export default {
  data () {
      return {
        select: ['Vuetify', 'Programming'],
        items: [
          'Programming',
          'Design',
          'Vue',
          'Vuetify',
        ],
      }
    },
}
</script>
```

### CODE REVIEW

**Comment by gitemad** [comment]
@KaelWD 
Can you merge this pull request?
I'm not authorized to do.

image

**Comment by johnleider** [comment]
Can you also try to resolve the Select placeholder issue as part of this PR?

```vue
<template>
  <v-app>
    <v-main>
      <v-autocomplete
        v-model="values"
        :items="items"
        label="Autocomplete"
        placeholder="Select Item"
        multiple
      />

      <v-combobox
        v-model="values"
        :items="items"
        label="Combobox"
        multiple
        placeholder="asdfasdfasdf"
      />

      <v-select
        v-model="values"
        :items="items"
        label="Select"
        multiple
        placeholder="asdfasdfasdf"
      />

    </v-main>
  </v-app>
</template>
<script>
  export default {
    data: () => ({
      items: ['foo', 'bar', 'fizz', 'buzz'],
      values: [],
    }),
  }
</script>
```

**Comment by gitemad** [comment]
> Can you also try to resolve the Select placeholder issue as part of this PR?
> 
> ```
> <template>
>   <v-app>
>     <v-main>
>       <v-autocomplete
>         v-model="values"
>         :items="items"
>         label="Autocomplete"
>         placeholder="Select Item"
>         multiple
>       />
> 
>       <v-combobox
>         v-model="values"
>         :items="items"
>         label="Combobox"
>         multiple
>         placeholder="asdfasdfasdf"
>       />
> 
>       <v-select
>         v-model="values"
>         :items="items"
>         label="Select"
>         multiple
>         placeholder="asdfasdfasdf"
>       />
> 
>     </v-main>
>   </v-app>
> </template>
> <script>
>   export default {
>     data: () => ({
>       items: ['foo', 'bar', 'fizz', 'buzz'],
>       values: [],
>     }),
>   }
> </script>
> ```

Sure. I fixed it.

**Comment by gitemad** [comment]
> > Sure. I fixed it.
> 
> persistent-placeholder is now broken:
> 
> ```
> <template>
>   <v-app>
>     <v-main>
>       <v-autocomplete
>         v-model="values"
>         :items="items"
>         label="Autocomplete"
>         placeholder="Select Item"
>         :multiple="multiple"
>         persistent-placeholder
>       />
> 
>       <v-combobox
>         v-model="values"
>         :items="items"
>         label="Combobox"
>         :multiple="multiple"
>         placeholder="asdfasdfasdf"
>         persistent-placeholder
>       />
> 
>       <v-select
>         v-model="values"
>         :items="items"
>         label="Select"
>         :multiple="multiple"
>         placeholder="asdfasdfasdf"
>         persistent-placeholder
>       />
> 
>     </v-main>
>   </v-app>
> </template>
> <script>
>   export default {
>     data: () => ({
>       items: ['foo', 'bar', 'fizz', 'buzz'],
>       multiple: true,
>       values: [],
>     }),
>   }
> </script>
> ```

Fixed.

**Review by johnleider — CHANGES_REQUESTED** [review]
Everything looks good except the unrelated changes to the package.json files. Can you remove them please?

**Comment by gitemad** [comment]
> Everything looks good except the unrelated changes to the package.json files. Can you remove them please?

I fixed the conflicts.

**Review by johnleider — APPROVED** [review]

**Pull request merged**
