### PR TITLE
fix(VTextField): input not being clicked after clear

### LINKED ISSUE #10965: [Bug Report] click handler not executed when clicked on clearable icon of empty text-field
### Environment
**Vuetify Version:** 2.2.19
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
Click on the right side of the input (the area where the clear icon is show if the clearable field has a value)

### Expected Behavior
Menu should open

### Actual Behavior
Menu doesn't open

### Reproduction Link
<a href="https://codepen.io/jkarczm/pen/OJVdJPm?editors=1010" target="_blank">https://codepen.io/jkarczm/pen/OJVdJPm?editors=1010</a>

### PR DESCRIPTION
**Pull request by Tzahile**
After pressing 'clear' button in a clearable v-text-field, no click event was invoked, and the
v-text-field was only focused. Hence, some anomalies occurred (like v-text-field in a v-menu that is not
opened but only focused).

fix #10965

## Description

In the callback invoked on clear, `clearableCallback( )`, I changed the function being made on the input from `focus()` to `click()`
fixes #10965

## Motivation and Context

Clearing a VTextField resulted only in focusing the component, but no `click` event was invoked.
Therefore, if one wraps his `VTextField` in a `VMenu`, `v-on` is not called after clearing. 
fixes issue [10965](https://github.com/vuetifyjs/vuetify/issues/10965)
## How Has This Been Tested?

It was tested visually only;
`click()` event automatically focuses on the clicked component, therefore changing `focus()` into `click()` should behave similarly.
## Markup:

<details>

```vue
<template>
  <v-container>
    <v-menu min-width="290" offset-y>
      <template #activator="{ on }">
        <div>
          <v-text-field
            v-model="date"
            clearable
            label="date"
            readonly
            v-on="on"
          />
        </div>
      </template>
      <v-date-picker v-model="date" landscape />
    </v-menu>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    date: null
  })
};
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
This fix is not resolving the issue as far as I can test.

**Comment by Tzahile** [comment]
> This fix is not resolving the issue as far as I can test.

@johnleider Thanks for your reply.
I double checked what I did with the template I provided, and it see it does work;

My steps are as follows:
* Click the empty `text-field`
* Choose a date from the `date-picker`
* Click the clearable icon (`x`)
* expect the date-picker to open

Please let me know if I got it wrong

**Comment by johnleider** [comment]
There are 3 components that extend `v-text-field` that also modify the clearableCallback:

image

Do these play into this change at all?

**Comment by MajesticPotatoe** [comment]
@Tzahile pulse check

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Tzahile** [comment]
Hi, sorry for being unresponsive for some time - lately my work kept me busy.
I want to continue with the PR and finish what I've starts during this weekend.
Can we please open the issue back?

**Comment by Tzahile** [comment]
Hi,

I edited further in all the components with `clearable` prop mentioned above.
Currently I'm facing failing tests due to outdated snapshots (after all, I'm changing the way those components are rendered) and I couldn't figure out how I can `--updateSnapshot`.

Please let me know how to continue.

**Comment by johnleider** [comment]
Should be able to simply use the `-u` modifier.

```bash
yarn test:unix -u
```

If not, can you post the error message?

**Review by johnleider — CHANGES_REQUESTED** [review]
please update existing components and test snapshots

**Review by johnleider — CHANGES_REQUESTED** [review]
Are these relevant to your fix?

Autocomplete
image

FileInput
image

**Comment by robreiss** [comment]
Hi @Tzahile 

I started working on #10965 before I saw your PR for the same issue. Sorry about that. I think we read the problem differently and maybe we need to create two separate issues. Let me try to explain.

Issue 1
The issue I am trying to solve is when the clear icon is not visible it is still in the markup and disabled. This creates a dead spot where a users click is not registered to the parent control. My solution is to not include the clear icon in the markup when there is no content instead of disabling it. 

Issue 2
I think the issue your PR addresses is if you click the active and visible clear icon then it will clear the content of the control and set focus to the control but it will not send a "click" event to the control to possibly pop up a datepicker or something. Is that right? I am actually not sure if that is by design or a bug. 

Let me know your thoughts.

**Comment by robreiss** [comment]
Hmmm. I just found a problem with my solution of removing the clear icon when using the VAutocomplete. For some reason if you remove the clear icon the drop down icon "close" function stops working. investigating

**Comment by robreiss** [comment]
Alternative PR is up https://github.com/vuetifyjs/vuetify/pull/13576

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
