### PR TITLE
fix(theme): support vueuse/head v1.0

### PR DESCRIPTION
**Pull request by KaelWD**
## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-btn color="primary" @click="toggle">Toggle theme</v-btn>
    </v-container>
  </v-app>
</template>

<script setup>
  import { useTheme } from 'vuetify'

  const theme = useTheme()

  function toggle () {
    theme.themes.value.light.colors.primary = theme.themes.value.light.colors.primary === '#1976d2' ? '#ff0000' : '#1976d2'
  }
</script>
```

### CODE REVIEW

**Comment by harlan-zw** [comment]
Not sure why the computed isn't triggered with watchEffects but you can make use of the API returned by `push`.

```ts
const getHead = () => ({
  style: [
    {
      children: styles.value,
      id: 'vuetify-theme-stylesheet',
      nonce: parsedOptions.cspNonce || false as never,
    },
  ],
})
// vueuse/head >= v1
if (head.push) {
  const entry = head.push(getHead)
  watch(styles, () => { entry.patch(getHead) })
} else {
  // vueuse/head < v1
  if (IN_BROWSER) {
    head.addHeadObjs(computed(getHead))
    watchEffect(() => head.updateDOM())
  } else {
    head.addHeadObjs(getHead())
  }
}
```

That seems to work but I only tested it with the playground code you posted

**Comment by harlan-zw** [comment]
Oh wait I know, because all of the reactivity is handled by the `useHead` function itself, these lower-level APIs are language agnostic, so they don't handle any of the reactivity for you.

See https://github.com/unjs/unhead/blob/main/packages/vue/src/runtime/composables/useHead/clientUseHead.ts

**Comment by KaelWD** [comment]
Makes sense, thanks. The unhead docs are a bit light on internals.

**Comment by KaelWD** [comment]
This was a breaking change: https://github.com/harlan-zw/zhead/commit/20884dc

**Pull request merged**
