### PR TITLE
refactor(styles): simplify cells selector

### PR DESCRIPTION
**Pull request by Djaler**
## Description
Looks like this old selector works for `not first child` **and** `first child` = `for all childs`. I just simplify it

## How Has This Been Tested?
visually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
Can you please provide an example of what this fixes either from an already created issue or a codepen.

**Comment by Djaler** [comment]
@johnleider I don't fix anything. This is just refactoring

**Comment by jacekkarczmarczyk** [comment]
Closing this as due to data table refactor all data table changes should go to next branch anyway and most probably this one is not needed anymore

Thank you for your interest in improving Vuetify though!

**Comment by nekosaur** [comment]
I can confirm that this css does not exist in refactor

**Pull request closed without merging**
