### PR TITLE
fix(VDataTable): sticky header problem with bgColor

### PR DESCRIPTION
**Pull request by websitevirtuoso**
Fixes https://github.com/vuetifyjs/vuetify/issues/18984

## Markup:

```vue

```

### CODE REVIEW

**Review by johnleider — APPROVED** [review]

**Comment by SveinnB** [comment]
@websitevirtuoso thank you for this PR 👍🏻 
But I have one problem
See [https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtlG1P2zAQx7/KLW+6SYQmlLRrVZA6NLqBuk3AxCTKC5McrYVjW7YLY1W/+y59TGlLWkHeOL4727/7n303Q8+auNzSev9xgF7DazpMtWAOj7sSoPnoM63Hv+NJrKRjXKKBWDBrj7reXc/XXD50vWnQOMyop/mUDPr4O+BfjbHDBFwfoY8soT2cgjuEbDkI/oBjl2N3Asks1FOzPDt5um3CHPPHAQszQIMTcoYSM2O73pKrj7zXd+Q7CIJll3U8fnjOW3IZOcOk1cygdPlVx81yHmKRMZnzKa9T4Of5K+m8zGEjy3YE2WxeqUkdyTIpZLOcKzBNbWy4dmDRDSZ4PNXKOBiCwXsYwb1RKZTobpSycFJJSesgtT04yiI+lr6hEAqulRHJh9KnfFCWC0XdTKCGM1bJUmxA6VSZBDoD65jslfZmzr4yFrV6QtOAwyiY2+8HKGhRm1klKKvFAmV4j0ty/b5sLaza8JgOiaIgmO0xmo4vOa7QCgYdlaCAy/Ug1doKyFdBt5kO2RKkVqevAORL5xo6lfUEUVDZQYo2mpTJ51UKUqNIjtYg4XBxWd3AUQ/fgSMM6sUgJ318NEqggxOWMqM2lObNd6RKraGI5RedGFNzqofheoxKbVbdt+kSFrOcsd6AGTj1r551bvOlKtWiXUQ5X9VkC44O+5fQu/njR+shws+7XJUzpplc4TioFnP84NYyCe0r/2KDGtVd1FgPEoaV6LBQETQxJmj9VqdNPBtoDt7jJYdhRE9oiec26+2Tbk593BvteZX9w/3Im4xh4N3+B+dOP9M=)

**Comment by websitevirtuoso** [comment]
Yes I see. It has to be new prop to set bgColor for header.

**Comment by websitevirtuoso** [comment]
What about option to set prop header
and for each item set class

```
![image](https://github.com/vuetifyjs/vuetify/assets/5112918/652bdc13-1317-41d6-82c9-586905f5470f)

```

**Comment by websitevirtuoso** [comment]
Created new PR with option to control color via props
ex:
image

**Pull request merged**
