### PR TITLE
feat: functional VSnackbar

### PR DESCRIPTION
**Pull request by L-Chris**
## Description
use VSnackbar with function, just like
`const message = this.$snackbar.error({ message: 'Something wrong!' })`
`// do something`
`message.close()`

## Motivation and Context
the feature is very common in other UI framework. And It can reduce the code.

## How Has This Been Tested?
tested in playground

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by johnleider** [comment]
I like this, but it is a massive breaking change.

**Comment by L-Chris** [comment]
ok

**Comment by bdeo** [comment]
@L-Chris Can you can write some tests for this, especially in VSnackbar? I want to start reviewing and test it locally to prepare it for merge.

**Comment by bdeo** [comment]
After further review, @johnleider mentioned this needs to not share a new Vue instance and should be installed as a method into $vuetify in src/components/Vuetify/index.js similar to goTo.js

**Comment by johnleider** [comment]
Overall this implementation has quite a few issues and while we are internally looking at a good way to do it, this will not be it. Thank you for your contribution.

**Comment by lynzz** [comment]
support importing snackbar ?
```
import snackbar from 'vuetify/util/snackbar'
```

**Comment by weihongyu12** [comment]
here are a lot of functions that require functional calls like this. After all, not all functions need to be called in the component. We also need some JS native calls.

Usually we will package them as a global Vue instance method.

I sorted it out, this type of component has:

- Dialogs: used for popping up prompts or confirming text
- Progress: used for loading progress bar
- Snackbar: used for pop-up reminders or message notifications

Currently in Vuetify, all three components can only control display through `v-model`.

We can refer to other Vue third-party components, such as `element`, `element` has many built-in instance methods:

- loading: [http://element.eleme.io/#/en-US/component/loading](http://element.eleme.io/#/en-US/component/loading)
- message: [http://element.eleme.io/#/en-US/component/message](http://element.eleme.io/#/en-US/component/message)
- message-box: [http://element.eleme.io/#/en-US/component/message-box](http://element.eleme.io/#/en-US/component/message-box)
- notification: [http://element.eleme.io/#/en-US/component/notification](http://element.eleme.io/#/en-US/component/notification)

Control the display of related elements by something like `$loading`.

I think we can design such an API:

``` javascript
Vue.prototype.$dialogs(options);
Vue.prototype.$loading(options);
Vue.prototype.$snackbar(options);
```

**Pull request closed without merging**
