### PR TITLE
feat(datatable row): DataTable header cellClass

### LINKED ISSUE #8474: [Feature Request] ability to modify VDataTable cell's properties without using `item` slot
### Problem to solve
When i create a datatable, i pass a headers and a item array to it.
If i want to add a style to a specific column (eg. color, font-size, alignment, disable sorting...) i have to use the template "<template v-slot:item.COLUMNNAME>...</template>". If i add a style in e extra <div> the style works, but the elements in the resulting table were nested like following.

< td>
   < div style:"color=red">Text< /div>
< /td>

instead of 

< td  style:"color=red">
   Text
< /td>

### Proposed solution
Add a property for passing the styles directly via the slot to prevent nesting of resulting elements.

### PR DESCRIPTION
**Pull request by peteruithoven**
## Description

DataTable headers cellClass property enabling adding classes to td's

fix #8474

## Motivation and Context
It's hard to add classes to DataTable cells / td's. Being able to add these classes more easilly enables:
- Tweaking width of columns when the header is hidden (`hide-default-header`)
- Changing the padding in the cells
- Other kinds of styling that would otherwise require a extra element like setting a background or text color. 

Also see: #8474

## How Has This Been Tested?

I've tested this in the Playground. ~~I can work on unit tests?~~
**Update** I've added a unit test:
https://github.com/vuetifyjs/vuetify/pull/11768/files#diff-44a9b747492d2b82ba824229ad9e5800

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="items"
    />
  </v-container>
</template>

<script>
  export default {
    data () {
      return {
        headers: [
          { text: 'Impact', value: 'name', cellClass: 'pl-0' },
          { text: 'Score', value: 'score', align: 'end', cellClass: ['pt-8', 'pb-8'] },
          { text: 'Counter', value: 'counter', align: 'end' },
        ],
        items: [
          { name: 'A', score: 10, counter: 1 },
          { name: 'B', score: 20, counter: 2 },
          { name: 'C', score: 30, counter: 3 },
        ],
      }
    },
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

I'm not sure what to add to the documentation? I did update the API.

### CODE REVIEW

**Comment by peteruithoven** [comment]
I've opened a separate issue on a helper to make some of this code easier and centralize the unit tests I should add.
https://github.com/vuetifyjs/vuetify/issues/11769

**Comment by peteruithoven** [comment]
Should have opened this against the dev branch. Opened a new PR: https://github.com/vuetifyjs/vuetify/pull/11775

**Comment by DRoet** [comment]
Just FYI you should be able to change the base branch if you press the "edit" button on the top right. In case it happens again in the future 😄

**Comment by peteruithoven** [comment]
:facepalm: @DRoet thanks

**Pull request closed without merging**
