### PR TITLE
fix(VOtpInput): limit length when type=number

### PR DESCRIPTION
**Pull request by yuwu9145**
## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-otp-input />
    </v-container>
  </v-app>
</template>

```

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
shouldn't it set https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode?

**Comment by yuwu9145** [comment]
> shouldn't it set https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode?

It says:

> It's important to understand that the inputmode attribute doesn't cause any validity requirements to be enforced on input.

**Comment by jacekkarczmarczyk** [comment]
I'm aware of this, it's not suppose to do any validation, it's for showing proper keyboard

**Comment by KaelWD** [comment]
#18560

**Comment by yuwu9145** [comment]
tested on my iphone, no regression

**Pull request merged**
