### PR TITLE
feat(VImg): Add prop to set crossorigin attr on v-img

### PR DESCRIPTION
**Pull request by websitevirtuoso**
## Description

https://github.com/vuetifyjs/vuetify/issues/17848

## Markup:

```vue

  <v-app>
      <v-img src="https://t3.ftcdn.net/jpg/00/92/53/56/360_F_92535664_IvFsQeHjBzfE6sD4VHdO8u5OHUSc6yHF.jpg" />
</v-app>
  <v-app>
      <v-img  crossorigin="use-credentials" src="https://t3.ftcdn.net/jpg/00/92/53/56/360_F_92535664_IvFsQeHjBzfE6sD4VHdO8u5OHUSc6yHF.jpg" />
</v-app>
```

### CODE REVIEW

**Comment by websitevirtuoso** [comment]
Anyone assist please. How o change to dev branch? 

When I do this via ui to apply changes for 1500 files

**Comment by MajesticPotatoe** [comment]
@websitevirtuoso probably best to do it locally via git.

**Comment by websitevirtuoso** [comment]
@MajesticPotatoe I did locally like

git merge origin/dev
git push my_origin/vimg-crossorigin
how to update PR now?

**Comment by pg-ahenry** [comment]
think you got that branch name wrong
[feat/vimg-crossorigin](https://github.com/websitevirtuoso/vuetify/tree/feat/vimg-crossorigin)
gotta push to github, and then change the base here

**Comment by MajesticPotatoe** [comment]
think you got that branch name wrong
[feat/vimg-crossorigin](https://github.com/websitevirtuoso/vuetify/tree/feat/vimg-crossorigin)
gotta push to github, and then change the base here

**Comment by KaelWD** [comment]
For next time: rebase and force push.

**Comment by websitevirtuoso** [comment]
Ok I will know

**Pull request closed without merging**
