### PR TITLE
fix(VTab): remove firefox invalid keyframe property

### LINKED ISSUE #16258: [Bug Report][3.0.4] VTab generates invalid keyframe background-color value
### Environment
**Vuetify Version:** 3.0.4
**Vue Version:** 3.2.45
**Browsers:** Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
- open codepen in firefox (used 107.0 on linux)
- open browser console (not just codepen console)
- flip between tabs and watch warning in console:
```
Keyframe property value “” is invalid according to the syntax for “background-color”. animation.ts:46:23
Keyframe property value “” is invalid according to the syntax for “transform”.
```
- using a breakpoint, this is caused by https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/components/VTabs/VTab.tsx#L98

### Expected Behavior
No warnings

### Actual Behavior
```
Keyframe property value “” is invalid according to the syntax for “background-color”. animation.ts:46:23
Keyframe property value “” is invalid according to the syntax for “transform”.
```

### Reproduction Link
[https://codepen.io/codesurfr/pen/MWXRvWv](https://codepen.io/codesurfr/pen/MWXRvWv)

### Other comments
I'm flagging this because it is polluting the browser log with warnings and I can't see other actually useful warnings. Dunno what your policy on such warnings is. The warnings are not shown in an up-to-date vivaldi browser, for example.

### PR DESCRIPTION
**Pull request by alexandreec**
Fixes #16258

### CODE REVIEW

**Comment by KaelWD** [comment]
This has the same problem as your previous PR.

https://github.com/vuetifyjs/vuetify/assets/16421948/31f86713-e14b-4924-a482-3668efdd2f87

**Comment by alexandreec** [comment]
@KaelWD I see now, sorry.

I just removed the `backgroundColor` option from the animate function, now it seems that it works properly, 
* Tested it in Firefox, Opera, Edge and Chrome (linux versions)

https://github.com/vuetifyjs/vuetify/assets/15526814/abe3426b-4ed7-406e-a772-1973cf65f92e

**Comment by alexandreec** [comment]
@KaelWD I prefer this rather than having an annoying warning in Firefox.

**Comment by lacksfish** [comment]
This fix would be needed for Firefox, currently without it warnings are being thrown. 

@alexandreec Possibly another similar fix is needed for the "transform" warning ?

image

**Pull request merged**
