### PR TITLE
feat: allow do something with vnode when image error

### PR DESCRIPTION
**Pull request by bluelovers**
## Description

something about if `src` is fail loaded, we can set it back to `lazy-src` or do other with vnode

## How Has This Been Tested?

i can't build this repo at local by some unknow reason
so i didn't test
but i try find vnode by chrome and set `vnode.__vue__.image.src = "xxxx" ` is work, so i think this change should be ok too

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
What is this for? You can access vnode using refs

**Comment by KaelWD** [comment]
Please explain what this is for and how it's supposed to be used.

**Comment by bluelovers** [comment]
i wanna do something like this

```html
<v-img
    src="a_image_url_maybe_not_exists1"
    lazy-src="a_image_url_maybe_not_exists2"
    height="150px"
    align-center="true"
    align-content-center="true"
    v-on:error="imageError"
    v-on:load="imageLoaded"
    slot="activator"

>
</v-img>
```

```ts
...

	imageError(url, vnode)
	{
		vnode.image.src = 'another_image_url_exists'
	}

...
```

**Comment by KaelWD** [comment]
Bind `:src` dynamically, you should never change props that way.

**Pull request closed without merging**
