### PR TITLE
fix(VBottomNavigation): make it work the input-value prop

### LINKED ISSUE #11640: [Bug Report] v-bottom-navigation appears on scroll when disabled
### Environment
**Vuetify Version:** 2.3.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.97
**OS:** Mac OS 10.15.2

### Steps to reproduce
Scroll the window content

### Expected Behavior
You should be able to scroll and bottom navigation should stay hidden since `input-value=false`

### Actual Behavior
Bottom-navigation pops up. 

### Reproduction Link
<a href="https://codepen.io/thomaskuhlmann/pen/OJMRJYx" target="_blank">https://codepen.io/thomaskuhlmann/pen/OJMRJYx</a>

### PR DESCRIPTION
**Pull request by ryo-gk**
## Description

The `input-value` prop was not checked when `thresholdmet` is invoked.
Fixed that to check the prop then.

## Motivation and Context

fixes #11640 

## How Has This Been Tested?

unit, visually

## Markup:

<details>

```vue
<template>
  <v-app>
    <v-bottom-navigation
      :input-value="show"
      app
    >
      <v-btn >
        <span >test</span>
        <v-icon>mdi-home</v-icon>
      </v-btn>
    </v-bottom-navigation>
    <v-main>
        <v-app-bar style="position: sticky; top: 0;">
          <v-spacer />
          <v-toolbar-title>Title</v-toolbar-title>
          <v-spacer />
        </v-app-bar>
        <v-sheet class="overflow-y-auto">
          {{ sentence.repeat(50) }}
        </v-sheet>
    </v-main>
  </v-app>
</template>

<script>
export default {
  data () {
    return {
      show: true,
      sentence: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero similique
          a harum repellendus maiores, porro aliquid placeat molestiae quos
          molestias? Architecto iure sint quis repudiandae corrupti fugiat dolore.
          Corrupti, unde? Lorem ipsum dolor, sit amet consectetur adipisicing elit.
          Aspernatur ab dicta incidunt natus tenetur dolorum, exercitationem ea
          minus inventore expedita culpa mollitia quam ullam cupiditate magnam error
          accusamus perspiciatis. Possimus.`
    }
  },
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
Thank you for your interest in improving Vuetify. Please create unit tests that correlate to the changes made in this request.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ryo-gk** [comment]
I added unit tests (https://github.com/vuetifyjs/vuetify/pull/11778/commits/fe370678ab269c0c8506eb96be74a410466c2466). Could you check it?

**Review by johnleider — DISMISSED** [review]
these tests pass regardless of the branch. we need a test that is going to protect against regression.

**Comment by MajesticPotatoe** [comment]
pulse check

**Review by MajesticPotatoe — APPROVED** [review]

**Review by johnleider — CHANGES_REQUESTED** [review]
The unit tests pass without the fix and also contains superfluous code, e.g. waiting for the `$nextTick`.

**Comment by MajesticPotatoe** [comment]
This PR is being closed due to:

- [x] Requested changes not provided (inactivity for 14 days)

Once the requested changes are made, we will reopen  and continue the review process. Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
