### PR TITLE
Fixed menu position

### PR DESCRIPTION
**Pull request by cawa-93**
Now the menu can be fixed near the activator and goes beyond the screen

### CODE REVIEW

**Comment by johnleider** [comment]
Could you please post an example implementation so I can load it in the playground.

**Comment by cawa-93** [comment]
Old:
```vue
<v-menu></v-menu>
```
New
```vue
<v-menu fixed-offset-y ></v-menu>
<v-menu fixed-offset-x ></v-menu>
```

**Comment by johnleider** [comment]
What is the usecase for this?

**Comment by cawa-93** [comment]
https://codepen.io/cawa-93/pen/LjWmEo/?editors=1010
The current behavior is as follows:
If you try to open a menu whose activator is at the bottom of the visible area, the menu will move up and to the left so that it fits into the visible area.
The presence of the `fixed-offset-*` attribute prevents such behavior, forcing the menus always appear in the same place, and go outside the visible zone.

**Comment by johnleider** [comment]
The behavior of menu has since changed and this PR is no longer needed. Thank you for your contributions.

**Comment by cawa-93** [comment]
How exactly did the behavior change?

**Pull request closed without merging**
