### PR TITLE
feat(VGrid): support for no grow/shrink, and better documentation

### PR DESCRIPTION
**Pull request by justinhelmer**
Reference: PR https://github.com/vuetifyjs/vuetify/pull/6533
Resolves https://github.com/vuetifyjs/vuetify/issues/6530

### CODE REVIEW

**Comment by sh7dm** [comment]
Don't worry about this:
default

**Comment by justinhelmer** [comment]
Wow you are fast :-)

One question - since this is in `next`, any ETA on when the package will be published for all to use? Otherwise we need to keep having custom classes in our code.

**Comment by sh7dm** [comment]
@justinhelmer what version do you use?

**Comment by justinhelmer** [comment]
@sh7dm - The latest published artifact:

```
npm view vuetify version
1.5.1
```

My assumption is that the `next` branch will be for `2.x` and as such, is not yet ready. Perhaps you are going to suggest we jump onto `2.0.0-alpha.X`?

**Comment by sh7dm** [comment]
`next` changes will be released in `v2.0.0-alpha.5` on Tuesday. `master` and `dev` are feature-frozen now

**Comment by MajesticPotatoe** [comment]
@justinhelmer would never suggest using an alpha/beta in production, considering stability is questionable and we are not accepting bug reports for 2.0 at this time. However you would be correct that if you would like to use these changes you would need to use use the alpha build. You are also welcome to patch these changes locally and use your own custom build knowing they will be there when upgrading to 2.0.

**Comment by justinhelmer** [comment]
Thanks, @sh7dm and @MajesticPotatoe.

Please let me know if you need anything else from me to get this merged into `next`, and become part of the `2.0.0-alpha.5` version being released tomorrow.

Cheers.

**Pull request merged**
