### PR TITLE
fix(VDataTable): support groupBy when sorting is disabled

### LINKED ISSUE #20046: [Bug Report][3.6.10] VDataTable: GroupBy sort is not possible when sorting is disabled
### Environment
**Vuetify Version:** 3.6.10
**Last working version:** 2.7.2
**Vue Version:** 3.4.27
**Browsers:** Chrome 125.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
When `disable-sort` is set on a `v-data-table`, any sorting in `group-by` is also disabled.

### Expected Behavior
Sorting should still work for the grouping

### Actual Behavior
Grouping does not work.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrFlt9v2jAQx/+VU6SprcSPEEhaIjapa7eu6x72OpU+mORKo5o4chw2VvV/n01MSEyMCg8dD8i+88X3+Z7Pyf2Lk/Oof5llvWWBTuhMBC4ySgR+mqYAk2U3JoJ0BZlRVAaAOMnVpJszLkpLOOesyLqz1cepsx5+Xk0d7XpCEiPPpUePKk8iN1L2GPMcuagcyt5dElqgdKZkgaWjTKdfz0eaJv1aunKaRzzJxHptvw+XcQxT5wVEIiiGcHKjkjvpwDOu5Gyd6gm8dqYOCAY6PzVUaBAxzjESdKUehn8yZYvxkRRUwIuWQqZyeraZAXAUBU+3cwAtRwj3WxvUF6hfPZ1O08W4zEk6pUhR0yfTrmYPtbHGMHesNLgu5YbTgevOQQ6XSTo/q0RRgq81aQ2+IpTxBPNqebQxWEO+ErlXbYNHIvY9n8/yxvJIWewBPzkTmKSNkKy02YNuOZMRH7YRiTTYl9tOTav8m9O8v+JKZaUNZ38xhV9sXnBhln4jbQgDf2z4pIghBD13J0SKFYI3MuxakRBGOyEKXWYy+GBuP6eFQOl6JDRH06c0kHlZD6QN+DZCiDiSBeQkjX8n0ZOd2huet1GPbdQ7y2vUw/9K/SWiJOF7SAOvjXRgL7DJU6HuhmjUcyuq4IWFtJnVW0iviiwiz2hHHbp+G+qwZxZPkwaHF/XiXUhv5K2JfCbPcryH1g8OK+zIbPQKd9gzXZszHLwL73ekdAUzJOke3PPW4ro22rH1ntoN0bTuMR17OO0PRmmSsZ3XcY113Nqzbs80b1gvrKztpN4xpM2WeAvpN5biKmKLmR115Jq56561oF5YezbomQdEw478Iw7x4bDXLC32vGdHfmtNPd92gP3mu6BxO1na1bPX1U7a7JO3kN4l4k5+aFlR/UFrTT3rzRSYlatQzWpr0GOuJTvn9hPrtRyUTjmZ9Ktvfue1kxaUrv8e/gEDKCrQ)

### Other comments
Was added to Vuetify 2 in https://github.com/vuetifyjs/vuetify/pull/13027

### PR DESCRIPTION
**Pull request by lzl0304**
## Description

fixes #20046 

## Markup:

```vue
<template>
  <v-data-table
    :group-by="groupBy"
    :headers="headers"
    :items="desserts"
    item-value="name"
    disable-sort
  />
</template>

<script>
  export default {
    data () {
      return {
        groupBy: [
          {
            key: 'group',
            order: 'desc',
          },
        ],
        headers: [
          { title: 'Dessert (100g serving)', key: 'name' },
          { title: 'Calories', key: 'calories' },
          { title: 'Fat (g)', key: 'fat' },
          { title: 'Carbs (g)', key: 'carbs' },
          { title: 'Protein (g)', key: 'protein' },
          { title: 'Iron (%)', key: 'iron' },
          { title: 'Group', key: 'group' },
        ],
        desserts: [
          {
            name: 'Frozen Yogurt',
            calories: 159,
            fat: 6.0,
            carbs: 24,
            protein: 4.0,
            iron: '1%',
            gluten: false,
            group: 1,
          },
          {
            name: 'Ice cream sandwich',
            calories: 237,
            fat: 9.0,
            carbs: 37,
            protein: 4.3,
            iron: '1%',
            gluten: false,
            group: 1,
          },
          {
            name: 'Eclair',
            calories: 262,
            fat: 16.0,
            carbs: 23,
            protein: 6.0,
            iron: '7%',
            gluten: true,
            group: 2,
          },
          {
            name: 'Cupcake',
            calories: 305,
            fat: 3.7,
            carbs: 67,
            protein: 4.3,
            iron: '8%',
            gluten: true,
            group: 2,
          },
          {
            name: 'Gingerbread',
            calories: 356,
            fat: 16.0,
            carbs: 49,
            protein: 3.9,
            iron: '16%',
            gluten: true,
            group: 2,
          },
          {
            name: 'Jelly bean',
            calories: 375,
            fat: 0.0,
            carbs: 94,
            protein: 0.0,
            iron: '0%',
            gluten: false,
            group: 2,
          },
          {
            name: 'Lollipop',
            calories: 392,
            fat: 0.2,
            carbs: 98,
            protein: 0,
            iron: '2%',
            gluten: false,
            group: 3,
          },
          {
            name: 'Honeycomb',
            calories: 408,
            fat: 3.2,
            carbs: 87,
            protein: 6.5,
            iron: '45%',
            gluten: true,
            group: 3,
          },
          {
            name: 'Donut',
            calories: 452,
            fat: 25.0,
            carbs: 51,
            protein: 4.9,
            iron: '22%',
            gluten: true,
            group: 4,
          },
          {
            name: 'KitKat',
            calories: 518,
            fat: 26.0,
            carbs: 65,
            protein: 7,
            iron: '6%',
            gluten: true,
            group: 4,
          },
        ],
      }
    },
  }
</script>
```

### CODE REVIEW

**Comment by SystemKeeper** [comment]
I don’t think the condition is correct now, it should depend on group by, see the original fix for vuetify2 https://github.com/vuetifyjs/vuetify/pull/13027

**Comment by lzl0304** [comment]
> I don’t think the condition is correct now, it should depend on group by, see the original fix for vuetify2 #13027

Thank you for the reminder. You are right. I oversimplified the issue. I will also try to restore the unit tests simultaneously.

**Comment by cjhudson101** [comment]
Just tested this change to see if it fixed an issue where sort-by overrides the group by order.  This change does restore group by sort by to respect each other properly!  Yay!!!

**Review by chudson-incomm — COMMENTED** [review]
Interesting way to check expected values from items array against nth child value in an anonymous function like that.  When we do e2e tests we actually just use a constant and check the first/last value after sorting.  May have to steal that syntax and write some component tests in our cypress test suite.  

This looks good to me.

**Review by johnleider — DISMISSED** [review]

**Review by johnleider — APPROVED** [review]

**Pull request merged**
