### PR TITLE
Fix toolbar style typo

### PR DESCRIPTION
**Pull request by anotherssa**
Fixes probable typo in toolbar's style.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by KaelWD** [comment]
`git rebase --onto master HEAD~1 && git push --force`

**Comment by johnleider** [comment]
What does this fix?

**Comment by anotherssa** [comment]
```
-    > .btn:last-child, > .menu:first-child
+    > .btn:last-child, > .menu:last-child
       margin-right: 8px
```
There's next style definition inside _toolbar.styl
```
.toolbar
    &__content, &__extension
        > .btn:last-child, > .menu:first-child
           margin-right: 8px
```
It adds right margin for the first menu inside .toolbar__content. I thought author meant it to be for the last menu inside .toolbar__content.

**Comment by johnleider** [comment]
What I mean is, provide markup that shows what this fixes.

**Comment by anotherssa** [comment]
[Here.](https://codepen.io/anotherssa/pen/rJqPYe) Take a look at the menu activator in form of avatar.

**Pull request merged**
