### PR TITLE
Show data iterator controls at top

### PR DESCRIPTION
**Pull request by Samour**
## Description

Add a prop `actions-top` to data iterators & data tables
When true, pagination controls are displayed above content instead of below
Also a `prepend` slot is added which will display above content. If `action-top` is set to true, the `prepend` slot will appear between the pagination controls & the content.
Resolves vuetifyjs/vuetify#2985

## Motivation and Context

Allows for improved UX in cases where a user may want to change pages without having to scroll down a potentially large page

## How Has This Been Tested?

Added unit tests - jest snapshots

## Markup:

```vue
<template>
  <v-data-iterator :items="items" :actions-top="true">
    <div slot="prepend">
      My custom header
    </div>
    <div slot="item" slot-scope="item">
      {{ item.item }}
    </div>
  </v-data-iterator>
</template>

<script>
  export default {
    data() {
      return {
        items: [
          'A',
          'B',
          'C',
          'D',
          'E',
          'F',
          'G',
          'H',
          'I',
          'J'
        ]
      }
    }
  }
</script>
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by KaelWD** [comment]
Please paste your *entire* working Playground.vue

**Comment by Samour** [comment]
```vue
<template>
  <v-data-iterator :items="items" :actions-top="true">
    <div slot="prepend">
      My custom header
    </div>
    <div slot="item" slot-scope="item">
      {{ item.item }}
    </div>
  </v-data-iterator>
</template>

<script>
  export default {
    data() {
      return {
        items: [
          'A',
          'B',
          'C',
          'D',
          'E',
          'F',
          'G',
          'H',
          'I',
          'J'
        ]
      }
    }
  }
</script>
```

**Comment by nekosaur** [comment]
The issue this attempts to solve has been scheduled for 2.0 because the data components are expected to be heavily restructured for that release. I can't say when or if this PR would be eventually merged.

This PR also does not completely solve it as there is no option to show actions both at top and bottom? A `header` slot has also been added to VDataIterator so not sure if `prepend` slot is necessary. If you want to update the PR to fix these things then I'll try to find time to review it.

**Comment by johnleider** [comment]
With the introduction of #3833 I'm going to go ahead and close this.

**Pull request closed without merging**
