### PR TITLE
feat(theme): change default theme colors

### PR DESCRIPTION
**Pull request by johnleider**
## Motivation and Context

This has always been messed up. Default Vuetify colors should correspond to what we are using in docs, ~~just as it was in previous versions~~.

## Markup:
<details>

```vue
<template>
  <v-app :theme="dark ? 'dark' : 'light'">
    <div class="ma-4 pa-4">
      <v-btn color="primary">Test</v-btn>
      <v-btn color="primary-darken-1">Test</v-btn>
      <v-btn color="secondary">Test</v-btn>
      <v-btn color="secondary-darken-1">Test</v-btn>
    </div>

    <v-btn text="Click" @click="dark = !dark" />
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const dark = ref(false)
</script>

```
</details>

### CODE REVIEW

**Comment by MajesticPotatoe** [comment]
v2 https://github.com/vuetifyjs/vuetify/blob/2ebcb15988ed23a9a854b9b9b2fe0747a9b48d41/packages/vuetify/src/presets/default/index.ts#L51-L57
v2 docs
https://github.com/vuetifyjs/vuetify/blob/2ebcb15988ed23a9a854b9b9b2fe0747a9b48d41/packages/docs/src/vuetify/index.js#L30-L33

**Comment by KaelWD** [comment]
And v3 docs https://github.com/vuetifyjs/vuetify/blob/7906d5fb9abfedbe8d0ec049b22d8584b60c6020/packages/docs/src/plugins/vuetify.ts#L69-L73
dunno what tertiary and quarternary are doing there they don't seem to be used. 

What's with the grey secondary?

**Comment by johnleider** [comment]
> And v3 docs
> 
> https://github.com/vuetifyjs/vuetify/blob/7906d5fb9abfedbe8d0ec049b22d8584b60c6020/packages/docs/src/plugins/vuetify.ts#L69-L73
> 
> dunno what tertiary and quarternary are doing there they don't seem to be used.
> What's with the grey secondary?

Open to suggestion. Just copying what we're doing in docs.

**Comment by KaelWD** [comment]
Idk what you mean by that, tertiary and quarternary are only in docs and docs don't have a grey secondary.

**Pull request merged**
