### PR TITLE
Docs: Plain markup docs

### PR DESCRIPTION
**Pull request by ricardovanlaarhoven**
## Description
I've tried to do something for #11340 but i'm not sure this is the way vuetify wan't to go, so i only did it for 2 examples.

## Motivation and Context
#11340

## How Has This Been Tested?
just opened the docs locally and checked if they have the same result as online

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
We have a usage component now that outputs markup based on selected props:  
https://vuetifyjs.com/en/components/alerts/#usage  
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/components/examples/Usage.vue

I wonder if it could be used here too instead of duplicating everything.

**Comment by ricardovanlaarhoven** [comment]
I'm not getting it to work with the current Usage component.
1. it's dedicated into turning the came of the usage into an element (in my case `<flex></flex>`)
2. when simply creating a new option `class` this is rendered as an attribute to the first element. And this should be on a lower element
3. i think the best way would be one usage example with multiple selects (one for justify, one for align etc) and this would require a big change to the usage component

I've tried to add an extra option with classes with something like this
`attributeArray.class = Object.values(this.usageClasses).join(' ');`
but i'm not sure how to get an extra object next to options passed from the flex usage to the base usage component.
It seems a bit like magic how this component get's its data

Perhaps with a bit more information i could get it to work

**Comment by MajesticPotatoe** [comment]
>i think the best way would be one usage example with multiple selects (one for justify, one for align etc) and this would require a big change to the usage component

The usage component was originally designed for components and prop usage, not class helpers. It is however still in its infancy (not all components use it, and it lacks the ability for some things like slot/events/functions). May be something simple as giving it `type="class"` and it just outputting a div and passing with the selected classes. Let me see about playing around with that.

**Comment by ricardovanlaarhoven** [comment]
So you'll create this new component or make this adjustment?

Thenit's up to you if you merge this PR and create a new issue (For me) or if i have to change this PR once this component is done

**Comment by MajesticPotatoe** [comment]
>So you'll create this new component or make this adjustment?
Thenit's up to you if you merge this PR and create a new issue (For me) or if i have to change this PR once this component is done

For now well take this as is. Changing/adding the usage component is a PR in itself and more than just this would be updated by it.

**Review by MajesticPotatoe — APPROVED** [review]

**Pull request merged**
