### PR TITLE
docs(FileBtn): fix source file link in 2.x docs

### PR DESCRIPTION
**Pull request by kidonng**
## Description

Fix source file link in Vuetify 2.x docs. Should use `next` branch for the moment.

## Motivation and Context

Keep docs up to date.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Links will be correct after merging `next` to `master` so there's no need to change it

**Comment by kidonng** [comment]
> Links will be correct after merging `next` to `master` so there's no need to change it

I know, but currently, if we need to check the source file for new components (for example [Chip groups](https://next.vuetifyjs.com/en/components/chip-groups)), when we click the source file button we get 404 error and that's confusing.

**Comment by MajesticPotatoe** [comment]
A better approach to this would be similar to how we do it in `examples.vue`. Ill commit the change this morning.

**Comment by kidonng** [comment]
> A better approach to this would be similar to how we do it in `examples.vue`. Ill commit the change this morning.
> (which will also need to be refined)

Thanks! And please make [View on GitHub button](https://github.com/vuetifyjs/vuetify/blob/9542e70ea97c16b048c2840e479ea004bd9c1df8/packages/docs/src/components/doc/Example.vue#L52) work too 😃

**Comment by MajesticPotatoe** [comment]
included in #7755

**Pull request closed without merging**
