### PR TITLE
fix(web-types): add support for VDataTable pattern slots

### PR DESCRIPTION
**Pull request by piotrtomiak**
Add support for VDataTable `header.<name>` and `item.<name>` slots in `web-types` metadata for better Vuetify support in JetBrains IDEs..

## Description

This fix properly describes item and header slots according to the newest supported web-types format. 

## Motivation and Context

It fixes issue https://youtrack.jetbrains.com/issue/WEB-55216/False-positive-Unrecognised-slot-name-warning-for-slots-with-dot-notation-in-Vuetify-components

## How Has This Been Tested?

Tested manually in the latest WebStorm version.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Where did you find the documentation for this?

**Comment by piotrtomiak** [comment]
@KaelWD I am developing Web Types support for WebStorm. The support for patterns arrived some time ago in WebStorm (and other IDEs). The main documentation source now is the Web Types schema - https://github.com/JetBrains/web-types/blob/master/schema/web-types.json . I will be providing a comprehensive documentation at a later stage.

**Comment by KaelWD** [comment]
Ah I didn't realise you were with jetbrains, I'll take your word that this works then I guess :P

**Comment by piotrtomiak** [comment]
@KaelWD Thanks for merging this!

**Pull request merged**
