### PR TITLE
fix(VTable): fixed-header with multiple tr headers

### PR DESCRIPTION
**Pull request by websitevirtuoso**
## Description

Position sticky should apply to all elements in tbody & thead

Issue
https://github.com/vuetifyjs/vuetify/issues/17806

## Markup:

```vue
<template>
  <v-table fixed-header height="500">
    <thead>
      <tr>
        <th colspan="2">Header of col 1 and 2</th>
      </tr>
      <tr>
        <th>Col 1</th>
        <th>Col 2</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(item, index) in data" :key="index">
        <td>{{ index }} in col 1</td>
        <td>{{ index }} in col 2</td>
      </tr>
    </tbody>
  </v-table>
</template>

<script setup lang="ts">
  import { ref } from "vue";

  const data = ref(Array(100).fill(null));
</script>

```

### CODE REVIEW

**Review by johnleider — APPROVED** [review]

**Comment by websitevirtuoso** [comment]
@johnleider could you check this small PR as well please
https://github.com/vuetifyjs/vuetify/pull/17861

**Comment by Winter979** [comment]
image

**Comment by Winter979** [comment]
Related to this patch, but now text fields and other inputs arent hidden behind the header

image

**Comment by websitevirtuoso** [comment]
ok I see. need to increase z-index. I can implement extra patch

**Pull request merged**
