### PR TITLE
feat(VImg): Add prop to set crossorigin attr on v-img

### PR DESCRIPTION
**Pull request by websitevirtuoso**
## Description

https://github.com/vuetifyjs/vuetify/issues/17848

## Markup:

```vue
  <v-app>
      <v-img src="https://t3.ftcdn.net/jpg/00/92/53/56/360_F_92535664_IvFsQeHjBzfE6sD4VHdO8u5OHUSc6yHF.jpg" />
</v-app>
  <v-app>
      <v-img  crossorigin="use-credentials" src="https://t3.ftcdn.net/jpg/00/92/53/56/360_F_92535664_IvFsQeHjBzfE6sD4VHdO8u5OHUSc6yHF.jpg" />
</v-app>
```

### CODE REVIEW

**Comment by KaelWD** [comment]
> If the crossorigin attribute is specified, then a CORS request is sent (with the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) request header); but if the server does not opt into allowing cross-origin access to the image data by the origin site (by not sending any [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) response header, or by not including the site's origin in any [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) response header it does send), then the browser blocks the image from loading, and logs a CORS error to the devtools console.

Sounds like the default should be undefined.

**Comment by websitevirtuoso** [comment]
Yes we can set undefined or even empty string but this is the same

image

**Comment by websitevirtuoso** [comment]
About undefined very clear. But not clear about boolean shorthand? How it can be shorthand if it can have 2 options?
'anonymous' | 'use-credentials'

**Comment by websitevirtuoso** [comment]
@KaelWD Could you assist with this PR please? I would create more PR but want to close this one first

**Pull request merged**
