### PR TITLE
[Bug] fix(VRangeSlider): fix focus/blur events not emitting

### LINKED ISSUE #8290: [Bug Report] v-range-slider focus and blur
### Environment
**Vuetify Version:** 2.0.4
**Vue Version:** 2.6.6
**Browsers:** Firefox 68.0, Google Chrome, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
see codepen

### Expected Behavior
Blur and focus events should be triggered like it does for v-slider

### Actual Behavior
blur and focus are not triggered for v-range-slider

### Reproduction Link
<a href="https://codepen.io/Dennisd/pen/zgEXJv" target="_blank">https://codepen.io/Dennisd/pen/zgEXJv</a>

### PR DESCRIPTION
**Pull request by nekosaur**
## Description
v-range-slider was not emitting focus/blur events

## Motivation and Context
closes #8290

## How Has This Been Tested?

playground

## Markup:

<details>

```vue
<template>
  <v-container grid-list-xl>
    <v-range-slider v-model="sliderData" height="10" :min="0" :max="100" :step="1" @focus="onfocus()" @blur="onblur()" ref="range"></v-range-slider>
    <v-text-field></v-text-field>
    <v-slider v-model="sliderData2" height="10" :min="0" :max="100" :step="1" @focus="onfocus()" @blur="onblur()"></v-slider>
    {{ sliderData }} <br/>
    {{ sliderData2 }} <br/>
    isfocus: {{ isFocused }}
  </v-container>
</template>

<script>
export default {
  data: () => ({
    sliderData: [10,30],
    sliderData2: 30,
     isFocused: false,
  }),
  methods:{
    onfocus(){
      this.isFocused = true;
    },
    onblur(){
      this.isFocused = false;
    }
  }
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
Hmm. Good question. I don't think we have a very clear strategy for which events to re-emit or not.

**Comment by jacekkarczmarczyk** [comment]
It emits blur/focus pair when clicking on the second thumb or navigating between thumbs with tab, not sure if that's the way it should behave
Similar when clicking on the track, but that's sounds like a VSlider issue not related to this one
Also resolve conflicts

**Comment by nekosaur** [comment]
It's how the thumbs are implemented right now. Changing that will most likely be a bigger refactor.

**Comment by johnleider** [comment]
While I agree we need to have a larger discussion about our event emit procedures, this accurately solves the created issue.

**Pull request merged**
