### PR TITLE
vDatePicker: property 'locale-days' which turns on the day numbers localisation

### PR DESCRIPTION
**Pull request by egudova**

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Do not include dist files in the commit

**Comment by egudova** [comment]
I found your answer for #989 issue. So, this request seems to be no longer actual. I will be able to display days as unformatted numbers after 0.17 is released.

**Comment by jacekkarczmarczyk** [comment]
Just out of curiosity - by default picker uses 'en' locale to display days, so it just displays numbers same like you display `day` var in this PR. My question is in what situations you want to change locale but still display days in english locale instead of the selected one?

**Comment by egudova** [comment]
In my project I use ja locale. And days are displayed like "1日". It looks not pretty and also a little strange, so my Japanese colleagues don't like it.

**Comment by jacekkarczmarczyk** [comment]
Ok, thanks for clarification

**Pull request closed without merging**
