### PR TITLE
Add `disable-initial-sort` prop to VDataTable

### PR DESCRIPTION
**Pull request by lukeed**
* Added a new `default-sort` prop to DataTable, which defaults to `true` (no breaking behavior)
* Use new prop to help determine the initial value for `defaultPagination.sortBy`, if any.

_Closes #2366_

### CODE REVIEW

**Comment by nekosaur** [comment]
Thank you for your contribution. However I'm not sold on the prop name. I would suggest something like `disable-initial-sort`, which is more in line with vuetify's style. Thoughts?

That said, I'm also not sold on our current implementation of combining both sorting and pagination under the `pagination.sync` prop. It likely won't get an overhaul until some time post-1.0 though.

**Comment by lukeed** [comment]
Sure. I like your prop name better, I just didn't want to introduce a breaking change. 

I would really like to get (some form of) this in asap. It makes sense to me to rework the pagination at a later point.

**Comment by jacekkarczmarczyk** [comment]
If `disable-initial-sort`'s default is `false` then it's not breaking
And I'd prefer then prop (or other mechanism) that defines which column should be initially sorted (none, first - by default, other) and whether initial sorting is asc or desc

**Comment by lukeed** [comment]
Ah, right, just woke up :zzz:

Do you guys want me to implement the additional prop? Imo, it's a separate PR but I can.

**Comment by nekosaur** [comment]
`And I'd prefer then prop (or other mechanism) that defines which column should be initially sorted (none, first - by default, other) and whether initial sorting is asc or desc`

This is currently done in `pagination.sync`. Like I said we should look it over for a later release but for now it works.

**Comment by lukeed** [comment]
Hey guys, update on this?

**Comment by lukeed** [comment]
Are you waiting for me to update the docs?

**Comment by nekosaur** [comment]
You're more than welcome to do it, otherwise we'll take care of it.

**Comment by lukeed** [comment]
I'm happy to do it if it means it'll land sooner (than 1.0) 🙏 I have a prod release that's pretty much waiting only on this.

**Comment by nekosaur** [comment]
Can't guarantee that.

**Comment by lukeed** [comment]
Thanks! 🎉

**Pull request merged**
