### PR TITLE
fix(VTextField): count characters instead of codepoints

### PR DESCRIPTION
**Pull request by kasecato**
## Description
Fixed the counter to be able to count surrogate pairs.

## How Has This Been Tested?
We can try it on the console of web browser.
```js
const internalValue = '𠝏'; // should be 1
(internalValue || '').toString().length; // 2
[...(internalValue || '')].length; // 1
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by KaelWD — APPROVED** [review]

**Comment by WhatFreshHellIsThis** [comment]
This change in 2.3.15 appears to have introduced a new bug.  Previously working code before this was ok with the v-text-field being bound to an integer with the "Type" set to number, now it is throwing an exception when the page is first drawn and the control is bound to an integer: "Invalid attempt to spread non-iterable instance".

This control now expects the data to be an array so when it's an integer it throws an exception here:
```
function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread(); }

function _nonIterableSpread() { throw new TypeError("Invalid attempt to spread non-iterable instance"); }
```

Stack trace: 
```
_nonIterableSpread (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#17)
_toConsumableArray (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#15)
computedCounterValue (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#132)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
evaluate (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4578)
computedGetter (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4828)
genCounter (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#314)
genMessages (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#399)
genControl (webpack-internal:///./node_modules/vuetify/lib/components/VInput/VInput.js#140)
genControl (webpack-internal:///./node_modules/vuetify/lib/components/VTextField/VTextField.js#319)
genContent (webpack-internal:///./node_modules/vuetify/lib/components/VInput/VInput.js#135)
render (webpack-internal:///./node_modules/vuetify/lib/components/VInput/VInput.js#279)
Render (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3542)
updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4060)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
Watcher (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4462)
mountComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4067)
$mount (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#8405)
init (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3115)
createComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5968)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5915)
createChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6043)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5944)
createChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6043)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5944)
createChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6043)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5944)
patch (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6467)
_update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3939)
updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4060)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
Watcher (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4462)
mountComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4067)
$mount (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#8405)
init (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3115)
createComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5968)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5915)
createChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6043)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5944)
createChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6043)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5944)
updateChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6206)
patchVnode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6309)
patch (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6472)
_update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3942)
updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4060)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
run (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4548)
flushSchedulerQueue (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4304)
nextTick (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#1979)
flushCallbacks (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#1905)
timerFunc (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#1932)
nextTick (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#1989)
$nextTick (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3515)
directive (webpack-internal:///./node_modules/vuetify/lib/directives/ripple/index.js#306)
callHook$1 (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6670)
_update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6591)
updateDirectives (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6572)
invokeCreateHooks (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6059)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5946)
patch (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6467)
_update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3939)
updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4060)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
Watcher (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4462)
mountComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4067)
$mount (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#8405)
init (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3115)
createComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5968)
createElm (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#5915)
addVnodes (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6096)
updateChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6223)
patchVnode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6309)
updateChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6183)
patchVnode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6309)
updateChildren (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6183)
patchVnode (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6309)
patch (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#6472)
_update (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#3942)
updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4060)
get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js#4473)
```

**Comment by jacekkarczmarczyk** [comment]
`type="number"` doesn't change the model type to number, also please create a new issue with reproduction, i don't see this error with simple `<v-text-field type="number" counter />`

**Comment by WhatFreshHellIsThis** [comment]
Did you try binding it to an integer or a string? 

Clearly the component will not always be bound to an array type of object so the code forcing it to an array shown in the call stack is broken right on the face of it unless I'm missing something obvious here.  It seems to assume the control will only be bound to a string or an array like object.

This will break a lot of UI's the moment people upgrade.

**Comment by kasecato** [comment]
It will reproduce like below codes; 
```javascript
<v-text-field v-model.number="num" counter />
<v-text-field v-model.boolean="num" counter />
```
We should to use `toString()`.

**Comment by jtavio** [comment]
how to apply a min-heigth in v-text-field ... it does not allow me either with the API props or by css ...
What solution is there?

**Pull request merged**
