### PR TITLE
Grammar fixes, improvements (Croatian locale)

### PR DESCRIPTION
**Pull request by luka-mikec**
## Description
Grammar fixes, improvements

## Markup:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by luka-mikec** [comment]
@MajesticPotatoe thanks, I'm there already, just not very active (luka#1482). Sorry for the wrong branch, I thought I've read somewhere it should be dev.

**Comment by MajesticPotatoe** [comment]
@luka-mikec fixes can go do master, new stuff to dev, when we were transitioning through to 2.0, master was locked down so everything went to dev xD

**Comment by luka-mikec** [comment]
@MajesticPotatoe hmm, should I have done this? Should I just create a new PR? :D

**Comment by MajesticPotatoe** [comment]
If you want. Probably be easiest. Only way I know to do it with git is to make a new local branch from master, cherry pick your commit, reset branch -> merge -> force push.

**Pull request closed without merging**
