### PR TITLE
feat(VTextField): add persistentPlaceholder prop

### LINKED ISSUE #12839: [Feature Request] persistent-placeholder for VTextField
### Problem to solve
After version 2.4.0, the logic of placeholder behavior changed.

### Proposed solution
To save previously implemented features, need to add a parameter `persistent-placeholder`

### PR DESCRIPTION
**Pull request by Shinigami92**
## Description
resolves #12839 

## Motivation and Context
#12839 

## How Has This Been Tested?
Locally with `yarn dev`

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-text-field label="Test1"></v-text-field>
    <v-text-field label="Test2" persistent-placeholder></v-text-field>
    <v-text-field label="Test3" :persistent-placeholder="false"></v-text-field>
    <v-text-field persistent-placeholder></v-text-field>
    <v-text-field
      label="Test5"
      persistent-placeholder
      placeholder="Test5P"
    ></v-text-field>
    <v-text-field label="Test6" placeholder="Test6P"></v-text-field>
  </v-container>
</template>

<script>
export default {
  data: () => ({
    //
  })
};
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by KaelWD — CHANGES_REQUESTED** [review]
Add prop description in api-generator.

**Review by KaelWD — APPROVED** [review]

**Comment by Shinigami92** [comment]
I don't want to stress or so, just asking :slightly_smiling_face:  
When can I expect a release for this fix?
I'm running on `2.3.23` because I cannot update to the newest `2.4+` version due to this blocking UX-issue.

The [milestone 2.5](https://github.com/vuetifyjs/vuetify/milestone/52) currently tells me that the release should be `9` days ago


_I would also be happy with a alpha/beta release of 2.5_ :slightly_smiling_face:

**Comment by andreapier** [comment]
I think this should be released as a v2.4 bugfix as it broke compatibility.  
Are you considering this possibility?  
Also, `persistentPlaveholder` should be set to `true` to restore backward compatibility with previous versions.

**Comment by Nizari** [comment]
Any update on this?

**Comment by Shinigami92** [comment]
@KaelWD @johnleider 
I'm stuck now on `2.3.23` since the release of `2.4.0` :slightly_frowning_face: 
Is there an ETA when this fix will be released?



It seems that the due date is passed by 15 days and it already was moved some weeks ago

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request merged**
