### PR TITLE
fix(v-tab): anchor hash routing

### PR DESCRIPTION
**Pull request by amritk**
## Description

Just a minor fix for the href attribute on v-tab when using hash urls. Originally it prevents default, but I believe that the intention was to only prevent default when the url is exactly '#'. In the case of using hash urls for the tab, this will not work. 

## Motivation and Context

I had this issue open for a while to see why this code was here in the first place, after no feedback decided to fix it as I am going live with a feature that is using this soon.
https://github.com/vuetifyjs/vuetify/issues/4784

## How Has This Been Tested?

I have tested that it works visually in my project, not quite sure how to write a test for this one.

## Markup:

<details>

```vue
<template lang="pug">
.main
    v-tabs.shadow(v-model="activeTab" slider-color="primary" fixed-tabs)
        v-tab(v-for="tab in tabs" :key="tab.name" :href="`#${tab.name}`")
            | {{ $t(tab.title) }}
        v-tab-item(id="teams")
            | These are the teams
        v-tab-item(id="players")
            | These are the players
        v-tab-item(id="matches")
            | These are the matches
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import * as VTabs from 'vuetify/es5/components/VTabs'

@Component({
    components: {
        ...VTabs
    }
})
export default class TeamFinderList extends Vue {
    activeTab: string = null
    tabs = [
        {
            name: 'teams',
            title: 'Teams'
        },
        {
            name: 'players',
            title: 'Players'
        },
        {
            name: 'matches',
            title: 'Matches'
        }
    ]

    created () {
        // Load the correct tab in the beinning
        this.activeTab = this.$route.hash.substr(1)
    }
}
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by amritk** [comment]
sounds good

**Comment by egeersoz** [comment]
Is this still slated for 1.3.0? A critical part of my app requires switching tabs using the URL.

**Comment by KaelWD** [comment]
This doesn't fix anything: you still can't link directly to a tab by its hash, and clicking a tab scrolls the page to the top of the tab item (https://vuetifyjs.com/en/components/alerts#props)

**Comment by amritk** [comment]
@kaelwd I had a working example. Let me try out the fix tomorrow and I'll see if it still works.

**Comment by amritk** [comment]
@KaelWD This fix was to set the hash fragment in the url, which it correctly does now. To set it initially, on mounted you can do something like this:
```
this.activeTab = this.$route.hash.substr(1)
```
Not sure if we want to include this as part of the tabs component.

**Comment by amritk** [comment]
@KaelWD actually that is probably why this code was in here in the first place, to prevent the scrolling in the docs. Maybe we should keep the routing but prevent the scroll.

**Comment by amritk** [comment]
I just realized if you use router-link instead of an achor it works much better, including linking directly to the tab
```
<template lang="pug">
    v-tabs(v-model="activeTab" slider-color="primary" fixed-tabs)
        v-tab(v-for="tab in tabs" :key="tab" :to="`#${tab}`")
            | {{ tab }}
        v-tab-item(:id="tab" v-for="tab in tabs" :key="tab")
            | This is the {{ tab }} feed
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import * as VTabs from 'vuetify/es5/components/VTabs'

@Component({
    components: {
        ...VTabs
    }
})
export default class Amrit extends Vue {
    activeTab: string = null
    tabs = ['teams', 'players', 'matches']
}
</script>
```

**Comment by KaelWD** [comment]
Correct. You could've also set the hash yourself with a watcher on `activeTab`, seeing as you're already doing `this.activeTab = this.$route.hash.substr(1)` in userland.

**Comment by amritk** [comment]
Yes that is what I was doing while I was waiting for the pull request. But the tabs component should be handling that.

**Pull request merged**
