### PR TITLE
fix(VField): Applied text-align to input element

### LINKED ISSUE #17856: [Bug Report][3.3.9] `reverse` is not working in `v-text-field` in LTR direction
### Environment
**Vuetify Version:** 3.3.9
**Vue Version:** 3.3.4
**Browsers:** Firefox 116.0
**OS:** Windows 10

### Steps to reproduce
No changes when add `reverse` into `v-text-field`

### Expected Behavior
input text in `v-text-field` will start from right in LTR direction.

### Actual Behavior
input text in `v-text-field` will start from left in LTR direction.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/?preview=false#eNrFk01PAjEQhv/Kpme6VTAxEjR68eQ/cD0UOkCxH5t2dpUQ/rvTXXDJIgl40NNm3+n0feajrxv2VJZ5XQEbswmCLY1EeChclk1qPvMOpXYQsrmptGrkJoDwiTKAbIUsc9LCfcG0Kyvkt/y6YPtILYOWDik418aA6iJGTsGQ/pK+nSwr9HwR/MdesF6B4bU0VbJwHrMANYTY3fUwER0SQf4L5g7qZ+q49JVR2RQuY+dzDUb1SZ51iNjU0uEstQKugKZlIh1JdF3wgg62jn/CcbonvWYewxEYSd/bScpEHOwuGzCj3XvMV9E72utNyijYLMaCjbPX9taCLRHLOBZiphydJDRdh9wBClda8UhPAvV8LZxeLNGsH0f5KL/jVkaEkA+vhiN+dcuH10LpiGJ3mFNrYt74JJO3wm2JRdvSB6TUsgfUBhqoRkka3ZT+z6AToXKoLbXb24bupmU5kHOIlk9pSSMxr8hocGCTgM+0+mUjyP3IVRAKzZYHcAoChHOL7aUdFtwLHRWd3LdpFNsBa9JoJieKYG9f2OKk3w==)

圖片

### Other comments
Releated to https://github.com/vuetifyjs/vuetify/issues/15432#ref-commit-1e4b2f7 but not fix `v-text-field`

### PR DESCRIPTION
**Pull request by prashantsinghb**
fixes #17856

## Description

Applied fieldClass to input element
## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-locale-provider rtl>
        <v-text-field v-model="msg" label="test" />
        <v-text-field v-model="msg" reverse label="test" />
        <v-textarea v-model="msg" label="test" />
        <v-textarea v-model="msg" reverse label="test" />
        <v-select
          label="Select"
          v-model="msg"
          :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
        ></v-select>
        <v-select
          label="Select"
          v-model="msg"
          :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
          reverse
        ></v-select>
      </v-locale-provider>
      <v-locale-provider ltr>
        <v-text-field v-model="msg" label="test" />
        <v-text-field v-model="msg" reverse label="test" />
        <v-textarea v-model="msg" label="test" />
        <v-textarea v-model="msg" reverse label="test" />
        <v-select
          v-model="msg"
          label="Select"
          :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
        ></v-select>
        <v-select
          v-model="msg"
          label="Select"
          :items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
          reverse
        ></v-select>
      </v-locale-provider>
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const msg = ref('California')
</script>


```

### CODE REVIEW

**Comment by johnleider** [comment]
This causes visual issues 
image

**Review by yuwu9145 — COMMENTED** [review]
In v2,

- labels are right aligned as well: [demo](https://codepen.io/yuchaosydney/pen/Jjexxrx?editors=101)
- Selections in select components are right aligned: [demo ](https://codepen.io/yuchaosydney/pen/qBQggjg?editors=1010)

**Comment by prashantsinghb** [comment]
@yuwu9145 - Have updated the fix as per you observation.
Please review.

**Review by johnleider — APPROVED** [review]

**Comment by johnleider** [comment]
This passed tests locally:
image

**Comment by yuwu9145** [comment]
inner icon should be left aligned: [v3 RTL](https://play.vuetifyjs.com/#eNqlUk1PGzEQ/StTX7aVsmsheooCokJqe28lDtkczO4kGPylsbOAovx3xt4ElnBB4jZ+b/zezLOXO/ErhGbYopiLRUIbjEp42TqAxVCrEEpZDp13SWmHdIAKaHynDNaB/KB7JKBkXunSENFgl94gAKNu0Vy04t/IiCk31zxCZHJZXSuj156cVtUMqmtvPKne5/o3l7ov8B/0tBk7/uOTirm4efZWu021mkpfLuRxlrfxGTqZ/7gtM+/XzciYxkJOUuJj7EiHBBHTdgxL2+ApwQ4I17CHNXkLFQdc5XYA1o0JbNzARe74Xv1FYzzceDL9t+pHNhglWUzMxKhWWxWa++gdv9Iuq7QHIrZiDgXJGLvkcyvuUgpxLmXXO77Wo9EDNQ6TdMHKK26TtHVJW6x7b6/Om/Pmp+x1TFO4wWjrW/KPEYlFWjGb2CS9fv6E1aGzOJydjRYHrOZ/ELPHB23JhgNSTej4SZA+u9LJtelaJ9SH1bL7vnV7Dtxo9xBPsu5iyXl5HPJrOxe1LLXKjvuZKIOy9XhDrF4A9uIsNA==)

Probably it should be handled in an new issue

**Comment by prashantsinghb** [comment]
@yuwu9145 - Could I look into the issue` But inner icon should be left aligned: `[v3 RTL](https://play.vuetifyjs.com/#eNqlUk1PGzEQ/StTX7aVsmsheooCokJqe28lDtkczO4kGPylsbOAovx3xt4ElnBB4jZ+b/zezLOXO/ErhGbYopiLRUIbjEp42TqAxVCrEEpZDp13SWmHdIAKaHynDNaB/KB7JKBkXunSENFgl94gAKNu0Vy04t/IiCk31zxCZHJZXSuj156cVtUMqmtvPKne5/o3l7ov8B/0tBk7/uOTirm4efZWu021mkpfLuRxlrfxGTqZ/7gtM+/XzciYxkJOUuJj7EiHBBHTdgxL2+ApwQ4I17CHNXkLFQdc5XYA1o0JbNzARe74Xv1FYzzceDL9t+pHNhglWUzMxKhWWxWa++gdv9Iuq7QHIrZiDgXJGLvkcyvuUgpxLmXXO77Wo9EDNQ6TdMHKK26TtHVJW6x7b6/Om/Pmp+x1TFO4wWjrW/KPEYlFWjGb2CS9fv6E1aGzOJydjRYHrOZ/ELPHB23JhgNSTej4SZA+u9LJtelaJ9SH1bL7vnV7Dtxo9xBPsu5iyXl5HPJrOxe1LLXKjvuZKIOy9XhDrF4A9uIsNA==).
Or you will handle this in #17960 ?

**Comment by yuwu9145** [comment]
> Could I look into the issueBut inner icon should be left aligned:[v3 RTL](https://play.vuetifyjs.com/#eNqlUk1PGzEQ/StTX7aVsmsheooCokJqe28lDtkczO4kGPylsbOAovx3xt4ElnBB4jZ+b/zezLOXO/ErhGbYopiLRUIbjEp42TqAxVCrEEpZDp13SWmHdIAKaHynDNaB/KB7JKBkXunSENFgl94gAKNu0Vy04t/IiCk31zxCZHJZXSuj156cVtUMqmtvPKne5/o3l7ov8B/0tBk7/uOTirm4efZWu021mkpfLuRxlrfxGTqZ/7gtM+/XzciYxkJOUuJj7EiHBBHTdgxL2+ApwQ4I17CHNXkLFQdc5XYA1o0JbNzARe74Xv1FYzzceDL9t+pHNhglWUzMxKhWWxWa++gdv9Iuq7QHIrZiDgXJGLvkcyvuUgpxLmXXO77Wo9EDNQ6TdMHKK26TtHVJW6x7b6/Om/Pmp+x1TFO4wWjrW/KPEYlFWjGb2CS9fv6E1aGzOJydjRYHrOZ/ELPHB23JhgNSTej4SZA+u9LJtelaJ9SH1bL7vnV7Dtxo9xBPsu5iyXl5HPJrOxe1LLXKjvuZKIOy9XhDrF4A9uIsNA==).

@prashantsinghb feel free to give it a crack. 

#17960 is just an irrelevant improvement

**Pull request merged**
