### PR TITLE
support font awesome 5 icons

### PR DESCRIPTION
**Pull request by BePsvPT**
Font Awesome 5 introduces new type of icons, like regular, light, brands and logos. When using these icons, each prefix name is different. For example, when using `facebook` icon, the class name should be `fab fa-facebook` instead of `fa fa-facebook`.

Currently, when using font awesome 5 icons and the icon is not solid type(solid is default type, prefix with `fa`), the icon class name is incorrect. This pull request add the function that support font awesome 5 icons.

Icon class name comparison:

| icon | before | after |
|-----|---------|---------|
| fa-check | fa icon fa-check| fa icon fa-check |
| far-check | far icon far-check | far icon fa-check |
| fab-facebook | fab icon fab-facebook | fab icon fa-facebook |

### CODE REVIEW

**Comment by Phlow2001** [comment]
It would be preferable to keep the icon name unmodified.
I would prefer changing it "fab fa-facebook" and have the code check for "fab " and "far " before assuming '-' is important.

**Comment by johnleider** [comment]
I agree with @Phlow2001 on this one. Thoughts @BePsvPT ?

**Comment by BePsvPT** [comment]
In font awesome 5, use `<v-icon>fab fa-facebook</v-icon>` instead of `<v-icon>fab-facebook</v-icon>` and in background, we just do nothing and return it when find `fab` or `far`. Am I understanding correctly?

**Comment by dwyer14** [comment]
+1, this would be a great addition to the 1.0 release!

**Comment by BePsvPT** [comment]
In latest font awesome 5, it seems `fa` prefix has been deprecated.

https://fontawesome.com/how-to-use/svg-with-js#styles-and-prefixes

**Comment by BePsvPT** [comment]
@Phlow2001 I have changed the code to check iconType instead of modified the icon name.

**Comment by nekosaur** [comment]
@BePsvPT Please fix the linting error and we'll merge this

**Comment by BePsvPT** [comment]
@nekosaur How do I fix this error?

/home/travis/build/vuetifyjs/vuetify/src/components/VIcon/VIcon.js
error  Method 'render' has too many statements (25). Maximum allowed is 24  max-statements

**Comment by nekosaur** [comment]
render function is too long. max number of lines for functions is 24. it is currently 25

**Comment by johnleider** [comment]
Any update on this?

**Pull request merged**
