### PR TITLE
feat(VSparkline): add fill property

### PR DESCRIPTION
**Pull request by dsseng**
## Description
Add fill property.
default

## Motivation and Context
Add new style of `VSparkline`

## How Has This Been Tested?
Markup

## Markup:
<details>

```vue
<template>
  <boilerplate>
    <v-sheet max-width="900">
      <v-sparkline
        type="bar"
        :value="value"
        :bar-width="5"
        auto-draw
        :gradient="['#ffbe88', '#ff93df']"
        :smooth="2"
      ></v-sparkline>
    </v-sheet>
    <v-sheet max-width="900">
      <v-sparkline
        type="bar"
        :value="value"
        :bar-width="5"
        auto-draw
        :gradient="['#ffbe88', '#ff93df']"
        :smooth="2"
        fill
      ></v-sparkline>
    </v-sheet>
  </boilerplate>
</template>

<script>
  export default {
    data: () => ({
      value: [1, 2, 1, 1, 2, 3, 1, 0, 1, 2],
      //value: [1.1, 1.5, 1, 2, 5, 9, 5, 10, 3, 5, 8, 12, 1, 8, 2, 9, 10, 2, 9, 4, 5, 6, 7, 3, 2, 3, 5]
    })
  }
</script>
```
</details>

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:
- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by MajesticPotatoe** [comment]
Would suggest adding a doc example

**Comment by jacekkarczmarczyk** [comment]
And unit tests as well

**Comment by sh7dm** [comment]
@MajesticPotatoe @jacekkarczmarczyk OK!

**Comment by sh7dm** [comment]
@jacekkarczmarczyk but there isn't a `VSparkline` spec

**Pull request closed without merging**
