### PR TITLE
feat(VAppBar): implement scrolling techniques

### LINKED ISSUE #12707: [Task] v-app-bar
# Overview

- Related Tasks: n/a

A conversion should not start until *all* assigned issues with the milestone v2.2.x are resolved and in the `next` branch. Reference our [Coding Guidelines](https://github.com/vuetifyjs/vuetify/wiki/coding-guidelines) for information regarding the team's practices or reach out to us on [Discord](https://community.vuetifyjs.com).

### PR DESCRIPTION
**Pull request by johnleider**
## Motivation and Context

resolves #12707

## Markup:
<details>

```vue
<template>
  <v-app-bar
    :image="props['fade-image'] ? 'https://picsum.photos/1920/1080?random' : undefined"
    v-bind="_props"
    extended
  >
    <v-app-bar-nav-icon />

    <v-app-bar-title>Title</v-app-bar-title>

    <v-spacer />

    <v-app-bar-nav-icon icon="mdi-vuetify" />
  </v-app-bar>

  <v-main style="height: 400vh;">
    <v-container>
      <v-checkbox-btn v-model="props['hide']" label="hide on scroll" />
      <v-checkbox-btn v-model="props['inverted']" label="inverted scroll" />
      <v-checkbox-btn v-model="props['elevate']" label="elevate on scroll" />
      <v-checkbox-btn v-model="props['collapse']" label="collapse on scroll" />
      <v-checkbox-btn v-model="props['fade-image']" label="fade img on scroll" />

      <v-text-field v-model="props['scroll-threshold']" label="threshold" />

      <div class="my-16 py-16" />

      <v-card title="Scroll Jolt Test" />
    </v-container>
  </v-main>
</template>

<script setup>
  import { computed, ref } from 'vue'

  const props = ref({
    hide: false,
    inverted: false,
    collapse: false,
    'fade-image': false,
    elevate: undefined,
  })

  const _props = computed(() => {
    return {
      scrollBehavior: Object.keys(props.value).reduce((acc, key) => {
        if (props.value[key]) acc.push(key)
        return acc
      }, []).join(' '),
    }
  })
</script>

```
</details>

### CODE REVIEW

**Comment by ferferga** [comment]
@johnleider Could #14484 be taken into consideration for this?

**Comment by KaelWD** [comment]
Also #16108 but that's a lot more limited in scope

**Comment by nekosaur** [comment]
This seems like a good place to replace multiple props with a single one, like we've done in other places? Most of these are exclusionary aren't they?

**Comment by johnleider** [comment]
Due to time constraints I'm going to have to bump this to v3.2.

**Review by dyc3 — COMMENTED** [review]
The migration guide and examples in the docs need to be updated.

In the migration guide, make sure to mention that the `inverted` scroll behavior no longer implies `hide` scroll behavior.

**Comment by dyc3** [comment]
I've implemented some e2e tests in #16401. That PR targets this branch, so merging it will add it to this PR.

**Pull request merged**
