### PR TITLE
fix(locale) correct translations for Chinese Simplified

### PR DESCRIPTION
**Pull request by myleslee**
## Description

fix translation
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
Please contribute any language updates through our crowdin project (https://crowdin.com/project/vuetify). When adding new translations on crowdin, use the `next` folder.

Thank you!

**Comment by myleslee** [comment]
@nekosaur I can't find the corresponding folder or file to add these updates to. It seems to me that the crowdin project handles Vuetify site's translation, not Vuetify's internal message translation.

**Comment by MajesticPotatoe** [comment]
@myleslee 
> Please contribute any language updates through our crowdin project (https://crowdin.com/project/vuetify). When adding new translations on crowdin, use the `next` folder.
> 
> Thank you!

<https://crowdin.com/project/vuetify/zh-CN#/next>

**Comment by myleslee** [comment]
@MajesticPotatoe still I can't find `packages/vuetify/src/locale/zh-Hans.ts` inside the `https://crowdin.com/project/vuetify/zh-CN#/next` you indicated. Did I miss anything?

**Pull request closed without merging**
