### PR TITLE
fix(vtabs): fix blank space in slider on mobile devices

### LINKED ISSUE #6932: [Bug Report] v-tabs bar missing offset on medium(?) viewports to indicate that scrolling is possible
### Versions and Environment
**Vuetify:** 1.5.9
**Vue:** 2.6.10
**Browsers:** Firefox 66.0
**OS:** Windows 7

### Steps to reproduce
1) Create a v-tabs component with more tabs than fit into it  
2) Lower viewport size to <=1263px, e.g. by resizing the window or rendering within an iframe

### Expected Behavior
Offset is shown on the left-hand size

### Actual Behavior
Offset is not displayed

### Reproduction Link
<a href="https://codepen.io/anon/pen/jRrbYy" target="_blank">https://codepen.io/anon/pen/jRrbYy</a>

### Other comments
Also happens in 2.0.0-alpha.12

[Google Material specs](https://material.io/design/components/tabs.html#scrollable-tabs) (ctrl+f -> "Placement"->scroll down) say that "Do: On mobile and desktop, offset the first tab on the left to signal that tabs are scrollable." This is not the case on devices with a medium(?) viewport.  
On larger viewports this is kinda supported, since the left arrow is not displayed while there are no items on the left, but smaller viewports don't show arrows unless the "show-arrows"-prop is provided.

Kinda off-topic: On Desktop the arrows vanish too, which makes scrolling hard on smaller viewports (e.g. when the page is rendered within an iframe on a small resolution, or when the browser window is not maximized). The only way to scroll then is to repeatedly click the last item. This was first discussed in #1789, which was closed in favor of #2530, resulting in the PR #2838, which supposedly made arrows show up on all viewport sizes - was this removed again or is the arrows vanishing on viewports with less than 1264px width a bug and should be covered in a new issue?

### PR DESCRIPTION
**Pull request by bhaskar-nair2**
Added display classes to hide the arrow placeholder which created a blank space in the VTabs slider
on mobile devices.

fix #6932

## How Has This Been Tested?

visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <!--  -->
    <v-tabs
      color="primary"
      slider-color="primary"
      dark
    >
      <v-tab
        v-for="item in items"
        :key="item"
      >
        {{ item }}
      </v-tab>
    </v-tabs>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      //
      items: Array.from({ length: 10 }, (v, x) => x),
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by bhaskar-nair2** [comment]
Do I need to make any changes before this can get accepted?

**Comment by johnleider** [comment]
This is on my list but currently lower priority.

**Review by MajesticPotatoe — CHANGES_REQUESTED** [review]
This simply hides the space all together which conflicts w/ MD spec:
`On mobile and desktop, offset the first tab on the left to signal that tabs are scrollable`

also causes some bad UX when scrolling forward and then back with `show-arrows` prop

**Comment by johnleider** [comment]
This Pull Request is being closed due to a conflicting change to MD spec.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
