### PR TITLE
better handling for menu displaying in relative context

### PR DESCRIPTION
**Pull request by vanhoavn**
Current `menu` content is attached to root container which will introduce problems for layouts that require absolute positioning within the root container (context inside context), we can resolve it by using `detachable-root` prop to `menu` component which finds the closest `[data-app]` parent.

Example Playground.vue:

```
<template>
    <v-app>
        <div style="position: fixed; top: 200px; left: 200px; width: 400px; max-height: 300px; overflow: auto" data-popup-context>
            <div>
                <main>
                    <v-card class="grey lighten-4 elevation-0">
                        <v-card-text>
                            <v-container fluid>
                                <v-layout row wrap>
                                    <v-flex xs6>
                                        <v-subheader>Standard</v-subheader>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-select
                                            v-bind:items="items"
                                            v-model="e1"
                                            label="Select"
                                            single-line
                                            bottom
                                        ></v-select>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-subheader>Standard with focus</v-subheader>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-select
                                            v-bind:items="items"
                                            v-model="e2"
                                            label="Select"
                                            class="input-group--focused"
                                            item-value="text"
                                        ></v-select>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-subheader>Error</v-subheader>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-select
                                            label="Select"
                                            v-bind:items="items"
                                            v-model="e3"
                                            v-bind:rules="[() => e3 && e3.text && e3.text.length > 0 || 'Please select an option']"
                                            item-value="text"
                                        ></v-select>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-subheader>Disabled</v-subheader>
                                    </v-flex>
                                    <v-flex xs6>
                                        <v-select
                                            label="Select"
                                            v-bind:items="items"
                                            v-model="e4"
                                            disabled
                                        ></v-select>
                                    </v-flex>
                                </v-layout>
                            </v-container>
                        </v-card-text>
                    </v-card>
                </main>
            </div>
        </div>
        <div v-for="i in 100">Content</div>
    </v-app>
</template>

<script>
    export default {
        data () {
            return {
                e1: null,
                e2: null,
                e3: null,
                e4: null,
                items: [
                    { text: 'State 1' },
                    { text: 'State 2' },
                    { text: 'State 3' },
                    { text: 'State 4' },
                    { text: 'State 5' },
                    { text: 'State 6' },
                    { text: 'State 7' }
                ],
                states: [
                    'Alabama','Alaska','American Samoa','Arizona',
                    'Arkansas','California','Colorado','Connecticut',
                    'Delaware','District of Columbia','Federated States of Micronesia',
                    'Florida','Georgia','Guam','Hawaii','Idaho',
                    'Illinois','Indiana','Iowa','Kansas','Kentucky',
                    'Louisiana','Maine','Marshall Islands','Maryland',
                    'Massachusetts','Michigan','Minnesota','Mississippi',
                    'Missouri','Montana','Nebraska','Nevada',
                    'New Hampshire','New Jersey','New Mexico','New York',
                    'North Carolina','North Dakota','Northern Mariana Islands','Ohio',
                    'Oklahoma','Oregon','Palau','Pennsylvania','Puerto Rico',
                    'Rhode Island','South Carolina','South Dakota','Tennessee',
                    'Texas','Utah','Vermont','Virgin Island','Virginia',
                    'Washington','West Virginia','Wisconsin','Wyoming'
                ]
            }
        }
    }
</script>
```

### CODE REVIEW

**Comment by nekosaur** [comment]
Please show example markup of how this would be used as well

**Comment by vanhoavn** [comment]
It's up to the implementation of `detachableRoot ` function, current implement just need the closest root has `data-app` attribute.

**Comment by vanhoavn** [comment]
The markup should like
```
<div data-popup-context>
... child
</div>
```
So all modals of that div[data-popup-context] will be inserted into that context only.

**Comment by vanhoavn** [comment]
@johnleider what's your thinking?
All of the failed tests on CI are unrelated.

**Comment by cazzerson** [comment]
I just wanted to say that I used this fork in a project where we were having menu positioning issues when embedding a Vuetify app in a branded HTML template and it fixed our problem.

**Comment by cazzerson** [comment]
Actually...seems to break my tab bar (it doesn't render at all).

**Comment by vanhoavn** [comment]
hmm tabbar is unrelated to my modifications, maybe the reason is from base's dev since i've just synced with base's dev.

**Comment by cazzerson** [comment]
@vanhoavn Thanks! Here is an example using a similar case from the docs: https://codepen.io/cazzerson/pen/oeoYeO?editors=1111

**Comment by vanhoavn** [comment]
@nekosaur why you remove the activator slot from render function? https://github.com/vuetifyjs/vuetify/commit/db8729f63f1a340138f03a23b322b00b39a08baa#diff-210e47de14c17f134b7d616d8619fd42L198

**Comment by johnleider** [comment]
Because it's no longer needed.

**Comment by vanhoavn** [comment]
@johnleider thank you
so @cazzerson  you should remove `slot="activators"`:
`
- <v-tabs-bar slot="activators" class="cyan">
+ <v-tabs-bar class="cyan">
`
since slot-ed elements wont be included into parent's render tree if not used.

**Comment by nekosaur** [comment]
@cazzerson I would advise against using dev at this time. There's a number of breaking changes (including v-tabs).

**Comment by cazzerson** [comment]
@nekosaur That did it--thanks!

**Comment by cazzerson** [comment]
@nekosaur OK, thank you. We badly need the changes in this PR, but will move away from dev as soon as we can. For now, we seem to have mostly adapted and are using a local build.

**Comment by johnleider** [comment]
Now that we have released 0.15, can you please update this PR, thank you!

**Comment by vanhoavn** [comment]
‎OK i'll do soon.
‎
‎
OK i'll do it soon :) 

‎

**Comment by vanhoavn** [comment]
I'm sorry i've been away for business, i'll fix tomm.

**Comment by vanhoavn** [comment]
hi @johnleider i updated.

**Comment by johnleider** [comment]
Please only add necessary files to the PR. There are tons of files that are not needed in it.

**Comment by vanhoavn** [comment]
What's the not necessary files? Only 5 files changed in this PR.

**Comment by johnleider** [comment]
Disregard, must have had cache or something, it looks correct now.

**Comment by johnleider** [comment]
I'm spending some time with this and at first glance, I'm not a fan of the implementation. I do not have a better solution at the moment, but the approach of this is not in line with how I would want to fix it. Not to diminish your hard work, thank you for your contribution.

**Comment by vanhoavn** [comment]
Can you please tell me what's your dislike in this solution? Get parent approach is inspired from vue's provide/inject implementation. I can provide other methods but first need to understand your thinking.

Đã gửi từ iPhone của tôi

Ngày 12 thg 9, 2017, vào lúc 00:37, John Leider <notifications@github.com> viết:

**Comment by johnleider** [comment]
For sure, it may not be until this weekend, but I'll provide you with a more detailed explanation. Thank you for your patience.

**Comment by KaelWD** [comment]
@johnleider Any update on this?

**Comment by johnleider** [comment]
This is something we will visit in the future, possibly for v1.1 or v1.2. `v-select` has changed drastically from the time this was implemented.

**Pull request closed without merging**
