### PR TITLE
fix(VTab): fix possibility to focus disabled tab by keyboard

### PR DESCRIPTION
**Pull request by lentyaevpk**
## Description

Disabled tabs still had tabindex attribute.

## Motivation and Context

This change improves tabs accessibility.

## How Has This Been Tested?

Visually.

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-tabs>
      <v-tab>Item One</v-tab>
      <v-tab :disabled="isDisabled">Item Two</v-tab>
      <v-tab>Item Three</v-tab>
    </v-tabs>
    <v-btn @click="isDisabled = !isDisabled">Click</v-btn>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      isDisabled: false,
    }),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Probably better fix would be to add `tabindex="-1"` to disabled tab

**Comment by LentyaevPK** [comment]
> Probably better fix would be to add `tabindex="-1"` to disabled tab

MDN says: A negative value (usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation, but could be focused with JavaScript or visually by clicking with the mouse. It's mostly useful to create accessible widgets with JavaScript.
I guess disabling means that we don't want this element to be focused at all.

**Comment by jacekkarczmarczyk** [comment]
ah sorry, i misread your PR

**Review by KaelWD — APPROVED** [review]

**Review by KaelWD — CHANGES_REQUESTED** [review]
This still doesn't prevent focus if an `<a>` tag is rendered (`href` or `to` props), or if there's an element with `pointer-events: auto` inside it (#13728)

**Comment by LentyaevPK** [comment]
> This still doesn't prevent focus if an `<a>` tag is rendered (`href` or `to` props), or if there's an element with `pointer-events: auto` inside it (#13728)

But this is deafult HTML behaviour. I mean, i don't think it's a Vuetify's bug.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
