### PR TITLE
fix(VEditDialog): return returnValue on save

### LINKED ISSUE #11736: [Bug Report] v-edit-dialog returns search-input string on save instead of value when using v-autocomplete
### Environment
**Vuetify Version:** 2.3.2
**Vue Version:** 2.6.11
**Browsers:** Chrome 83.0.4103.116
**OS:** Windows 10

### Steps to reproduce
1. Click on the name in the table column to open the v-edit-dialog
2. Select 'Eve' in the v-autocomplete and hit enter to save

### Expected Behavior
`:return-value.sync="item.person_id"` should be syncing the new `item.person_id` on save

### Actual Behavior
Instead, on save, `:return-value.sync` is syncing the search-input string from the v-autocomplete.

### Reproduction Link
<a href="https://codepen.io/z3nz/pen/oNbewLz" target="_blank">https://codepen.io/z3nz/pen/oNbewLz</a>

### Other comments
Cancel works correctly. If you change the name to 'Eve' in the v-autocomplete and then hit 'Esc' to cancel your change, `:return-value.sync` returns the `person_id` that was previously selected. Here are some screenshots showing the events and their different return values for each.

cancel
cancel

save
save

### PR DESCRIPTION
**Pull request by z3nz**
Fixes a bug where save returns the input value instead of the returnValue. This also updates the
test to ensure cancel and save are working as intended.

fix #11736

## Description

This fix allows more than just input fields to be used in the `v-slot:input`. Before, on save, the VEditDialog would only return the value of the input field in the slot. So, if you used an autocomplete it would not return the value of the autocomplete, but instead, it would return the value of the search-input.  This change will allow autocompletes, selects, etc to be used inside the slot and will now return the correct value that is specified in the `returnValue` prop.

Fixes #11736 

## Motivation and Context

This allows the VEditDialog to use more than just text input fields when inside a VDataTable, which can have a variety of value types. See bug for the full description of the issue that is being fixed.

## How Has This Been Tested?

I have updated the unit test to ensure that save is returning the updated value and cancel is returning the original value.

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table
      :headers="headers"
      :items="items"
    >
      <template v-slot:item.name="{ item }">
        <v-edit-dialog
          :return-value.sync="item.person_id"
        >
          {{ getPersonName(item.person_id) }}
          <template v-slot:input>
            <v-autocomplete
              v-model="item.person_id"
              label="Name"
              :items="people"
            />
          </template>
        </v-edit-dialog>
      </template>
    </v-data-table>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      headers: [{
        text: 'Name',
        value: 'name',
      }],
      items: [{
        person_id: 1,
      }],
      people: [
        {
          value: 1,
          text: 'Adam',
        },
        {
          value: 2,
          text: 'Eve',
        },
      ],
    }),
    methods: {
      getPersonName (id) {
        return this.people.find(p => p.value === id).text
      },
    },
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
Someone trying to resuscitate `v-edit-dialog` before it's inevitable death is fitting.

**Comment by z3nz** [comment]
If it needs more than a quick fix, I'd be happy to refactor/overhaul as needed.

**Comment by johnleider** [comment]
Probably but it would be a v3 thing if you're interested.

**Comment by z3nz** [comment]
I'd be happy to work on it for v3. Can we still potentially use this fix for v2 in the meantime?

**Pull request merged**
