### PR TITLE
fix(VListItem): Align content start when multiple lines

### LINKED ISSUE #15764: [Bug Report][3.0.0-beta.10] `v-list` prepend-avatar alignment issue in `density="compact"`
### Environment
**Vuetify Version:** 3.0.0-beta.10
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
Please try to use a list with `prepend-avatar` and `density compact.`

### Expected Behavior
The avatar should be aligned with the title. 

### Actual Behavior
It is not aligned. See Img

### Reproduction Link
<a href="https://codepen.io/Alokdev/pen/KKRzaNg?editors=101" target="_blank">https://codepen.io/Alokdev/pen/KKRzaNg?editors=101</a>

image

### LINKED ISSUE #16175: [Bug Report][3.0.2] Using two or three lines in a compact list item causes the prepended icon to be too far up
### Environment
**Vuetify Version:** 3.0.2
**Vue Version:** 3.2.45
**Browsers:** Chrome 107.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
See the reproduction example. Note that this is using `density="compact"` and `lines="three"`.

### Expected Behavior
The prepended icon should be centered or at least within the vertical range of the list item's content.

### Actual Behavior
The prepended icon is floating left and above of the title.

### Reproduction Link
[https://codepen.io/douira/pen/MWXXvep](https://codepen.io/douira/pen/MWXXvep)

### Other comments
This used to work with Vuetify 2, but I'm not sure if it has previously worked on Vuetify 3 or not.

### PR DESCRIPTION
**Pull request by sMesle**
## Description

Add `align-self: start` to list content when there are two or three line. 

Resolves #15764 

## Motivation and Context

Allow list content to be aligned with the prepend or append content.
If you lack some lines, it prevent prepend or append being too far up

## How Has This Been Tested?

Playground

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-card
      class="mx-auto"
      max-width="500"
    >
      <v-list density="compact">
        <v-list-subheader>REPORTS</v-list-subheader>

        <v-list-item
          v-for="(item, i) in items"
          :key="i"
          :value="item"
          active-color="primary"
          :prepend-icon="item.icon"
          :title="item.text"
          :subtitle="item.text.repeat(10)"
          lines="three"
        />
      </v-list>
    </v-card>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      items: [
        { text: 'Real-Time', icon: 'mdi-clock' },
        { text: 'Audience', icon: 'mdi-account' },
        { text: 'Conversions', icon: 'mdi-flag' },
      ],
    }),
  }
</script>

```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [X] The PR title is no longer than 64 characters.
- [X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [X] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Review by johnleider — CHANGES_REQUESTED** [review]
This breaks avatars:

```html
<template>
  <v-container>
    <v-card
      class="mx-auto"
      max-width="500"
    >
      <v-list density="compact">
        <v-list-subheader>REPORTS</v-list-subheader>

        <v-list-item
          v-for="(item, i) in items"
          :key="i"
          :value="item"
          active-color="primary"
          :prepend-icon="item.icon || undefined"
          :prepend-avatar="item.avatar || undefined"
          :title="item.text"
          :subtitle="item.text.repeat(10)"
          lines="three"
        />

      </v-list>
    </v-card>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      items: [
        { text: 'Real-Time', avatar: 'https://vuetifyjs.b-cdn.net/images/john-smirk.png' },
        { text: 'Audience', icon: 'mdi-account' },
        { text: 'Conversions', icon: 'mdi-flag' },
      ],
    }),
  }
</script>
```

**Comment by sMesle** [comment]
With your markup: 
image

What does it really break ? The margin consistency between avatar and list item ? 
For me the alignment of the list item content and avatar should be correct

**Comment by KaelWD** [comment]
That looks like a separate bug and already exists on next, the icons should have a reduced margin with density or the avatar should have increased margin to account for its size decrease.

**Comment by sMesle** [comment]
I have fixed by adding a margin for `v-icon` and  `v-avatar`

**Comment by johnleider** [comment]
This is what it looks like for me: 
image

**Comment by johnleider** [comment]
This Pull Request is about to be closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
