### PR TITLE
feat(VBackdrop): add a new component

### PR DESCRIPTION
**Pull request by dsseng**
## Description
Create a new backdrop component.

## Motivation and Context

https://material.io/components/backdrop/#

## How Has This Been Tested?
markup
- [ ] `jest`
- [ ] kitchen

## Markup:

<details>

```vue
<template>
  <v-backdrop v-model="model">
    <template #collapsed>
      <v-toolbar :dense="dense" dark color="#6217ee">
        <v-btn @click="model = true" icon><v-icon>mdi-arrow-left</v-icon></v-btn>
        <v-toolbar-title>Step 1</v-toolbar-title>
        <v-btn @click="subheader = !subheader" icon><v-icon>mdi-checkbook</v-icon></v-btn>
        <v-btn @click="dense = !dense" icon><v-icon>mdi-arrow-collapse-vertical</v-icon></v-btn>
      </v-toolbar>
    </template>

    <template #back>
      <v-sheet color="#6217ee">
        <v-toolbar :dense="dense" flat dark color="#6217ee">
          <v-btn @click="model = false" icon><v-icon>mdi-close</v-icon></v-btn>
          <v-toolbar-title>Step 1</v-toolbar-title>
          <v-btn @click="subheader = !subheader" icon><v-icon>mdi-checkbook</v-icon></v-btn>
          <v-btn @click="dense = !dense" icon><v-icon>mdi-arrow-collapse-vertical</v-icon></v-btn>
        </v-toolbar>
        Steps:
        <v-slider v-model="steps" min="0" max="20"></v-slider>
        <v-stepper vertical dark>
          <v-stepper-step v-for="x in steps" :key="x" :step="x">Step {{ x }}</v-stepper-step>
        </v-stepper>
      </v-sheet>
    </template>

    <template #subheader v-if="subheader">
      <v-toolbar :dense="!dense" flat>
        <v-toolbar-title>Payment</v-toolbar-title>
        <div class="flex-grow-1"></div>
        <v-btn @click="model = false" v-if="model" icon><v-icon>mdi-chevron-up</v-icon></v-btn>
      </v-toolbar>
      <v-divider />
    </template>

    <v-sheet class="pa-3">
      <v-text-field outlined label="First name"></v-text-field>
      <v-text-field outlined label="Last name"></v-text-field>
      <v-text-field outlined label="Phone"></v-text-field>
      <v-text-field outlined label="Street"></v-text-field>
      <v-text-field outlined label="City"></v-text-field>
      <v-text-field outlined label="Zip"></v-text-field>
      <v-text-field outlined label="First name"></v-text-field>
      <v-text-field outlined label="Last name"></v-text-field>
      <v-text-field outlined label="Phone"></v-text-field>
      <v-text-field outlined label="Street"></v-text-field>
      <v-text-field outlined label="City"></v-text-field>
      <v-text-field outlined label="Zip"></v-text-field>
      <v-text-field outlined label="First name"></v-text-field>
      <v-text-field outlined label="Last name"></v-text-field>
      <v-text-field outlined label="Phone"></v-text-field>
      <v-text-field outlined label="Street"></v-text-field>
      <v-text-field outlined label="City"></v-text-field>
      <v-text-field outlined label="Zip"></v-text-field>
    </v-sheet>
  </v-backdrop>
</template>

<script>
export default {
  data: () => ({
    model: false,
    steps: 3,
    subheader: true,
    dense: false,
  }),
}
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sh7dm** [comment]
Paused by #9148

**Comment by robertofd1995** [comment]
HI @sh7dm  I don't see this component in the roadmap, it's just missing there or you are not gonna include this component at the end in vuetify.

Thanks in advance for your awesome project

**Comment by johnleider** [comment]
> Paused by #9148

@sh7dm that's merged in now

**Comment by nekosaur** [comment]
What is this component? It's not self-evident to me from the name alone.

**Comment by robertofd1995** [comment]
@nekosaur https://material.io/components/backdrop/

**Comment by johnleider** [comment]
This will have to re-emerge for the v3 development.

**Pull request closed without merging**
