### PR TITLE
fix(VAutocomplete): Retain filtered list on item selection

### LINKED ISSUE #6260: [Bug Report] VAutocomplete broken suggestions if the value match input
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Linux x86_64

### Steps to reproduce
define a prefix filter for VAutocomplete like this:
```javascript
methods: {
  filter: (item, queryText, itemText) => itemText.startsWith(queryText)
}
```
suppose, items containing values, some of which are the prefix for others
```javascript
data() {
  return {
    items: ["bar", "baz", "foo", "foo-bar", "foo-baz", "foo-foo"],
    val: ""
  };
}
```
in this example "foo" is the prefix for "foo-bar", "foo-baz", "foo-foo")

If for such autocomplete element first select "foo", so that the value will be "foo", then edit the input to "fo" and then to "foo" again, then suggested items are incorrect: all of items (unfiltered) are shown and none of them is highlighted.

### Expected Behavior
Instead of all items just items, which prefixed by "foo" must be shown.

### Actual Behavior
But the item list is not filtered and none of items is highlighted.

### Reproduction Link
<a href="https://codesandbox.io/s/32xn42o03q" target="_blank">https://codesandbox.io/s/32xn42o03q</a>

### Other comments
The issue occurs due to the check (`this.internalSearch !== this.getText(this.selectedItem)`) in the function `isSearching` of `components/VAutocomplete/VAutocomplete.js` at the  [line 120](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAutocomplete/VAutocomplete.js#L120):
```javascript
isSearching: function isSearching() {
  if (this.multiple) return this.searchIsDirty;
  return this.searchIsDirty && this.internalSearch !== this.getText(this.selectedItem);
}
```

### PR DESCRIPTION
**Pull request by heidricklevi**
Closes #6260

## Description

Modify Autocomplete to retain the filtered list after an item has been selected (based on input)

## Motivation and Context

Addresses [#6260](https://github.com/vuetifyjs/vuetify/issues/6260)
## How Has This Been Tested?

visually, unit

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-app>
    <v-card>
      <v-card-text>
        <v-subheader class="pa-0" v-text="`Model value is '${a1}'`" />
        <form>
          <v-autocomplete
            v-model="a1"
            autofocus
            auto-select-first
            clearable
            :items="items"
            :filter="filter"
          />
        </form>
      </v-card-text>
    </v-card>
  </v-app>
</template>

<script>
  export default {
    data() {
      return {
        items: ["bar", "baz", "foo", "foo-bar", "foo-baz", "foo-foo"],
        a1: '',
      };
    },
    methods: {
      filter: (item, queryText, itemText) => itemText.startsWith(queryText)
    }
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by sh7dm** [comment]
Looks like I messed something up when resolving a merge conflict :(

**Comment by heidricklevi** [comment]
I updated it locally, and it looks like my other recent changes to VAutocomplete might have caused some unexpected results for this. I will see if I can get it fixed. @sh7dm I don't think it was anything you did :)

**Comment by heidricklevi** [comment]
Changes to address the failing test

**Comment by DRoet** [comment]
This seems quite `semver-major` with this being default behaviour and not behind a prop....

**Comment by heidricklevi** [comment]
Should I resubmit to dev branch?

**Pull request merged**
