### PR TITLE
fix(VTextField): calculate label width depending on the textfield width

### LINKED ISSUE #10030: [Bug Report] Very long labels on text field makes the whole field wider
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.88
**OS:** Windows 10

### Steps to reproduce
create outlined text field with very long label

### Expected Behavior
same behaviour as non outlined text fields. Not increasing width of whole text field

### Actual Behavior
if the label is too long and the outlined style is used, the label will be truncated to the visible part (that's OK), but the width of the entire input will increase, which is not OK.

### Reproduction Link
<a href="https://codepen.io/maylow/pen/GRgmJYv" target="_blank">https://codepen.io/maylow/pen/GRgmJYv</a>

### PR DESCRIPTION
**Pull request by Djaler**
## Description
Limit the width of the label to the width of the field itself

## Motivation and Context

Fixes #10030 

## How Has This Been Tested?

visually (using this template https://codepen.io/maylow/pen/GRgmJYv)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by Djaler** [comment]
I don't think tests failed because of my changes ^

**Comment by MajesticPotatoe** [comment]
@djaler they didnt. Some date based tests are acting up because of the new year. When we fix it it will trickle down.

**Comment by Djaler** [comment]
@KaelWD check this please

**Comment by Djaler** [comment]
@KaelWD check this, please

**Pull request merged**
