### PR TITLE
feat(locale): add slovak locale

### PR DESCRIPTION
**Pull request by xspaniki**
Add slovak locale -> https://en.wikipedia.org/wiki/Slovak_language

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
Please add an export to index.ts and corresponding PR in vue-cli-plugin-vuetify

**Comment by xspaniki** [comment]
> Please add an export to index.ts and corresponding PR in vue-cli-plugin-vuetify

@jacekkarczmarczyk 
I added export to index.ts but I dont understand what you mean with 'corresponding PR in vue-cli-plugin-vuetify'. Thx :)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vue-cli-plugins/blob/master/packages/vue-cli-plugin-vuetify/util/locales.js

**Comment by xspaniki** [comment]
ok thanks :) here -> https://github.com/vuetifyjs/vue-cli-plugins/pull/154

**Comment by johnleider** [comment]
Should this be to `dev`? There are currently no plans for v2.3.

**Pull request merged**
