### PR TITLE
fix(VData): prevent array value from sort-desc

### LINKED ISSUE #9267: [Bug Report] Datatable - Sorting the same column multiple times turn the sort-desc parameter from boolean to array after the 4th click
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux x86_64

### Steps to reproduce
1. Pick a column header.
2. Click it's header to sort.  sort-desc = false (Works as expected)
3. Click the same header to reverse your sort. sort-desc = true  (Works as expected)
4. Click the same header again.  sort-desc = undefined  (Works as expected)
5. Click the same header again. sort-desc = [ false ] the type will change to Array!

### Expected Behavior
In the 4th click, the value should be false not [ false ]

### Actual Behavior
The sort-desc value changed to array in the 4th click

### Reproduction Link
<a href="https://codepen.io/alaarihan/pen/yLLyMda?&editable=true&editors=101" target="_blank">https://codepen.io/alaarihan/pen/yLLyMda?&editable=true&editors=101</a>

### PR DESCRIPTION
**Pull request by whoistobias**
## Description
VData would emit correct values for the first 3 sorts of a data-table column, followed by emitting
array values for every sort following. VData now correctly removes the array before emitting the
value.

fixes #9267

## Motivation and Context
 The data returned from `v-data-table` can now be consumed reliably as a boolean or undefined as well as in array form. This change enables users to use the model emitted from sort-desc without breaking expectations and causing confusing interactions, such as `[false]` returning truthy.

https://github.com/vuetifyjs/vuetify/issues/9267

## How Has This Been Tested?
I added a new unit test which runs through the scenario of passing a normal boolean prop as well as an array containing a boolean, and then checks to ensure all values emitted are consistent with the type used in the prop.

## Markup:

<details>

```vue
<template>
  <v-container>
    <h1>VData</h1>
    <div>value: <span class="font-weight-bold blue--text">{{ desc }}</span></div>
    <div>type: <span class="font-weight-bold blue--text">{{ typeof desc }}</span></div>
    <v-btn @click="toggleArray">Toggle array</v-btn>
    <v-data-table
      :headers="headers"
      :items="items"
      :custom-group="groupBy"
      :sort-desc.sync="desc"
    />
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      desc: true,
      headers: [
        { text: 'ID', value: 'id' },
        { text: 'Name', value: 'name' },
        { text: 'Value', value: 'value' },
      ],
      items: [
        { id: 1, name: 'Test1', value: 2 },
        { id: 2, name: 'Test2', value: 3 },
        { id: 3, name: 'Test3', value: 1 },
        { id: 4, name: 'Test4', value: 2 },
        { id: 5, name: 'Test5', value: 3 },
        { id: 6, name: 'Test6', value: 1 },
      ],
    }),
    methods: {
      toggleArray () {
        this.desc = Array.isArray(this.desc) ? true : [true]
      },
    },
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by whoistobias** [comment]
Okay I've added the unit test, corresponding playground as well as a better description. Let me know if there's anything else I can do.

**Comment by johnleider** [comment]
Thanks for adding a test. The problem is that test still passes without your fix.

**Comment by whoistobias** [comment]
Hahaha, Okay, I'll tackle that next. No idea why I didn't think to check that.

**Comment by whoistobias** [comment]
This is all very educational for me.

**Comment by whoistobias** [comment]
Okay, I've got a good test for the use case now. Sorry this has taken forever. I'm really just learning the ropes of contributing in general.

**Comment by whoistobias** [comment]
@johnleider @nekosaur Is there anything I need to do to indicate that I've made revisions and this is ready for a new review? If so, I can't find it.

**Pull request closed without merging**
