### PR TITLE
fix(layout): handle nav drawer scrim correctly

### PR DESCRIPTION
**Pull request by nekosaur**
## Description

- layout composable will now apply `position: fixed` to layout items in the root layout (v-app), and `position: absolute` to items in child layouts.
- scrim is now contained inside layout
- scrim is now in correct z-order among layout items

## Markup:

<details>

```vue
<template>
  <v-app full-height>
    <v-navigation-drawer v-model="drawer" temporary color="secondary" />
    <v-main>
      <v-switch v-model="drawer" />
      <v-card class="ma-10" style="margin-top: 10rem">
        <v-layout>
          <v-navigation-drawer v-model="drawer2" temporary absolute color="primary" />
          <v-main>
            <v-switch v-model="drawer2" />
          </v-main>
        </v-layout>
      </v-card>
    </v-main>
  </v-app>
  <!-- <v-app>
    <v-app-bar height="22" color="grey-darken-3" elevation="0" />
    <v-navigation-drawer v-model="drawer" width="72" color="grey-darken-2" temporary />
    <v-navigation-drawer width="150" color="grey-darken-1" permanent />
    <v-app-bar height="48" color="grey" elevation="0" />
    <v-navigation-drawer position="right" width="150" color="grey-lighten-1" permanent />
    <v-app-bar position="bottom" height="48" color="grey-lighten-2" elevation="0" />
    <v-main>
      <v-card elevation="0" height="400px">
        <v-switch v-model="drawer" />
      </v-card>
    </v-main>
  </v-app> -->
</template>

<script>
  export default {
    data: () => ({
      drawer: false,
      drawer2: false,
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [ ] The PR title is no longer than 64 characters.
- [ ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
It should still be possible to override this to get a drawer that scrolls with the page: `<v-navigation-drawer app absolute>`

**Comment by johnleider** [comment]
Opening the top navigation drawer produces this:

image

**Comment by nekosaur** [comment]
I forgot to remove `absolute` prop from it

**Comment by johnleider** [comment]
Does this PR do anything to address this issue? It happens whenever the breakpoints change, it opens the drawers in temporary mode.

navigation-drawer-issues
?

**Comment by nekosaur** [comment]
> Is this PR intended to address this issue? It happens whenever the breakpoints change, it opens the drawers in temporary mode.
> 

No, that's outside scope

**Review by johnleider — APPROVED** [review]

**Pull request merged**
