### PR TITLE
refactor: abstract picker save/cancel functionality

### LINKED ISSUE #2422: [Feature Request] optimised datepicker for date of birth
### New Functionality
It'll be great to have a datepicker that allows the following things:
1- be able to firstly select year, then month and then the dat
2- set a years range, for example [1950-2000]
3- automatically close the datepicker when the user selects the day which is basically the last action

Thanks again for your great work

### Improvements
better UX

### Bugs or Edge Cases it Helps Avoid
better UX

### LINKED ISSUE #2930: [Bug Report] Date-picker don't update internal originalDate value on v-model value changes
**Versions and Environment**
- Vuetify: v1.0.0-beta.1
- Vue: 2.5.2
- Browsers: Chrome  63.0.3239.84 (64bit)

**Steps to reproduce**
1. Open the reproduction link
2. Open date-picker by click on text field
3. Select new date (ex. 2000-01-31) and press "OK" action button
4. Press "Reset" button to reset model "date" value to default ("2000-01-01")
5. Open date-picker again and after it's open - just press "Cancel" action button

**Expected Behavior**
    After step 5 value in text field must be same as model "date" value - i.e. "2000-01-01"

**Actual Behavior**
   Text field value resets to previously selected in step 3

**Reproduction Link**
[https://codepen.io/bartsimpson/pen/MrvxaW](https://codepen.io/bartsimpson/pen/MrvxaW)

### LINKED ISSUE #2945: [Feature Request] Abstract picker save/cancel functionality
### New Functionality
Simplify the responsibilities of the picker components

### Improvements
It will allow for easier implementation for developers when working with pickers as a whole

### Bugs or Edge Cases it Helps Avoid
Will help make testing and development easier when the component will not be responsible for arbitrary functionality.

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Description
- removes save/cancel functionality from `v-date-picker` and `v-time-picker` and moves it to `v-edit-dialog`, `v-menu` and `v-dialog` (which are using new `returnable` mixin)
- adds `change` event to `v-date-picker` and `v-time-picker` which is emitted when the last part of the date or time is clicked (day for date picker, month for month picker, minute for time picker).

## Motivation and Context
fixes #2930 
closes #2945
closes #2422 (this PR will allow to automatically close the datepicker when the user selects the day which is basically the last action, other problems from this issue are already solved), birthday picker **#needs-docs-update**

## How Has This Been Tested?
manually

## Markup:
See comments below

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by jacekkarczmarczyk** [comment]
With the first commit (or maybe even without, didn't check lol) dev can control cancel/save functionality with a quite simple markup. Maybe this is the way how it should work?

```vue
<template>
  <v-app>
    <v-content>
      <v-menu :close-on-content-click="false" v-model="menu" offset-y>
        <v-text-field clearable slot="activator" label="Picker in menu" v-model="date" readonly></v-text-field>
        <v-date-picker v-model="date">
          <v-spacer></v-spacer>
          <v-btn flat color="primary" @click="date = originalDate; menu = false">Cancel</v-btn>
          <v-btn flat color="primary" @click="originalDate = date; menu = false">OK</v-btn>
        </v-date-picker>
      </v-menu>
    </v-content>
  </v-app>
</template>

<script>
export default {
  data: () => ({
    date: '2000-01-01',
    originalDate: null,
    menu: false
  }),
  watch: {
    menu (v) {
      v ? (this.originalDate = this.date) : (this.date = this.originalDate)
    }
  }
};
</script>
```

**Comment by jacekkarczmarczyk** [comment]
Example markup for `returnable` mixin (a21c4bacefbc09b4e15210ca54e78df654652f2c). Prize for better name

```vue
<template>
  <v-app>
    <v-content>
      <v-menu ref="menu" :close-on-content-click="false" v-model="menu" :return-value.sync="date" offset-y>
        <v-text-field clearable slot="activator" label="Picker in menu" v-model="date" readonly></v-text-field>
        <v-date-picker v-model="date">
          <v-spacer></v-spacer>
          <v-btn flat color="primary" @click="menu = false">Cancel</v-btn>
          <v-btn flat color="primary" @click="$refs.menu.save(date)">OK</v-btn>
        </v-date-picker>
      </v-menu>
    </v-content>
  </v-app>
</template>

<script>
export default {
  data: () => ({
    date: '2000-01-01',
    menu: false
  })
};
</script>
```

**Comment by nekosaur** [comment]
Hm. My first reaction to the mixin approach is that it seems like the single responsibility principle is broken. Why should the menu have anything to do with saving the date?

**Comment by jacekkarczmarczyk** [comment]
@nekosaur it has nothing to do with date, it works with any value and this is very common scenario when you have some data and you click somewhere to open the dialog where you can edit this data and save it or close without saving

deedd3b add `returnable` mixin to `v-edit-dialog` changing the docs markup from

```vue
              <v-edit-dialog>
                {{ props.item.name }}
                <v-text-field slot="input" v-model="props.item.name"></v-text-field>
              </v-edit-dialog>

              <v-edit-dialog large @open="tmp = props.item.iron" @save="props.item.iron = tmp || props.item.iron">
                {{ props.item.iron }}
                <v-text-field slot="input" v-model="tmp"></v-text-field>
              </v-edit-dialog>
```

to 

```vue
              <v-edit-dialog :return-value.sync="props.item.name">
                {{ props.item.name }}
                <v-text-field slot="input" v-model="props.item.name"></v-text-field>
              </v-edit-dialog>

              <v-edit-dialog large :return-value.sync="props.item.iron">
                {{ props.item.iron }}
                <v-text-field slot="input" v-model="props.item.iron"></v-text-field>
              </v-edit-dialog>
```

The first original example still works, but adding `:return-value:sync="props.item.name"` fixes the bug when clicking outside the dialog or pressing esc after editing value saved the new value. 
Second example doesn't work after this commit so it's a breaking change

Full **playground.vue** for `v-edit-dialog`:
```vue
<template>
  <v-app>
    <v-container>
      <v-data-table :headers="headers" :items="items" hide-actions>
        <template slot="items" slot-scope="props">
          <td>
            <v-edit-dialog :return-value.sync="props.item.name">
              {{ props.item.name }}
              <v-text-field slot="input" v-model="props.item.name"></v-text-field>
            </v-edit-dialog>
          </td>
          <td>
            <v-edit-dialog large :return-value.sync="props.item.iron">
              {{ props.item.iron }}
              <v-text-field slot="input" v-model="props.item.iron"></v-text-field>
            </v-edit-dialog>
          </td>
        </template>
      </v-data-table>
    </v-container>
  </v-app>
</template>

<script>
export default {
  data() {
    return {
      headers: [
        { text: "Dessert (100g serving)", value: "name" },
        { text: "Iron (%)", value: "iron" }
      ],
      items: [{ value: false, name: "Frozen Yogurt", iron: "1%" }]
    }
  }
}
</script>
```

**Pull request merged**
