### PR TITLE
fix(VListItem): allow default color to change when inactive

### LINKED ISSUE #9285: [Bug Report] Impossible to set color of List Item text
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.6

### Steps to reproduce
Try to set color (text/icon) of not active list item with available tools:
- `color` prop on list item;
- `active-class` prop on list item;
- `class` on list item;
- css;
- css with `!important`;
- inline css;

### Expected Behavior
image

### Actual Behavior
image

Impossible to replace light* text color of dark list item without inline css.
With inline css active tile is effected and cannot be styled to have dark* text color.

*light = the white color used for light theme backgrounds and dark theme texts.
*dark = the black color used for dark theme backgrounds and white theme texts.

image

### Reproduction Link
<a href="https://codepen.io/JesusCrow/pen/OJJPqVb?editors=0100" target="_blank">https://codepen.io/JesusCrow/pen/OJJPqVb?editors=0100</a>

### Other comments
I tried everything I could think up to create a list item that has a certain color for text and icon. I think that this is impossible without inline css. Using inline css disables me from styling active item text.

### LINKED ISSUE #14186: [Bug Report][2.5.8] Color prop is not working for v-list-item
### Environment
**Vuetify Version:** 2.5.8
**Vue Version:** 2.6.14
**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
1. Create some `v-list-item`s with `to` prop.
2. Set the `color` in `v-list-item`.
3. The `color` prop is not working. `v-list-item` color is not changed when it is in `active` state.

According to the docs it should change the color, when it is in the active state:
https://vuetifyjs.com/en/api/v-list-item/#props-color

### Expected Behavior
Color should change to the selected one when `v-list-item` is in the active state.

### Actual Behavior
Color is not changed from the default one when `v-list-item` is in the active state.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/MWoBjLr" target="_blank">https://codepen.io/mikilll94/pen/MWoBjLr</a>

### PR DESCRIPTION
**Pull request by Tofandel**
## Description

Restores #13719
Fixes #14186
Fixes #9285

## Motivation and Context
The isActive variable was not changing when using a router element, with this PR this makes sure that it reflects the current state of the router link, taking into account if it's exact

## How Has This Been Tested?
With the playground, the doc and new test units
image

## Markup:

<details>

```vue<template>
 <template>
  <v-container>
    <v-list-group group="/page2">
      <template #activator>
        <v-list-item-title>Pages</v-list-item-title>
      </template>
      <v-list>
        <v-list-item
          v-for="i in 2"
          :key="i"
          :to="{path: '/page' + i}"
          color="primary"
        >
          <v-list-item-content>
            <v-list-item-title>Page {{ i }}</v-list-item-title>
          </v-list-item-content>
        </v-list-item>
      </v-list>
    </v-list-group>
    <v-list-group group="/page1">
      <template #activator>
        <v-list-item-title>Pages</v-list-item-title>
      </template>
      <v-list>
        <v-list-item
          v-for="i in 2"
          :key="i"
          :to="{path: '/page' + i}"
          color="primary"
        >
          <v-list-item-content>
            <v-list-item-title>Page {{ i }}</v-list-item-title>
          </v-list-item-content>
        </v-list-item>
      </v-list>
    </v-list-group>
    <v-list>
      <v-list-item>
        <v-list-item-icon>
          <v-icon>mdi-home</v-icon>
        </v-list-item-icon>

        <v-list-item-title>Home</v-list-item-title>
      </v-list-item>

      <v-list-group
        :value="true"
        prepend-icon="mdi-account-circle"
      >
        <template v-slot:activator>
          <v-list-item-title>Users</v-list-item-title>
        </template>

        <v-list-group
          :value="true"
          no-action
          sub-group
        >
          <template v-slot:activator>
            <v-list-item-content>
              <v-list-item-title>Admin</v-list-item-title>
            </v-list-item-content>
          </template>

          <v-list-item
            v-for="([title, icon], i) in admins"
            :key="i"
            link
          >
            <v-list-item-title v-text="title"></v-list-item-title>

            <v-list-item-icon>
              <v-icon v-text="icon"></v-icon>
            </v-list-item-icon>
          </v-list-item>
        </v-list-group>

        <v-list-group
          no-action
          sub-group
        >
          <template v-slot:activator>
            <v-list-item-content>
              <v-list-item-title>Actions</v-list-item-title>
            </v-list-item-content>
          </template>

          <v-list-item
            v-for="([title, icon], i) in cruds"
            :key="i"
            link
          >
            <v-list-item-title v-text="title"></v-list-item-title>

            <v-list-item-icon>
              <v-icon v-text="icon"></v-icon>
            </v-list-item-icon>
          </v-list-item>
        </v-list-group>
      </v-list-group>
    </v-list>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      admins: [
        ['Management', 'mdi-account-multiple-outline'],
        ['Settings', 'mdi-cog-outline'],
      ],
      cruds: [
        ['Create', 'mdi-plus-outline'],
        ['Read', 'mdi-file-outline'],
        ['Update', 'mdi-update'],
        ['Delete', 'mdi-delete'],
      ],
    }),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by KaelWD** [comment]
This breaks list groups, try expanding some sections in the sidebar on https://vuetify-ehm9rsjlu-vuetifyjs1.vercel.app/en/getting-started/installation/

**Comment by Tofandel** [comment]
Seems to only happen the first time, I'll have a look

**Comment by Tofandel** [comment]
This was one very weird issue as it was only happening on the Vercel preview, if I ran the doc in local I didn't get the issue, but I managed to track down the cause, there is a watcher for the inputValue toggle the isActive and because a VListGroup contains an VListItem reflecting the state of the group it shouldn't toggle when it gets it's value from inputValue

**Comment by Tofandel** [comment]
Only applying the isActive change to Router link list item fixed the issue, added a test case for this case to avoid a future regression

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
