### PR TITLE
feat(VTimePicker): update to v3

### PR DESCRIPTION
**Pull request by blalan05**
```vue 
<template>
  <v-app>
    <v-main>
      <v-container>
        <v-row>
          {{ thisDate }}
          <v-col>
            <v-switch v-model="format24" label="24hr" false-value="ampm" true-value="24hr" color="primary" />
          </v-col>
          <v-col>
            <v-switch v-model="seconds" label="Seconds" />
          </v-col>
          <v-col>
            <v-switch v-model="actions" label="No Actions" />
          </v-col>
        </v-row>
        <v-row>
          <v-col cols="12">
            <v-time-picker v-model="thisDate" :format="format24" :use-seconds="seconds" :hide-actions="actions" />
          </v-col>
        </v-row>
        <v-row>
          <v-col>
            <v-date-picker />
          </v-col>
        </v-row>
      </v-container>
    </v-main>
  </v-app>
</template>
<script setup>
  import { ref } from 'vue'

  const thisDate = ref(new Date())

  const format24 = ref('24hr')
  const seconds = ref(false)

  const actions = ref(false)
</script>
```

### CODE REVIEW

**Comment by nekosaur** [comment]
I think this needs to be rebased? Seems like a lot of unrelated commits have snuck in

**Comment by blalan05** [comment]
> I think this needs to be rebased? Seems like a lot of unrelated commits have snuck in

Done.

**Comment by ascott18** [comment]
> What do you think?

@johnleider Personally, I'm not sure what the plan for this is, and I think that's also why @AngeloACR was asking. I see the comment at https://github.com/vuetifyjs/vuetify/issues/13516#issuecomment-1681308398, but at the same time I don't see anything about this component on the [roadmap](https://vuetifyjs.com/en/introduction/roadmap/#in-development), nor on the [labs schedule](https://vuetifyjs.com/en/labs/introduction/#up-next). The [issue](https://github.com/vuetifyjs/vuetify/issues/13516) is still in the `3.x.x` milestone.

Is there any work left to do on this PR? Are community contributions needed? We'd love to know if there's anything we can do to help out on this.

**Comment by johnleider** [comment]
2024 roadmap at the end of this week.

**Comment by simonbuehler** [comment]
any news for this one, it's really needed!

**Comment by johnleider** [comment]
> any news for this one, it's really needed!

https://vuetifyjs.com/en/introduction/roadmap/#section-2024-component-roadmap

**Review by johnleider — APPROVED** [review]

**Pull request merged**
