### PR TITLE
fix(VSlideGroup): a 'window is not defined' error

### LINKED ISSUE #12016: [Bug Report] v-tabs "window is not defined" Error with SSR
### Environment
**Vuetify Version:** 2.3.8
**Vue Version:** 2.6.11
**Browsers:** Edge 85.0.564.23
**OS:** Windows 10

### Steps to reproduce
Doing Static Build via "nuxt generate"

### Expected Behavior
No error is produced during build

### Actual Behavior
Encounters an error which adumbrates malfunction

### Reproduction Link
<a href="https://github.com/mcdmaster/covid19" target="_blank">https://github.com/mcdmaster/covid19</a>

### Other comments
Thank you!

スクリーンショット 2020-08-05 234444

### PR DESCRIPTION
**Pull request by mcdmaster**
## Description

Resolves #12016 
Resolves https://github.com/tokyo-metropolitan-gov/covid19/issues/5352

## Motivation and Context

This is for smooth proceeding with repetitive updates on Tokyo Met's COVID-19 Information site.

## How Has This Been Tested?

Run the Testing instance of Tokyo Met's site for related areas which may be concerned

## Markup:

A full clone done to the local environment from the [Tokyo Met's app repo](https://github.com/tokyo-metropolitan-gov/covid19)

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [-] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
Have you actually tested this? `requestAnimationFrame` isn't available in node either.

**Comment by mcdmaster** [comment]
Hi @KaelWD,

Indeed, Typescript is referenced with `requestAnimationFrame` as if it was expecting for being superseded:
https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts (please see L 2108 et al.)

Please forgive me if I am misunderstanding. But I did not want to see such an error message which annoys me.
Thank you anyway

**Comment by KaelWD** [comment]
With this change you'll just get "requestAnimationFrame is not defined" instead. The real problem is the fact that `setWidths` is called on the server-side at all.

**Comment by mcdmaster** [comment]
I do not think so because the `setWidth()` function is originally designed and implemented on `Vuetify`'s end.
If the call to `setWidths()` incurs an unexpected error when it is made "improperly" in some practical case, I think that the `Vuetify` expert(s) is/are responsible to do the fix, instead of this PR. Thank you anyway.

**Review by mcdmaster — COMMENTED** [review]
Please note that the file that I have dealt with is only one indeed: VSlideGroup.ts. I will much appreciate if you proceed to review and approve my change so that our tech guys can go on under certain assumptions and constraints that have been agreed. Thanks!

**Comment by mcdmaster** [comment]
Hello Team,

Can you please let me know how we should collaborate on resolving conflicts which we are having?
I suppose that the conflicts resolution has to be done on your end, in accordance with the PR logs that have been produced. Thank you very much for cooperation in advance anyway

**Review by mcdmaster — COMMENTED** [review]
Fine with the change

**Review by mcdmaster — COMMENTED** [review]
Convinced going ahead

**Review by johnleider — COMMENTED** [review]
There is an overwhelming amount of unrelated changes that need to be removed from this PR.

**Comment by mcdmaster** [comment]
Hi @johnleider ,

Indeed. The artifact that is in need is VSliderGroup.ts .

Can you please let me know if it is okay now to drop the rest ones that needed to commit/push for the formal testing / checking purpose. Thank you

**Comment by johnleider** [comment]
We only want to see the necessary changes as concisely as possible in as few commits as possible. Make sure to check our [Contributing Guidelines](https://vuetifyjs.com/en/getting-started/contributing/) in the documentation for more information.

**Comment by KaelWD** [comment]
Thanks for trying but I'm going to close this PR now. This is not a suitable fix and you still have lots of unrelated changes.

**Comment by mcdmaster** [comment]
Okay, I will retry with smarter way than past. Thank you for patience

**Pull request closed without merging**
