### PR TITLE
fix(resize): use ResizeSensor

### PR DESCRIPTION
**Pull request by mrodal**
## Description

Change the resize directive to use ResizeSensor instead of the window resize event

## Motivation and Context

It fixes this long lasting and with many duplicates issue https://github.com/vuetifyjs/vuetify/issues/1978 that I opened again here https://github.com/vuetifyjs/vuetify/issues/6626

It fixes the issue because the current window resize implementation requires the window to be resized for the onresize event to be triggered, and with this alternative, the onresize is fired when the _element_ is resized. For this reason, I think this might help with other possible issues as well.

Here are the docs to css-element-queries: http://marcj.github.io/css-element-queries/. 

## How Has This Been Tested?

Visually

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [X] The PR title is no longer than 64 characters.
- [X] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ ] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by mrodal** [comment]
😁 sorry, I thought I had selected next by mistake

**Comment by mrodal** [comment]
@MajesticPotatoe did you leave comments on the files? I cant see them

**Comment by MajesticPotatoe** [comment]
> @MajesticPotatoe did you leave comments on the files? I cant see them

I did not.

**Comment by johnleider** [comment]
This will have to be done differently. We have a no external dependencies rules that I do not intend on breaking 😉

**Comment by mrodal** [comment]
hmm what about copying the ResizeSensor code into vuetify? 😂 
Its this file:
https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js

**Comment by DRoet** [comment]
I don't think copying in upstream source code is a valid solution to the no-dependencies rule, but maybe it's possible to allow people to create adapters for stuff like this? so we can always go back to the default behaviour if none is provided?

**Comment by johnleider** [comment]
Closing due to inactivity.

**Comment by mrodal** [comment]
@johnleider I proposed taking the ResizeSensor code into vuetify, which isnt much code.. isnt that ok?

**Pull request closed without merging**
