### PR TITLE
refactor(goTo): Full rewrite. Allow target container selection

### LINKED ISSUE #3510: [Feature Request] Specify a target element for goTo
### New Functionality
Currently it is not possible to scroll a full screen dialog, as one might want to do when validating a form before submission. If the goTo function could be handed an element to scroll (as an example) it might be possible to enable it to scroll in this case.

Here's an example where it would be nice if it worked: https://codepen.io/anon/pen/bvGrja

### Improvements
Right now one has to find the proper offsets and scroll the particular div they're working with, rather than using goTo, which scrolls the entire document. In the case of a fixed full screen dialog, all elements are currently 'on screen' even when scrolled out of view since they're subelements of the fixed element.

### Bugs or Edge Cases it Helps Avoid
The code for determining where and how to scroll can get rather complicated when rolling it on one's own.

### PR DESCRIPTION
**Pull request by zaken**
## Motivation and Context
- More modular
- Allow target container selection (fixes #3510)

## How Has This Been Tested?
Visually

## Markup:
<details>

```vue
<template>
  <v-app>

    <v-navigation-drawer app fixed right permanent class="pb-0" id="s" ref="sidebar">
      <h1 id="st">Top</h1>
      <h1 id="sm">Middle</h1>
      <h1 id="sb">Bottom</h1>
    </v-navigation-drawer>

    <v-toolbar app fixed dense flat dark>
      <v-btn @click="$vuetify.goTo(0)" small light>0</v-btn>
      <v-btn @click="$vuetify.goTo('#nt')" small light>nested</v-btn>
      <v-btn @click="$vuetify.goTo(2222)" small light>2222</v-btn>
      <v-btn @click="$vuetify.goTo('#cb')" small light>bottom</v-btn>
      <v-spacer></v-spacer>
      <v-btn small light @click="$vuetify.goTo(
        '#st', {
          container: '#s',
          duration: 300
        }
      )">#st</v-btn>
      <v-btn small light @click="$vuetify.goTo(
        1500, {
          container: '#s',
          duration: 1000
        }
      )">1500</v-btn>
      <v-btn small light @click="$vuetify.goTo(
        '#sb', {
          container: '#s',
          duration: 3000
        }
      )">#sb</v-btn>
    </v-toolbar>

    <v-content>
      <v-btn @click="toggle = true">Dialog</v-btn>
      <h1 id="ct">Top</h1>
      <div id="n">
        <h1 id="nt">I'm a nested element</h1>
      </div>
      <h1 id="cm">Middle</h1>
      <h1 id="cb">Bottom</h1>
    </v-content>

    <v-dialog v-model="toggle" fullscreen transition="dialog-bottom-transition" :overlay="false" scrollable>
      <v-card tile>
        <v-toolbar card dark color="primary">
          <v-btn icon @click.native="toggle = false" dark>
            <v-icon>close</v-icon>
          </v-btn>
          <v-toolbar-title>Test Dialog</v-toolbar-title>
        </v-toolbar>
        <v-card-text ref="dialog">
          <v-form @submit.prevent="$refs.form.submit">
            <v-text-field
              v-for="i in 20"
              :key="i"
              :placeholder="'Field ' + i"
              :id="'field-' + i"
            />
          </v-form>
          <v-btn @click="$vuetify.goTo('#field-7', { container: $refs.dialog, offset: 64 })">Go to field 7</v-btn>
        </v-card-text>
      </v-card>
    </v-dialog>

  </v-app>
</template>

<script>
export default {
  data: () => ({
    toggle: false
  })
}
</script>

<style scoped>
#cm, #sm {
  margin: 1500px 0;
}
h1 {
  padding: 10px 0;
  text-align: center;
}
#n {
  height: 200px;
  margin: 500px 0;
  border: 2px dashed red;
  position: relative;
}
#n h1 {
  color: red;
  margin: 100px 0;
}
</style>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by husayt** [comment]
This is really needed. Having target container in `$vuetify.goTo`  is the key.  

Looking forward to seeing this merged.

Thanks

**Comment by husayt** [comment]
Just to let you know, I have been using this for last two weeks and it works like a charm.

**Comment by johnleider** [comment]
image

This needs to account for application components. The above is clicking the nested link and it essentially hides the text we want to see.

**Comment by hb0nes** [comment]
> Just to let you know, I have been using this for last two weeks and it works like a charm.
> 
> Thank you. This really helped

How do I use this?

**Comment by johnleider** [comment]
This Pull Request is being closed due to unresolved merge conflicts. Once corrected we will re-open.

Thank you for your contribution and interest in improving Vuetify!

**Pull request closed without merging**
