### PR TITLE
feat(display): add local mobile-breakpoint support

### LINKED ISSUE #15381: [Feature Request] Add missing `mobile-breakpoint` prop in navigation drawer like v2
### Problem to solve
Same as v2

### Proposed solution
Same as v2

### PR DESCRIPTION
**Pull request by johnleider**
## Motivation and Context
resolves #15381

## Markup:
<details>

```vue
<template>
  <v-app>
    <v-navigation-drawer mobile-breakpoint="xl" color="purple" />
    <v-navigation-drawer location="end" color="primary" />
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  import { useDisplay } from '../src/composables/display'

  const { mobile, isLocalMobile, displayClasses } = useDisplay({
    mobileBreakpoint: 2156,
  }, 'v-my-class')

  console.log(mobile, isLocalMobile)
  console.log(displayClasses.value)
</script>

```
</details>

### CODE REVIEW

**Comment by KaelWD** [comment]
Does there need to be a distinction between mobile and localMobile?

**Comment by johnleider** [comment]
> Does there need to be a distinction between mobile and localMobile?

I was looking forward to feedback on this part. I wasn't sure what to call it or how to differentiate it from **mobile**. I feel like it was a missed opportunity not originally naming it **isMobile**. I'm open to any suggestions.

**Comment by KaelWD** [comment]
I was thinking just keep it always mobile, if props are provided and the prop is set then it would be local instead of global

**Comment by KaelWD** [comment]
Like that

**Pull request merged**
