### PR TITLE
Don't set aria-hidden if icon is a button

### LINKED ISSUE #4770: [Enhancement] Accessible icon button
### Versions and Environment

Vuetify: 1.1.9
Vue: -
Browsers: Firefox
OS: Linux

### Steps to reproduce

1. Go to https://vuetifyjs.com/en/components/icons#example-clickable
2. Inspect the clickable button

### Actual Behavior

    <i aria-hidden="true" class="v-icon v-icon--link 
          mdi 
          mdi-chevron-right" style="font-size: 36px;"></i>

This icon serves as a button it should not have `aria-hidden="true"`.

### Expected Behavior

The icon should probably have `role="button"`.

A workaround is to explicitly override them:

    <v-icon aria-hidden="false" role="button" @click="foo">add</v-icon>

### Reproduction Link

https://codepen.io/anon/pen/oMqxXe

### Additional Comments:

Additionally, the documentation should probably recommend setting `aria-label` and/or `title`:

    <v-icon "@click="foo" aria-label="Add">add</v-icon>

### PR DESCRIPTION
**Pull request by catskull**
Also set role="button" if the icon is a button.

## Description
This will only set aria-hidden=true on v-icon if the icon does not have a click event bound to it. Additionally, if the button does have a click event, then it will set role="button".

## Motivation and Context

Fixes #4770 

## How Has This Been Tested?
I am new, I don't know how to test Vuetify locally. I have not tested this.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by catskull** [comment]
I apologize for not testing this. If there is documentation on how to build and test vuetify locally that I missed please let me know so I can do it!

**Comment by johnleider** [comment]
Fix conflict and I'll merge in.

**Comment by catskull** [comment]
Okay, not totally sure what changed but I think the conflict is resolved.

**Comment by johnleider** [comment]
It's failing because you need to update the snapshots for the unit tests.

**Comment by johnleider** [comment]
This Pull Request is being closed due to unresolved merge conflicts. Once corrected we will re-open.

Thank you for your contribution and interest in improving Vuetify!

**Pull request closed without merging**
