### PR TITLE
fix(VCalendar): implicitly narrow TouchEvent

### LINKED ISSUE #14276: [Bug Report][2.5.10] Calendar click event failing on latest Firefox
### Environment
**Vuetify Version:** 2.5.10
**Vue Version:** 2.6.14
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
Failing on latest Firefox (and Safari). Unable to click any events on a v-calendar. A "ReferenceError: TouchEvent is not defined" is thrown. On my own Vuetify installation and the live vuetify docs.

This seems to be an issue regardless of OS.

### Expected Behavior
Clicking a calendar event should work.

### Actual Behavior
Clicking a calendar event fails. 

### Reproduction Link
https://vuetifyjs.com/en/components/calendars/#click

Could be similar to this issue: https://github.com/vuetifyjs/vuetify/issues/14243

### PR DESCRIPTION
**Pull request by yuwu9145**
## Description

According to [MDN doc (TouchEvent)](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/TouchEvent)

`TouchEvent` constructor is not available on Safari and might not be available in Firefox.

Therefore, `if (e instanceof TouchEvent) {...}` does not work on Safari & Firefox

## Motivation and Context

1. ✅fixes #14276 
2. ✅keeps the fix for #12366
3. ⚠️revert fix for #13174 and make a separate proper dedicated pull request to tackle it in future because previous changes of fixing it breaks #14243
4. ⚠️chagnes in point 3 restores [drag & drop example](https://vuetifyjs.com/en/components/calendars/#drag-and-drop) back to its previous version . #14243 is caused by a Firefix behaviour regarding `overflow: hidden` which has been officially  confirmed by Firefox as an issue [detail](https://bugzilla.mozilla.org/show_bug.cgi?id=1736188), a fix in vuetify level will be made by a separate pull request

## How Has This Been Tested?

visually
## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <h1><a href="https://github.com/vuetifyjs/vuetify/issues/12366" target="_blank">12366 (fixed)</a></h1>
    <v-calendar 
      type="category"
      category-show-all
      :categories="categories"          
      :events="events"
      @mousemove:time-category="move"
      @touchmove:time-category="move"
    />
    <br> 
    <br> 
    <br> 
    <v-divider></v-divider>
    <br> 
    <br> 
    <br>
    <h1><a href="https://github.com/vuetifyjs/vuetify/issues/13174" target="_blank">13174 (not fixed)</a></h1>
    <div>Data and time: {{moveCategoryWeek}}</div>
    <v-calendar 
      type="week"
      :events="eventsWeek"
      @mousemove:time="moveWeek"
      @touchmove:time="moveWeek"
    />

  </v-container>
</template>

<script>
export default {
  data: () => ({
    events: [],
    eventsWeek: [],
    categories: ['John Smith', 'Tori Walker'],
    moveCategory: null,
    moveCategoryWeek: null
  }),
  methods: {
    move({category}) {
      console.log(category)
      this.moveCategory = category
    },
    moveWeek({date, time}) {
      console.log(date, time)
      this.moveCategoryWeek = date + ', ' + time
    }
  },
};
</script>

<style>
.scrolling-div {
  width: 200px;
  height: 100px;
  overflow: auto;
  white-space: nowrap;
}
</style>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by yuwu9145** [comment]
Hi @KaelWD , I tried to make a pull request as minimum as possible and here is a summary of what does it mean for each ticket:

1. For #14276, it is due to `TouchEvent` constructor is not available on Firefox and safari, so `if (e instanceof TouchEvent) {...}` will result in console error. Easy fix
2. For #12366, changes in this pull request keeps its fix so it can remain closed
3. For #13174, it was supposed to be resolved by changes of the file `packages/vuetify/src/components/VCalendar/VCalendarDaily.ts` in https://github.com/vuetifyjs/vuetify/pull/14084, but changes in this file breaks [drag & drop example](https://vuetifyjs.com/en/components/calendars/#drag-and-drop), so I revert this file changes, I think this ticket should be resolved with a dedicated pull request that construct some logic around its ` @touchmove:time` on top of  the `touchEvent` that is always dispatched from the element that is being hovered. I think it should be reopened.
4. For #14243,  as explained in point 3,  [drag & drop example](https://vuetifyjs.com/en/components/calendars/#drag-and-drop) is back to work, but the original issue in this ticket still remains, so it should be kept open for a dedicated pull request

**Comment by yuwu9145** [comment]
New update for #14243:

I manged to find the cause, Firefox has very wired mouse event behaviour on div with `overflow: hidden` applied, which can be demonstrated with this [simple javascript codepen example ](https://codepen.io/yuchaosydney/pen/NWvxXVX).

After removing `overflow: hidden` on `.v-event-timed`, drag & drop works perfectly on Firefox

**Comment by denizaygun** [comment]
Hi @yuwu9145 , thanks a lot for fixing this so promptly, when could we expect to see it released?

**Comment by yuwu9145** [comment]
I look forward to any feedback and happy to address them asap

**Review by KaelWD — APPROVED** [review]

**Pull request merged**
