### PR TITLE
Allow for more customisability - New slot for the VDataTable

### PR DESCRIPTION
**Pull request by DCzajkowski**
## Description
Added a scoped slot for adding additional things to the data table's actions footer.

## Motivation and Context
It allows for more customisability. Currently, to add anything to the actions footer one needs to remake whole table's footer.

## How Has This Been Tested?
Visually

## Markup:
<details>

```vue
<template>
  <v-data-table
    :headers="headers"
    :items="desserts"
    hide-actions
    class="elevation-1"
  >
    <template slot="items" slot-scope="props">
      <td>{{ props.item.name }}</td>
      <td class="text-xs-right">{{ props.item.calories }}</td>
      <td class="text-xs-right">{{ props.item.fat }}</td>
      <td class="text-xs-right">{{ props.item.carbs }}</td>
      <td class="text-xs-right">{{ props.item.protein }}</td>
      <td class="text-xs-right">{{ props.item.iron }}</td>
    </template>

    <!-- What was added -->

    <template slot="actions-extras">
      <v-btn color="green">New</v-btn>
    </template>
    
    <!-- /What was added -->

  </v-data-table>
</template>

<script>
  export default {
    data () {
      return {
        headers: [
          {
            text: 'Dessert (100g serving)',
            align: 'left',
            sortable: false,
            value: 'name'
          },
          { text: 'Calories', value: 'calories' },
          { text: 'Fat (g)', value: 'fat' },
          { text: 'Carbs (g)', value: 'carbs' },
          { text: 'Protein (g)', value: 'protein' },
          { text: 'Iron (%)', value: 'iron' }
        ],
        desserts: [
          {
            value: false,
            name: 'Frozen Yogurt',
            calories: 159,
            fat: 6.0,
            carbs: 24,
            protein: 4.0,
            iron: '1%'
          }
        ]
      }
    }
  }
</script>
```

</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by nekosaur** [comment]
To make things consistent with the rest of the framework, I think it should probably be named `actions-append`. And you could add a `actions-prepend` slot as well.

**Comment by DCzajkowski** [comment]
Good call. I'll update that today.

**Comment by DCzajkowski** [comment]
Ok, done :)

**Comment by DCzajkowski** [comment]
Thanks 👍

**Comment by ais-one** [comment]
I used it so far no issue...

**Pull request merged**
