### PR TITLE
docs/restructure

### PR DESCRIPTION
**Pull request by johnleider**
## Description
Restructured documentation to better support various layouts. Cleaned up code and updated grid in places that I touched (there is still more to be done that is outside the scope of this PR). Normalized data structures and moved to vuex store. Updated numerous visual aspects including the Home page, all heading, text and added breadcrumbs to every page.

Search has moved and is now automatically focusable by pressing "/".

## Motivation and Context
Improve doc experience.

## How Has This Been Tested?
visually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
> * Somewhere around the md breakpoint area, nav-drawer + ToC disappears with no way to bring it back (aside or resizing)
> * LTS + Migration pages have headers that arn't registered in ToC (minor)
> 
> Other than that looks pretty damn spiffy

Fixed migrations page. LTS will not be solvable due to the new structure only pulling headings from the structure. They will still work, just won't show up in the toc.

**Comment by johnleider** [comment]
Addressed the md breakpoint. The ToC is expected to behave like that for now, haven't come up with a design for letting mobile users toggle it. Considering mobile/tablet make up like 1.5% of our traffic, I'm, not too concerned with it.

**Comment by MajesticPotatoe** [comment]
> Addressed the md breakpoint. The ToC is expected to behave like that for now, haven't come up with a design for letting mobile users toggle it. Considering mobile/tablet make up like 1.5% of our traffic, I'm, not too concerned with it.

No biggy, the nav-bar was more important 👍

**Comment by DRoet** [comment]
`shrink` usage is all messed up in IE11 (logos on the homepage), but I opened https://github.com/vuetifyjs/vuetify/pull/9450 for that

**Comment by johnleider** [comment]
I think we should always be improving what we can with IE11 but it should never be a blocker in regards to the docs.

**Comment by vanillamasonry** [comment]
API explorer - missing component property details.

Please compare:
https://vuetifyjs.com/en/components/api-explorer - v-row (description missing)
and https://vuetifyjs.com/en/components/grids -  v-row

On the other hand is faster to find components via API explorer and for this reason showing usage and examples in API explorer will be a great addition.

**Comment by MajesticPotatoe** [comment]
@vanillamasonry 
Slightly outside the scope of this PR. API explorer is already planned to be reworked as a whole and will be handled as a separate PR which will address your open issue.

**Pull request merged**
