### PR TITLE
fix(VDataTable): bg color change via class

### LINKED ISSUE #17714: [Feature Request] v-data-table background-color
### Problem to solve
Change the background-color of v-data-table. The component v-data-table does not support color change.

### Proposed solution
Listen and respect css background-color property provided with css-classes as v-table does.

See
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNrtV81u4zYQfhVCReEUiCQ7TpyN4A223bZAu5dei/UeKHFss5FIgRx76xp+9w6pH0uWsi7QW7u5xJzfb+YbD+mPx+D7soz2OwiSYIlQlDlHeF4pxpb7kJcls3jI4e0qSHn2sjF6p0SY6VybhH2TvYFF9rQKvLl3yLRCLhWYWkTCkmU5t5YiFIdwzhD+xNCAaL3c3z4UHHmIPM2BCQ2WKY0slxZBMdQMt8Aya9klBlYaXYLBwzkUSfZSgGCfJW6dU+jTR+yHHfo4a60RDGVpEcYlQWlPXSznsMkWuADjyqg/rYKOVlLnnE6AtYSnp3S6cM/zneui4gV0lb4MkpdGFtwceqq6bekm1IarTc+v2OUoQ6sNNrLnZdyF3i1pjIKNAVAXJFT9r9vOlWAGbAkZWt+4q80fNLKKN1JHJ+uSQnPRETjReXxaI4K39p1y5kwq1tLwfDz6Q4QSczidljFu+/HiXkCn76dcYqrF4RJDm9GnOzM7wCYcAhE5aplP3y+nY5Jx6puk8f6y2Zrj1UAmvRaF6EEg5F+2kkaPmgyb1uuRG7bBnI0wjsS4LbkBhV9p///QntK2C3O52dImCR++Mv/fYr459297J6EHA30m3/NDgo42M7JEZgF3Tk1XYlHSzcWOdMGs2YmtjS7YhN4gk2qqKK7Fhm/2ln2sUh4bLJ73hE1+rChiN7PpdEPhzV6qzXeT28aO0wQqsrPIDZ7F7tZ0lSRszXMLrfwFDmTsWG1sT/X/Y5vyfU3o5LaNDkrQqXJu+J6MuP5MJN84eKOeNAJjTu8976+7+bkYc/ytHobXXetxGXP+xc3IzbeveboRatw+dSlrvjMjnLm2uiYY/Rc9Ln7Xm12XkqZvCZs9PLVS6knCFtG0Y0bVJuzuvpXURSTsvmPm8FGu2YDGCzC/Qp4fWApcjSGZPz70kUyHSJ5GkHTNaiTTa0g+SPxAAzCC4mH2po/ibqQhizPSFsbjJYjFNRA/0QKXZgzE3eKuD2I2xsp8CKJrVsN47MOg+VnG1YKg1RDcBtVuCAteRn9Yrehnice5qhW0j5MG+SqgneHOdEkgljaJ40wochOQy72JFGCsyiJ+R2ax2SmUBYRCF+/m0Ty6jwU9dLviCGwRpkZ/phmmIKugBurToFzT6/xqqtrSZ1hUGWpRmPPUuhSD0LHbXGDoV5GihQfmn1Z04dat6kI1qMxlP63UifqdS/ViL1pNP5sciPo7/C9L9sFqqk/B6TbwOCmzdwg+/Q1FT0F1)

### PR DESCRIPTION
**Pull request by BaltacMihai**
resolves #17714
``` background: rgb(var(--v-theme-surface)) ``` - overwrites the selected background color

## Markup:

```vue

<template>
  <v-app style="background-color: #c8e6c9">
    <v-container>
      <h1 class="text-center my-3">v-data-table</h1>
      <p class="my-3 text-green">
        css background-color property provided with css-class
      </p>

      <v-data-table
        :headers="headers"
        :items="desserts"
        item-value="name"
        color="primary"
        multi-sort
        class="bg-orange"
      ></v-data-table>

      <p class="my-3 text-green">
        css background-color: transparent property provided with css-class
      </p>

      <v-data-table
        :headers="headers"
        :items="desserts"
        item-value="name"
        color="primary"
        class="bg-transparent"
        multi-sort
      ></v-data-table>

      <p class="my-3 text-green">
        without css background-color property provided
      </p>

      <v-data-table
        :headers="headers"
        :items="desserts"
        item-value="name"
        color="primary"
        multi-sort
      ></v-data-table>
    </v-container>
  </v-app>
</template>

<script setup>
import { ref } from "vue";

const headers = [
  {
    title: "Dessert (100g serving)",
    align: "start",
    sortable: false,
    key: "name",
  },
  { title: "Calories", align: "end", key: "calories" },
  { title: "Fat (g)", align: "end", key: "fat" },
  { title: "Carbs (g)", align: "end", key: "carbs" },
  { title: "Protein (g)", align: "end", key: "protein" },
  { title: "Iron (%)", align: "end", key: "iron" },
];

const desserts = [
  {
    name: "Frozen Yogurt",
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
    iron: "1",
  },
  {
    name: "Jelly bean",
    calories: 375,
    fat: 0.0,
    carbs: 94,
    protein: 0.0,
    iron: "0",
  },
  {
    name: "KitKat",
    calories: 518,
    fat: 26.0,
    carbs: 65,
    protein: 7,
    iron: "6",
  },
  {
    name: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 23,
    protein: 6.0,
    iron: "7",
  },
];
</script>


```

### CODE REVIEW

**Comment by johnleider** [comment]
paging @nekosaur

**Comment by SveinnB** [comment]
Hi guys, nice work.

_Setting some pressure on this._
Very much appreciated if you can finish this one before v-data-table will be push to stable 💯

**Comment by johnleider** [comment]
Should this have a corresponding scss variable?

**Comment by SveinnB** [comment]
Sure
Yes, I think that would only make vuetify better and more customizable.

**Comment by BaltacMihai** [comment]
The resolution to this issue involves the elimination of the background: `rgb(var(--v-theme-surface))` declaration, which was conflicting with the backgrounds set by the respective classes. Normally, the `--v-theme-surface` value is applied due to inheritance, meaning it remains unaffected when the background class is not explicitly specified.

I'm unsure about the subsequent steps I need to take.

**Comment by SveinnB** [comment]
@johnleider Is it possible to merge this PR now and create a seperate Feature Request for the scss variables support?
It will solve my problem to be able to change the color with css-class.

I agree that adding a corresponding scss variable is good idea but not necessary to solve this "FR/Bug".
I am using nuxt3 + vuetify3 and vuetify scss variables does not work with nuxt3 [long story](https://github.com/nuxt/nuxt/issues/15412)

**Review by johnleider — APPROVED** [review]

**Pull request merged**
