### PR TITLE
fix(VSelect): resolve "Expected identifier." error

### PR DESCRIPTION
**Pull request by SetZero**
## Description

This will fix a Bug which makes it impossible to use VSelect in projects

## Motivation and Context

Currently using VSelect causes the following error:
```
SassError: Expected identifier.
   ╷
68 │       position: relative
   │                         ^
   ╵
 [...]\VSelect\VSelect.sass 68:25  root stylesheet
```

This PR will fix this issue by removing unnecessary whitespace in the related file.

## How Has This Been Tested?

This has been tested visually. Removing the whitespace got rid of the error

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by kdankert** [comment]
There are some more problems with whitespaces in the sass files. Those are present in vuetify 2.4.9, which is the latest version at the time of this message.

The errors are at:
- l. 5 VWindows.sass
- l. 12 VCalendarCategory.sass

Is there the possibility to add them to this Pull Request or should I create a new one.

**Comment by jacekkarczmarczyk** [comment]
There's also one in VCalendarDaily.sass in line 15

Command to find all:
```
$ grep -r '[[:blank:]]$' .|grep ss
./src/components/VCalendar/VCalendarCategory.sass:
./src/components/VCalendar/VCalendarCategory.sass:
./src/components/VCalendar/VCalendarDaily.sass:
./src/components/VSelect/VSelect.sass:
./src/components/VWindow/VWindow.sass:
```

**Comment by kdankert** [comment]
> There's also one in VCalendarDaily.sass in line 15
> 
> Command to find all:
> 
> ```
> $ grep -r '[[:blank:]]$' .|grep ss
> ./src/components/VCalendar/VCalendarCategory.sass:
> ./src/components/VCalendar/VCalendarCategory.sass:
> ./src/components/VCalendar/VCalendarDaily.sass:
> ./src/components/VSelect/VSelect.sass:
> ./src/components/VWindow/VWindow.sass:
> ```

This one didn't throw an error for me. So I didn't find it.

**Comment by SetZero** [comment]
> Is there the possibility to add them to this Pull Request or should I create a new one.

If it's ok I'll add them to this PR

> There's also one in VCalendarDaily.sass in line 15

I only found the error in VSelect, as I wasn't using the calendar in my app, but good idea using grep to find similar issues

**Review by jacekkarczmarczyk — APPROVED** [review]
verified by updating sass in the repo to the latest and building with and without PR

**Comment by Tofandel** [comment]
@kdankert You can pin the sass package to `"sass": "1.32.8"` in your package.json, this will fix your issue in the meantime

**Comment by kdankert** [comment]
This PR fixes my issues as well. Unfortunately the publish to npm registry failed, so the version with the fix is not available yet.

> @kdankert You can pin the sass package to `"sass": "1.32.8"` in your package.json, this will fix your issue in the meantime

I might use this until the version is published successfully.

**Comment by maketa521** [comment]
@Tofandel  Still got the same error using `sass-loader@10.1.1` and `sass@1.32.8`.

```
Module build failed (from /data/xxx/node_modules/.pnpm/sass-loader@10.1.1_fibers@5.0.0+sass@1.32.8/node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
```

**Comment by AhmadMuhamo** [comment]
The merged fix for this issue fixes it, when is this expected to be part of a release. I hope sooner rather than later. 
like @maketa521 I still get the error no matter which `sass-loader` and `sass`. Only updating the files to remove the white spaces worked

**Comment by hamzalija** [comment]
<3

**Comment by chiragparekh** [comment]
Hi I am having same issue when I try to deploy site on netlify but its working fine on my local machine. Here is my package.json

{
"name": "dashboard-nuxt-app",
"version": "1.0.0",
"private": true,
"scripts": {
"dev": "nuxt",
"build": "nuxt build",
"start": "nuxt start",
"generate": "nuxt generate"
},
"dependencies": {
"@nuxtjs/axios": "^5.13.1",
"@nuxtjs/vuetify": "^1.11.3",
"chart.js": "^2.9.4",
"core-js": "^3.9.1",
"js-cookie": "^2.2.1",
"nuxt": "^2.15.3",
"sweetalert2": "^10.16.4",
"vee-validate": "^3.4.5",
"vue-chartjs": "^3.5.1",
"vuex-map-fields": "^1.4.1",
"vuex-persistedstate": "^4.0.0-beta.3"
},
"devDependencies": {
"eslint-config-prettier": "^8.1.0",
"eslint-plugin-prettier": "^3.3.1",
"prettier": "^2.2.1",
"sass": "^1.32.8",
"sass-loader": "^10.1.1"
}
}

**Comment by johnleider** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request merged**
