### PR TITLE
month picker

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
Commits up to "test ca37fb8" introduce VMonthPicker component, next commits up to "splitted code into shorter methods f7f53e1" move duplicated code from VDatePicker and VMonthPicker to common base (mixins/calendar-*.js) and then there are some minor tweaks and bug fixes and allowedDates prop

## Props:

- [x] actions
- [x] allowed-dates
- [x] autosave
- [x] dark
- [x] date-format
- [x] formatted-value
- [x] landscape
- [x] locale
- [x] no-title
- [x] scrollable
- [x] v-model
- [x] year-icon
- [x] type (**new**) - allowed values: 'month' or 'date' (default), in the future 'year' or 'week' can be added
- [x] headerDateFormat - now accepts also Function
- [x] titleDateFormat - now accepts also Function
- [x] monthFormat (**new**) - accepts Object or Function 

Playground.vue
https://gist.github.com/jacekkarczmarczyk/a2911675b03983ee974447ea2cd31ca8

### CODE REVIEW

**Comment by nekosaur** [comment]
Nice work, but would this not be integrated into the date-picker?

**Comment by johnleider** [comment]
I have not reviewed this and did not realize it was not built in to the current date picker, that's a must.

**Comment by jacekkarczmarczyk** [comment]
If you mean that the month picker should be used for selecting month in date picker (similar to win10 date picker in taskbar - clicking on a month name in header opens table with months), then definitely I agree and even planned to try to do this, however not in this PR. I'd rather have reviewed (and maybe even merged) this change and then integrate it into date picker.

And if you agree for similar design like in win10 then I guess year picker should be also refactored to visually match with the day and month chooser

**Comment by johnleider** [comment]
I just believe this would be better served in what already exists as opposed to creating an entirely new component.

**Comment by jacekkarczmarczyk** [comment]
Something like `<v-datepicker type="month">`?

**Comment by johnleider** [comment]
Since I generally favor boolean props, ```<v-datepicker selectable-months>``` or some derivative of.

**Comment by nekosaur** [comment]
I would probably include the months selection by default

**Comment by johnleider** [comment]
I'm not opposed to this.

**Comment by jacekkarczmarczyk** [comment]
@johnleider @nekosaur - enjoy code review

**Comment by johnleider** [comment]
Could you please update this for the latest release, thank you!

**Comment by jacekkarczmarczyk** [comment]
@johnleider done with merge, still there are issues with theming, but i'd prefer to fix it in another change (and maybe I'll need help)

I've also added Playground.vue to the description

**Pull request merged**
