### PR TITLE
fix(VTextarea): set overflow:auto when auto-grow

### PR DESCRIPTION
**Pull request by sunner**
## Description

Set `overflow` from `hidden` to `auto`.

If `auto-grow` and `max-rows` are used together, the scroll bar should not be hidden.

## Markup:

```vue
<template>
  <v-container fluid>
    <v-textarea name="input-7-1" variant="filled" label="Label" auto-grow rows="3" max-rows="5"
      model-value="The Woodman set to work at once, and so sharp was his axe that the tree was soon chopped nearly through."></v-textarea>
  </v-container>
</template>
```

### CODE REVIEW

**Review by johnleider — APPROVED** [review]

**Comment by johnleider** [comment]
This breaks functionality. I understand the bug and your approach to fixing it. Unless @KaelWD thinks otherwise.

**Comment by johnleider** [comment]
Pinging the author, are you still interested in this PR?

**Comment by sunner** [comment]
I'm still interested. But I don't know what is your consideration about breaking functionality.

**Comment by johnleider** [comment]
I don't have a suggestion for how to approach this but it most definitely will have to go to the `dev` branch.

**Comment by KaelWD** [comment]
It was already fixed by	0a03a4377b004ad797be536d43203dd3034bbc03

**Pull request closed without merging**
