### PR TITLE
perf: avoid useless re-render on parent update - move to v1.5

### PR DESCRIPTION
**Pull request by Mikilll94**
## Description
Moving #8822 to v1.5

Right now it is not finished. I checked all components and replaced $attrs and $listeners with attrs$ and listeners$ like @KaelWD did in #8822. I did not also check and fix tests, because right now it is complete.

## Motivation and Context
For me and maybe many others including #8822 in v1.5 version is very crucial. I have made this first huge step and have implemented a lot of boring stuff which needs to be done in this issue.

## How Has This Been Tested?

The best way to test this is to use this file as a Playground.

https://pastebin.com/Lfm5Mm0s

It is a large form. When you are typing something into input the perfomance should be nice. Right now it is not. I don't know why. I have implemented @KaelWD trick from #8822 for all components but it is not working. Could someone look at this? 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by Mikilll94** [comment]
I will also look at this later why this is not working like in v2.0.

**Comment by Mikilll94** [comment]
Hey!

I have force-pushed new changes. Now al components are using attrs$ and listeners$ instead of $attrs and $listeners.

Unfortunately I don't know why this won't improve the performance like in v2.0. Could someone check that.

Also I don't know how to deal with "avoriaz" tests :(

**Comment by Mikilll94** [comment]
I have noticed that problems with performance are in this file:
`
src\components\VTextField\index.js
`

If you change these lines:
```
    if (props.textarea || props.multiLine) {
      data.attrs.outline = props.textarea
      return h(VTextarea, data, children)
    } else {
      return h(VTextField, data, children)
    }
```

to these:

```
    if (props.textarea || props.multiLine) {
      data.attrs.outline = props.textarea
      return h(VTextarea, data, children)
    } else {
      return h(VTextField, data) <-- HERE IS CHANGE
    }
```

the performance is improved a lot.

Unfortunately, my knowledge about Vuetify codebase is not big enough to correctly implement that change.

@KaelWD 
Could you find some time to look at this issue and maybe finish it?

**Comment by johnleider** [comment]
Pulse check. Any additional comments @KaelWD ?

**Comment by KaelWD** [comment]
IDK I haven't really looked at it. This isn't a critical bug imo - everything still works just a bit slow sometimes. As it is this PR allegedly doesn't help and also breaks a whole bunch of tests with the same problem I had in #8822.

**Comment by NerijusD** [comment]
@KaelWD Could you take a look at this? I think this is pretty major fix. It is quite noticeable on mobile devices.

**Comment by johnleider** [comment]
At this point we are coming to the end of LTS and it seems the existing repository is gone, I'm going to close this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
