### PR TITLE
Added Afrikaans locale

### PR DESCRIPTION
**Pull request by wernerm**

### CODE REVIEW

**Comment by wernerm** [comment]
Also see https://github.com/vuetifyjs/vuetifyjs.com/pull/645 and https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/50

**Comment by KaelWD** [comment]
This needs to be updated to match the new folder structure.

**Comment by wernerm** [comment]
Should I maybe just create a new PR?

**Comment by DRoet** [comment]
If that makes it easier for you sure, rebasing the branch should usually resolve it but can be a little tricky

**Comment by KaelWD** [comment]
Just move the file lmao

**Comment by jacekkarczmarczyk** [comment]
And add entry in src/locale/index.ts

**Comment by jacekkarczmarczyk** [comment]
locale/index.ts is in dev (merged today)

**Pull request merged**
