### PR TITLE
feat(VDataIterator): emit the page-count event from VData

### PR DESCRIPTION
**Pull request by fjogeleit**
Description

Also emit the page-count event from the inner VData component to update the external pagination on async item changes

This feature is already documented but not implemented at this time

## Motivation and Context

It makes a pagination pageCount update possible if the Iterator items changes in a async matter

## How Has This Been Tested?

No additional tests because I don't find any similar tests in the VDataTable component who already implements this feature

## Markup:
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by fjogeleit** [comment]
@jacekkarczmarczyk should it be labeled as VDataIterator instead of VDataTable?

**Comment by jacekkarczmarczyk** [comment]
yup, fixed

**Comment by johnleider** [comment]
Just to confirm, this is intended to go to `dev`?

**Comment by fjogeleit** [comment]
I read in the contribution Guide that new features should merged into dev. If it could be released earlier with another Target it would be also Fine.

**Pull request merged**
