### PR TITLE
fix(VDataTableHeaderMobile): don't show disabled headers in sort select

### LINKED ISSUE #8036: [Bug Report] Datatables Disabled Sort Key is still showing on small screens
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
Open the Codepen link

### Expected Behavior
Disabled keys must not be present in dropdown selection

### Actual Behavior
All keys are visible

### Reproduction Link
<a href="https://codepen.io/msforbes09/full/zgKaOY" target="_blank">https://codepen.io/msforbes09/full/zgKaOY</a>

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
## Description
hides disabled headers in sort VSelect, hides VSelect if there's no sortable headers at all

Alternatively it can show disabled VSelect if there's no sortable headers @vuetifyjs/core-team ?

## Motivation and Context
fixes #8036 

## How Has This Been Tested?
playground

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-data-table :headers="headers" :items="desserts" :items-per-page="5" class="elevation-1" />
    <v-data-table :headers="headers2" :items="desserts" :items-per-page="5" class="elevation-1" />
  </v-container>
</template>

<script>
export default {
  data: () => ({
    headers: [
      { text: 'Dessert (100g serving)', sortable: false, value: 'name' },
      { text: 'Calories', value: 'calories' },
    ],
    headers2: [
      { text: 'Dessert (100g serving)', sortable: false, value: 'name' },
      { text: 'Calories', sortable: false, value: 'calories' },
    ],
    desserts: [
      { name: 'Frozen Yogurt', calories: 159 },
      { name: 'Ice cream sandwich', calories: 237 },
    ],
  })
}
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
I know at least one person who has commented on a disabled select being still visible. I could go either way with it but wouldn't be heartbroken if it went away.

**Comment by jacekkarczmarczyk** [comment]
Since we have a prop to hide the default header i think i'll do the disabled select version

**Comment by jacekkarczmarczyk** [comment]
@johnleider done

**Comment by dsanders11** [comment]
@jacekkarczmarczyk, I don't think `hide-default-header` is a good solution for that issue. I want headers on the table, I just don't want to show the `Sort By` on mobile. None of my columns are sortable. It's inconsistent to show no sorting behavior on desktop, and then have a disabled, but visible, sort select on mobile. You can mostly get around this by using `:hide-default-header="$vuetify.breakpoint.xsOnly"`, but that's fragile since it depends on the `mobile-breakpoint` prop remaining untouched.

**Pull request merged**
