### PR TITLE
fix(VChip): add aria-label to chip close button

### LINKED ISSUE #11165: [Bug Report] v-chip close lacks accessibility label
### Environment
**Vuetify Version:** 2.2.22
**Vue Version:** 2.6.11
**Browsers:** Chrome 81.0.4044.113
**OS:** Linux x86_64

### Steps to reproduce
Load a `v-chip` component with "close" enabled.  The close button fails accessibility tests because it have a label.

noDiscernableText

Additionally, how come this is not a slot?  I could fix it myself with a slot if that were an option.

### Expected Behavior
To either have a slot I could pass this in, or a way to specify a label for the close button

### Actual Behavior
Not able to do that.

### Reproduction Link
<a href="https://codepen.io/gabaum10/pen/bGVwqyY" target="_blank">https://codepen.io/gabaum10/pen/bGVwqyY</a>

### PR DESCRIPTION
**Pull request by jyburns**
## Description

fixes #11165 by adding a default aria-label of `'$vuetify.close'` to the close `<button>` tag on VChip. This change also created a new prop of `close-label` on VChip.

## Motivation and Context

#11165

## How Has This Been Tested?

Tested in playground and with unit tests. Added a unit test to check for new aria-label when expected.

## Markup:

```vue
<template>
  <v-container>
    <v-chip
      close
      close-icon="mdi-close-outline"
      color="green"
    >Hello Vuetify (default aria label)</v-chip>
    <v-chip
      close
      close-icon="mdi-close-outline"
      color="purple"
      close-label="custom aria label"
    >Hello Vuetify (custom aria label)</v-chip>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      //
    }),
  }
</script>
```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by jyburns** [comment]
Looking for guidance on properly updating the API docs. Initially thought https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/v-chip.json would be the file to update, but it is gitignored.

**Review by KaelWD — CHANGES_REQUESTED** [review]
- That file is correct, change the gitignore to `!/src/locale/en`
 - Don't need a new test, it's already covered by the snapshot
 - v-alert calls the prop `closeLabel`
 - This adds a new prop so rebase to dev: `git fetch && git rebase origin/dev && git push --force` then click edit on github and change the base branch

**Comment by jyburns** [comment]
@KaelWD I was being associated with previous commits to the dev branch after rebasing... I was able to get the diff to just reflect my changes again but i'm afraid I lost my previous commit history in the process. Apologies for that.

**Review by MajesticPotatoe — APPROVED** [review]
👍 
Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).

**Pull request merged**
