### PR TITLE
Don't offset last tab when scrolling

### LINKED ISSUE #3294: [Bug Report] Tabs with grow option move left when selecting second tab (on smaller screen)
### Versions and Environment
**Vuetify:** 1.0.0
**Vue:** 2.5.13
**Browsers:** Chrome 64.0.3282.119
**OS:** Windows 10

### Steps to reproduce
1. Open the pen
2. Select the second tab
3. Resize the window to make it less wide
4. Make window smaller until tab bar shifts left

### Expected Behavior
The tab bar should stay in place

### Actual Behavior
The tab bar receives a CSS style: "transform: translateX(...);" and moves left

### Reproduction Link
[https://codepen.io/anon/pen/eVGxRN](https://codepen.io/anon/pen/eVGxRN)

### Other comments
In the pen this issue is only triggered by resizing the window, when running a collapsible sidebar menu it is triggered on page load once the tab is switched.

### PR DESCRIPTION
**Pull request by smiller171**
fixes #3294

## Description
Check if active tab is last in list and don't add an offset when scrolling if it is.

## Motivation and Context
When using `grow` sometimes tabs would get scrolled (and offset) incorrectly.
This change also improves look and feel of normal scrolling tabs

## How Has This Been Tested?

visually

## Markup:

```vue
<template>
  <v-app>
    <v-toolbar
      dark
      dense
    >
      <v-tabs
        grow
      >
        <v-tabs-slider></v-tabs-slider>
        <v-tab
          v-for="item in tabs"
          :key="item.key"
        >
          {{ item.label }}
        </v-tab>
        <v-tab
          v-for="(item, index) in tabs"
          :key="index + 3"
        >
          {{ item.label }}
        </v-tab>
        <v-tab
          v-for="(item, index) in tabs"
          :key="index + 6"
        >
          {{ item.label }}
        </v-tab>
      </v-tabs>
    </v-toolbar>
  </v-app>
</template>

<script>
export default {
  data() {
    return {
      tabs: [
        {
          key: 'about',
          label: 'About',
          target: '/about/'
        },
        {
          key: 'resume',
          label: 'Resume',
          target: '/resume/'
        },
        {
          key: 'contact',
          label: 'Contact',
          target: '/contact/'
        }
      ]
    }
  }
}
</script>
```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by smiller171** [comment]
I don't agree with codecov here. Ideally there should be a special test case for the last tab.

**Comment by johnleider** [comment]
This doesn't actually resolve the underlying issue. The problem is scrollOffset is not being properly reset when **isOverflowed** changes, which happens when going from mobile to desktop.

**Comment by johnleider** [comment]
My current proposition for this fix: #3781. After running through, this ends up being more of a feature request. If I'm wrong please correct me.

**Comment by smiller171** [comment]
@johnleider I think you're correct, though I believe this solves the presentation of the underlying issue as a side effect. That said, I would think that scrolling past the end in any situation is still a bug, as it sends a signal to the user that there are more options off to the right when there are not, and it's inconsistent with the behavior of the overscroll on the left side since the left side will not overscroll beyond the first tab.

**Comment by johnleider** [comment]
It's only a bug if it wasn't intentional by us. The offset is intentional. Your logic in regards to it being a worse user experience, that may be, but this should still be a feature request to `dev` branch.

**Comment by KaelWD** [comment]
Does this still apply, and if so can you explain what it's actually about? The original issue appears to be fixed now.

**Comment by smiller171** [comment]
@KaelWD I'll have to build a new test case. Something has changed that radically altered how my codepen renders.

**Comment by smiller171** [comment]
@KaelWD No, this isn't fixed. I'll get a codepen together in a minute, but the short version is that if you have 6 tabs and only room on screen for 4 tabs, when tab 5 is selected you expect the bar to scroll so that you can see part of tab6, so you know something is there, but you would expect that when tab 6 is selected the right edge of tab 6 should line up with the right edge of the tab bar so that it's clear you're at the end of the list of tabs. Instead the behavior seen is that there is a gap between the right edge of tab 6 and the right edge of the bar, making it appear to the user as if there is another interactive tab when there is not.

**Comment by smiller171** [comment]
@KaelWD Here's an example pen. Make the view narrow enough to overflow the tabs and select tab 10 to see what I mean

https://codepen.io/smiller171/pen/MXrjEq

**Comment by KaelWD** [comment]
That's what the spec says should happen, it's actually incorrect because the left side is supposed to have that offset too.

**Comment by smiller171** [comment]
Could you point to the spec? This behavior increases user friction and as far as I can tell it deviates from every other material design implementation, including those by Google.

**Comment by KaelWD** [comment]
I guess it doesn't say anything about the right-hand side, just that the left should align with the keyline. I don't really mind either way so I'm ok to merge this if the bossman is alright with it.

**Pull request merged**
