### PR TITLE
feat(VSlider): add decreasing prop

### PR DESCRIPTION
**Pull request by sureshvv**
Implementation is very similar to global Vue rtl setting but specific setting is local to the particular v-slider.

## Motivation and Context

Needed just one particular slider to have a decreasing mode - max on the left and min on the right

## How Has This Been Tested?

Manual testing only.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by nekosaur** [comment]
1. I think we might use the prop name `reverse` in other components for similar functionality. It might be a good idea to align them so that we're consistent

2. This solution does not make it possible to have a reverted slider when RTL is active

**Comment by sureshvv** [comment]
@nekosaur Can you review and approve if I make above changes?

**Comment by johnleider** [comment]
Thank you for your interest in improving Vuetify. Please create unit tests that correlate to the changes made in this request.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by sureshvv** [comment]
@nekosaur I have made the changes you asked for,

**Comment by sureshvv** [comment]
@johnleider I do not see any unit tests for VSlider. I do see some for VRangeSlider. Should I add my tests there?

**Comment by nekosaur** [comment]
The tests are there. `__tests__` folder in component folder.

**Comment by sureshvv** [comment]
> The tests are there. `__tests__` folder in component folder. Also it should be `reverse` without the `d`.

Thank you. Will fix.

**Comment by sureshvv** [comment]
Made the minor changes but everything is broke now. Not sure that I have caused it.

**Comment by sureshvv** [comment]
@nekosaur @sh7dm Seems ok now. Please let me know if anything else needs to be done.

**Comment by johnleider** [comment]
There are modifications to files that have nothing to do with this PR, please remove them.

**Comment by sureshvv** [comment]
@johnleider I resolved some conflicts. Can you tell me what other files need changing? I did a git pull and that seemed to have created a merge and introduced some changes. Some changes have happened since and I am bit lost as what to undo.

**Comment by sureshvv** [comment]
Travis Buddy lint seems to be failing. These are not due to my changes. Should I attempt to fix after learning Typescript?

**Comment by sh7dm** [comment]
@sureshvv you shouldn't, it's failing on `next`

**Comment by sureshvv** [comment]
> @sureshvv you shouldn't, it's failing on `next`

anything else needed from me?

**Comment by sureshvv** [comment]
Can this be merged? Anything else going on?

**Comment by sh7dm** [comment]
@sureshvv contact me (@sh7dm) in Discord, I'll help you with lint, snapshots etc. And I hope this'll be merged

**Comment by sureshvv** [comment]
> @sureshvv contact me (@sh7dm) in Discord, I'll help you with lint, snapshots etc. And I hope this'll be merged

Thank you. What is your time zone and what time are you around? I am GMT + 5.30 and I can't see you.

**Comment by sh7dm** [comment]
+4, sometimes I'm busy, sorry. I'll help you when i have time

**Comment by sureshvv** [comment]
Superceded by #7215

**Pull request closed without merging**
