### PR TITLE
fix: pagination for server-side data-table with search val

### LINKED ISSUE #2761: [Bug Report] Server-side data-table with search val breaks pagination
### Versions and Environment
**Vuetify:** 0.17.4
**Vue:** 2.5.3
**Browsers:** Chrome 62.0.3202.94
**OS:** Mac OS 10.12.6

### Steps to reproduce
Enter something in the search field.

### Expected Behavior
The totalItems set after data fetch would still be used for paging.

### Actual Behavior
Paging breaks.

### Reproduction Link
[https://codepen.io/kdholt34/pen/mqNbQP](https://codepen.io/kdholt34/pen/mqNbQP)

### Other comments
I did check v1-alpha.2 and the bug seems to still exist there.  Related to the fact that computed prop itemsLength returns searchLength if there's a search val without first checking if there's a totalItems prop (server-side processing) and elsewhere searchLength is never set if there's totalItems.

### PR DESCRIPTION
**Pull request by kdholt34**
## Description

Fixed pagination for server-side data-table with search val, so computed prop `itemsLength` will use `totalItems` if available.

## Motivation and Context

fixes #2761 

## How Has This Been Tested?

Snapshot tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

### CODE REVIEW

**Comment by nekosaur** [comment]
I'm not sure I understand what this is supposed to fix, even after looking at the related issue. 

If you're using server side data, you shouldn't be using the `search` prop, since it would only filter the local data only, which is not the source of truth. With that said it won't actually do anything (as evidenced by the codepen). If `total-items` is set then all local sorting, pagination and search filtering is disabled.

**Comment by kdholt34** [comment]
For simplicity, the related codepen doesn't actually filter, but the desired use is for the server to do the filtering.  So I want to utilize the search prop which already has code in place to reset the pagination page (and emits an update event) and just send that search val to the server.

**Comment by nekosaur** [comment]
If you want the server to do filtering, don't use `search` prop. Do something like this

https://codepen.io/anon/pen/Zvovwz?editors=1010

**Comment by kdholt34** [comment]
Generally when adding a search/filter, the page is reset to 1.  To do that and not cause an endless loop issue with the watchers, I'd literally be duplicating the code from the existing `search` prop watcher.  What I'm wanting to do is essentially the same as using the existing `pagination` object for server-side processing, so I'm not sure I understand the issue or difference.  All the other places in the code that might use the val from the `search` prop (like` filteredItems`) use a return early pattern that checks for `totalItems`.

**Comment by johnleider** [comment]
Closing due to inactivity.

**Comment by milosbarlov** [comment]
@nekosaur  in this example https://codepen.io/anon/pen/Zvovwz?editors=1010 when you type something in search box you will have two request to the server. The issue is in  
 watch: {
      search () {
        this.fetch()
      },
      pagination: {
        handler () {
          this.fetch()
        },
        deep: true
      }
    },
First will be called search function then pagination function . We need only one request to the server. Can we prevent this situation?

**Comment by nekosaur** [comment]
See open issue https://github.com/vuetifyjs/vuetify/issues/3585

**Pull request closed without merging**
