### PR TITLE
fix(VListGroup): convert icon slots to kebab

### PR DESCRIPTION
**Pull request by MajesticPotatoe**
## Description
converts `append-icon` and `prepend-icon` slots to kebab case on `v-list-group`

## Motivation and Context
So they can be used

## How Has This Been Tested?
unit | visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-row justify="center">
      <v-card
        class="mx-auto"
        max-width="450"
        tile
      >
        <v-list>
          <v-list-group></v-list-group>
          <v-list-group
            prepend-icon="mdi-star"
            append-icon="mdi-star"
          >
          </v-list-group>
          <v-list-group>
            <template #prepend-icon>
              <v-icon>mdi-star</v-icon>
            </template>
            <template #append-icon>
              <v-icon>mdi-star</v-icon>
            </template>
          </v-list-group>
        </v-list>
      </v-card>
    </v-row>
  </v-container>
</template>

<script>
  export default {
    data: () => ({}),
  }
</script>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [x] My code follows the code style of this project.
- [x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
- [ ] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by KaelWD** [comment]
This is a breaking change.

**Comment by MajesticPotatoe** [comment]
@KaelWD Even though it didn't work before? 🤷‍♂ oh well, guess this will just sit until v3.

**Comment by KaelWD** [comment]
It does, just not in DOM templates: https://codepen.io/kaelwd/pen/mddZJmv

**Comment by johnleider** [comment]
I've moved this to the `dev` branch.

Requesting final comments @vuetifyjs/core-contributors @vuetifyjs/core-team

**Comment by jacekkarczmarczyk** [comment]
As Kael stated - it's a breaking change, `appendIcon`/`prependIcon` slot now don't work:
```vue
<template>
  <v-container>
    <v-row justify="center">
      <v-card
        class="mx-auto"
        max-width="450"
        tile
      >
        <v-list>
          <v-list-group></v-list-group>
          <v-list-group
            prepend-icon="mdi-star"
            append-icon="mdi-star"
          >
          </v-list-group>
          <v-list-group>
            <template #prepend-icon>
              <v-icon>mdi-star</v-icon>
            </template>
            <template #append-icon>
              <v-icon>mdi-star</v-icon>
            </template>
          </v-list-group>
        </v-list>
      </v-card>
      <v-card
        class="mx-auto"
        max-width="450"
        tile
      >
        <v-list>
          <v-list-group></v-list-group>
          <v-list-group
            prepend-icon="mdi-star"
            append-icon="mdi-star"
          >
          </v-list-group>
          <v-list-group>
            <template #prependIcon>
              <v-icon>mdi-star</v-icon>
            </template>
            <template #appendIcon>
              <v-icon>mdi-star</v-icon>
            </template>
          </v-list-group>
        </v-list>
      </v-card>
    </v-row>
  </v-container>
</template>
```
`dev`
image

`fix/listgroup-slot-kebab`
image


By the way (not related to the PR) - is this jumping expected?
GIF

**Comment by johnleider** [comment]
I'd say let's punt on this since we are already into v3 development.

**Pull request closed without merging**
