### PR TITLE
feat(v-data-table): added ondblclick event

### PR DESCRIPTION
**Pull request by DrDynamic**
## Description

Added onDblclick:row event to VDataTable.

## Markup:

```vue
<template>
  <v-app>
    <v-container>
      <v-data-table
        :headers="state.headers"
        :items="state.desserts"
        @dblclick:row="onClick"
      />
    </v-container>
  </v-app>
</template>

<script setup>

  import { reactive } from 'vue'

  const state = reactive({
    headers: [
      {
        title: 'Dessert (100g serving)',
        align: 'start',
        sortable: false,
        key: 'name',
      },
      { title: 'Calories', align: 'end', key: 'calories' },
      { title: 'Fat (g)', align: 'end', key: 'fat' },
      { title: 'Carbs (g)', align: 'end', key: 'carbs' },
      { title: 'Protein (g)', align: 'end', key: 'protein' },
      { title: 'Iron (%)', align: 'end', key: 'iron' },
    ],
    desserts: [
      {
        name: 'Frozen Yogurt',
        calories: 159,
        fat: 6.0,
        carbs: 24,
        protein: 4.0,
        iron: '1%',
      },
      {
        name: 'Ice cream sandwich',
        calories: 237,
        fat: 9.0,
        carbs: 37,
        protein: 4.3,
        iron: '1%',
      },
      {
        name: 'Eclair',
        calories: 262,
        fat: 16.0,
        carbs: 23,
        protein: 6.0,
        iron: '7%',
      },
      {
        name: 'Cupcake',
        calories: 305,
        fat: 3.7,
        carbs: 67,
        protein: 4.3,
        iron: '8%',
      },
      {
        name: 'Gingerbread',
        calories: 356,
        fat: 16.0,
        carbs: 49,
        protein: 3.9,
        iron: '16%',
      },
      {
        name: 'Jelly bean',
        calories: 375,
        fat: 0.0,
        carbs: 94,
        protein: 0.0,
        iron: '0%',
      },
      {
        name: 'Lollipop',
        calories: 392,
        fat: 0.2,
        carbs: 98,
        protein: 0,
        iron: '2%',
      },
      {
        name: 'Honeycomb',
        calories: 408,
        fat: 3.2,
        carbs: 87,
        protein: 6.5,
        iron: '45%',
      },
      {
        name: 'Donut',
        calories: 452,
        fat: 25.0,
        carbs: 51,
        protein: 4.9,
        iron: '22%',
      },
      {
        name: 'KitKat',
        calories: 518,
        fat: 26.0,
        carbs: 65,
        protein: 7,
        iron: '6%',
      },
    ],
  })

  function onClick (event, item) {
    console.log(event, item);
  }

</script>

```

### CODE REVIEW

**Comment by uschmann** [comment]
lgtm

**Comment by KaelWD** [comment]
There's a lot more than just click and dblclick

**Comment by DrDynamic** [comment]
I'd like to implement "a lot more"
Could you tell me what you mean by this?

**Comment by uschmann** [comment]
It would be nice if you could give a detailed description on what is missing. 
We really need to have a double click event for the rows.

I dont think that you can motivate people to contribute to vuetify if you don´t value th free work they provide.
Itś ok if you want to implement the feature in a better way but at least tell us about the next steps or how to fix the issue with this pull request.

**Pull request closed without merging**
