### PR TITLE
fix(VSelect): fix v-select item-text value props bug

### LINKED ISSUE #14783: [Bug Report][3.0.0-beta.1] v-select item-text and item-value props do not work
### Environment
**Vuetify Version:** 3.0.0-alpha.13
**Last working version:** 2.6.3
**Vue Version:** 3.2.25
**Browsers:** Google Chrome
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. use v-select
2. use item-text and item-value

### Expected Behavior
normal use 

### Actual Behavior
display error

### Reproduction Link
<a href="https://codepen.io/guxuerui-the-decoder/pen/ExbGLKj" target="_blank">https://codepen.io/guxuerui-the-decoder/pen/ExbGLKj</a>

### PR DESCRIPTION
**Pull request by shadrqen**
## Description

Adds support for VSelect itemText and itemValue props and their corresponding functionality. Fixes #14783

## Motivation and Context

Fixes #14783

## How Has This Been Tested?

I created an instance of the VSelect component on Playground.vue. I worked on the changes and submitted once the VSelect worked well.

## Markup:

<details>

```vue
// Paste your FULL Playground.vue here
<template>
  <v-container>
    <v-row class="text-center">
      <v-col class="mb-4">
        <VSelect
          label="Persons"
          :items="items"
          item-text="name"
          item-value="id"
        />
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  import { VSelect } from '../src/components'

  const items = ref([{ name: 'James', id: 10001 }, { name: 'Peter', id: 10002 }, { name: 'John', id: 10003 }])
</script>

<style scoped>

</style>

```
</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by johnleider** [comment]
We are still working out a definitive process for this. Putting this on hold until we reach a conclusion.

**Comment by Antti-Palola** [comment]
What are the pain points in this? Is there something that can be assisted in?

**Comment by shadrqen** [comment]
Well, I am also not in the loop for the 'definitive process.' Been hoping to hear more about this @johnleider

**Comment by johnleider** [comment]
Couldn't have better timing: https://github.com/vuetifyjs/vuetify/pull/15079

**Pull request closed without merging**
