### PR TITLE
fix(VIcon): size with ems instead of px

### PR DESCRIPTION
**Pull request by KaelWD**
<details>
<summary>Playground</summary>

```html
<template>
  <v-app class="v-application--is-ltr">
    <v-container>
      <h1>Density</h1>

      <h2>Default</h2>
      <div>
        <v-btn class="mr-4">
          button
        </v-btn>

        <v-btn class="mr-4" flat>
          button
        </v-btn>

        <v-btn class="mr-4" outlined>
          button
        </v-btn>

        <v-btn class="mr-4" text>
          button
        </v-btn>

        <v-btn class="mr-4" plain>
          button
        </v-btn>

        <v-btn class="mr-4" icon="mdi mdi-vuetify" plain />
        <v-btn class="mr-4" icon="mdi mdi-vuetify" />
      </div>

      <h2 class="mt-6">Comfortable</h2>
      <div>
        <v-btn class="mr-4" density="comfortable">
          button
        </v-btn>

        <v-btn class="mr-4" flat density="comfortable">
          button
        </v-btn>

        <v-btn class="mr-4" outlined density="comfortable">
          button
        </v-btn>

        <v-btn class="mr-4" text density="comfortable">
          button
        </v-btn>

        <v-btn class="mr-4" plain density="comfortable">
          button
        </v-btn>

        <v-btn class="mr-4" icon="mdi mdi-vuetify" plain density="comfortable" />
        <v-btn class="mr-4" icon="mdi mdi-vuetify" density="comfortable" />
      </div>

      <h2 class="mt-6">Compact</h2>
      <div>
        <v-btn class="mr-4" density="compact">
          button
        </v-btn>

        <v-btn class="mr-4" flat density="compact">
          button
        </v-btn>

        <v-btn class="mr-4" outlined density="compact">
          button
        </v-btn>

        <v-btn class="mr-4" text density="compact">
          button
        </v-btn>

        <v-btn class="mr-4" plain density="compact">
          button
        </v-btn>

        <v-btn class="mr-4" icon="mdi mdi-vuetify" plain density="compact" />
        <v-btn class="mr-4" icon="mdi mdi-vuetify" density="compact" />
      </div>

      <v-divider class="my-6" />

      <h1>With icon</h1>
      <h2>Default</h2>
      <div>
        <v-btn class="mr-4">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" flat>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" outlined>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" text>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" plain>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
      </div>

      <h2 class="mt-6">Comfortable</h2>
      <div>
        <v-btn class="mr-4" density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" flat density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" outlined density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" text density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" plain density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
      </div>

      <h2 class="mt-6">Compact</h2>
      <div>
        <v-btn class="mr-4" density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" flat density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" outlined density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" text density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" plain density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
      </div>

      <v-divider class="my-6" />

      <h1>Disabled</h1>
      <h2>Default</h2>
      <div>
        <v-btn class="mr-4" disabled>
          button
        </v-btn>

        <v-btn class="mr-4" flat disabled>
          button
        </v-btn>

        <v-btn class="mr-4" outlined disabled>
          button
        </v-btn>

        <v-btn class="mr-4" text disabled>
          button
        </v-btn>

        <v-btn class="mr-4" plain disabled>
          button
        </v-btn>

        <v-btn class="mr-4" icon="mdi mdi-vuetify" plain disabled />
        <v-btn class="mr-4" icon="mdi mdi-vuetify" disabled />
      </div>

      <h2 class="mt-6">With icon</h2>
      <div>
        <v-btn class="mr-4" disabled>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" flat disabled>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" outlined disabled>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" text disabled>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>

        <v-btn class="mr-4" plain disabled>
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
      </div>

      <v-divider class="my-6" />

      <h1>Density + size</h1>
      <h2>Default</h2>
      <div>
        <v-btn v-for="size in sizes" class="mr-4" :size="size">button</v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4 mt-2" :size="size">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4" :size="size" icon="mdi mdi-vuetify">button</v-btn>

        <h2 class="mt-6">Comfortable</h2>
        <v-btn v-for="size in sizes" class="mr-4" :size="size" density="comfortable">button</v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4 mt-2" :size="size" density="comfortable">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4" :size="size" density="comfortable" icon="mdi mdi-vuetify">button</v-btn>

        <h2 class="mt-6">Compact</h2>
        <v-btn v-for="size in sizes" class="mr-4" :size="size" density="compact">button</v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4 mt-2" :size="size" density="compact">
          <v-icon left icon="mdi:mdi-vuetify" />
          button
        </v-btn>
        <br>
        <v-btn v-for="size in sizes" class="mr-4" :size="size" density="compact" icon="mdi mdi-vuetify">button</v-btn>
      </div>

      <v-divider class="my-6" />

      <h1>Variants</h1>
      <div>
        <v-btn class="mr-4" rounded="0">
          Tile Button
        </v-btn>

        <v-btn class="mr-4" rounded="pill">
          Rounded Button
        </v-btn>

        <v-btn class="mr-4" rounded="shaped">
          Shaped Button
        </v-btn>

        <v-btn class="mr-4" elevation="12">
          Elevation
        </v-btn>

        <v-btn class="mt-4" block>
          Block Button
        </v-btn>
      </div>
    </v-container>

    <div class="text-center">
      <v-btn
        v-if="!chip1 && !chip2 && !chip3 && !chip4"
        close
        color="primary"
        dark
        @click="(chip1 = true), (chip2 = true), (chip3 = true), (chip4 = true)"
      >
        Reset Chips
      </v-btn>

      <v-chip
        v-if="chip1"
        class="ma-2"
        closable
        color="primary"
        border
        variant="text"
        @click:close="chip1 = false"
      >
        Closable
      </v-chip>

      <v-chip
        v-if="chip2"
        class="ma-2"
        closable
        color="red"
        text-color="white"
        @click:close="chip2 = false"
      >
        Remove
      </v-chip>

      <v-chip
        v-if="chip3"
        class="ma-2"
        closable
        color="green"
        variant="outlined"
        @click:close="chip3 = false"
      >
        Success
      </v-chip>

      <v-chip
        v-if="chip4"
        class="ma-2"
        closable
        color="orange"
        label
        variant="outlined"
        @click:close="chip4 = false"
      >
        Complete
      </v-chip>
    </div>
    <div class="text-center">
      <v-chip class="ma-2"> Default </v-chip>

      <v-chip class="ma-2" color="primary"> Primary </v-chip>

      <v-chip class="ma-2" color="secondary"> Secondary </v-chip>

      <v-chip class="ma-2" color="red" text-color="white"> Red Chip </v-chip>

      <v-chip class="ma-2" color="green" text-color="white">
        Green Chip
      </v-chip>
    </div>
    <div>
      Draggable
      <v-chip draggable> Default </v-chip>
    </div>
    <div class="text-center">
      <v-chip class="ma-2" color="success" variant="outlined">
        <v-icon left> mdi-server-plus </v-icon>
        Server Status
      </v-chip>

      <v-chip class="ma-2" color="primary" variant="outlined">
        User Account
        <v-icon right> mdi-account-outline </v-icon>
      </v-chip>

      <v-chip class="ma-2" color="deep-purple accent-4" variant="outlined">
        <v-icon left> mdi-wrench </v-icon>
        Update Settings
      </v-chip>

      <v-chip class="ma-2" closable color="indigo darken-3" variant="outlined">
        <v-icon left> mdi-fire </v-icon>
        New Posts Available
      </v-chip>
    </div>
    <div class="text-center">
      <v-chip class="ma-2" size="x-small"> x-small chip </v-chip>

      <v-chip class="ma-2" size="small"> small chip </v-chip>

      <v-chip class="ma-2"> Default </v-chip>

      <v-chip class="ma-2" size="large"> large chip </v-chip>

      <v-chip class="ma-2" size="x-large"> x-large chip </v-chip>
    </div>
    <div class="text-center">
      <v-chip density="compact">Compact</v-chip>
      <v-chip density="comfortable">Comfortable</v-chip>
      <v-chip>Default</v-chip>
    </div>
    <div>
      <v-chip :ripple="false">No Ripple</v-chip>
      <v-chip to="/page1">Link</v-chip>
      <v-chip to="/page2">Link</v-chip>
      <v-chip to="/page2" :ripple="false">Link No Ripple</v-chip>
    </div>
    <div>
      <v-chip
        class="ma-2"
        color="indigo"
        text-color="white"
        size="small"
        pill
      >
        <template #prepend>
          <v-avatar>
            <v-icon>mdi-account-circle</v-icon>
          </v-avatar>
        </template>
        Mike
      </v-chip>
      <v-chip
        class="ma-2"
        color="indigo"
        text-color="white"
        pill
        label
      >
        <template #prepend>
          <v-avatar left>
            <v-icon>mdi-account-circle</v-icon>
          </v-avatar>
        </template>
        Mike
      </v-chip>
      <v-chip
        class="ma-2"
        color="indigo"
        text-color="white"
        size="x-large"
        density="compact"
        pill
      >
        <template #prepend>
          <v-avatar color="indigo">
            <v-icon>mdi-account-circle</v-icon>
          </v-avatar>
        </template>
        Mike
      </v-chip>
    </div>
  </v-app>
</template>

<script>
  import { ref } from 'vue'
  export default {
    setup () {
      const chip1 = ref(true)
      const chip2 = ref(true)
      const chip3 = ref(true)
      const chip4 = ref(true)

      return {
        chip1,
        chip2,
        chip3,
        chip4,
      }
    },
    data: () => ({
      sizes: ['x-small', 'small', 'default', 'large', 'x-large'],
    }),
  }
</script>
```
</details>

### CODE REVIEW

**Comment by glen-84** [comment]
Will these changes support non-font icons (images and SVG)? (somewhat-related to #13974)

It seems like those would require a width and height, as opposed to a font size.

**Comment by KaelWD** [comment]
Should do, v-icon has width/height of 1em now so it'll always be the same as font-size. We've had problems with some components wanting to override icon sizing but only changing font-size so they looked bad with SVG icons, that should no longer be a problem with this change.

**Comment by KaelWD** [comment]
I checked #13974 and it works *without* v-avatar, `.v-avatar > .v-icon` and `.v-avatar > *` still override an explicit size on v-icon though.

**Comment by KaelWD** [comment]
Those styles seem to have been added for chips (#13192), which kinda makes sense - if you want to change the size you should do it on the avatar instead.

**Comment by glen-84** [comment]
My codepen has the size on both the avatar and the icon, and it doesn't seem to change anything.

Anyway, this is off-topic, I just wanted to make sure that things wouldn't regress further with this change. 🙂

**Comment by KaelWD** [comment]
I mean it works with these changes

**Review by johnleider — APPROVED** [review]

**Pull request merged**
