### PR TITLE
feat(VSkeletonLoader): Add eager prop

### LINKED ISSUE #12987: [Feature Request] [VSkeletonLoader] Add eager prop like VDialog
### Problem to solve
Pre-Render content on mounted for VSkeletonLoader, as it can already be done with VDialogs

### Proposed solution
Add the same prop VDialog has to VSkeletonLoader

### PR DESCRIPTION
**Pull request by FriiZe**
pre render child componenet before father's one
See #12987 

## Description
 add eager prop on VSkeletonLoader component which permit to render child component before father's one

resolves #12987 

## How Has This Been Tested?

 Tested by Playground.Vue but I did not create unit tests 

 visually

## Markup:

<details>

```vue
<template>
  <v-container>
    <v-skeleton-loader
      :eager="true"
      :loading="true"
    >
      <p
        ref="child"
      >
        Test
      </p>
    </v-skeleton-loader>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
    //
    }),
    mounted () {
      console.log(this.$refs.child)
    },
  }
</script>
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x ] The PR title is no longer than 64 characters.
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x] My code follows the code style of this project.
- [ ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)

### CODE REVIEW

**Comment by thegoldgoat** [comment]
> pre render child componenet before father's one
See #12978

Beware the typo!

As stated afterwards, the correct issue is #12987

**Comment by thegoldgoat** [comment]
The commit message contains the same typo

**Comment by johnleider** [comment]
This seems overly complicated. Why are we having to chain so many nextTicks?

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Pull request closed without merging**
